#+title: The Age of Commodity
:PROPERTIES:
:ID:       4fb240m099k0
:END:
#+cite_export: csl ieee.csl



#+begin_postscript
This post is highly based on [cite:@byron-2019-fifteen-million] and Marxism
Today content about commodity.
#+end_postscript


Unlike my [[id:inf7qkj0r1k0][previous post]], this one is being written while in my travels, I expect
it to be less comprehensive but I believe I've some thoughts that deserve to be
shared.

[[id:6c54fdi0swj0][Karl Marx]] described capitalist societies as following: “the wealth of societies
in which the capitalist mode of production prevails appears as an immense
collection of commodities.”[cite:@marx-1990-capit-volum-i], it should be noted that "wealth" also imply "value"
in [[id:h762nqb0jek0][Marxism]] sociology, and not much has changed as of today.

But what's a commodity anyway? Marx described the state of a capitalist society
as to be in a "commodity fetishism", the term fetishism here means that an
object that appears to have some kind of magical or mystical, supernatural
powers within it, which might sound similar to the sexual term as well, when we
describe something as a sexual fetish we usually mean that it gets that
unexpected (if sexual standardization is a thing) interest in a non-genital
human part sexually.

Let's take for example a magic ring as an object. The object somehow contains a
power or value that’s perceived to be inherent within it.


The question of where this power or value has come from is obscured, hidden
behind a veil of mysticism. Questions regarding where the ring came from, under
what conditions it was produced, what its molecular composition is, why it has
appeared at this specific moment in time, etc. are all brushed aside. We instead
just see a static object that exists with power and value which appears to
emanate from the object itself – rather than from complex processes of
production among people which have actually given rise to it.

In a capitalist society we are more expected to think of everything as a
commodity, no maters what is behind it from production relationship, it's just a
commodity that's exchanged with other value commodity, that is money.

In /Fifteen Million Merits/, Bing works to live, and in order to live he must
buy, infinite cycle that even an attempt of breaking it will trigger a rough
"resume watching", or he might even get incarcerated. Although the type of
commodified life sounds extreme, it's the same kind of society that we live in
currently, you can imagine yourself how everything around has been commodified,
even the methods you use to read these words are extremely commodified.

One can argue that a commodified life is not that bad, which is usually the
counterargument for the free market, however, what about commodified people?

With a historical context, commodification was never the case. Hunter‐gatherers
did not have prices for their goods. As societies developed technologically,
they often engaged in trade, but there was no system of universalized pricing.
For instance, a serf could trade her apples for more chickens, cows, tools, or
money. The apples had no normalized universal price stamped on them. But in a
capitalist society, eventually one unit of pricing congeals around all objects
of use. In /Fifteen Million Merits/ as also in real life (with the concept of
international dollars for example) we see the apples are stamped “5000M,” the
bananas “2000M,” and the soda “500M.” In principle then, two apples are worth
five bananas, or twenty sodas, which infact sounds as a normal thing to us.

No, it's not. As Marx noted, the concept of universalized pricing – where all
commodities, including human ones, can theoretically be equated with a single
unit of measure – is a relatively recent development. Once established, it
appears natural and timeless. As capital expands, it increasingly needs to
create markets and commodify goods. This is how capitalism functions to generate
more profits, ultimately turning everything into a commodity.

In his essay "Reification and the Consciousness of the Proletariat," Georg
Lukács argued that the commodity fetishism inherent in capitalist society was
transforming human consciousness. Lukács supported Marx's claim that "it is not
the consciousness of men that determines their existence, but their social
existence that determines their consciousness." The term "reification" in
Lukács's essay refers to a dual phenomenon: people are viewed as objects, like
apps and apples, and objects—whether they are people, apps, or apples—take on
social relationships.


Reification results from living in a society obsessed with commodity fetishism.
"Fifteen Million Merits" offers compelling examples of this, showing how humans
are turned into objects and how commodity relationships overshadow human life.
One example is Oliver the Lemon, and another is Glee, the silver-haired girl who
waits a week for her chance to perform on "Hot Shot." When she finally performs,
her voice is found lacking, and she is viewed as unlikable. As a result, Glee is
labeled "quite worthless." Her human worth is directly linked to her ability to
produce value for exchange.

Abi also tries to create personalized artwork in the form of a papier-mâché
penguin, but the janitor throws it away, calling it "detritus" (trash). However,
Abi gains value because she can provide sexual gratification in purchasable
Wraith Babes episodes. When she makes objects for use rather than for sale, they
lack the commodity form and are treated as disposable as trash. Disturbingly,
Bing’s fellow cyclist, Dustin, consistently sees humans as objects, making it
easier for him to accept their physical and psychological abuse on Wraith Babes
and Botherguts (see also [[id:yh5juz019wj0][Industry and Consumption of Pornography]]) .


* The Real Plot

After Bing is able to get his /One Shot/ he is able to give a speech there,
which is regarded the end of the episode. While much of his speech is garbled
and nonsensical, it is also insightful and true, both for the world of "Fifteen
Million Merits" and our own:

#+begin_quote
All we know is fake fodder and buying shit. That’s how we speak to each other,
how we express ourselves is buying shit. …Show us something real and free and
beautiful, you couldn’t. It’d break us, we’re too numb for it, our minds would
choke. There’s only so much wonder we can bear, that’s why when you find any
wonder whatsoever you dole it out in meager portions, and only then till it’s
augmented and packaged and pumped through ten thousand pre‐assigned filters, til
it’s nothing more than a meaningless series of lights, while we ride day‐in,
day‐out–going where?  Powering what? All tiny cells in tiny screens and bigger
cells in bigger screens and fuck you…fuck you all, for taking the one thing I
ever came close to anything real about anything! For oozing around it and
crushing it into a bone, into a joke, one more ugly joke in a kingdom of
millions…  fuck you!
#+end_quote

What really interests me about this episode, especially this scene, is how it's
actually is about the previous episode and I think about the show at whole. In
my past post about the [[id:inf7qkj0r1k0][The National Anthem]], I mentioned that what made the plan
of the kidnapper successful is that he knew that everyone would be focused in
watching the Prime Minster having an intercourse with a pig rather than watching
for the princess appearance, although she appeared in the most evident place,
the most one that could be noticed, London bridge.

This scene shows us a similar analogy, Bing gave a very strong speech that
should affect everyone who's listening to it, to question their life, morals,
principles and policy, however, what happens instead is that he gets an offer
from the committee to have this performance commodified! That even a message
resisting commodification can get commodified itself, and get consumed in that
context instead of examining the moralities that it reflects. This concepts
apply mostly to every episode in /Black Mirror/ where there a great exciting
plot that attracts everyone, similar to Bing's story and speech, however, to
most of the consumers, it's just a commodity formed in a video that they
purchased from a streaming platform. It's a self-referencing scene. #[[id:4swh72s0s1k0][Postmodern Abyss: Black Mirror]]

#+print_bibliography:
