#+title: سبحان خالق نفسي
:PROPERTIES:
:CUSTOM_ID: szj4j7618ik0
:ID: szj4j7618ik0
:lang: ar
:subtitle: Praise to the Architect of Self
:END:
#+BEGIN_tag
{{{t}}} [[id:nk2kigk0ybk0][al-Mutanabbi]] and [[id:ydb1kfn02wj0][Modus Vivendi]]
#+END_tag

قال أبو الطيب:
#+begin_verse
[[id:ll3af9418ik0][سُبحان خالق نفسي كيف لذتها]]
فيما النفوسُ تراه غاية الألمِ
#+end_verse

قال الواحدي: يقول: سبحان من جعل نفسي صبورةً، متجلدةً أمام شدائد الدهر، تجد لذّتها
فيما تتألم منه سائر النفوس، وتسكن إلى ما يكرهه غيرها. كتب المتنبي هذه الأبيات
قبيل وفاته، وأحسب أنه في تلك الفترة كان يغوص في تأملات عميقة حول مسار حياته.
يقول في البيت الذي يليه:

#+begin_verse
[[id:yfok0d618ik0][أتى الزمان بنوه في شبيبته]]
فسرّهم وأتيناه على الهرمِ
#+end_verse

إن بلوى المتنبي في حياته أمر لا يدركه كثيرون، ولعل من وعى مسيرته، وتلمس آماله
ومطامحه، وأحسّ بغربته بين قومه، فقط من يدرك مداها. وهو القائل:

#+begin_verse
[[id:0s92bns0zek0][أَذاقَني]] زَمَني بَلوى شَرِقتُ بِها
لَو ذاقَها لَبَكى ما عاشَ وَاِنتَحَبا
#+end_verse

ولعل هذا البيت من أعمق ما قاله في رثاء نفسه، وكأنّي به يقف على أطلال تاريخه وهو
ينشده، مستعيدًا مشاهد الاضطرار إلى مدح من يمقتهم، وفقدان زوجته وجدته، وحرمانه من
طفولة سليمة، وخيانة الملوك والعبيد له على السواء، ومحاولات اغتياله، لكن أشدّ ما
أنهكه: بعد مقدرته عن إدراك غايته. ومن المصادفة الطريفة أنه قال:

#+begin_verse
[[id:kr1hea81k8k0][لَحا]] اللَهُ ذي الدُنيا مُناخاً لِراكِبٍ
فَكُلُّ بَعيدِ الهَمِّ فيها مُعَذَّبُ
#+end_verse

قبل أن يبدأ مدح كافورٍٍ ببيت واحد. وفي ذلك البيت يقول ضمنيًا أنه مُجبر على ذلك
المديح. نعود إلى البيت الأول؛ ففيه يتعجب المتنبي من غربته عن أبناء عصره – وقد
هجاهم في البيت الذي يسبقه – إذ يجد في الألم والعذاب، اللذين يواجههما في سبيل
غايته، لذّةً أسمى وأرفع من المتع التي ينعم بها أهل زمانه. وكنت قد كتبتُ فيما مضى:
"For those who live loftily and dangerously, who need few comforts, the very
things that others dread—solitude, pain, hardship, weirdness—actually become
their pleasures."

وقد حدث أن اشتدت الحمى على المتنبي، فقال:


#+begin_verse
ذَراني وَالفَلاةُ بِلا دَليلٍ
وَوَجهي وَالهَجيرَ بِلا لِثامِ

[[id:v4ehu4418ik0][فَإِنّ]]ي أَستَريحُ بِذي وَهَذا
وَأَتعَبُ بِالإِناخَةِ وَالمُقامِ
#+end_verse

أي: أن الراحة عنده ليست في السكون والاستقرار، بل في السعي الدؤوب نحو المجد. وقد
قال [[id:7sq9bk71x2k0][أبو العباس]]: [[id:7wtatv50tfk0][وملحمة]] الإنسان هي ملحمة الانتقال. ولا يكون الانتقال بمجرّد
الارتحال؛ وإنّما هو عملية عنيفة. ولا يكون ارتحال بلا سيْف: ذهني أو واقِعي. والسيفُ
أبو الارتحال، ولذات السبب، أبو التاريخ.
