#+TITLE: A Guide to Existential Crisis, v1
#+DATE: <2022-11-26 Sat 18:13>
:PROPERTIES:
:ID:       fiwcgi21w2k0
:END:
#+OPTIONS: broken-links:t

- [2024-01-18 Thu 08:18]: Beware that I'm really unaware of what is written
  below, the only reason that I keep this page on my personal website is that I
  think it might help some people. I'm not the author of the text. Also, see:
  https://psyche.co/guides/how-kierkegaard-can-help-you-cope-with-an-existential-crisis
  it might be more helpful than this.

#+BEGIN_PREVIEW
/I found the following text file in some obscure online corner. I'm posting it here that it
might help someone and for archiving purpose./
#+END_PREVIEW

* What is an existential crisis
An existential crisis is the situation in which significant negative emotion is
caused by the feeling, or perhaps knowledge, that life is in some sense
meaningless or absurd. There is something about existence itself that can't be
dealt with because of the seeming lack of a solid frame, goal, or meaning.
* By whom, for whom, and what is this guide?
I am not an expert on existential crisis from a psychological or philosophical
point of view. That is to say, I have no credentials in this area. I have just
struggled a lot with these issues myself, and feel that I have made signficant
progress in this area, and I would like to share my ideas of how to deal with
existential crisis. This guide is for anyone who feels like they have the
issues I describe. I will have to warn you though; Nietzsche's "If you stare
long into an abyss, the abyss will stare back into you" can apply to
existential crisis. If you're not already in this hole, then it may be better
to just stay away from it lest you fall into it. More concretely: I fear that
if you read too much about people's struggles with the meaningless of life and
why they feel this way, you may end up in this struggle yourself, being able to
relate too much to the problem. I must also warn you that feelings of
existential crisis can be a symptom of depression, which drives some people to
suicide, and I am not a psychologist. If you have serious problems, perhaps you
should seek professional help rather than trying to create self-therapy based
on writings on the internet.
* The general approach
I don't think it is possible to find an answer to the question of why we are here, which
goals we should have, or what the meaning of life is. In my opinion, we simply have to
accept that we could be here without any intention, that there is no intrinsic goal to life,
and no intrinsic meaning either. It is possible that we are just the product of how a
complex system like our universe evolves over time, and that's it. All we feel, even, could
be meaningless. Love is just how humans pair-bond, and they have come to pair-bond because
this is evolutionarily advantageous for us. Compassion is just how one copy of a gene helps
another copy of itself.

My approach therefore isn't to look for these answers. If you are so inclined, you could
become religious. I can't bring myself to believe any of it anymore, but if this helps you
then go ahead. I think neopaganism can be pretty cool but try not to be too cringy, and say
hi to Odin for me.

So what is my approach? It is to find attitudes to life which are acceptable and which make
us able to live life without being paralyzed by these questions. In general, it is an
attitude that shifts the value from some objective kind of answer, to a subjective kind of
answer. "What should I do" becomes "what do I want to do", "what am I avoiding", et cetera.
To put it poetically I will draw on Nietzsche once more, who said (I'm paraphrasing) "God is
dead, and we have killed him. Must we not become gods ourselves to be worthy of this?" We
are without a foundation for our highest ideals and a meaning to our life: God is dead. We
have stopped believing in ideals and meaning in an attempt to throw away superstition, or to
be closer to the truth, or just because we dared "look into the void" by asking ourselves
the question: We have killed him. And now for the critical point, that we must become gods
ourselves to be worth of this: We need to take our ourselves as the foundation of our ideals
and meaning.


This then takes us somewhat in the direction of Nietzsche, who was one of the authors I
started reading in my search for meaning. Initially I was a fan, but Nietzsche does fail on
a critical point, as I think Peterson mentions as well: Nietzsche has the romantic ideal of
a world as a canvas on which you paint the artwork that is your life. You with your
creativity just come up with it. Concretely: Nietzsche has this idea of man as being able to
create his own values. I would argue that Nietzsche does not exactly say that we are that,
but rather that we should seek to be that; this is what he calls the ubermensch (sometimes
translated as superman or overman). The problem with this way of thinking is that it isn't
at all clear that we can create our own values; the process by which we come to verbalize
our values is more like one of discovery. This is what then took me in the direction of
Jung, who focuses on the subconscious. Central to Jung's way of thinking is individuation, a
process in which an individual shapes himself by integrating certain parts of his
unconscious. This is more akin to how I think you can come to value things once more.

To put it in the shortest way possible: I think that through introspection you can find your
true self which will then allow you to find ways to fill in your daily life in such a way
that these existential questions won't bother you anymore.
* How to start
The trouble I have in writing this guide is that I need to find a way to describe the
solution that will in some sense 'click' for you. Just describing the activities may not be
enough. To some extent you have to earn the knowledge. I can tell you that taking a shower
will help, and if you do it you may find that it has helped, but before you do this may seem
like an absurd proposition: Why would it help to have water run over your body? How will
putting shampoo in your hair give more meaning to your life? And yet it works. So I write
most of this just in the hope that you are willing to try it, because I think that before
you try it, much of it may seem unhelpful.
* Humble beginnings
I'm not sure if this is the right way to start. When in the middle of an existential crisis
these things can sometimes seem very hard to do. Not all of them usually, but we all have
our vices. I for one shower regularly, but my room is usually a mess, for example. Let me
argue the case like this: If you really want to feel better, this stuff will help. Taking a
optimistic approach, namely working from the assumption that you will recover from your
existential crisis, it would be good to start building certain routines.

You are a human who needs to take care of him/herself. Try having the discipline to do all the
basic stuff: Brush your teeth, take showers regularly, et cetera. Chances are that you
aren't doing all that you should do in this respect.

Already your feelings of meaninglessness may start creeping in. Why would I do all of this,
does it really matter that I don't do x every day? Well, having some good routines will come
a long way. Not only will you have solved the problem of how to spend about 15-45 minutes
every day, you may actually start believing that you are a decent human being who could be
worthwhile. In some sense, not smelling like shit may help in not feeling like shit. There
might actually be a lot in this category. I would second the recommendation by Jordan
Peterson to clean your room: Maybe if you cleaned your room you could walk into it and think
"a civilized human being could actually live in here". I know it can be hard, especially if
you haven't done it in a while, and it's one big horrible mess, and you know it will take
hours to get everything right. Just pick a sub-problem you can handle and solve it. Maybe
you can start by cleaning up some of the empty coffee cups on your desk; you'd be surprised
how much it could help. In the same vein, get some nice clothes, a decent haircut, et
cetera. Maybe if you dressed like someone worth taking seriously you would feel more like
taking yourself seriously.
* What you most want to find is where you least want to look
What may be one of the root causes of your existential crisis is repression. By that I mean
that you are experiencing a problem that is quite significant to you, but you don't actually
think about this problem, because you don't want to for some reason. For example, maybe
you've never had a boy/girlfriend and have arrived at an age where you feel like you
should've had such an experience by now. It could very well be that you repress this thought
however, because you feel that you are pathetic for not having had a boy/girlfriend, but
also for the fact that this is causing negative emotion to you. It may be hard to find out
such things about yourself. A bit of concrete advice I would give, is that what you most
need to find is where you least want to look: What are you scared of, that others aren't?
What do you not have in your life, that 'normal people' do? Are there things in your past
that are still causing negative emotions?

It can help to just be aware of these things, and accept them as part of your being rather
than repressing these thoughts: Once you have stopped repressing a part of yourself you get
a more complete view of yourself. You may suddenly find that there's dreams you have that
you had repressed, or problems that you were subconsciously aware of but never allowed
yourself to think about. Taking the example further: Once you accept that you really are
desperate for attention from the other sex, you can then perhaps ask yourself how you could
be less desperate and/or how you could get more attention from the other sex. Perhaps you
have some personal hygiene issues, or perhaps you should engage in more social activities,
or maybe you can find a reason for why you need all this external validation. The truth will
set you free.

I'll copy some of Jung's terminology here to guide this process a bit. There is your
conscious experience and then there is your subconscious. Together, they are the entirety of
you. There are parts of you that you readily accept: Most of which you are conscious of, you
accept as part of you, like memories you are thinking about, which you consider to be 'your'
memories, or feelings of sadness which is really 'you' feeling sad. Then there's all the
stuff in your subconscious. Take the experience of thinking about some memory that you
haven't thought about for months: The fact that you suddenly started thinking about it means
that it was still 'in' you all this time, but you weren't consciously aware of it: It was in
your subconscious. Usually you accept these as 'your' memories when they become conscious,
and so you'll probably have no trouble accepting that a lot of your memories are
subconsciously present. So far so good.

But there may also be parts (emotions, memories, opinions, attitudes, etc.) that you do not
accept as you but still are part of the unconscious. There are two main categories that Jung
describes: The shadow and the animi.

The shadow is the name used for that part of you that you suppress because you consider it
to be too evil for you in some sense. For example, there has been a lot of talk lately about
the so-called 'nice guys', a euphemism for guys who call themselves nice but really are
assholes. A pattern often seen is that they will, usually over text, talk with a girl in a
normal way until the girl makes it clear that she's not interested in dating the 'nice guy'.
At that point the 'nice guy' completely changes his behavior into name-calling and insulting
that looks a lot like sour-grapes syndrome (you we're ugly anyway, nobody wants you, you're
a bitch, I bet you're a slut anyway, etc.). When you ask a girl out, and she rejects you,
you hopefully aren't like this. You respond calmly and accept the fact that she rejected
you. But that does not mean that you do not feel any anger. Perhaps you are actually
thinking the thoughts that the 'nice guy' would text to the girl. However, it is quite
possible that you try to repress these thoughts, because you feel like you shouldn't have
them. That would make them part of your shadow. You repressed these thoughts because you
imagine yourself to be better than that.

What you should do is integrate your shadow. That does not mean that you start acting out
all this repressed 'dark side', that would be something referred to as 'shadow posession'
rather than shadow integration. The process of shadow integration is merely one of accepting
that this really is a part of you.

The other main category consists of animi. There's two 'flavours' to this. Males have a
female variant, the anima, and females have a male variant, the animus. This is greatly
oversimplifying it but in general animi contain those parts which aren't compatible with
your self-identity in another way. The animus are those parts of herself that the woman
represses because they are too male in nature, too agressive for example. The anima are
those parts of himself that the man represses because they are too female in nature, too
soft for example. One may argue here that not all women are soft and not all males are
agressive, but that's exactly the point: Both sexes have both tendencies to some extent, but
based on one's sex certain categories will be repressed because they conflict with what the
man or woman thinks they are supposed to be like. Again, the process of integration is not a
process of surrender to this side of you, but a process of becoming aware. I'm not saying
that males should be spineless whimps and females should be out for blood. I'm saying that
you need to accept urges of those categories as really being part of you, and to fix them if
you find them problematic rather than pretend that they don't exist.
* How to do this, practically

I think that the concrete way of doing this is perhaps something that varies a lot person to
person. There are some pointers I can give you and I'll provide you with two methods of my
own. First off, if something is just bothering you then something is going on. If while
reading the previous part you suddenly started thinking of something that could be what
you're repressing, then certainly that's worth considering. Just in daily life options may
occur to you, now that you're aware of this possibility. A good general pointer is also to
just look at what people generally need for their well-being: Some close friends, a stable
job, a romantic relationship, etc. If you're missing one of these then consider if it's
perhaps something you should try to work on.

What I like to do is just accuse myself of some complex that I'm not sure exists but is
indicated. I just think about the decisions I've made that day; perhaps I had a question in
class and didn't ask it; now I can accuse myself: Am I a coward who does not even dare ask a
question? Do I care too much about what others think of me? I then try to have an honest
conversation with myself, and deliberate on whether this is something I should work on.

Something else I really like is dream analysis. Dream analysis is a bit 'spooky' and how
much truth there is in dreams is hard to say, but one thing should be somewhat clear: If
there's a recurring distressing theme in a dream, then something is triggering your mind to
produce such dreams: Something is bothering you. Also, in interpreting dreams it is not
necessarily the dream itself that reveals information to you; it can also be the process of
interpretation itself. If you see a flower in a dream and see this as a symbol of growth,
then even if the flower really wasn't "meant" by your mind to be a symbol of growth, there's
still something about your mind that made that the first thing to pop into your mind when
you thought about what a flower might mean.
* Search for meaningful activities
First off, think about what you'd like to do. Most likely this list will be rather short,
because you're in an existential crisis. But you can probably make a start and over time you
can add things. Perhaps there's a book you'd like to read one day, or maybe you're
overweight and need to get in shape, or maybe you've found some repressed desires like
finding a boy/girlfriend. Write these down so you're aware of them.

Sometimes you will completely forget about your existential crisis for a while. Sometimes
just 30 minutes, sometimes hours, sometimes even for a day. Try to notice the patterns in
these moments, because this might show you some things about what you're looking for.

Assuming you get out of this existential crisis before you kill yourself, you will have to
pay rent, buy food, etc. And thus you'll have to make money, and thus you better find a job
or go to school. Add to this all the responsibility you should take for yourself.

With many of these things you've found so far, there may be subtasks or things that you can
do to improve your performance. For example, if you need to get in shape, then perhaps you
should also go to the gym, and perhaps rather than just eating less you should really keep
track of what you eat and plan your meals. Using this, there's perhaps a lot of other things
you should do that you can come up with.

Apart from all the stuff you know you want, also "don't deny it before you try it": Maybe
there's things you're not sure if it would help to do them but you feel are worth a try.
Maybe you've never painted but you are willing to give it a try.

Look at how you live your life and what you could improve. Which habit can you perhaps
change to a better habit? Example: Maybe instead of getting out of bed whenever you want,
you could get set a maximum of 10 AM. Just try to come up with these kinds of improvements.
By the end of this you hopefully have an impressive list of activites you can do. You should
at least have some activities in the categories of taking care of yourself, and education or
work.

You will have to review this list from time to time. Perhaps there are new things you'd like
to try, or maybe you find out that something wasn't really your thing. In the end, this is
about living your life in a way that's meaningful to you so do whatever you need to make it
so.

I advise you to have the attitude that every learning experience is worthwhile. Don't be
afraid of spending your time on something you deem meaningful because maybe you won't find
it meaningful next week: Every such experience will tell you more about what way you need to
go in life and is therefore worthwhile.
* Implementation
The answer as to how to achieve these goals is simple: Schedule. You need some structure in
your life for you to actually do all the things you want to do. So make a schedule of when
you're going to do "those things you always wanted to try" and make a schedule of how your
day will look like tomorrow. I'll just borrow some advice from Peterson once more which is
really good advice in my opinion, and central to all of this if you really want it to work:
Make the schedule of the day you'd like to have. Don't think in terms of a perfect you. If
you want to spend all the time you don't know how to spent on reading, then you may end up
planning in 8 hours of reading per day, even though you aren't actually capable of that and
will start playing video games after an hour. In that case, plan in that you will play video
games rather than holding up the pretense that you'll do better. You can gradually improve
your schedules towards what your perfect self would do but it's much more important that you
actually keep to your schedule than that you'll have a good schedule.
* You may resist
Part of the existential crisis is a resistance to solutions, even if the solutions help.
Perhaps this is why existential crises occur to people who are in some sense intellectual:
When you're constantly using rational thought to guide you through life you will hit a wall
when rationality comes short. Having studied all the existing literature on love but never
having experienced it, there's still parts that you're missing: You have to experience it to
truly know what it's like. I think the same goes for existential crises, on two levels: You
can't really understand it unless you're having one, but you also can't really grasp why any
solution would work until you tried it.

Another reason to resists can be because the solution to some of your problems, that you're
aware of, will actually require you to do things you don't want to do. Getting into a
romantic relationship involves asking people out; losing weight will involve actions that
show to other people that you're trying to lose weight, something that may make you feel
vulnerable. Reading a book may make you fear that your friends will see you as a nerd, and
going to the gym may make you fear that they'll see you as a meathead.

I'm not sure if this is the right attitude for everyone, because it can make your
self-esteem even worse, but to be honest: If you're aware of your problems and their
solutions and you don't do anything about them, then perhaps your failure to escape your
existential crisis is there really just for lack of trying, and you should stop looking for
an easy way out and accept that life is hard. Let me counter this with something more
encouraging as well though: You can probably handle much more than you think. I've been in
the habit now for a year or so to document my day-to-day concerns. I just read back parts
about this girl I wanted to date but I feared approaching and the feeling that I'd never be
able to approach her because the fear was just too much. Or how I should probably start
lifting but just couldn't get the courage to do so because I found the gym to be
intimidating and had the fear of looking stupid there. I read back those writings of me, as
someone who has by now had a date with this girl and has been regularly going to the gym for
months. What seems impossible to do now may be the reality of your life 2 months later.

I hope this will be of help to you.


