#+title: Notes about the pornography industry
#+DATE: <2023-07-21 Fri 21:05>
:PROPERTIES:
:ID:       yh5juz019wj0
:END:
#+filetags: :project:permanent:
#+toc: t

* [2025-12-11 Thu 19:53] Update
I must note that this post is a draft, incomplete, and not even self-reviewed.

[2023-10-16 Mon 12:15] /Update/: I much concentrated in few resources for
writing this post, most of them were authored by feminists whose view on
pornography is centered upon Women's Liberation/Oppression Theory *only*.
Although this view is not present in the post, it's important to alert that all
mentioned about acts against women is applicable to men too, even if it was in
narrower domains.

I have begun to yearn for the days when pornography held a less normalized
stance in society, and when people would jest about others who engaged with it.
Meanings are lost in a post-modernist area of mindsets, it's much harder to
explain to people how such a thing is not normal and very malicious. In this
article I'm going to discuss my views on how both consumption and industry of
pornography are dangerous for individuals.

#+BEGIN_PREVIEW
This page contains my views about both the consumption and industry of
pornographic content. along with other related sexual activies.
#+END_PREVIEW

* Consumption

#+begin_quote
Men who read it [beauty pornography] don't do so because they want women who
look like that. The attraction of what they are holding is that it is not a
woman, but a two-dimensional woman-shaped blank. The appeal of the material is
not the fantasy that the model will come to life; it is precisely that she will
not, ever. Her coming to life would ruin the vision. It is not about life.

― Naomi Wolf
#+end_quote

From The Beauty Myth [cite:@wolf1990beauty]

In this section I'm going to discuss the effect that  pornographic content holds
on its consumers. [fn:2]
** Porn as a media platform for sexual violation
:PROPERTIES:
:ID:       7y88co21swj0
:END:

It's a known claim by porn propagandists that "since rapists are likely to use
adult content to relieve themselves because it's easier than raping someone" as
seen [[https://youtu.be/9BcX4evzDjI?t=10][here]]. 

However, the vast majority of porn content is correlated with things like the
degradation of women. If you ask someone to categorize a film for you as
pornographic or erotic, their categorization will be largely based on the level of
degradation that is being applied to women; on the other hand, erotica has more
of a depiction of a real relationship. As described by Ikram Hawramani [cite:@Hawramani_2019]:

#+begin_quote
Pornography equalizes all humans into a new world order of bodies. One body can
be as good as another for satisfying one’s needs. But love and romance require
treating a person as if they are infinitely worthy and irreplaceable. The
“morality” that pornography teaches is entirely opposed to the morality of love.
The two cannot coexist.
#+end_quote

This is generally related to a primitive untamed instinct in many humans that
relates sex to will and domination over women, some researchers suggested that
it is related to the evolutionary history of men and how rape was the thing
until romantic relationships emerged, in which some types of violence is
employed [cite:@lussier-2016-under]. Such a norm is so common that made
researchers define it as a normal act which is "natural"
[cite:@Ford_Beach_1981]. Personally I totally dislike any kind of eroticization
of power through sexual intercourse, I argue that pornography helped much
establishing this sickness.

Porn is a media for sex. What is media? It is the system that is "to inculcate
individuals with the values, beliefs, and codes of behavior that will integrate
them into the institutional structures of the larger society"
[cite:@herman-2008-perfac]. What is represented in whatever collective consent
of pornography, is the how individuals are expected to act from. This is to say,
porn is very related to common memes of domination. Other norms are being
affected as well, such as the designation of "stepsister, stepfather", or any
other step-first family relative, it is being linked to porn films, since it's a
common standard in the industry to use such prefixes to  bypass the legal
limitation on incest content.

Studies found that typical pornographic content introduces women mostly depicted in
subordinate, submissive and forced position [cite:@brosius-1993-explor],
[cite:@dines2013pornography], [cite:@tyler2010now], such positions are known to
be animalistic and were common in brothels where consumers are never into the
personhood of whom they are having the intercourse with, since they are interchangeable
objects of sex. Porn producers do not usually try to hide such things, a porn
director talked once of the animalistic nature of relationship that is embedded
in porn content as it was like "a dog marking its territory"
[cite:@sun_picker_2008] and other shows the interest of violence
acts[cite:@stoller-1993-comin]:

#+begin_quote
“I’d like to really show what I believe the men want to see:
violence against women … [but] the most violent we can get is the cum
shot in the face. Men get off behind that, because they get even with the
women they can’t have”
#+end_quote


The general pattern of the behavior of women in porn can be described as
follows[cite:@dines2013pornography]:

+ Women are generally sexually active creatures at any possible position, let it be public
  or private and let the woman be any human being that can be described as a
  female, including family member (see [[#inf][Intrafamilial rape]]).
+ Women who do not respond with the same amount of phantasy are actually
  responding but in their special way because they like to be forced into it.
  Some porn creators indicate that the actress would "beg him to stop".
+ Women are rarely coherent, which is to say they mostly exhibit whore-like
  behavior. No matter how much elevation and nobility a wman may
  show, she sums up whoring.

Since porn consumption is being a common thing, such regularization is to be
normalized by many males and females, in my opinion such ideology will never
help maintaining a healthy relationship.

Studies indicate that pornography is a factor in male attitude of aggression
[cite:@malamuth_pitpitan_2007]. In contemplating a typical porn site, observers
find "forceful sex with infliction of pain on the girl or woman is the norm.[..]
she is penetrated any-which way – into her mouth, anus or vagina – sometimes
simultaneously. Verbal abuse is showered on her by the man (or men) as they
penetrate her. Subjugation and humiliation of girls and women are depicted
repeatedly."[cite:@gupta_2011].
*** Intrafamilial rape
:PROPERTIES:
:CUSTOM_ID: inf
:END:

Studies highlighted that a significant amount of porn materials is dedicated to
intrafamilial porn in which wife is presented as either sexual unattractive or
is in the picture, she is always looking for being penetrated by her father
[cite:@russell_purcell_2006].

Engaging in sexual activities with children undergoes a transformation with pornography from a sickness to a natural activity, which, as Gail Dines argues, was an achievement for pornography to have such a normalization[cite:@dines_2010]. #[[id:9kk956p02wj0][Propaganda]].

** Porn and sexual kinkiness
:PROPERTIES:
:ID:       qw5hfo21swj0
:END:

There is a reason why top porn content are usually kinky stuff, continuous
consumption of porn and hence the objectification of women causes people to look
for other kinds of domination (or humiliation) As explained, women are no more
than mere objects for porn consumers and directors, the same goes for real animals.
Jeffrey Moussaieff Masson puts it:

#+begin_quote
Pornography involving animals satisfies both the urge to
see women as animals, and to see animals as under the control of a
dominating male. Some males wish to see both suffer. This is true even
when there is a cover, for example pretending that the woman or the
animal likes the suffering or in some sense deserves it.
#+end_quote

BDSM is an example of how that view reflects on real humans, following is a
description of typical BDSM porn content by Margot Wieiss[cite:@donham-2018]:
#+begin_quote
My copy of the monthly newsletter of a San Francisco SM organization
included a scene report, a written description of a consensual BDSM play
scene. The scene took place at a San Francisco dungeon in March 2004.
It was an interrogation scene, involving a Colonel, a Captain, a General,
and a spy. The spy was hooded, duct-taped to a chair, and slapped in the
face. As she resisted, the spy was threatened with physical and sexual
violence, stripped naked, cut with glass shards, vaginally penetrated with
a condom-sheathed hammer, force-fed water, shocked with a cattle
prod, and anally penetrated with a flashlight. The scene ended when the
spy screamed out her safeword, the word that ends the scene: ‘Fucking
Rumsfeld!’.
#+end_quote

Specifically speaking about BDSM, studies have shown that
BDSM are interests for oppressed communities who have endured torment under
dictatorial governments or have suffered under racist regimes, as well as the
struggles faced by lesbians in fundamentalist and militarized environments
[cite:@Hawthorne-2005].

Modern studies have found that there is an association between men being sexually
interested in consensual kinky practices and using pornography (pornography
generally, not just violent pornography)[cite:@mckee-2021].

The consumption of porn is also linked to other kind of kinkiness, like being
more likely to engage in multipartner sex[cite:@harkness-2015-assoc-between].
** Health
Health should be one of the most important aspect for porn consumers, however,
in our modern world people are less convinced by how it affect them badly;
better inform them about smoking. Unlike smoking though, pornography has a very
decent propaganda. I will try to list some of the proven effects of consuming
pornographic content on one's health and productivity.

+ Pornographic picture processing interferes with working memory performance
  [cite:@laier-2013-pornog-pictur].

Generally porn is known to affect one's productivity, it desensitizes dopamine
receptors and rewires your pathways to respond to porn more than other
stimulus (like achieving your long-term goals and what actually matters).

* Industry

#+begin_quote
Pornography is humiliation and degradation of women, it's disgraceful activity
[..] women are degraded as vulgar sex objects, it's not what human beings are.

"But didn't porn performers are choose to do the job and get paid for it?"

The that we should be in favor of sweatshops and China or where women are locked
into a factory and work 15 hours a day and then the factory burns down and they
all die yeah they were paid and they consented [..] as to the fact that it's
some people's erotica well you know that's their problem doesn't mean I have to
contribute to it if they get enjoyment out of humiliation of women they have a
problem.


Suppose there's at a starving child in the slums and you say well I'll give you
food if you'll let me abuse you well I suppose there have to be laws against
child abuse fortunately but suppose somewhere to give your argument well you
know after all a child starving otherwise so you're taking away his chance to
get some food if you ban abuse and is that an argument the argument the answer
to that is stop the conditions in which the child is starving and the same is
true here eliminate the conditions in which women can't get decent jobs not
permit abusive and destructive behavior.

— Noam Chomsky
#+end_quote

From a YouTube interview [cite:@YouTube_2008].
** Porn as a new prostitution
:PROPERTIES:
:ID:       anpcko21swj0
:END:

Karl Marx stated that prostitution is only a particular expression of the
general prostitution of the labor, Eveline Goibbe explained how “pornography is
pictures of [that] prostitution”. Some porn consumers who don't like to have the
moral guilt of it and other people whose benefits will shrink if pornography is
declared legally to be a kind of prostitution will try hard to make unimaginable
allegations that try to unlink porn from prostitution, however, everybody
acknowledges the link.

#+begin_export html
<iframe width="100%" height="515" src="https://www.youtube.com/embed/JDscdmOwDNA?controls=0&amp;start=10" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
#+end_export


One individual who has experienced prostitution firsthand went on to elaborate,
stating that in their view saying "pornography is prostitution that is legalized
as long as someone gets to take pictures" [cite:@stark-2004-pornog-who].

There is a common area between the reasons that might make someone get into
prostitution and porn industry as of poverty and extortion (sometimes porn
workers are filmed secretly to blackmail them [cite:@stark-2004-pornog-japan]).
A porn worker states it[cite:@morita-2004-who-women-nude] :
#+begin_quote
“The owner of the ‘nude photo agency’ offered me a place to live and a
lot of other work if I did film. At that point in my life, I really didn’t have
any other options”
#+end_quote

Studies have shown that there is a direct link between being abused as a kid and
participating in sex industry[cite:@silbert-1983-early-sexual],
[cite:@nadon-1998-antec-prost], [cite:@widom-1996-child] , one can argue that
the trauma makes it harder for the abused to fit in with community easily, so they do
their best trying to make living which ends to be in sex industry if they were
lucky enough to have selling bodies.

In 2007, Peter Acworth, a British individual associated with explicit and
extreme adult content, acquired a building in San Francisco worth 14 million
dollars for his business. Acworth, though he identifies himself as a
pornographer, denies any involvement in pimping. His work revolves around
catering to fetishes and involves paying women to engage in scenarios that may
include distressing situations such as being terrorized, confined in tight
spaces, hogtied, subjected to physical violence, near-drowning experiences, and
suspension from ceilings. [cite:@Mckinley_2007].

Acworth offers porn actress some enticing pay, in 2007, he paid > 1.4K USD for
"forced vaginal fingering"[cite:@harper_2007]. The experience is no much
difference from known torture, as described be survivor [cite:@amis_2001]

#+begin_quote
‘I got the shit kicked out of me,’ … ‘I was told before the video – and they
said this very proudly, mind you – that in this line most of the girls start
crying because they’re hurting so bad … I couldn’t breathe. I was being hit
and choked. I was really upset, and they didn’t stop. They kept filming.
You can hear me say, “Turn the fucking camera off,” and they kept going’
#+end_quote

Following are common areas between prostitution and pornography, shows that
pornography is just as bad but actually worse.

— Research indicates that women engaged in prostitution, whose clients or pimps
  created pornography featuring them, experienced more pronounced symptoms of
  post-traumatic stress disorder (PTSD) compared to women who did not have such
  explicit content produced of them [cite:@farley_2007_ptsd]. The connection between the production of
  pornography within the context of prostitution and heightened PTSD symptoms
  suggests that the experiences of being recorded and potentially exploited in
  this manner can have a detrimental impact on the mental health and well-being
  of those involved.

— Sex workers are suffering for ever from pornography unlike prostitution, one
  of them[cite:@stark-2004-porn-vs-porst]:
  #+begin_quote
  [P]ornography is much worse than prostitution because it affects me for the
  rest of my life. It’s not like I just … had sex with a john, collected my
  money, and went home … I’m still exploited all over the Internet ten years
  later. People recognize me. I’m harassed because of it. My kids are being
  harassed.
  #+end_quote

** TODO Porn as a capitalism lobbying machine                         :@write:@later:
Porn is very profitable, The Global Online Adult Entertainment Market by
ResearchAndMarkets.com estimates the global online adult entertainment market to
be worth $97.05 billion in 2022 and is expected to grow at a CAGR of 11.3% from
2022 to 2027[cite:@researchandmarkets2022global].

In August 1994, Dr. M. Buthelezi, the Minister of Home Affairs at that time,
commissioned a Task Group to develop a new act that would replace the existing
Publications Act of 1974. The new act's scope included addressing issues related
to the production and distribution of pornography [cite:@vanrooyen_1996].
The Task Group's initial research involved international consultations, leading
them to conclude that a mere amendment to the Act would not be sufficient to
address the situation. Instead, they believed that the approach to handling
pornographic material needed to shift from a focus on morality to considering
potential harm [cite:@vanrooyen_1996].

During this period of research, there was also a widely circulated national
petition opposing the legalization of pornography. The petition, organized by
Pat and Horace van Rensburg's organization STOP Pornography, amassed an
impressive 250,000 signatures. Additionally, approximately 1800 submissions were
presented during the Portfolio Committee Hearings, and an overwhelming 95% of
these submissions urged the government not to legalize pornography (pers. comm.
retired MP Horace van Rensburg). Despite these numerous appeals from the public,
it appears that their concerns were not heeded by the authorities.

Within a surprisingly short period of six weeks, the research was completed, and
the new Act was drafted. Despite the involvement of internationally recognized
anti-pornography feminists, sociologists, legal experts, and psychologists, as
well as substantial input from a significant portion of the South African
public, their findings and perspectives were entirely disregarded. Instead, the
opinion of international patriarchal 'legal experts' took precedence in shaping
the new Act. This decision raised concerns about the exclusion of diverse
viewpoints and the potential influence of gender-biased perspectives in the
legislative process.

* Masturbation

This is a little bit an off-topic, but I do not usually discuss sexual topics
on this website, and pornography is usually associated with masturbation, so I
will put my views here too.

While I have other reasons for which I abandon masturbation, I will try to discuss
a philosophy that was (and still is) very convincing for me; [[id:0ay33tp0r1k0][deontological ethics]]
and [[id:yix9gup0r1k0][consequentialism]]:
#+begin_quote
That such an unnatural use (and so misuse) of one's sexual attributes is a
violation of one's duty to himself and is certainly in the highest degree
opposed to morality strikes everyone upon his thinking of it. Furthermore, the
thought of it is so revolting that even calling such a vice by its proper name
is considered a kind of immorality.
#+end_quote

— Immanuel Kant[cite:@kant2017kant_masturbation].

Deontology is an ethical theory that maintains that the morality of an action is
determined by its adherence to certain moral principles or rules. In this
context, the act of masturbation may be considered immoral if it violates a
fundamental moral rule set forth by the deontological framework. Some
deontological perspectives, such as certain religious beliefs, may view
masturbation as immoral because it violates specific commandments or divine
decrees.

The principle of autonomy is crucial in deontological ethics, as it upholds the
individual's right to self-determination and rational decision-making. However,
critics of masturbation within a deontological framework may argue that
self-gratification conflicts with the broader principles of self-control,
moderation, and respect for the human body as a vessel for spiritual and
procreative purposes. As such, masturbation is forbidden under deontology
due to its perceived violation of these principles.

Consequentialism, on the other hand, evaluates the morality of actions based on
their consequences. The central idea is to promote the greatest overall good or
minimize harm for the greatest number of people. Under this ethical framework,
the morality of masturbation would depend on its impact on individual well-being
and societal welfare.

Consequentialists standpoint argue that excessive indulgence in solitary
pleasure could have detrimental effects on personal well-being and social
interactions. They assert that masturbation lead to diminished motivation,
decreased sexual satisfaction with a partner, or even social withdrawal, which
can negatively impact relationships and social cohesion.


In deontological ethics, it's known for a fact that happiness "is only good on
the condition that the happiness is deserved" which is basically not the case
with these things.

In a consequentialist view, how does masturbation affect one? This is an
important question that we should ask to determine how “good” would it be to us
(if deontology were to be thrown away). I personally have the belief that it
only worked as a damper, which definitely has bad effects on one’s mettle, I
have no scientific citation for this claim, but it is my personal experience,
and I bet you have a similar one. Actually, this can be observed in animal
behavior if you have seen a cat before and after being castrated. Sexual
motivation has always been a major factor in our inducements throughout history,
some psychologists (psychoanalysis  specifically) argue that it has always been
the main motivation, and the instant dissimulation of such a motivation
throughout masturbation will definitely have a bad effect in one’s activity. #[[id:v3b25op0r1k0][Philosophy of Ethics]]

* Footnotes

[fn:2]Unless specified, I'm talking about heterosexual porn only.

* [[id:4b45b3aa-faac-4698-ba6b-b120ac166453][agenda]]                                                              :noexport:
** DONE On Pornography                                               :@write:
:LOGBOOK:
CLOCK: [2023-07-22 Sat 11:49]--[2023-07-22 Sat 13:35] =>  1:46
CLOCK: [2023-07-21 Fri 20:28]--[2023-07-22 Sat 00:36] =>  4:08
CLOCK: [2023-07-21 Fri 16:13]--[2023-07-21 Fri 19:41] =>  3:28
CLOCK: [2023-07-21 Fri 08:59]--[2023-07-21 Fri 15:39] =>  6:40
CLOCK: [2023-07-21 Fri 05:37]--[2023-07-21 Fri 08:35] =>  2:58
:END:
