:PROPERTIES:
:ID:       7vlhf73083k0
:END:
#+date: <2024-01-23 Tue 19:43>
#+title: About names

I like thinking about names, they usually reflect people's dreams and values, many times I feel devastated when contemplating names, like when find a convicted thief named Ali I usually think that their parents did find great values in the historical character of Imam [[id:pq37d981zzj0][Ali]] that they wished to recall in their child, and how sad it went. I personally believe that names have a great effect on us. Which is not debatable [from a theory-of-complexity perspective]. But how can they shape our personalities? A study once showed that boys who are given names more common among girls are more likely to develop behavioral problems when they reach puberty[cite:@figlio-2005-boys-named-sue], but the reason behind that itself is very obvious (likely to be). What about their effect on our innersole? I think there should be. The priming effect is one that proves it, however, it's very controversial, but let me tell you about it. [[id:la9ghl2083k0][Priming]] is the idea that exposure to one stimulus may influence a response to a subsequent stimulus, without conscious guidance or intention. The stimulus itself can be a [[id:nzgime0143k0][subliminal stimuli]], for example, if someone were to read you an article about people in a retirement home, your subconscious recalls old people, who walk very slow, the Priming theorists believe that this might actually cause you to walk slightly slower as result of your subconscious thinking. And if you were to experience the same thing but with talking about top football players, you might walk faster. Interesting theory no? Unfortunately it has great problems in documenting the experiments[cite:@bower-2012].