:PROPERTIES:
:ID:       q1v1r670kek0
:CUSTOM_ID: q1v1r670kek0
:END:
#+date: <2024-12-10 Tue 10:54>
#+title: The slavery of our time

I found an interesting piece by [[id:jhxdza81e3k0][Leo Tolstoy]]: https://www.marxists.org/archive/tolstoy/1900/slavery-of-our-times.html on wage labor: Slavery exists in full vigor, but we do not perceive it, just as in Europe at the end of the Eighteenth Century the slavery of serfdom was not perceived. People of that day thought that the position of men obliged to till the land for their lords, and to obey them, was a natural, inevitable, economic condition of life, and they did not call it slavery.  It is the same among us: people of our day consider the position of the laborer to be a natural, inevitable economic condition, and they do not call it slavery. And as, at the end of the Eighteenth Century, the people of Europe began little by little to understand that what formerly seemed a natural and inevitable form of economic life-namely, the position of peasants who were completely in the power of their lords-was wrong, unjust and immoral, and demanded alteration, so now people today are beginning to understand that the position of hired workmen, and of the working classes in general, which formerly seemed quite right and quite normal, is not what it should be, and demands alteration. #[[id:ydb1kfn02wj0][Modus Vivendi]]


