:PROPERTIES:
:ID:       dn5aojy0bqk0
:CUSTOM_ID: dn5aojy0bqk0
:END:
#+date: <2024-11-12 Tue 04:49>
#+title: Buying Votes

It's been said we are in the age of pricing. [[id:4fb240m099k0][The Age of Commodity]]. I had a lot of thoughts about that when I was reading this paragraph from Harper's review ([[id:klqcz9v0zfk0][“Were all going to be dead soon.”]]): In the United States, it was reported that the Microsoft founder Bill Gates, the world's twelfth-richest person, secretly gave $50 million to an organization supporting the campaign of the Democratic presidential candidate; and that the Tesla and SpaceX co-founder Elon Musk, the world's richest person, had been warned by federal prosecutors of the potential illegality of his practice of giving $1 million each day to a randomly selected swing-state voter who signed a petition for his super PAC that backs the Republican presidential candidate. [[https://www.fox29.com/news/bill-gates-not-10-wealthiest-billionaires-world-who-made-list#][^{1}]] [[https://www.nytimes.com/2024/10/22/us/elections/bill-gates-future-forward-kamala-harris.html][^{2}]] [[https://www.forbes.com/real-time-billionaires/#2bf3dcf3d788][^{3}]] [[https://www.nbcnews.com/tech/tech-news/elon-musk-defends-1-million-petition-giveaway-federal-warning-rcna177377][^{4}]] In Moldova, where last month it was reported that the Russian government had paid at least 130,000 people more than $15 million to vote against joining the European Union, authorities announced that they had identified an additional $24 million also directed toward purchasing the votes of 20 percent of the entire electorate; violence erupted at polling stations across the country of Georgia, where international observers warned of Russian “vote-buying” in its parliamentary elections and whose president said that the elections' results “cannot be accepted” and should be opposed with protests in the streets; and police in Mozambique shot and killed at least ten of the thousands of demonstrators marching against the ruling party's claim that it had just won more than 70 percent of votes nationally. [[https://kyivindependent.com/moldova-uncovers-15-million-russian-backed-plot-to-influence-upcoming-elections-with-bribes-and-disinformation/][^{5}]] [[https://kyivindependent.com/moscow-funneled-39-million-into-moldova-ahead-of-presidential-election-in-attempt-to-influence-results-moldovan-authorities-say/][^{6}]] [[https://www.politico.eu/article/georgia-president-protests-election-salome-zourabichvili-widespread-citizens/][^{7}]] [[https://clubofmozambique.com/news/cip-mozambique-elections-up-to-10-dead-in-two-days-of-demonstrations-269621/][^{8}]] [[https://www.aljazeera.com/news/2024/10/24/mozambique-ruling-party-declared-winner-of-election-amid-fraud-claims][^{9}]] Days before Uzbekistan's parliamentary elections, a would-be assassin fired five bullets at the car of the country's former head of communications, who was lobbying for reforms to protect press freedoms; and in Bulgaria, hackers published a list of more than 200 businessmen and government officials who are alleged to have bought votes under the direction of the former owner of 6 of the country's 12 largest-circulating newspapers. [[https://www.forbes.com/sites/melikkaylan/2024/10/26/a-failed-assassination-attempt-in-uzbekistan-as-it-faces-elections/][^{10}]] [[https://www.politico.eu/article/bulgaria-ethical-hacking-group-bg-elves-oligarch-delyan-peevski-election-fraud-vote-buying/][^{11}]] [[https://www.economist.com/eastern-approaches/2013/09/20/breaking-up-with-peevski][^{12}]] It was reported that an internal battle in the Iranian government over the 85-year-old ayatollah's successor would likely be won by his second son, a former de facto commanding officer in the Basij who was accused of rigging the 2009 election in favor of the incumbent, who later accused him of embezzling money from the treasury; the Vietnamese parliament elected a military general to replace its president, who, while being investigated for bribery, resigned from the presidential office he'd taken over from his predecessor, who himself had resigned after 539 of his subordinates were implicated in multiple corruption rackets; and Tunisia's incumbent president, who last month arrested dozens of members of the nation's largest opposition party, was inaugurated for a second term. [[https://www.jpost.com/middle-east/iran-news/article-826211][^{13}]] [[https://web.archive.org/web/20090621204752/http://www.atimes.com/atimes/Middle_East/KF19Ak04.html][^{14}]] [[https://english.alarabiya.net/articles/2012/01/15/188461][^{15}]] [[https://www.channelnewsasia.com/commentary/vietnam-president-vo-van-thuong-resign-cpv-national-congress-general-secretary-4211431][^{16}]] [[https://www.reuters.com/world/asia-pacific/vietnams-president-phuc-quits-blamed-ministers-violations-2023-01-17/][^{17}]] [[https://apnews.com/article/tunisia-president-kais-saied-f911f1dfc86445ef8be157a3a792e1e2][^{18}]] “Vipers,” he said at his swearing in, are “circulating.”  [[https://apnews.com/article/tunisia-president-kais-saied-f911f1dfc86445ef8be157a3a792e1e2][^{19}]] #[[id:thc4j6p02wj0][Politics]]