:PROPERTIES:
:ID:       81b61ec1b4k0
:END:
#+date: <2024-02-01 Thu 02:15>
#+title: Reading [[id:zv7b8b11j2k0][Don Quixote]]

I am considering reading Don Quixote. But I'm still unsure. I think there are
so many books that are propagated around and everywhere merely because of
pseudointellectuality. War and Peace by [[id:jhxdza81e3k0][Leo Tolstoy]] was one of those novels
that I had a similar experience with. It's one of the most unreadable novels
in my opinion, however, it's always considered either #1 or #2 best works by people who
post book ratings on [[id:1g48iao02wj0][book communites]]. After I read it back then, due to the
severe amount of recommendation, I was surprised that it's hardly a plain, and
very long, novel, I tried to find later someone to discuss my view with him
about the novel, I could only find people majored in literature who can discuss
it, but theoretically only, and I found out that most of the people who
recommenced it to me never actually read it. #[[id:6318fd43-4f0d-4c3b-9c83-5cadbeca2260][Literature]]