:PROPERTIES:
:ID:       0dvc5611e2k0
:END:
#+date: <2024-01-04 Thu 16:06>
#+title: A tip on post-achievement depression

I think I've a nice tip on that, although it might sounds very naive, it really
helped me personally. I think that the reason behind post-achievement depression
is that we forget why we wanted whatever we achieved or that we no longer
possess the same perspectives that made us want that thing, the reason behind
that is usually the long period that is dedicated on achieving it, in which you
are likely to change more. That's why it's most common in [[id:j242xt40xyj0][academia]] especially
with people getting their Ph.D after 5 years of work or even more. So basically
we forget why we want something and how we felt towards wanting it (think of it
like someone working 2 years to earn an Ijazah believing it to be a great
achievement, but they turn atheist in the second year). So my tip is basically a
usage of intensive imagination in a different stages of what we want.

And this does not have to be a protection from depression to be honest, but it

can be used as a refreshing method to really understand our passions and what we
"really" want (not what we ought to by collective consciousness or propaganda):
think of yourself getting it and estimate your happiness or satisfaction.

- [2025-04-12 Sat 18:40] As of now, I'm not really sure if this method will work
  properly for most people, as most of us generate these delusional views about
  how things are going to be like after the achievement. See also: [[id:yh144x4121k0][On Depression]]. #[[id:ydb1kfn02wj0][Modus Vivendi]]