:PROPERTIES:
:ID:       ffc2i8a0ahk0
:CUSTOM_ID: ffc2i8a0ahk0
:END:
#+date: <2024-12-18 Wed 05:06>
#+title: Jean Baudrillard theory on Adult Content

I wrote about the [[id:yh5juz019wj0][Industry and Consumption of Pornography]] a while ago. Today I learnt that [[id:91y900c06fk0][Jean Baudrillard]] has a related theory[cite:@lenoir-2023-philos-desir p.45] that reminded me of the Social Learning theory in the [[id:wwgil641edk0][sociobiological theories of rape]]: Jean Baudrillard wrote the following maxim: "Sexuality does not hide in tolerance, repression, or morality, it is certainly hidden in what is more sexual than sex itself: pornography." In Baudrillard's view, the global success of pornography is not a result of sexual liberation but rather the triumph of capitalism, which turns everything into a commodity, including bodies that lose their ability to enjoy and experience desire. Hans Blüher continued where Baudrillard’s works left off and tried to show that the transition from sexual desire to pornography marks the boundary of the "unforgivable violation" with absolute permission—driven immediately by the urge to fulfill expectations and fantasies. This, he claims, signals the end of otherness in sexual and romantic relationships. The body of the other is consumed and discarded as if it were a consumable and disposable object. The desire for the other becomes a desire for oneself alone. We now strive for comfort, safety, and ease in the field of unity and isolation. Today’s love is free of all excess and all sin (...). Eros aims for the other in an emotional sense, yet does not allow itself to recover in the system of the self. In this identical, increasingly homogeneous society, contradictions no longer exist, and hence no erotic experience. This assumes a state of both internal and external dissonance.