:PROPERTIES:
:ID:       imngbvs01ek0
:CUSTOM_ID: imngbvs01ek0
:lang: ar
:subtitle: Incompetence by Abbass Braham
:ROAM_ALIASES: incompetence
:END:
#+title: عدم الكفاءة
#+DATE: <2024-11-17 Sun 09:21>


[[https://x.com/abbassbraham/status/1414250711341309952][إنّ]] تفاهة الخصم مُحبِطة، لأنّ الواحِد يحلُم بمبارزة شريفة وصراع التيتان. ولكن نيتشة دعا للنظر
للجانِب الممتلئ. قال: "أحياناً لا يبقى المرأ وفياً لقضية إلاّ لكونِ خصومِه لا ينفكّون عن
التفاهة".

[[https://x.com/abbassbraham/status/1292161573960716290][ثمّ]] إنّني شاهدتُ كيف ينعكِسُ عدم الاحتراف والإتقان حتّى على الناس في ممارسة عقائدهم اليومية.
فشاهدتُ متصوفّة لا يُحسِنون التصوّف؛ وسلفيين لا يُحسِنون التسلّف؛ ومصلين لا يُحسِنون الصلاة. دع عنك
النظرية جانِباً فإنّما أتحدّث عن عدم إتقانِهم للممارسة الأهلية نفسها.

و[[https://x.com/abbassbraham/status/1467491830426222593][لا]] يمتلِك المحاجِج الرديء خارِطة طريق في النقاش. فيضيع فيما هو عارِض وغير صميم. بالنهاية يلتفُّ
حبل المحاججة على عنقه وهو لا يدري. تُخاضُ المحاججات باستراتيجيات الحروب: توضَع فيها كمائن
وأشراك ويترَك المحارِب الردئي يتعالقَ مع الطُعم فيفوتُه الطلَب.

[[https://x.com/abbassbraham/status/1005385072525041664][فإنما]] يُحاجَجُ: (1)من يأتي بمحاججة؛ و(2)يحتكِمُ للأدلّة؛ و(3)تُلزِمُه الحجّة إذا ألزمته؛ و(4)يتقيّد
بالموضوع؛ و(5)يُناقِشُ في وعيٍ بالتقاليد الجِدالية في الموضوع المطروح. الباقي هذَر ومِراء.

[[https://x.com/abbassbraham/status/1332351835399737348][وواقِع]] الأمر أنّ فقيد الأمّة هو الإتقان. فمع العصر الافتراضي حاز الذكر بالسبق على الإنجاز.
وصارت صيحة الحرب لهؤلاء هو أن يُحمَدوا بما لم يفعَلوا.

ف[[https://x.com/abbassbraham/status/1499492500754649105][أقصى]] ما يمكن للمرء أن يطلبه بخصوص الأعداء ليس انعدامَهم، بل الظفر بالنوّع العاقِل منهم.
فالغريم- تماماً كالمُلاعِب- تُطلَب منه المهارة.

[[https://x.com/abbassbraham/status/1545450958863360000][وأوّل]] عدم الكفاءة شخصنة الخلافات. لأنّ الذم والثلب يعني عدم القُدرة على التعرّف على مواطِن
الصراع، والانتقال بالمعرَكة إلى أرضية أخرى. وفي غضون هذا تُخسَر البيادِق على الأرضية الحقيقية،
أرضية الأفكار والوقائع والاستراتيجية.

ف[[https://x.com/abbassbraham/status/1566050473408331777][العدو]] النبيل يرتقي بالصراع، أمّا الضعيف فيجذب الخصومة إلى الحضيض. العداوة مسؤولية بين
 عقلين. الشريف كالنسر: يتقاتَل في عنان السماء، لا في الطمي. يحترِم عدوّه ويعترف له، بل ويرثيه
 لأّنه لا يُعادي إلاّ في الأعالي. النفس الساميّة تقدر على الترفّع.

[[https://x.com/abbassbraham/status/1566052529036738563][فالخصومة]] هي معاداة أفكار ومواقِع الناس. أمّا الحقد فهو الغيلة: وهو كره الناس أنفسهم. في كلّ
الآداب الملحمية من عنترة إلى رولاند وسيف بن ذي يزن وصلاح الدّين يمايز المحارب الجيّد، الذي
يعادي التموقعات، عن الركيك الذي يأكُل الأكباد.

[[https://x.com/abbassbraham/status/1566065026049392641][والعدو]] النزيه تضع يدك في يده: "اسمع، لقد أوقعنا القدر في هذا الشيئ. والآن دعنا نستفيد منه
بأن نخوض نزالاً يليق بنا". أمّا العدو الأخرق فيبدأ بـ"علي وعلى أعدائي". ويخوض المعركة على
مستوى الركاكة: من هجاء وتلفيق وشتيمة ونميمة ودسيسة.

[[https://x.com/abbassbraham/status/1450473540520656904][ومن]] القيم النبوية الاحتراف: "لا ينبغي للمرء أن يُذّل نفسَه" قالوا: وكيف يُذلّ نفسه؟ قال: يتعرّضَ
من البلاء ما لا يُطيق."

[[https://x.com/abbassbraham/status/1079305530504433664][وجماعات]] عدم الاحتراف هي عينها جماعات الطّيش. وهي تتخلّى عن احترافِها طيشاً: أي لقولِها بعدم
نجاعة الاحتراف، وليس فقط بافتقارِها إليه.

[[https://x.com/abbassbraham/status/1291110890155147264][ومن]] مشاكِل جماعات عدم الكفاءة هو أنها: 1-لا تعرِف كيف تُحسِن الخلاف فسرعان ما يتحوّل إلى فجور
وثأر. و2-لا تعرِف كيف تُحسِن المشاركة، فتتحوّل المسايرة إلى منافَرة. و3- لا تعرِف كيف تزن
تجارِبَها وتتحمّل مسؤولياتها في الإخفاق، فسرعان ما تلقي باللائمة على الغير وتخسَر قيمة
التجربة.

[[https://x.com/abbassbraham/status/1292113312600268801][لا]] تعرِف جماعات عدم الكفاءة المقامات والمراتِب. ولا تعرِف ما هو فاصِل وتاريخي. فتتحرّف للقتال
غير مدرِكة لأوان الحرب. فتراها تُشعِل حرباً على مسِّّ الحصى أو على تغريدة دون أنْ تكون تحريكاً
للبيادِق. ومعظَم طاقاتِ هذه الجماعات مهدورة أو سلبية أو تؤدِّي إلى عكسها.

[[https://x.com/abbassbraham/status/1423365538722598914][لا]] بد لجماعات عدم الكفاءة أن تخصِف على نفسِها من زعمٍ يُغطي على تهافُتها: قداسة، علم لدني،
بشارات إلهية، مرائي، مهداويات، دم أزرَق، اصطفاء، مصير قومي، حتمية تاريخية، إلخ

[[https://x.com/abbassbraham/status/1445097312041136147][فجماعات]] عدم الكفاءة تُغطِّي على زيفِها بالاعتقاد أنّها ستتعلّم قواعِد اللعبة لدى الوصول. وهذه هي
حيلة باغي التوظيف، الذي يُضخِّم سيرته المهنيّة على أساس أنّه سيتعلّم المواهِب التي زعمها بعد
التوظيف. فهو نوعٌ من نيل المطالِب بالتمّني.

[[https://x.com/abbassbraham/status/1293240525739499523][فاحذَر]] أنْ تكون عداواتك نخوية، لا ذهنية؛ وحملاتك هشتاقية، لا استراتيجية؛ وأفكارُك ائتمارية، لا
تدليليّة. فذلك أوّل الهوان. #[[id:7sq9bk71x2k0][Abbass Braham, fragments]]
