:PROPERTIES:
:ID:       1uw1fd21udk0
:END:
#+date: <2024-10-17 Thu 18:27>
#+title: Abdel Wahab al-Messiri, Paul Fussell and Kagi

- [2025-10-24 Fri 13:29] \\
  Found a video of Messiri talking about his model and the incident. https://youtu.be/qs7Dp8ckFO8
:DATE:
[2024-10-17 Thu 18:27]
:END:
I was reading Messiri's "[[id:356ikhg02ck0][Rehlati al-fikriah]]", and he mentioned something very interesting there about [[https://en.wikipedia.org/wiki/Paul_Fussell][Paul Fussell]], the renowned literary historian, apparently he was one of his PhD external examiners. But that's not the interesting thing, it is what he mentions about him: being a homosexual pervert. I was shocked from the information that Messiri mentioned about him, that I quickly jumped to Wikipedia searching for anything with the keyword "gay", "homosexual", etc.. Nothing (surprisingly) was there, I started to think that Messiri might have linked to some other Paul Fussel. I then tried to search Google with keywords like "homosexual" "Paul Fussel", still, nothing there. I was finally certain that either Messiri is talking about someone else, or this information were discrete. Then I read a post on HN that was talking about Kagi, a less screwed (suckless) search engine, it quickly linked me to the information Messiri mentioned about Fussel (his wife article about their relationship and how he would like to enter a room full of guests naked) https://www.youtube.com/watch?v=wnacdOIoTBQ I don't frequently post here, or anywhere, unlike past times. Lately I explored one of my friend's music library, he told me how it's extremely diverse, he was correct about it. I later wondered if that has anything to do with a disorder that he suffers from, which relates to his ear. I wonder if how his music changes has anything to do with how that acoustic  disorder affect his music taste. I also wondered if there's anything about me that affects my frequency of writing here. Sometimes it's fascinating —even if you believe in free will— how unfree we might be. How we might have the wrong ideas because the search engine chooses not to be helpful enough, or have different views due to a biological state. [[id:tixkcwk0gwj0][Related]].