:PROPERTIES:
:ID: uhej5u91bhk0
:lang: ar
:subtitle: The Poet
:END:
#+title: الشاعر
#+DATE: <2025-02-15 Sat 03:04>
كان المعري يذكر اسم من يقتبسه، فلو اقتبس من النابغة الذبياني شيئًا يقول: "قال
الذبياني" أو "قال الفرزدق" وهلم جرا، ولكن إذا ما اقتبس من المتنبي كان يقول "قال
الشاعر" وكأنه لا شاعرٌ سوى المتنبي. وللمتنبي كثير في المعنى، فما كان يرتضي لفظة
"شاعر" غير لنفسه، فوصف من يعانده من الشعراء الآخرين [[id:727bjwe0bck0][قائلًا]]:

#+begin_verse
أَفي كُلِّ يَومٍ تَحتَ ضِبني شُوَيعِرٌ
ضَعيفٌ يُقاويني قَصيرٌ يُطاوِلُ
#+end_verse

فيصغر باقي الشعراء على نفسه. [[id:7wfc6m81udk0][وله]] أيضًا:

#+begin_verse
أَرى المُتَشاعِرينَ غَروا بِذَمّي
وَمَن ذا يَحمَدُ الداءَ العُضالا
#+end_verse
وللمتنبي باع طويل في التصغير. [[id:06j6ceq03fk0][فيقول]]:

#+begin_verse
أذم إلى هذا الزمان «أهيله»
 فأعلمهم فدم وأحزمهم وغد
#+end_verse

وكتب عباس محمود العقاد في كتابه "مطالعات في الكتب والحياة" فصلًا عن التصغير عند
المتنبي، ولأيمن العتوم الكثير من المقاطع على النت عن ولع المتنبي بالتصغير.
المهم، أن المتنبي كان يُصغر باقي شعراء عصره، وكان المعري لا يرى شاعرًا سواه.
وللمتنبي أيضًا كثير في هذا الوصف، فيقول:

#+begin_verse
خَليلَيَّ إِنّي لا أَرى غَيرَ شاعِرٍ
فَلِم مِنهُمُ الدَعوى وَمِنّي القَصائِدُ
#+end_verse

أي: لا أرى شاعرٌ سواي. وفي نفس القصيدة في البيت التالي يقول ألا سيف سوى سيف الدولة:

#+begin_verse
فَلا تَعجَبا إِنَّ السُيوفَ كَثيرَةٌ
وَلَكِنَّ سَيفَ الدَولَةِ اليَومَ واحِدٌ
#+end_verse

ويقول له أيضًا:

#+begin_verse
فَنَحنُ الأُلى لا نَأتَلي لَكَ نُصرَةً
[[id:73g8ps80mik0][وَأَنتَ الَّذي لَو أَنَّهُ وَحدَهُ أَغنى]]
#+end_verse

طيب الله ثراه. #[[id:nk2kigk0ybk0][al-Mutanabbi]]
