:PROPERTIES:
:ID:       16ikbws0tfk0
:CUSTOM_ID: 16ikbws0tfk0
:END:
#+date: <2025-10-20 Mon 21:16>
#+title: [[https://twitter.com/ohreallytruly/status/1491569252809117699][Chomsky connection with Jeffrey Episten]]

Years ago, a meeting between Noam Chomsky and Episten was highly discussed on the r/Chomsky subreddit. I didn't give it much attention because I know how Dr. Chomsky rarely does research of the people [[https://www.hustlingtheleft.com/chomsky/][he conducts interviews with]]. However, doing some research now I can see that Episten was kinda of an octopus of connections. Apparently, Epstein had a lot of philanthropy work, worked with MIT professors, funded multiple universities and had met with many figures in the scientific and intellectual community, Chomsky just happens to be one of them [[https://www.science.org/content/article/what-kind-researcher-did-sex-offender-jeffrey-epstein-fund-he-told-science-he-died][more on that here]]. Regarding the funds, Chomsky [[https://www.theguardian.com/us-news/2023/may/17/jeffrey-epstein-noam-chomsky-bard-college-president][explained]] that it was from his own money "In response to questions from the Journal, Chomsky confirmed that he received a March 2018 transfer of roughly $270,000 from an Epstein-linked account. He said it was “restricted to rearrangement of my own funds, and did not involve one penny from Epstein". Anyway, I think that Chomsky's personal life matters or should be associated in consideration of his ideas or works. #[[id:da1by2o0eqk0][Jeffrey Episten]] #[[id:5a780a66-e9ff-4712-8269-3d1cd1556c95][Noam Chomsky]]


- [2025-11-15 Sat 20:46] \\
  https://www.youtube.com/watch?v=xgEUAM1s6vc
:LOGBOOK:
CLOCK: [2025-10-20 Mon 21:04]--[2025-10-20 Mon 21:41] =>  0:37
:END:
