:PROPERTIES:
:CUSTOM_ID: jly77mb1ohk0
:ID: jly77mb1ohk0
:END:
#+title: Something Worth Living For
#+DATE: <2025-02-25 Tue 00:21>
Henry David Thoreau, Journal, March 31, 1852 (emphasis mine):

#+begin_quote
Why the moaning of the storm gives me pleasure. Methinks it is be cause it
puts to rout the trivialness of our fair-weather life and gives it at least
a tragic interest. The sound has the effect of a pleasing challenge, to call
forth our energy to resist the invaders of our life's territory. It is
musical and thrilling, as the sound of an enemy's bugle. Our spirits revive
like lichens in the storm. There is something worth living for when we are
resisted, threatened. As at the last day we might be thrilled with the
prospect of the grandeur of our destiny, so in these first days our destiny
appears grander. What would the days, what would our life, be worth, if some
nights were not dark as pitch,—of darkness tangible or that you can cut with
a knife? How else could the light in the mind shine? How should we be
conscious of the light of reason? If it were not for physical cold, how
should we have discovered the warmth of the affections? I sometimes feel
that I need to sit in a far-away cave through a three weeks' storm, cold and
wet, to give a tone to my system. The spring has its windy March to usher it
in, with many soaking rains reaching into April. Methinks I would share
every creature's suffering for the sake of its experience and joy. The song
sparrow and the transient fox-colored sparrow,—have they brought me no
message this year? Do they go to lead heroic lives in Rupert's Land? They
are so small, I think their destinies must be large. Have I heard what this
tiny passenger has to say, while it flits thus from tree to tree? Is not the
coming of the fox-colored sparrow something more earnest and significant
than I have dreamed of? Can I forgive myself if I let it go to Rupert's Land
before I have appreciated it? God did not make this world in jest; no, nor
in indifference. These migrating sparrows all bear messages that concern my
life. I do not pluck the fruits in their season. I love the birds and beasts
because they are mythologically in earnest. I see that the sparrow cheeps
and flits and sings adequately to the great design of the universe; that man
does not communicate with it, understand its language, because he is not at
one with nature. I reproach myself because I have regarded with indifference
the passage of the birds; I have thought them no better than I.
#+end_quote

URL: https://thematamixta.blogspot.com/2025/01/something-worth-living.html #[[id:ydb1kfn02wj0][Modus Vivendi]]
