:PROPERTIES:
:ID:       qvz6ot50hqk0
:CUSTOM_ID: qvz6ot50hqk0
:END:
#+date: <2025-10-22 Wed 21:07>
#+title: The life of [[id:0zif2xf0dqk0][Pellizza da Volpedo]]

I enjoyed this week of going through de Volpedo's art. It was very interesting. When I saw that he died before aging 40 I thought "greats die young", attributed his death to his life-style. Little I knew that he committed suicide. The Wikipedia page about him sneaks that information real quick "It seemed the beginning of a new period of favour, in which finally artistic and literary groups would recognize the themes of his work. However, the sudden death of Pellizza's wife in 1907 threw the artist into a deep depression. On 14 June of the same year, Pellizza hung himself in his Volpedo studio. He was not yet 40." His story with [[id:n93cgz50hqk0][Giovanni Segantini]] is as equally tragic. I wonder if any media works, novels, or the like portrayed this tragic life of his. #[[id:mvk9gc7014k0][Art]]

- [2025-10-24 Fri 02:16] \\
  I tried to look for anything that documents his life or letters, but in vain.
:LOGBOOK:
CLOCK: [2025-10-24 Fri 02:14]--[2025-10-24 Fri 02:20] =>  0:06
:END: 
