:PROPERTIES:
:ID:       xdykbzb0eok0
:CUSTOM_ID: xdykbzb0eok0
:END:
#+title: On Solitude and Other Things
#+date: <2025-08-27 Wed 02:01>

William Rounseville Alger, The Solitudes of Nature and of Man; or, The Loneliness of Human Life (Boston, Roberts
Brothers, 1867), 122-24, 126: (emphasis mine):

 The man who separates himself from mankind to nourish dislike or contempt for them, has in him a morbid element
 which must make woe. True content, a life of divine delight, cannot be attained through a sense of superiority
 secured by thrusting others down; but only through one secured by lifting ourselves up, by communing with
 the great principles of morality, contemplating the conditions of universal good, laying hold of the will of
 God. Whoso would climb over a staircase of subjected men into a lonely happiness, will find it misery when he
 arrives. To be really happy one must love and wish to elevate men, not despise and wish to rule them. There is
 nothing in which the blindness and deceit of self-love is more deeply revealed than in the supposition with which
 misanthropic recluses frequently flatter themselves, of their complete detachment from other men, their lofty freedom.
 Spatial separation is not spiritual independence. Of all men the man-hater is the one who is fastened to his
 fellow-men by the closest and the most degrading bond. Misanthropy, as a dominant characteristic, if thoroughly
 tracked and analyzed, will be found almost always to be the revenge we take on mankind for fancied wrongs it has
 inflicted on us, especially for its failure to appreciate us and admire us according to our fancied deserts. The powerful
 and savagely alienated Arthur Schopenhauer, who said that, in order to despise men as they deserved, it was
 necessary not to hate them, was embittered, almost infuriated, by disappointment in not obtaining the notice he
 thought he merited. He came daily from his sullen retreat to dine at a great public table where he could display his
 extraordinary conversational powers. He eagerly gathered every scrap of praise that fell from the press, and fed on it
 with desperate hunger. He sat in his hotel at Frankfort, in this age of newspapers and telegraphs, a sublimer
 Diogenes, the whole earth his tub. An apathetic carelessness for men shows that we really despise them, but an
 angry and restless resentment towards them betrays how great a place they occupy in our hearts. Diogenes and
 Alcibiades were equally dependent on public attention; the one to feel the enjoyment of his pride and scorn intensified
 by the reaction of hate and admiration he called forth; the other to feel the similar fruition of his vanity and sympathy. .
 . . The greatest egotists are the most fond both of retirement and publicity. There they lave their wounds with the
 anodyne of self-love; here they display their claims to admiration. The truly great and healthy man is not
 dependent on either, but draws blessings out of both,—resolve, inspiration, consecration, sanity. In both he
 pleases himself by improving every possibility of indulging in sentiments of respect and affection towards
 his race.

 The great danger of the courters of solitude is the vice of pampering a conviction and feeling of their own worth by
 dwelling on the ignobleness of other men. They are tempted to make the meanness and wretchedness of the world
 foils to set off their own exceptional magnanimity. They need especially to guard themselves against this fallacy
 by laying bare to their own eyes the occult operations of pride and vanity. An efficacious antidote for their
 disease is a clear perception of the humbling truth of the case, of the ignoble cause of the disease. For it is
 unquestionably true that the man who despises the world, and loathes mankind, is usually one who cannot enjoy the
 boons of the world, or has been disappointed of obtaining from his fellows the love and honor he coveted. He then
 strives to console himself for the prizes he cannot pluck, by industriously cultivating the idea of their
 contemptibleness. Rousseau demanded more from men than they could give him. His brain and heart were pitched
 too high; with the fine intensity of their tones the cold and coarse souls of common men made painful discords.
 Instead of wisely seeing the truth, and nobly renouncing his excessive exactions, he turned against the world and
 labored with misanthropic materials to build up his overweening self-love. Of course he was not conscious of this
 himself. It was a disease, and, fleeing from all antidotes, it fed in solitude; whence he looked abroad and fancied that
 he saw his contemporaries leagued in a great plot against him.

 . . . Thousands have been impelled to solitude by resentment,—as the hermit confessed to Imlac he was,—where one
 has been led to it by devotion. The true improvement of our lonely hours is not to cherish feelings of superiority to our
 neighbors, but to make us really superior by a greater advancement in the knowledge of truth, the practice of virtue,
 communion with the grandeurs of nature, and absorption in the mysteries of God. He who is continually exercising
 scorn towards the pleasures of society and the prizes of the world, is one who has failed in the experiment of
 life and been soured by his failure. The truly successful man appreciates these goods at their genuine
 value,—sees that in their place they have sweetness and worth, but knows that there are other prizes of
 infinitely higher rank, and is so content with his possession and pursuit of these latter as to have no
 inclination to complain of the deceitfulness and vileness of the former. To dwell alone is an evil when we use
 our solitude to cherish an odious idea of our race, and a disgust for the natural attractions of life. It should be
 improved, not negatively for dislike and alienation, but positively to cultivate a more earnest love for higher mental
 pursuits, choicer spiritual fruitions, than the average community about us are wonted to. Scorn for man, disgust for
 the world, is no sign of strength, loftiness, or victory, but rather a sign of weakness, defeat, and misery. “The
 great error of Napoleon was a continued obtrusion on mankind of his want of all community of feeling for or with
 them.” He deceived himself in fancying his ruling feelings unlike in kind to those of the bulk of men; they were the
 same in sort, only superior in scale and tenacity, and in the greater stage on which they were displayed.

URL: https://thematamixta.blogspot.com/2024/10/on-solitude-isolating-oneself-from.html #[[id:ydb1kfn02wj0][Modus Vivendi]]
