:PROPERTIES:
:CUSTOM_ID: im0655n0shk0
:ID: im0655n0shk0
:END:
#+title: Let no man seek to make it easy
#+DATE: <2025-02-27 Thu 00:21>

[[id:2a92650b-2c62-4c4a-86d4-fcb377d2b100][Carl Jung]], “The Love Problem of a Student,” in Civilization in Transition
(Princeton: Princeton University Press, 1978, vol. 10 of the Collected Works),
§§231-2, 111-112:

. . . Love requires depth and loyalty of feeling; without them it is not love but mere caprice. True love will always commit itself and engage in lasting ties; it needs freedom only to effect its choice, not for its accomplishment. Every true and deep love is a sacrifice. The lover sacrifices all other possibilities, or rather, the illusion that such possibilities exist. If this sacrifice is not made, his illusions prevent the growth of any deep and responsible feeling, so that the very possibility of experiencing real love is denied him.

Love has more than one thing in common with religious faith. It demands unconditional trust and expects absolute surrender. Just as nobody but the believer who surrenders himself wholly to God can partake of divine grace, so love reveals its highest mysteries and its wonder only to those who are capable of unqualified devotion and loyalty of feeling. And because this is so difficult, few mortals can boast of such an achievement. But, precisely because the truest and most devoted love is also the most beautiful, let no man seek to make it easy. He is a sorry knight who shrinks from the difficulty of loving his lady. Love is like God: both give themselves only to their bravest knights.

URL: https://thematamixta.blogspot.com/2024/12/let-no-man-seek-to-make-it-easy.html #[[id:a4154d94-7914-48ce-bcd8-025ac0608d5b][Philosophy]] #[[id:ydb1kfn02wj0][Modus Vivendi]]
