:PROPERTIES:
:ID:       sljh9tm01nk0
:CUSTOM_ID: sljh9tm01nk0
:END:
#+date: <2025-07-20 Sun 23:59>
#+title: [[https://www.marxists.org/][Marxists Internet Archive]]

I spent some time today reading about the Maxist Internet Archive history. I
used to contribute to the Arabic section back in the day before realizing that
this was not really helpful[fn:3]. Anyway, I found it quite funny that it didn't
take them much time to have their first fight: " By 1996 the website, Marx.org,
was hosted by a commercial ISP. This was followed by an increased activity from
the volunteers. In the following years, however, a conflict developed between
the volunteers working on the website and Zodiac, who retained control of the
project and domain name. As the scope of the archive expanded, Zodiac feared
that the opening toward diverse currents of Marxism was a "slippery slope"
toward sectarianism. The volunteers who had been undertaking the work of
transcribing texts resented having little influence over the way in which the
archive was organized and run. In early 1998 Zodiac decided that Marx.org would
return to its roots and that all writers other than Marx and Engels would be
removed.


[fn:3] I'm not talking here about Marxism, but contributing to Arabic
translation, such contributions are not really helpful at this point, as you
can not reach such an advanced point in learning something without mastering the
lingua de franca.
