:PROPERTIES:
:ID:       msribvy0vqk0
:CUSTOM_ID: msribvy0vqk0
:END:
#+date: <2025-10-29 Wed 23:51>
#+title: Waiting and Music

Some quick notes I had recently. 1.  If you play Jeno Jando's performance of Hungarian Rhapsody No. 2 (C Sharp Minor, S244), and you listen really really carefully to the part in which he starts with the famous friska, you can hear him humming. Which is very spectacular, in my opinion. 2 Dmitri Shostakovitch wrote about waiting in his journals. I don't have access to it right now and I can't rephrase it because I read it very long time ago. As of now (me writing this), he was correct about a lot of points.  3. Most engineering disciplines have a distinction between "waiting" and "blocking". Usually waiting is purposeful and justified (an ongoing process we must await). On the other hand, blocking is usually seen as a symptom of poor design. Most of the waiting I experience is blocking. 4. Everyday I walk myself into a state of well-being and walk away from every illness. I have walked myself into my best thoughts, and I know of no thought so burdensome that one cannot walk away from it [Soren [[id:qn03i1a1e3k0][Kierkegaard]]] 5. The world lost a lot from transforming the concept of playing from having joy and fun with others using tools and rocks, to sitting in front of a computer monitor staring at pixel dots. #[[id:ydb1kfn02wj0][Modus Vivendi]] #[[id:lfoaq730yck0][Music]]
