:PROPERTIES:
:ID:       z6s48l31ook0
:CUSTOM_ID: z6s48l31ook0
:END:
#+date: <2025-09-03 Wed 23:59>
#+title: Aang realizing it's a long journey

In ATLA, the episode S01E03 ends in a way that I just noticed it in a rewatch
I'm makign now. Aang is realizing that the world he knew and loved is no longer
there again for him, however, the realization is not there yet until he is
saying goodbye to his home, flying away from it, looking at it and contemplating
his memories that will never be revived again, and thinking of how it is going
to be a very long journey in this new world he spawned into. How ironic that I
watched this as a kid, with memories that I yearn everyday to revive, but will
never be able to. It's really a spectacular scene. And a spectacular show.

- [2025-09-06 Sat 15:03] \\
  I still wish I could learn how to be a good teacher like Iroh was. My
  exeperience has teached me that I'm terrible at teaching, not exactly at
  transfering knowledge (in which I believe I'm outstanding) but in keeping my
  temper when my students do not get what I'm saying, or do not apperciate it. We
  call this in Arabic [[https://t.me/IneffableText/1365][Holm]].
- [2025-09-06 Sat 15:00] \\
  I learned a lot from this show as a kid. I learned responsability and sacrifice.
- [2025-09-06 Sat 02:16] \\
  I'm rewatching the show slowley for the fisrt time now, and I'm realizing how
  absurd was the reason that made Katara hate Jack a lot. I always remembered him
  as her cheater ex-boyfriend who lied to her horribly. I even remember believing
  that he tried to trade Aang with the fire nation at least (that's how I was
  trying to understand why Katara hated him that much), founded that he just lied
  to her about destroying a settlement. I personally agree with views like his:
  there is no victories without some loses (can't make an omelet without breaking
  some eggs), and I think it was not that big of a reason to hate on Jack (well,
  maybe his dishonesty?). It's a bit sad that we had to live with a leftover like
  Jack in the show.
- [2025-09-04 Thu 02:16] \\
  https://www.youtube.com/watch?v=_6FbPLEW_p4 I uploaded the scene.
