:PROPERTIES:
:ID:       inf7qkj0r1k0
:END:
#+title: The National Anthem
#+DATE: <2023-12-17 Sun 23:20>
#+cite_export: csl ieee.csl

#+BEGIN_propert
{{{s}}} [[id:4swh72s0s1k0][Postmodern Abyss: Black Mirror]]
#+END_propert
#+begin_postscript
This post is highly based on [cite:@collins-2019-nation-anthem]
#+end_postscript

#+BEGIN_PREVIEW
This is going to be the first episode from a series about my favorite anthology
TV show: Black Mirror (2011). It's also about its first episode: The National
Anthem.
#+END_PREVIEW


Black Mirror is one of the cinematic works that I personally believe has a very
high level of /subliminal messaging/ in a way that makes it has a large domain
of viewers (which is a main interest for streaming services, for revenues) but still
present a sophisticated philosophical assertion. It might relate to the popular
movie —that I admire as well— V for Vendetta (2005) which many people liked for
different reasons: the action adventure, the ambiguous romantic relationship, the
anarchism vibes, the anti-anarchism vibes (catholic monarchist V), etc.

While many people like about Black Mirror its anthologist and thriller style, what
attracts me really is the philosophical reflections.
-----

* Is it ever okay to {something bad most of the times}?
:PROPERTIES:
:ID:       sxb2fsp0r1k0
:END:

#+BEGIN_tag
{{{t}}} [[id:v3b25op0r1k0][Philosophy of Ethics]]
#+END_tag

The episode starts with a sudden great epiphany of the Prime Minister Michael
Callow knowing about the kidnapping of one of the Royal family, a beloved known
princess named Susannah, as a ransom, the kidnapper demand the PM of a very
indecent sexual act, that is to have sex with a pig.

Before going more into the plot details which is still much interesting, a moral
question has been just asked: if there a demand $X$ that might cause the hurt
$Y$, however, it will has a terminus of goodness $Z$ like saving the life of
something of someone, or even some people, what action should be taken?

In the example of our PM $Z$ is saving the life of the princess and $Y$ would be
traumatizing the PM (and also hurting the pig if animal rights are to be taken
in this example). This question might have a harder version that would put the
risk not on someone reputation but someone's physical safety or life, for
example, sacrificing one life for 10 people.

As of Callow understanding the demand and asserting his position while querying
for his coworkers', he states directly "I'm not fucking a pig, that's not
happening". This form "I'm not fucking a pig" while said in the mere focus in
Callow's interest (saving himself), it abstracts the problem totally to what
seems an indecent action "fucking a pig", this sentence could be taken from any
context and be still sound. It's the same as "I'm not killing anybody", "I'm not
lying to my wife".

This kind of abstracting the act to decide its rightness or wrongness —which is
the view everyone in the show starts with— is called [[id:0ay33tp0r1k0][deontological ethics]], which
means that "the morality of an action should be based on whether that action
itself is right or wrong under a series of rules and principles, rather than
based on the consequences of the action". So in traditional deontological
ethics, we should not study the consequences of lying to someone, for example
lying to a thief or a murderer, because lying should be always wrong.
Contemporary deontological theorists like John Rawls thinks that in such cases
we should have a "moral weight" to consider.

The moral weight of the demand is neglected initially in Callow's statements
and his interest in self-dignity is evident.

"I do not understand, why it is not on the news?" a commoner asks while watching
the princess YouTube video, meanwhile in UKN, a popular national TV news agency,
headquarter colleagues are discussing whether to voluntarily complain with the
government media notice request not to broadcast this event, or to make the best
of the capitalism of crisis and be the exclusive media provider and profit, "A
woman's life is at stake" what seem to be a team leader cries, however, he
quickly gives up once he finds out that he would be the only one respecting his moral
obligation, as he knows that many other news media are broadcasting it.

As mentioned, other philosophical views on moralities are presented throughout
the episode and we will see how and which events affect the participants views
on what happens, let's quickly talk about one other ideology in advance; we have
seen that traditional deontological ethics does not really care about the
consequences of the event, unlike it, [[id:yix9gup0r1k0][consequentialism]] suggests than the
morality of any action merely depends on the consequences of that action.  is
considered to be one of the consequentialism theories thatprescribe actions that
maximize happiness and well-being for all affected individuals and take the
action that will maximize the goodness, so we should take the life of princess
Susannah, the effect of her death on the society, the effect of having the
sexual intercourse on Callow's family and reputation.

* A preview of the worthy propaganda filter
:PROPERTIES:
:ID:       7xp5k5q0r1k0
:END:
#+BEGIN_tag
{{{t}}} [[id:9kk956p02wj0][Propaganda]]
#+END_tag
The identifiable victim effect is the tendency of individuals to offer greater
aid when a specific, identifiable person ("victim") is observed under hardship,
as compared to a large, vaguely defined group with the same need
[cite:@jenni-1997-explain-ident].

The identifiable victim effect (IVE henceforward) is a commonly used filter in
everyday media, whether intentional or unintentionally. A current example of it
is in the ongoing war on Gaza that caused so far the death of more than 10,000
children in Gaza, however, lots of media campaigns were about the kidnapped
teenagers and children, who were about 10 to 50. People do not really put weight
on the 50 Israeli kids more than they would put on 10,000 Arab child
(hopefully), but humans intuitively would put their attention on something that
is constantly streamed into their views, and much more identifiable.

This is used commonly on media, take cancer charities for example, most of the
time they advertise for a single story that might sound the most touching one
for viewers instead of presenting the fact that they have so many other cases,
some of them might be even more critical but it would be either less effective
for them to market, or it might be disrupting to show them on advertisement.

[[id:5a780a66-e9ff-4712-8269-3d1cd1556c95][Noam Chomsky]] in his [[id:2gjizbz0gzj0][Propaganda Model]] introduced the concept of worthy and
unworthy victims. In [cite:@chomskycontest], Chomsky used the case of the murder
of Jerzy Popieluszko in Poland (which had a very extensive and wide media
coverage) versus the murder of hundred religious participants in Latin America.

In nutshell, people will show general inclination for things that they had more
inputs about, things that the media can make it experience, you can discuss the
sadness of a victim family for their lose, and that of his friends extensively
more than you can do with many others, and more than you can do with any other
story that you media may suppress.

-----

As the public think initially of the demand, all of them are deontologists: "I
do not think anyone should concede to any humiliation under threat" a commoner
explains on TV followed by other agreeing participants, a poll has shown that
the majority of the public indeed thinks that he should not take the action.

However, very surprisingly the public views shifts extremely once the media
broadcasts an experience of the princess suffering, a video showing her finger
getting cut. 86% of them gain a consensus on Callow should actually do the pig
thing. The viewers now are consequentialists, although their view of the utility
is not completely accurate.

Note that the public were aware of the princess death if Callow decide to
preserve his dignity, yet they were only touched when they were able to see a
view, an experience, of the princess suffering; if a graphic emulated media was
broadcasted instead about the slaughter of the princess it would have the same
effect on the media.

* The notion of disgust and origin of wrongfulness                    :@write:
The most thing I find very interesting about the episode is how everyone of the
viewers were interested in thriller storytelling of what will the PM do, what I
described earlier as subliminal messaging,  ignoring all the moral,
philosophical and intellectual questioning of the event and its recipients, and
by "everyone" I mean both the NPCs in the show and us, the observers.

I personally believe that this was a very interesting symbolization in the first
gate into black mirror, akin to a national anthem reciting: while everyone is
concentrated, a much more bigger interest was happening in the same scene: in
Blcak Mirror case, that's freeing the princess, for the observer, it is ignoring
everything but the main story of the PM and Susannah.

This style is very common especially in the first season, as we are going to see
in the next episode and next article, the whole episode 2 of season 1 is about
nothing but the show itself.

* Bibliography
#+print_bibliography:
