:PROPERTIES:
:CUSTOM_ID: vfi1bv910ik0
:ID: vfi1bv910ik0
:lang: ar
:subtitle: A believer eats in one intestine
:END:
#+title: المؤمن يأكل في معي واحد

#+DATE: <2025-03-11 Tue 05:15>
#+BEGIN_tag
{{{t}}} [[id:nm0dxtp02wj0][Islam]], [[id:nk2kigk0ybk0][al-Mutanabbi]] and [[id:ydb1kfn02wj0][Modus Vivendi]]
#+END_tag

يُروى أن النبي صلى الله عليه وسلم زاره رجل من الأعراب في المدينة وتعشى عنده، فملئ
له النبي وعاء اللبن أولًا فشربه، فثانيًا فشربه، وثالثًا فشربه حتى بلغ سبعة أوعية من
اللبن، فلما أسلم في اليوم التالي جاء عند النبي وملئ له وعاء اللبن فشربه، وقدم له
النبي الوعاء الثاني، فقال شبعت. فقال النبي: إن المؤمن يأكل في مِعيٍ واحد، والكافر
يأكل في سبعة أمعاء. وهذا لهم المؤمن في الدنيا، وقال تعالى: والذين كَفروا يأكلون
ويتمتعون كما تأكل الأنعام، فالتشبيه هنا في محل عقلية الأنعام وليس نهمها. يقول
أبو الطيب: 

#+begin_verse
[[id:va9lv220nek0][تَهوي بِمُنجَرِدٍ لَيسَت مَذاهِبُه]]ُ
لِلُبسِ ثَوبٍ وَمَأكولٍ وَمَشروبِ
#+end_verse
والمنجرد هو الرجل الماضي في الأمور، الجادّ فيها لا يردّه شيء، وكذا المؤمن وهَمه في
الدنيا، وكيف بهمه في أهم حقبة في الإسلام وتعمير دولته. وقال أيضًا في ذلك:

#+begin_verse
شَرابُه النَّشح لا لِلرِيّ يَطلبه
وطَعمهُ لقوام الجِسم لا السمنِ
#+end_verse

والنشح هو القليل، أي أن شرابه قليل جدًا. والشرب لا يُعاب عليه، ولكن أنظر لعلو
الهمة وطلب المجد، فهو لا يجد وقتًا ولا يأخذ من هذا إلا ما يعينه على ما يريد من
الدنيا، وليس العكس: أن يكدح في الدنيا لطلب ما يستهلكه من متاعها "لا للري يَطلبه"
أي ليس بطالب شرابه لأن يرتوي ويشبع ويرضي بدنه: وطَعمه لقوام الجسم، كي يقضي
حواجيه، لا للإكثار والسِمن. وقال ديوجانس الحكيم: آكل لأعيش، وغيري يعيش ليأكل.
