:PROPERTIES:
:ID:       r5z3kwt0xlk0
:CUSTOM_ID: r5z3kwt0xlk0
:END:
#+DATE: <2025-06-20 Fri 22:30>
#+title: A Raw Definition of Capitalism

#+BEGIN_tag
{{{t}}} [[id:46whu3b0axj0][Economics]] and [[id:ex4aa6b0axj0][Capitalism]]
#+END_tag

I have been reading[cite:@e.-2011-histor-econom-thoug] recently, which contains a very nice, raw, critical, philosophical definition of capitalism; it correlates the existence of capitalism to consumerism, which I have not seen a lot in multiple trails to define capitalism (my old post [[id:4fb240m099k0][The Age of Commodity]] might be related here). The definition from chapter no. 1:

It is, of course, simplistic to say that attempts to understand capitalism began with Adam Smith. Capitalism as the dominant social, political, and economic system, first of western Europe and later of much of the world, emerged very slowly over a period of several centuries . As it emerged people sought to understand it.

To survey the attempts to understand capitalism, it is necessary first to define it and then to review briefly the historical highlights of its emergence. It must be stated at the outset that there is no general agreement among economists or economic historians as to what the essential features of capitalism are. In fact, some economists do not believe that it is fruitful to define distinctly different economic systems at all ; they believe in a historical continuity in which the same general principles suffice to understand all economic arrangements.  Most economists would agree, however, that capitalism is an economic system that functions very differently from previous economic systems and from contemporary noncapitalist systems. This book is based on a methodological approach that defines economic systems according to the mode of production on which the system is based. The mode of production is, in turn, defined by the forces of production and the social relations of production.

The forces of production constitute what would commonly be called the productive technology of a society. These consist of the current state of productive or technical knowledge, skills, organizational techniques, and so forth, as well as the tools, implements, machines, and buildings involved in production.  Within any given set of forces of production there are certain necessary costs that must be met in order to insure the system's continued existence. Some new resources, or raw materials, must be continuously extracted from the natural environment. Machinery, tools, and other implements of production wear out with use and must be replaced. Most important, the human beings who expend the effort necessary to secure raw materials and to transform these raw materials into finished products must have a minimum level of food, clothing, shelter, and other necessities to sustain social life.

Modes of production that have not satisfied these minimum requirements of continued production have vanished. Many historical modes of production successfully met these minimum requirements for a period of time and then, due to some change in circumstances, were unable to continue doing so, and, consequently, became extinct. Most modes of production that have continued to exist for very long periods of time have, in fact, produced enough to meet not only these necessary costs but also an excess, or social surplus, beyond these necessary costs . A social surplus is defined as that part of a society's material production that is left over after the necessary material costs of production have been deducted.

The historical development of the forces of production has resulted in a continuously increasing capacity for societies to produce larger social surpluses.  In this historical evolution, societies have generally divided into two separate groups. The vast majority of people in every society has toiled to produce the output necessary to sustain and perpetuate the mode of production as well as the social surplus, while a small minority has appropriated and controlled it. In this book, social classes are distinguished accordingly ; the social relations of production are defined as the relationships between these two classes. A mode of production, then, is the social totality of the technology of production (the forces of production) and the social arrangements by which one class uses these forces of production to produce all output including the surplus and another class appropriates the surplus (the social relations of production).

Within the context of this general set of definitions, we can define capitalism, the particular mode of production with which the thinkers surveyed in this book have been concerned. Capitalism is characterized by four sets of institutional and behavioral arrangements : market-oriented commodity production; private ownership of the means of production; a large segment of the population that cannot exist unless it sells its labor power in the market; and individualistic, acquisitive, maximizing behavior by most individuals within the economic system. Each of these features will be discussed briefly.

In capitalism, the products of human labor are valued for two distinct reasons. First, products have particular physical characteristics by virtue of which they are usable and satisfy human needs. When a commodity is valued for its use in satisfying our needs, it is said to have use value. All products of human labor in all societies have use value. In capitalism, products are also valued because they can be sold for money in the market. This money is desired because it can be exchanged for products that have a desired use value. Insofar as products are valued because they can be exchanged for money, they are said to have exchange value. Products of human labor have exchange value only in modes of production characterized by commodity production. A society must have a well-developed market in which products can be freely bought or sold for money in order for commodity production to exist. Commodity production exists when products are created by producers who have no immediate personal concern for the use value of the product but are interested only in its exchange value. Thus commodity production is not a direct means of satisfying needs. Rather, it is a means of acquiring money by exchanging the product for money, which, in turn, may be used to acquire products desired for their use value. Under such conditions, the products of human labor are commodities, and the society is described as a commodity-producing society.

Under commodity production, a person's productive activity has no direct connection to that person's consumption; exchange and the market must mediate the two. Furthermore, a person has no direct connection to the people who produce the commodities he or she consumes. This social relationship is also mediated by the market. Commodity production implies a high degree of productive specialization, in which each isolated producer creates only one or a few commodities and then must depend on other individuals, with whom he or she has no direct personal relations, to buy the commodities on the market.  Once the person has exchanged the commodity for money, that person again depends on people with whom he or she has no direct personal relationship to supply on the market the commodities he or she must purchase in order to satisfy personal needs.

This type of economy is one in which extremely complex economic interrelationships and dependencies exist that do not involve direct personal interaction and association. The individual interacts only with the impersonal social institution of the market, in which the individual exchanges commodities for money and money for commodities . Consequently, what is in reality a set of complex social and economic relations among people appears to each individual to be merely so many impersonal relations among things namely, commodities . Each individual depends on the impersonal forces of the market-of buying and selling or demand and supply-for the satisfaction of needs.


The second defining feature of capitalism is private ownership of the means of production. This means that society grants to private persons the right to dictate how the raw materials, tools, machinery, and buildings necessary for production can be used. Such a right necessarily implies that other individuals are excluded from having any say about how these means of production can be used. Early defenses of private property spoke in terms of each individual producer owning and therefore controlling the means of individual production. But very early in the evolution of capitalism things developed differently. In fact, the third defining feature of capitalism is that most producers do not own the means necessary to carry on their productive activity. Ownership came to be concentrated in the hands of a small segment of society-the capitalists .  An owner-capitalist needed to play no direct role in the actual process of production in order to control it; ownership itself granted control. And it was this ownership that permitted the capitalist to appropriate the social surplus. Thus, ownership of the means of production is the feature of capitalism that bestows the power on the capitalist class by which it controls the social surplus, and, thereby, establishes itself as the dominant social class.


The fourth and final defining feature of capitalism is that most people are motivated by individualistic, acquisitive, maximizing behavior. This is necessary for the successful functioning of capitalism. First, in order to assure an adequate supply of labor and to facilitate the strict control of workers, it is necessary that working people produce commodities whose value is far in excess of the value of the commodities that they consume. In the earliest period of capitalism, workers were paid such low wages that they and their families were kept on the verge of extreme material deprivation and insecurity. The only apparent way of decreasing this deprivation and insecurity was to work longer and harder in order to obtain a more adequate wage and to avoid being forced to join the large army of unemployed workers, which has been an ever-present social phenomenon in the capitalist system.


As capitalism evolved, the productivity of workers increased. They began to organize themselves collectively into unions and workingmen's associations to fight for higher wages. By the late nineteenth and early twentieth centuries, after many hard battles and innumerable setbacks, these struggles began to have an impact. Since that time, the purchasing power of the wages of working people has been slowly and consistently increasing . In place of widespread physical deprivation, capitalism has increasingly had to rely on new types of motivation to keep working people producing the social surplus. A new social ethos, sometimes called consumerism, has become dominant, and is characterized by the belief that more income alone always means more happiness.

The social mores of capitalism have induced the view that virtually every subjectively felt need or unhappiness can be eliminated if one can buy more commodities. The competitive and economically insecure world within which workers function generally creates subjective feelings of anxiety, loneliness, and alienation. The cause of these feelings has been perceived by most working people as their inability to buy enough commodities to make them happy.  But as workers have received higher w ages and bought more commodities, the general unhappiness and anxiety have continued. The problem, they have tended to conclude, is that the increase in wages was insufficient. Misperceiving the root cause of their condition, they have frequently gotten aboard an Alice in Wonderland treadmill, where the more one gets the more needy one feels, the faster one runs the more inadequate one's pace appears to be, the harder one works the greater appears to be the need for even harder work in the future.

Secondly, capitalists have also been driven to acquisitive, combative behavior. The most immediate reason for this is the fact that capitalism has always been characterized by a competitive struggle among capitalists to secure larger shares of the social surplus. In this endless struggle the power of any given capitalist depends on the amount of capital that he or she controls.  If a capitalist's competitors acquire capital-and hence size and economic strength-more rapidly than he or she does, then it becomes highly likely that he or she will face extinction. So continued existence as a capitalist depends on the ability to accumulate capital at least as rapidly as competitors. Hence, capitalism has always been characterized by the frantic effort of capitalists to make more profits and to convert these profits into more capital.

Consumerism among capitalists has also been important for the successful functioning of capitalism. In the process of production, after the workers have produced surplus value, the capitalists own this surplus value in the form of the commodities that the workers have produced. In order for this surplus value to be converted into monetary profit, these commodities must be sold on the market. The workers can usually be counted on to spend all of their wages on commodities, but their wages can purchase only some of the commodities (or else there would be no social surplus). Capitalists will purchase many of the commodities as investments to add to their accumulation of capital. But these two sources of demand have never been adequate to generate enough spending for the capitalists as an entire class to sell all of their commodities. Therefore, a third source of demand, ever-increasing consumption expenditures by capitalists, has also been necessary to assure adequate money demand to enable capitalists to sell all of their commodities.

When such demand has not been forthcoming, capitalism has experienced depressions in which commodities cannot be sold, workers are laid off, profits decline, and a general economic crisis ensues. Throughout its history, capitalism has suffered from recurring crises of this kind. A major concern of most of the economic thinkers discussed in this book has been to understand the nature and causes of these crises and to ascertain whether remedies can be found to eliminate or at least to alleviate the crises.

[[id:5a780a66-e9ff-4712-8269-3d1cd1556c95][Noam Chomsky]] also has a nice video on the nature of consumerism: [[https://youtu.be/Mg50wCe-Z7U]]
