:PROPERTIES:
:ID:       q822pmp02wj0
:END:
#+title: Beyond Decliamists and Intellectuals
#+DATE: <2021-09-29 Wed 09:36>


#+BEGIN_tag
{{{t}}} [[id:ydb1kfn02wj0][Modus Vivendi]]
#+END_tag

I thought that maybe 'intellectuals' is not the best word to describe
them, there is an old Arabic word "Al Mutakalimin المتكلمين" that might
be better for such a demonstration. Mutkalmin means, idiomatically, the
people who -probably Muslims- talked about the qualities of god
(e.g. Can he smell or speak just like his creature?), however, the word
"Mutkalim" in Arabic has nothing to do with the attributes of god the
but it means "the people who talk", I think the best translation for it
is the "declaimists", as Sa'adeldin Al Taftazani said once: Al Mutkalim
were named after their statements that were starting with "Al Kalam on
*some topic."[fn:1].

There is a common ground between the meaning of a 'declaimist' and a
non-intellectual that you see on daily basis especially in average
social media site, I don't want to single out a live example but let's
take \(x\) and \(let\) \(x\) be right-wing social media intellectual who
has more than 100k loyal follower of his medieval instructions about
miscarriage or the sexual orientations, if one day \(x\) figured out, or
even less revolutionary, let's say he'd found that some of his beliefs
are either wrong or obsolete, what would he do? I can tell the answer is
cognitive dissonance tends to be ended by denial of facts, trying to
stick to what he already believes (just like Chatelier's principle
object), he is not only required to comprehend whatever he believes in,
but his loyal fellows also are waiting for his directive, he won't let
them down. It's getting worse in cases in which x has already a lot of
bestselling publications which in he insures his points. Of course,
within time numerous intellectuals are getting a cognitive flexibility
enables them to change their thoughts smoothly, however, the majority
won't.



That's why I don't like either to have that little audience that adapts
what I think because I seem like a smart guy to them or to get into a
discussion with anyone of such a kind because I know he will use all the
fallacies he can use before he rethinks about any argument. Wise man
once side:

#+begin_quote
Before getting into a debate, ask your opponent, what kind of argument
might can change your mind (in other words, ask if his beliefs are
falsifiable), if he couldn't tell, then such a debate is a waste of
time.

-- I don't know who said this.

#+end_quote

Also read this. (broken link. stupid old post.)

* Footnotes

[fn:1] Kalam on something means a statement on it.


