:PROPERTIES:
:ID:       vp2hw8v0pok0
:CUSTOM_ID: vp2hw8v0pok0
:lang: ar
:subtitle: Allah Nour
:END:
#+title: اثبات ابن سينا للنبوة وتفسير آية النور
#+DATE: <2025-09-04 Thu 05:14>

#+BEGIN_tag
{{{t}}} [[id:a4154d94-7914-48ce-bcd8-025ac0608d5b][Philosophy]] and [[id:j3uepmk08ok0][Ibn Sina]]
#+END_tag

النص التالي من كلام ابن سينا عن اثبات النبوة وتفسير آية النور والنفس والوجود،
وقد مررت به وأحببت أن أنقله. ابن سينا عنده باع كثير في الرمزية symbolism وهو يرى
أن الفيض الآلهي والقصص النبوي والقرآن مَلئ بالترميز، وأن هذه فعل من الحكمة
الآلهية، ونرى هذا في تفسيره التالي وأيضًا في قصته ”حي بن يقظان“ والتي يرمز بها
للعقل والحواس والشهوات بحي بن يقظان (العقل) ورفقاه. والنص منقول من كتابه: تسع
رسائل في الحكمة والطبيعيات“: الرسالة السادسة في اثبات النبوات و تأويل رموزهم و
امثالهم‌ ”:

بسم اللّه الرّحمن الرّحيم قال الرئيس ابو على الحسين بن سينا رحمه اللّه تعالى (سألت)
اصلحك اللّه تعالى ان اجعل جمل ما خاطبتك به في ازالة الشكوك المتأكدة عندك في تصديق
النبوة لاشتمال دعاويهم على ممكن سلك به مسلك الواجب و لم يقم عليه حجة لا برهانية
و لا جدلية و منها ممتنعة تجري مجرى الخرافات التي للاشتغال في استيضاحها من المدعي
ما يستحق ان يهزأ به في رسالة (فاجبتك) مد اللّه في عمرك الى ذلك فابتدأت بان قلت ان
كل شي‌ء في شي‌ء بالذات فهو بعد بالفعل ما دام هو و كل شي‌ء في شي‌ء بالعرض فهو فيه
بالقوة و مرة بالفعل و من له ذلك بالذات فهو فيه بالفعل أبدا و هو المخرج لما فيه
بالقوة الى الفعل أما بواسطة أو بغير واسطة مثل ذلك الضوء مرئي بالذات ‌ علة الخروج
كل مرئي بالقوة الى الفعل و كالنار و هو الحار بالذات و هو المسخن لسائر الأشياء
أما بواسطة تسخينه الماء بتوسطه القمقمة و أما بلا واسطة كتسخينه القمقمة بذاته
أعنى مماسة بلا متوسط و لهذا أمثلة كثيرة و كل شي‌ء هو مركب من معنيين فاذا وجد أحد
المعنيين مفارقا للثاني وجد الثاني مفارقا له مثاله السكنجبين مركب ممن الخل و
العسل فاذا وجد الخل بالعسل وجد العسل بلا خل و كالصنم المصور المركب من نحاس و
صورة انسان اذا وجد النحاس بلا صورة انسان وجد تلك الصورة بلا نحاس و كذلك يوجد في
الاستقراء و لهذا أمثلة كثيرة (فأقول) ان في الانسان قوة تباين به سائر الحيوان و
غيره و هي المسماة بالنفس الناطقة و هي موجودة في جميع الناس على الاطلاق و أما في
التفصيل فلا لان في قواها تفاوتا في الناس فقوة أولى متهيأة لان تصير صور الكليات
منتزعة عن موادها ليس لها في ذاتها صورة و لهذا سميت العقل الهيولاني تشبيها
بالهيولى و هي عقل تام بالقوة كالنار بالقوة مبردة لا كالنار بقوة محرق و قوة ثانية
لها قدرة و ملكة على التصور بالصور الكلية لاحتوائها على الآراء المسلمة العامية و
هو عقل قام بالقوة أيضا كقولنا النار لها على الاحراق قوة أو قوة ثالثة متصورة بصور
الكليات المعقولة بالفعل‌  منها القوتان الماضيتان و خرجتا الى العقل و هو المسمى
بالعقل الفعال و ليس وجوده في العقل الهيولاني بالفعل فليس وجوده فيه بالذات فاذا
وجوده فيه من موجد هو فيه بالذات به خرج ما كان بالقوة الى الفعل و هو الموسوم
بالعقل الكلي و النفس الكلي و نفس العالم و اذا كان القبول ممن له القوة المقبولة
بالذات على وجهين أما بواسطة و أما بغير واسطة و كذلك اذا وجد القبول من العقل
الفعال الكلي على وجهين فأما القبول عنه بلا واسطه فكقبول الآراء العامية و بداية
العقول و أما القبول بتوسط فكقبول المعقولات الثانية بتوسط الآلات و المواد و كالحس
الظاهر و الحس المشترك و الوهم و الفكرة و اذا كانت النفس الناطقة تقبل كما بينا
مرة بتوسط و مرة بغير توسط فليس له القبول بغير توسط بالذات فهو فيه بالعرض فهو في
آخر بالذات مستفاد و هذا هو العقل الملكي الذي يقبل بغير توسط بالذات و يصير قبوله
علة لقبول غيره من القوى و ليس اختصاص المعقولات الأول بالقبول بغير توسط الا من
جهتين على الاختصار من أجل سهولة قبولها او من أجل ان القابل ليس يقوى ان يقبل بغير
توسط الا ليسهل قبوله ثم رأينا في القابل و المقبول تفاوتا في القوة و الضعف و
السهولة و العسورة و كان محالا ان لا يتناهى لأن‌  النهاية في طرف الضعف ان لا يقبل
و لا معقولا واحدا بتوسط و لا بغير توسط و النهاية في القوة هو ان يقبل بغير توسط
فيكون يتناهى في الطرفين و هذا خلف لا يمكن و قد بين ان الشي‌ء المركب من معنيين اذا
وجد أحد المعنيين مفارقا للثاني وجد الثاني مفارقا له* و قد رأينا أشياء لا تقبل
بغير واسطة و تقبل بغير واسطة و وجدنا أشياء لا تقبل من إفاضات العقل بغير واسطة و
أشياء تقبل كل الافاضات العقلية بغير واسطة و اذا تناهى في الطرف الضعفي يتناهى في
الطرف القوي و اذا كان التفاضل في الأسباب يجري على ما أقول ان من الأسباب ما هي
قائمة بذاتها و منها غير قائمة بذاتها و الأول أفضل. و القائم بذاته أما صورة و
اثبات لا في مواد أو صورة ملابسة للمواد و الأول أفضل.

و لنقسم الثاني اذا كان المطلب فيه و الصور و المواد التي هي الأجسام أما نامية أو
غير نامية و الأول أفضل. و الناطق أما ملكة او بغير ملكة و الأول افضل. و الحيوان
اما ناطق او غير ناطق و الأول افضل. و الناطق اما بملكة او بغير ملكة و الأول افضل.
و ذو الملكة اما خارج الى الفعل التام او غير خارج و الأول افضل. و الخارج اما بغير
واسطة او بواسطة و الأول افضل. و هو المسمى بالنبي و اليه انتهى التفاضل فى الصور
المادية و ان كان كل فاضل يسود المفضول و يروسه‌  فاذا النبي يسود و يروس جميع
الاجناس التي فضلها. و الوحي هذه الافاضة و الملك هو هذه القوة المقبولة المفيضة
كأنها عليه افاضة متصلة بافاضة العقل الكلي مجراة عنه لا لذاته بل بالعرض و هو
المرئى القابل و سميت الملائكة بأسامي مختلفة لأجل معاني مختلفة و الجملة واحدة غير
متجزئة بذاتها الا بالعرض من اجل تجزي القابل. و الرسالة هي اذا ما قيل من الافاضة
المسماة و حيا على اي عبارة استصوبت لصلاح عالمي البقاء و الفساد علما و سياسة و
الرسول هو المبلغ ما استفاد من الافاضة المسماة و حيا على عبارة استصوبت ليحصل
بآرائه صلاح العالم الحسي بالسياسة و العالم العقلي بالعلم. فهذا مختصر القول في
اثبات النبوة و بيان ماهيتها و ذكر الوحي و الملك و الموحي و اما صحة نبوة محمد صلى
اللّه عليه و سلم فتبين صحة دعوته للعاقل اذا قاس بينه و بين غيره من الانبياء عليهم
السلام و نحن معرضون عن التطويل* و نأخذ الآن في حل المراميز التي سألتنى عنها و
قيل ان المشترط على النبي ان يكون كلامه رمزا و الفاظه ايماء و كما يذكر افلاطون في
كتاب النواميس ان من لم يقف على معاني رموز الرسل لم ينل الملكوت الالهي و كذلك
اجلة فلاسفة يونان و انبياؤهم كانوا يستعلمون في كتبهم المراميز و الاشارات التي
حشوا فيها اسرارهم كفيثاغورس‌  و سقراط و افلاطون و اما افلاطون فقد عذل ارسطاطاليس
في اذاعته الحكمة و اظهاره العلم حتى قال ارسطاطاليس فاني و ان عملت كذا فقد تركت
في كتبي مهاوي كثيرة لا يقف عليها الا القليل من العلماء العقلاء و متى كان يمكن
النبي محمدا صلى اللّه عليه و سلم ان يوقف على العلم اعرابيا جافيا و لا سيما البشر
كلهم اذ كان مبعوثا اليهم كلهم. فاما السياسة فانها سهلة للانبياء و التكليف ايضا
فكان اول ما سألتني عنه ما بلغ محمد صلى اللّه عليه و سلم عن ربه عز و جل. اللّه نور
السماوات و الارض مثل نوره كمشكاة فيها مصباح المصباح في زجاجة الزجاجة كأنها كوكب
دري توقد من شجرة مباركة زيتونة لا شرقية و لا غربية يكاد زيتها يضي‌ء و لو لم تمسه
نار نور على نور يهدي اللّه لنور من يشاء. و يضرب اللّه الامثال للناس و اللّه بكل شي‌ء
عليم (فاقول) النور اسم مشترك لمعنيين ذاتي و مستعار. و الذاتي هو كمال المشف من
حيث هو مشف كما ذكر ارسطاطاليس. و المستعار على وجهين اما الخير و اما السبب الموصل
الى الخير و المعنيّ هاهنا هو القسم المستعار بكليّ في قسميه اعني اللّه تعالى خيرا
بذاته و هو سبب لكل خير كذلك الحكم في الذاتي و غير الذاتي. و قوله السماوات و
الارض عبارة عن الكل و قوله مشكاة فهو عبارة عن العقل‌  الهيولاني و النفس الناطقة
لان المشكاة متقاربة الجدران جيدة التهيؤ للاستضاءة لان كل ما يقارب الجدران كان
الانعكاس فيه اشد و الضوء اكثر و كما ان العقل بالفعل مشبه بالنور كذلك قابله مشبه
بقابله و هو المشف و افضل المشفات الهواء و افضل الأهوية هو المشكاة فالرموز
بالمشكاة هو العقل الهيولاني الذي نسبته الى العقل المستفاد كنسبة المشكاة الى
النور و المصباح هو عبارة عن العقل المستفاد بالفعل لأن النور كما هو كمال للمشف
كما حد به الفلاسفة و مخرج له من القوة الى الفعل و نسبة العقل المستفاد الى العقل
الهيولاني كنسبة المصباح الى المشكاة* و قوله في زجاجة لما كان بين العقل الهيولاني
و المستفاد مرتبة أخرى و موضع آخر نسبة كنسبة الذي بين المشف و المصباح فهو الذي لا
يصل في العيان المصباح الى المشف الا بتوسط و هو المسرجة و يخرج من المسارج الزجاجة
لأنها من المشفات القوابل للضوء* ثم قال بعد ذلك كأنها كوكب دري ليجعلها الزجاج
الصافي المشف لا الزجاج المتلون الذي لا يستشف فليس شي‌ء من المتلونات يستشف. توقد
من شجرة مباركة زيتونة يعني به القوة الفكرية التي هي موضوعة و مادة للافعال
العقلية كما ان الدهن موضوع و مادة للسراج لا شرقية و لا غربية الشرق في اللغة  حيث
يشرق منه النور و الغرب حيث فيه يفقد النور و يستعار الشرق في حيث يوجد فيه النور و
الغرب في حيث يفقد فيه النور فانظر كيف راعى التمثيل و شرائطه حين جعل أصل الكلام
النور بناء عليه و قربه ثلاث و معادنها فالرمز بقوله لا شرقية و لا غربية ما أقول
ان الفكرية على الاطلاق ليست من القوى المحضة النطقية التي يشرق فيها النور على
الاطلاق فهذا معنى قوله شجرة لا شرقية و لا هي من القوى البهيمية الحيوانية التي
يفقد فيها النور على الاطلاق و هذا معنى قوله و لا غربية قوله يكاد زيتها يضئ و لو
لم تمسسه نار مدح القوة الفكرية ثم قال و لو مسها يعني بالمس الاتصال و الافاضة و
قوله نار لما جعل النور المستعار ممثلا بالنور الحقيقي و آلاته و توابعه بآلاته و
توابعه مثل الحامل الذاتي الذي هو سبب له في غيره بالحامل له في العادة و هو النار
و ان لم تكن النار بذي لون في الحقيقة فالعادة العامية انها مضيئة فانظر كيف راعى
الشرائط و ايضا لما كانت النار محيطة بالامهات مشبها بها المحيط على العالم لا
احاطة سقفية بل احاطة تولية مجازية و هو العقل الكلي و ليس هذا العقل كما ظن
الاسكندر الافروديسئ و نسب الظن الى ارسطو بالاله الحق الأول لان هذا العقل الأول
واحد من جهة و كثير من حيث هو صور كليات كثيرة  فليس بواحد بالذات و هو واحد بالعرض
فهو مستفيد الوحدة ممن له ذلك بالذات و هو اللّه الواحد جل جلاله و اما ما بلغ النبي
عليه السلام عن ربه عز و جل من قوله تعالى يحمل عرش ربك فوقهم يومئذ ثمانية (فنقول)
ان الكلام المستفيض في استواء اللّه تعالى على العرش و من اوضاعه ان العرش نهاية
الموجودات المبدعة الجسمانية و تدعى المتشبهة من المتشرعين ان اللّه تعالى على العرش
لا على سبيل حلول هذا و اما في كلام الفلسفي فانهم جعلوا نهاية الموجودات الجسمانية
الفلك التاسع الذي هو فلك الافلاك و يذكرون ان اللّه تعالى هناك و عليه لا على حلول
كما بين ارسطو في آخر كتاب سماع الكيان و الحكماء المتشرعون اجتمعوا على ان المعنيّ
بالعرش هو هذا الجرم هذا و قد قالوا ان الفلك يتحرك بالنفس حركة شوقية و انما قالوا
يتحرك بالنفس لان الحركات اما ذاتية و اما غير ذاتية و الذاتية اما طبيعية و اما
نفسية. ثم بينوا ان نفسها هو الناطق الكامل الفعال ثم بينوا ان الافلاك لا تفنى و
لا تتغير ابد الدهر و قد ذاع في الشرعيات ان الملائكة احياء قطعا لا يموتون
كالانسان الذي يموت فاذا قيل ان الافلاك احياء ناطقة لا تموت و الحي الناطق الغير
الميت يسمى ملكا فالافلاك تسمى ملائكة فاذا تقدم هذه المقدمات و صح ان العرش‌  محمول
ثمانية و وضح ان تفسير المفسرين انها ثمانية افلاك و الحمل يقال على وجهين حمل بشري
و هو اولى باسم الحمل كالحجر المحمول على ظهر الانسان و حمل طبيعي كقولنا الماء
محمول على الارض و النار على الهواء و المعنىّ هاهنا هو الحمل الطبيعي لا الأول* و
قوله يومئذ و الساعة و القيامة فالمراد بها ما ذكره الشارع ان من مات قامت قيامته و
لما كان تحقيق نفس الانسانية عند المفارقة آكد جعل الوعد و الوعيد و اشباههما الى
ذلك الوقت* و اما ما بلغ النبي عليه الصلاة السلام عن ربه عز و جل ان على النار
صراطا صفته انه احد من السيف و ادق من الشعر و لن يدخل احد الجنة حتى يجوز عليه فمن
جاز عليه نجا و من سقط عنه خسر فتحتاج قبل هذا ان تعلم العقاب ما هو و اي شي‌ء هو
المعنىّ بالجنة و النار (فاقول) اذا كان الثواب هو البقاء في العناية الالهية الاولى
مع عدم النزاع الى ما لا سبيل اليه من الأشياء العلمية و العملية و لا يحصل ذلك الا
بعد الاستكمال من العمليات و مجانبة خسائس العمليات لئلا تعود عادة و ملكة تتوق
اليها النفس توقان الألوف فتعذر الصبر عنها و عليها و لن يحصل ذلك إلا بعد مخالفة
النفس الحيوانية في افعالها العملية و ادراكاتها العلمية الا ما لا بد منه فما هلك
من هلك الا بمطابقة الوهم من القوى الحيوانية  الحاكم على الصورة المجردة في غيبة
الحواس بالكذب و الجسور المتسم بسمة العقل الهيولاني بحلبة اللب لا جرم لا يعرى عن
ارتياب في مقلده و ارتداد في معتقده و فساد منتظر و عطب مستقبل فاذا فسد بالصورة
المعتقدة وجد النفس الناطقة في مطابقتها له نوعا من التطابق عارية عن الصور الشريفة
العقلية المخرجة لها الى الفعل و قد احوجت طبعها ادراك مانعها كحجر شاله الى العلو
شائل فبلغ به غبر مركزه الطبيعي ففارقه فانثنى الى السفل هابطا و الى طبيعته معاودا
اذ بأين عائقه و ذلك بعد ان فسدت آلاته التي كان يتصرف بها في اكتساب العقل
المستفاد كالحس الظاهر و الحس الداخل و الوهم و الذكر و الفكر فبقى مشتاقا الى طبعه
من اكتساب ما يتم ذاته و ليس معه آلة الكسب و اي محبة اكثر منها و لا سيما اذا
تقادم الدهر في بقائها على تلك الحالة فاما في مطابقتها له من الخسائس العملية
فيوشك ان تبقى النفس مفارقة لاحوالها السوء و قد الف ما طابقهم عليه و لم يمانعهم
فيه من اللذة الشهوانية الحسية فاني يحصل له ذلك و لا قوة شهوانية حسية معه و مثله
كما يقال لا تعشق احدا من السفر و مات الرجل فينتزع ما يدهمك الباقي فتبقى في حروفة
الصبابة. و اذ تبين على الاختصار معنى العقاب و الثواب فالآن نتكلم في ماهية الجنة
و النار (فنقول)  و اذا كان العوالم ثلاثا عالم حسي و عالم خيالي و همي و عالم
عقلي. فالعالم العقلي حيث المقام و هو الجنة. و العالم الخيالي الوهمي كما بين هو
حيث العظب و العالم الحسي هو عالم القبور* ثم اعلم ان العقل يحتاج في تصور اكثر
الكليات الى استقراء الجزئيات فلا محالة انها تحتاج الى الحس الظاهر فنعلم انه يأخذ
من الحس الظاهر الى الخيال الى الوهم و هذا هو من الجحيم طريق و صراط دقيق صعب حتى
يبلغ الى ذاته العقل فهو اذا يرى كيف الحد صراطا و طريقا في عالم الجحيم فان جاوزه
بلغ عالم العقل فان وقف فيه و تخيل الوهم عقلا و ما يشير اليه حقا فقد وقف على
الجحيم و سكن في جهنم و هلك و خسر خسرانا مبينا. فهذا معنى قوله في الصراط. و اما
ما بلغ النبي محمد عليه الصلاة و السلام عن ربه عز و جل من قوله عليها تسعة عشر فاذ
قد تبين ان الجحيم هو ما هو و بينا انه بالجملة هو النفس الحيوانية و بينا انها
الباقية الدائمة في جهنم و هي منقسمة قسمين ادراكية و عملية. و العملية شوقية و
غضبية. و العلمية هي تصورات الخيال المحسوسات بالحواس الظاهرة و تلك المحسوسات ستة
عشر و القوة الوهمية الحاكمة على تلك الصور حكما غير واجب واحدة ذاتياني و ستة عشر
و واحد تسعة عشر فقد تبين صحة قوله عليها تسعة عشر و اما قوله و ما جعلنا اصحاب
النار الا  ملائكة فمن العادة في الشريعة تسمية القوى اللطيفة الغير المحسوسة
ملائكة. و اما ما بلغ النبي محمد عن ربه عز و جل ان للنار سبعة ابواب و للجنة
ثمانية ابواب فاذ قد علم ان الأشياء المدركة اما مدركة للجزئيات كالحواس الظاهرة و
هي خمسة و ادراكها الصور مع المواد او مدركة متصورة بغير مواد كخزانة الحواس
المسماة بالخيال و قوة حاكمة عليها حكما غير واجب و هو الوهم و قوة حاكمة حكما
واجبا و هو العقل فذلك ثمانية فاذا اجتمعت الثمانية جملة ادت الى السعادة السرمدية
و الدخول في الجنة و ان حصل سبعة منها لا تستتم الا بالثامن ادت الى الشقاوة
السرمدية و المستعمل في اللغات ان الشي‌ء المؤدي الى الشي‌ء يسمى بابا له فالسبعة
المؤدية الى النار سميت ابوابا لها و الثمانية المؤدية الى الجنة سميت ابوابا لها.
فهذا ابانة جميع ما سألت عنه على الايجاز و الحمد لواهب العقل و صلاته على اشرف
خلقه محمد النبي و آله الطاهرين و صحابته اجمعين آمين.
