:PROPERTIES:
:ID:       h7qk80q02wj0
:END:
#+title: Nietzsche on The Desire to Excite Pity
#+DATE: <2023-02-14 Tue 12:04>


#+BEGIN_propert
{{{s}}} [[id:loqfv5p02wj0][Nietzsche, Unveiling the Depths of Human Existence]]
#+END_propert

I'm getting through a new adventure recently, chess programming; I've posted a
while ago about studies related to [[id:i70j8rp02wj0][Chess and Brains]] and there is something
that I find very effective in chess so far, that's a discipline. You see, chess
is purely an abstractive game[fn:1], you are playing for survival (even when you
are playing for win), doing something fancy or fashionable doesn't mean anything
no matter in which context, if it doesn't boost or neutralize you in computer
evaluation number, or sometimes if it is not a part of a plan, then it's
basically useless.

#+BEGIN_PREVIEW
A life principle that I always try to live by is: "reasons not feelings", humans
are not cleaver in accepting that naturally, that nature needs taming to accept
such a principle, and I believe that chess is a powerful tool to do that.
#+END_PREVIEW

I will elaborate on that later when I publish my chess collection soon, this
post was created instead to share with you a similar discipline that I found
[[id:1634e2c7-c5aa-44bf-b0c7-00ff078366f3][Nietzsche]] talking about, that's pity. Pity as a feeling really fits in many
examples of how our feelings can be unnecessary heavy loads in our brains. Pity
only yields on two possible outcomes 1. "Generously" pity someone (we tend to
simulate an effect of solidarity in feeling pity, so we do it as a matter of
generousness, which, of course, makes us feel great) 2. Barely help them to get
the feeling that you already did all you can (like when you really pity those
poor kids, so you donate some amount of money, but you are not really willing to
investigate the reason behind it to give them a real hand of help). Let's move
to the text, I will leave the Arabic translation as well because, as I mentioned
before, I find it more poetic.



#+begin_quote
Larochefoucauld is certainly right when, in the most noteworthy passage of his
self-portrait (first printed 1658), he warns all those who possess reason
against pity, when he advises that it be left to those people of the commonality
who (because their actions are not determined by reason) require the passions if
they are to be brought to the point of aiding a sufferer or energetically
intervening in a case of misfortune; while pity, in his (and Plato' s) judgment,
enfeebles the soul. One should, to be sure, manifest pity, but take care not to
possess it; for the unfortunate are so stupid that the manifestation of pity
constitutes for them the greatest good in the world. - Perhaps one can warn even
more strongly against this having pity if one understands this need felt by the
unfortunate, not precisely as stupidity and intellectual deficiency, as a kind
of mental disturbance that misfortune brings with it (that, indeed, is how
Larochefoucauld seems to conceive it), but as something quite different and more
suspicious. Observe children who weep and wail in order that they shall be
pitied, and therefore wait for the moment when their condition will be noticed;
live among invalids and the mentally afflicted


and ask yourself whether their eloquent moaning and complaining, their
displaying of misfortune, does not fundamentally have the objective of hurting
those who are with them: the pity which these then express is a consolation for
the weak and suffering, inasmuch as it shows them that, all their weakness
notwithstanding, they possess at any rate one power: the power to hurt. In this
feeling of superiority of which the manifestation of pity makes him conscious,
the unfortunate man gains a sort of pleasure; in the conceit of his imagination
he is still of sufficient importance . to cause affliction in the world . The
thirst for pity is thus a thirst for self-enjoyment, and that at the expense of
one's fellow men; it displays man in the whole ruthlessness of his own dear
self: but not precisely in his 'stupidity', as Larochefoucauld thinks. - In the
conversations of social life, three-quarters of all questions are asked,
three-quarters of all answers given, in order to cause just a little pain to the
other party; that is why many people have such a thirst for social life: it
makes them aware of their strength. In such countless but very small doses in
which malice makes itself felt it is a powerful stimulant to life: just as
benevolence, disseminated through the human world in the same form, is the ever
avail­ able medicine. - But will there be many honest men prepared to admit that
causing pain gives pleasure? that one not seldom entertains oneself ­ and
entertains oneself well - by mortifying other people, at least in one's own
mind, and by firing off at them the grapeshot of petty malice? Most are too
dishonest, and a few too good, to know anything of this puderzdum;* and they are
welcome to deny if they like that Prosper Merimeet is right when he says:
'Sachez aussi qu'il n'y a rien de plus commun que de faire Ie mal pour Ie
plaisir de Ie faire.'[fn:2]
#+end_quote


#+begin_quote
كان لاروشفوكو مصيبًا وهو يحذر في إحدى المواقع الأكثر روعة من البروتريه الذاتي كل ذوي العقل من الشفقة، في حين ينصح بتركها لعامة الشعب الذين يحتاجونها (لأنهم ليسوا مُسيرين بأحكام العقل) كي تدفع بهم إلى مساعدة من يعاني والتدخل بحزم عند حصول كارثة؛ في حين أن الشفقة تستنفد طاقات الروح وتنهكها بحسب حكمه. وفي الحقيقة ينبغي أن نعرب عن الشفقة وأن نحترس من أن نكون حاملين لها؛ ذلك أن الأشقياء في رأيه على غاية من السخافة تجعل ابداء الشفقة تجاههم أكبر فضل يمكن أن يمنحهم إياه العالم. ولعلنا سنحذر بأكثر من هذه الشفقة التي يحملها المرء في نفسه إذا ما اعتبرنا حاجة الأشقياء إليها، لا كسخافة ونقص ذهني واضطراب عقلي يرافق حلول المصيبة (ويبدوا أن لاروشفوكو يفهم الأمر من هذا الوجه)، بل كشيء مختلف تمامًا ومشبوه. لننظر بالأحرى بعين المتفحص إلى الأطفال الذين يبكون ويصرخون كي يستدروا الشفقة، ولذلك يظلون منتظرين اللحظة التي سيقع انتباه الآخرين فيها على حالتهم؛ ولنعايش عن قرب مرضى ومصابين بالإرهاق الذهني، ولنتساءل إن لم تكن تلك الشكوى والتأوهات التي يستعرضون بها تعاستهم تسعى في الحقيقة إلى إيلام المحيطين بيهم: فالشفقة التي يبديها هؤلاء نحوهم هي إذن عزاء للضعفاء والمتألمين، بما أنها تجعلهم يشعرون معها بأنهم بالرغم من ضعفهم يملكون سلطة واحدة على الأقل هي القدرة على إيلام الآخرين. يجد الشقي نوعًا من اللذة في هذا الشعور بالتفوق الذي يمنحه إياه إبداء الشفقة، ويتفاقم وهمه ليشعر بأنه ما يزال على قدر من الأهمية كي يثير الألم في العالم المحيط به. وبهذا يكون الظمأ إلى الشفقة ظمئًا إلى الالتذاذ بالذات، وذلك على حساب الآخرين؛ ويكشف لنا هذا الأمر عن الإنسان في كامل وقاحة حبه لذاته، وليس في سخافته كما يقول لاروشفوكو.
#+end_quote





* Footnotes
[fn:2] Nietzsche, F., Zimmern, H., & Nietzsche, F. (2009). Human, all-too-human
parts one and two. p. 51 Prometheus Books.

[fn:1] I agree with Stefan Zweig description of calling chess a game as
Disparagement: "And are we not guilty of offensive disparagement in calling
chess a game? Is it not also a science and an art, hovering between those
categories as Muhammad’s coffin hovered between heaven and earth, a unique link
between pairs of opposites: ancient yet eternally new; mechanical in structure,
yet made effective only by the imagination; limited to a geometrically fixed
space, yet with unlimited combinations; constantly developing, yet sterile;
thought that leads nowhere; mathematics calculating nothing; art without works
of art; architecture without substance – but nonetheless shown to be more
durable in its entity and existence than all books and works of art; the only
game that belongs to all nations and all eras, although no one knows what god
brought it down to earth to vanquish boredom, sharpen the senses and stretch the
mind."
