:PROPERTIES:
:ID:       dzihxcp02wj0
:END:
#+title: “Connection” and “Meant-To-Be”
#+DATE: <2021-05-22 Sat 06:17>

#+BEGIN_PREVIEW
2 concepts that seem really nice and agreeable, but I find are psychically terrible, are
“connection” and “meant-to-be”.
#+END_PREVIEW


My issue with the concept of connection is that it requires equally the notion of
disconnection, which I find logically leads to mass-extinction-production as
suicide-bomber-ideology. The idea we are disconnected - which is different from the
perspective that we are alienated (with connection/disconnection being a mode of
alienation) - and must acquire connection, religious or spiritual or technological, I find
to be a psychic trap, like a hamster wheel that never goes anywhere. The destruction of
connection-disconnection is the eco-egoism of finding the oneness of individuality as the
oneness of the world - which is why connectivity thought is so disastrous for environmental
thought, which is embracing ever more the connectivity-techno-logic of alienation.

My issue with the idea of meant-to-be is primarily that the notion insists upon there being
a right way for the world to be and a wrong way for the world to be. This first of all takes
a Gods-eye-view upon the world and assumes a level of gnostic-awareness that I don’t believe
anyone can authentically actually hold, from the perspective of the stupid earth level
badger I am. This also constructs the duality of right and wrong, with people constantly
bickering over which is which. My perspective is that the world is neither right nor wrong,
but just is - as is my desires regarding the world, with my desire being part of the world,
and it being my responsibility to actualise my desires. My feeling is that if individuals
sympathetic to environmental thought were to talk in terms of desire (in other words,
honestly/sincerely) they might be heard more - the statement “the badger cull is wrong”
requires epistemological justification, whereas “I don’t want to see badgers abused”
doesn’t, as experience is immediate.

I personally encounter the world as more beautiful when I destroy these (human, all too
human) concepts for myself! #[[id:a4154d94-7914-48ce-bcd8-025ac0608d5b][Philosophy]]
