:PROPERTIES:
:ID:       qfji16d144k0
:lang: ar
:subtitle: Regarding Music Prohibition in Islam
:ROAM_ALIASES: "Music in Islam"
:END:
#+TITLE: رأيي في تحريم الموسيقى
#+DATE: <2024-02-20 Tue 21:09>

#+begin_verse
رُبَّ وَرقاءَ هتوفٍ في الضُحى
ذاتِ شَجوٍ صَدَحت في فَنَنِ

ذكرت إِلفاً ودهراً صالحاً
فبكت حزناً وهاجت حَزني

فبكائي ربما أرَّقَها
وبكاها ربما أرَّقَني

ولقد تشكو فما أفهمها
ولقد أشكو فما تفهمني

غير أنّي بالجوى أعرِفُها
وهي أيضاً بالجَوى تعرفُني

(أبو بكر الشبلي)
#+end_verse


يُعلِق بعض الباحثين المُعاصرين، وبالأخص المُعممين (mainstreamed) —لأسباب لا نخوض
فيها هنا— تحريم الموسيقى التاريخي في الإسلام على واقعتين أساسيتين: الصراع
الإسلامي التاريخي بين الممالك الإسلامية التي حاربت بعضها ثقافيًا ونيل من أمر
المعازف خلالها، وهذه كمعارك الأندلسيين مع العباسيين (بفترات الانقلابات السياسية)
أو كصراعات الحجازيين والشاميين المبكرة[fn:1]، أو على حدث سياسي
أيضًا معاصر أكثر من هذا وهو صحوة بلاد الحرمين في فترة حكم الملك فهد.

إن الهدف من القراءة المادية التاريخية (historical materialist) لتحريم الموسيقى
هو وضعها في حيز الأفكار الناشئة لتحقيق مبتغى سياسي في حدود ما، كالحرب الثقافية
على فصيل ما أو بناء شخصية سياسية-اجتماعية (sociopolitical character) ما يدعو
لاستنباط أنها ليست فكرة قائمة بحد ذاتها، ولإهمال أدلتها ونقدها، فهي لم تكن
لتتواجد من الأساس.

والدين في رأيي ليس له مواقف وإنما يُبنى عليه المواقف، وقد يطول الجدل في هذا على
خلاف ما هو في موضوع الموسيقى، فهي لم تُنهَ عنها مباشرة في نص قرآني، والشكل الحالي
للموسيقى (من حيث تكوينها وطُرق استهلاكها) يختلف عما كان عليه زمن النبي واللاحقين
به، وما كانت عليه شكل الموسيقى أيام النبي تبدل عما كانت عليه زمن الفقهاء
والمحدثين، ولفظا النبي وأصحابه عن الموسيقى، المعازف واللهو، يُختلف في شموليتهما
وتأويلهما، وما بعد الاتفاق على تأويلها يصبح الخلاف على كرهها أم تحريمها (فعادة
ما كانت دلالة التحريم الفقهية في الحديث هي دلالة الاقتران، وهي دلالة ضعيفة في
الفقه الإسلامي). سأخوض في هذه الرسالة حول رؤيتي عن تحريم الموسيقى، ورأيي أنها
ليست حراماً.

* عن الإجماع
#+begin_quote
من قال بالإجماع فقد كذب (أحمد)
#+end_quote

إن وُجد خلافٌ تاريخي على حرمانية الموسيقى فقد وُجد إجماعٌ معاصرٌ على وجود إجماعٍ
تاريخي علي حرمانيتها. يقول الشيخ ابن باز في [[https://web.archive.org/web/20240116010949/https://binbaz.org.sa/fatwas/17415/%D8%AD%D9%83%D9%85-%D8%A7%D9%84%D8%A7%D8%BA%D8%A7%D9%86%D9%8A-%D9%88%D8%A7%D9%84%D9%85%D9%88%D8%B3%D9%8A%D9%82%D9%89][فتوى]]: "[أجمع] أهل العلم على
تحريم ما يكون فيه اجتماع الغناء مع آلات الملاهي يكون الشر أعظم والفتنة أكبر،
وإذا انفرد الغناء وحده ليس معه آلة لهو فالذي عليه جمهور أهل العلم وهو كالإجماع
منهم التحريم لما فيه من الفساد، فإذا انضاف إلى ذلك آلات الملاهي من موسيقى أو
مزمار أو غير ذلك من آلات الملاهي كالطبل وكالرباب وأشباه ذلك كل ذلك يجعله أشد
تحريمًا وأشد فساداً". وأما الشيوخ الأكثر عصرية انتقلت فتاويهم نحو الحكمة من تحريم
الموسيقى وليس شكوكية تحريمها، وينشر اليافعون في العلم هُنا وهناك مقالات علمية
شعبية تؤيد الحكمة من هذا التحريم لضرر الموسيقى العظيم على الدماغ.


إن اللمحة التاريخية عن استقبال المسلمين للموسيقى هامة كي تُبطل الصورة التي خلقها
المعاصرون، ولعلها أيضًا تخفف من وطئة الحديث عن حرمانية الموسيقى للقارئ، وأنا أعلم
أن بعض القراء قد يكتفي عند قولي إن الإمام الفلاني قد سمع الأغاني، ورخصها أو عند
أن عزة الميلاء كانت مطربة شهيرة في التاريخ الإسلامي وهذا غير صائب، فالإمامة لا
تُنبط العصمة، وقد شاعت فترات في التاريخ الإسلامي قل فيها القدح تجاه المجون
واللواط (أنظر قصيدة علي بن أبي طالب الأعمى الشهيرة مثلًا أو أخبار شعراء حمص في
القرن الثاني الهجري) ولم يعني هذا خروجها من التحريم.

لفظ "السماع" أو "التسميع" في التاريخ الإسلامي يعني سماع الموسيقى، يقول ابن عبد
البر عن مفتي المدينة عبد الملك عبد العزيز الماجشون، وكان تلميذًا لمالك: كان مولعًا
بالسماع[fn:2]. ويروي أيضًا عن الإمام أحمد أن الماجشون قد جاءه ومعه جواري تغني[fn:4] . وكان عبد
العزيز بن الماجشون[fn:3]، كما روى الذهبي، "يُعلم الغناء"[fn:5] أي يدرسه وينشره
(وسنرى لهذا نظائر لاحقة عند علماء المسلمين الذين أسهموا في نظرية الموسيقى music
theory)، ونقل الإمام الشوكاني عن المغيرة بن شعبة في كتابه "إبطال دعوى الإجماع
على تحريم مطلق السماع"، وهو كتاب ينقد فيه مزاعم إجماع تحريم الغناء، أن الصحابي
مغيرة بن شعبة، وكان من الطائف، أباح السماع. وذكر ابن حجر العسقلاني أن ابن سيرين
كان يستمتع بضرب الدف[fn:6] . وذكر الشوكاني في نيل الأوطار أثرًا عن ابن أبي الدم
أن عبد الله بن الزبير كان له جوار عوادات، أي يلعبن على العود، وأن ابن عمر دخل
عليه وإلى جنبه عود فقال: ما هذا يا صاحب رسول الله؟ فناوله إياه فتأمله ابن عمر
فقال: هذا ميزان شامي، قال ابن الزبير: يوزن به العقول[fn:7]. وقال أبو طالب المكي، وهو
أحد من أخذ عنهم الغزالي: مَن أنكر السماعَ مطلقًا غيرَ مقيَّد فقد أنكر على سبعين صدّيقًا،
ومن الطريف أن ابن القيم كان يستنكر شيوع السماع، فأخرج هذا القول في كتابه "الكلام
على مسألة السماع"، وعلق عليه قائلًا: "هذا في زمانه، ولا ريبَ أن المنكر بعده يكون
إنكاره على أضعاف هؤلاء"[fn:8] أي إن عد "الصديقين" قد تضاعف في زمن ابن القيم. وانتشرت
إسهامات المسلمين في نظرية الموسيقى في زهاء ممالك الإسلام، وكان صفي الدين الأرموي
البغدادي أحد أشهر منظري الموسيقى المسلمين، وقد كتب أبو نصر الفارابي، وله ينسب
الفضل في اختراع أداة القانون الموسيقية، عن العلاج بالموسيقى[fn:9].



وقد كثرت الأخبار عن أصحاب النبي المدنيين وغيرهم من الصالحين في استماعهم
للموسيقى، وقد أورد الشوكاني جملة منهم في كتابه، وهو ما اعترف به الألباني في
كتابه تحريم آلات الطرب في رده على رسالة ابن حزم، فقال في رده على ما أورده
الشوكاني: "[وإن] صحت نسبتها إلى قائلها وفيهم الكوفي والمدني وغيرهم [وهو ما ثَبُت]
فلا حجة فيها لمخالفتها لما تقدم من الأحاديث الصحيحة الصريحة الدلالة"[fn:10] أي إن هناك
من الأصحاب الصالحين من كان يستمع للموسيقى، ولكن، بالنسبة للألباني، هذا لا يغير
شيئًا فالأحاديث "صريحة الدلالة".

* ما أذهب عليه في الموسيقى

وأما مُعتقدي في أمر الموسيقى فهو مُعتقد الإمام أبو حامد الغزالي في كتاب آداب
السماع والوجد، ورؤيتي لتحريم فقهاء المذاهب للغناء (الذي لا أنكرهُ) هي رؤيته. إن
"السماع" كما وُصف لنا في التاريخ الإسلامي كان مقترنًا دائمًا بالفتن كاقتران
البلوتوث بالإباحيات في زهرته بداية الألفية (وقد وُجد من شيوخ الحرمين من رأى
بتحريم البلوتوث وقتها بسبب ذلك الاقتران)، والواضح أنه لم يُبين في فتاوي أئمة
المذاهب أمر الغناء تجريديًا، لأن سماع الموسيقى دون الجلوس في مجلس خمر لم يكن أمرًا
واردًا (ويبدوا أنه حتى إن وجد كان يستحي الفقهاء أن يقترنوا به، لارتباطه في
أذهانهم بما يعدونه مشينًا لأنفسهم، وقد روُي عن مالك أنه إذا اقتنى جارية فوجدها
تغني أعادها) كما هو اليوم.


وهذا قريب مما اعتقده الغزالي، وفي كتاب آداب السماع بعد أن يستدل بحديث مزامير آل
داود، أن تحريم السماع كان كتحريم الخلو بالأجنبية، فهو حرام لأنه مُحث على الزنا
فيقول في أسباب تحريم الموسيقى: "الاجتماع عليها لما أن صار من عادة أهل الفسق
فيمنع من التشبه بهم؛ لأن من تشبه بقوم فهو منهم [...] فحرم معها ما هو شعار أهل
الشرب وهي الأوتار والمزامير فقط، وكان تحريمها من قبل الأتباع كما حرمت الخلوة
بالأجنبية لأنها مقدمة الجماع، وحرم النظر إلى الفخذ لاتصاله بالسوأتين، وحرم قليل
الخمر وإن كان لا يسكر لأنه يدعو إلى السكر". ولست أدري كيف وصل الغزالي لهذه
الرؤية التحليلية المبكرة، وكأنه كان يدري أن الموسيقى يمكن أن تخلوا من هذه
الأسباب لتتجرد في جمالية الصوت دوم المنكرات، ولعله رأى ذلك فعلًا في التغني بالحب
الإلهي بعد تصوفه.



ولن أذكر المزيد في تفصيل الغزالي هنا، وعلى القارئ إن كان مهتمًا، بالفائدة في
العلم وفي قوت القلب، أن يعود لفصل آداب السماع والوجد في الإحياء.



يبقى هنا الأحاديث التي خرجت واستدل عليها بتحريم الموسيقى، ومنها الصحاح. على أن
ابن حزم قد رأى أن لا يصح أي منها وله تعليقات على البخاري في تخريجهم، وذكر هذا في
رسالته القصيرة "رسالة في الغناء الملهي أمباح هو أم محظور"، ومن ناحية الغزالي فهو
يجيب فقط على حديث "كل شيء يلهو به الرجل فهو باطل" وحديث تحريم القينة، أما في
الأخير فهو يرى حرمتها استنباطية كما ورد، أي إن القينة تعرفيها عنده هي الجارية
التي تغني في الرجال في مجلس شرب، ولا شك في حرمانية هذا، وأما الأول فيرى أن مقصد
النبي فيه هو القصر الإضافي يلحق بالمحصور غير المحصور قياسًا فيه، كأن يقول "لا يحل
دم امرئ مسلم إلا بإحدى ثلاث" أو قول "وما الحياة الدنيا إلا متاع".

وأعلى حديث بدرجة الصحاح عن الموسيقى، وأكثرهم وضوحًا هو حديث الخمر والمعازف:
"ليكونن من أمتي أقوام يستحلون الحر والحرير والخمر والمعازف" فهو يعتمد على
التحريم بالاقتران وهو حجة ضعيفة كما أوردت، فالحرير ليس حرامًا مطلقًا مثلًا، فقد جاز
بيعه للكفار ولبسه للمسلمات، ولعل المعازف ذكرت هُنا لاقترانها بالخمر في جلسات
الأُنس. وعلى كلٍ فالقول بالتحريم هنا يخالف ما كان عليه أصحاب النبي كعبد الله بن
جعفر وقد اقتنى العود.

إن ما أتبعهُ في قراءة النص النقلي الذي يخالف ما يسير الاستنتاج العقلي إليه هو أن
التأويل النقلي ليس في محله أو أن النص النقلي يتطلب قراءة أكثر سياقية (وهو ما
فعله الغزالي في هذه المسألة كما أظهرنا)، فالموسيقى والغناء هي من زينة الله في
الحياة الدنيا يطرب بهما الوجد ويتحرك القلب، ومثلها كالمبصرات الجميلة والأطعمة
الحسنة والأصل بها جميعًا الحلال "وقد فصل لكم ما حرم عليكم". بل إن القول بتحريم
الموسيقى لا يستقيم تطبيقيًا، فالموسيقى نظريًا (بالتعريف الحديث) هي ما استقام فيها
الانسجام، واللحن والإيقاع ولا يوجد قياس رشيد يقول يبين لنا ما درجات الثلاثة في
المُقاس لتبيين دخوله في نطاق الحرمانية أم لا، على عكس تحريم المسكرات والكحوليات
مثلًا (وقد فُصلت)، فهناك قياسٌ للشيء أكان مُسكرًا أم لا، ولكن يستحيل أن يوجد قياس في
شيء غير موضوعي (subjective) كالموسيقى: لا وجد لخط حدودي واضح يخبرنا ما هو موسيقيٌ
أم لا.



وأخيرًا فأحد الأدلة المشهورة بين العوام هي الآية في سورة لقمان "ومن الناس من
يشتري لهو الحديث ليضل عن سبيل الله بغير علم"، وهي حجة ضعيفة لذا أردت أن أوردها
في ختامي، فقد قيل هنا أن لهو الحديث هو الموسيقى والغناء، وهذا ليس بمصيب وإن
اتفقت عليه فئة كثيرة من المفسرين، فلهو الحديث قد يكون أي شيء به صورة كلامية،
كالشعر أو الكلام الزور واللغو، بل وإن كان كلامًا قدسيًا (كما طرح ابن حزم)، كأن
يلهوا أحدهم بالقرآن ليصد به عن سبيل الله لانطبقت عليه الآية، ولو كرر أحدهم لفظ
الجلالة بصوت عال وقت الدجى ليزعج به المسلمين لكان هذا من لهو الحديث، وغير ذلك
فالآية تضع شرط الصد عن سبيل الله، هل يصد أن يسمع أحدهم مجموعة التشيلو سويت
ليوهان سباستيان باخ عن طاعة الله؟ لا. وإني لأحسب أن قول المفسرين بأن المقصود هنا
هو الغناء ينطبق عليه ما ذكرت أعلاه بأن جلسات السماع ما كانت تخلوا من المعصية
بزمانهم، أو ما ظهر في زمين النبي بتغني الكفار بسجع الكهان وبالشعر الذي يؤذي
النبي.


** [2024-03-29 Fri 09:10]
وأخيرًا فإني أعتقد أن حكم الموسيقى عند الشيوخ سيجري عليه يومًا ما حكم التصوير
الفوتوغرافي، وقد قال الكثير من علماء المسلمين المعاصرين بتحريم التصوير لحديث
النبي "أشد الناس عذابا يوم القيامة المصورون" وكإقامة تشريعية للسلطة "للمراقبة
والمعاقبة" رأى ابن باز أن التصوير محرم إلا بما فيه الضرورة، وكانت الضرورة عنده
هي تمكين دولة آل سعود. أما غيره فقد وجدوا أن لا معنى للحديث بمعناه المعاصر، وأن
النبي لم يعرف التصوير الفوتوغرافي بل عرف التصوير الذي يُرسم فيه صنم فيعبد، فيحرم
التصوير في تحريم ما يُصور.

وكما أوضحت فالنبي ومن لحق زمانه من المسلمين لم يعرفوا السماع دون ارتباطه بما
يستنكرونه، وقد اُستثني الغزالي من هذا. والسؤال (والمعضلة أيضًا) هنا، إذا كان ما
جعل علماء المسلمين ينتبهون لسخافة تحريم التصوير هو حاجة السلطة له، فأنى لهم أن
ينتبهوا لسخافة الأمر في الموسيقى؟  #[[id:nm0dxtp02wj0][Islam]]

* Footnotes

[fn:10] كتاب تحريم آلات الطرب، الرد على رسالة ابن حزم وبيان سبب الرد، الفصل
الخامس: مذاهب العلماء في تحريم آلات الطرب.

[fn:9] al-Hasan ibn
Ahmad al-Kâtib, La Perfection des connaissances musicales, trans. by A. Shiloah, Paris, 1972, pp. 99ff.
[fn:8] كتاب الكلام على مسألة السماع، فصل: بطلان قول أهل السماع: إن السماع يحصل
محبوب الله، وما حصل محبوب الله فهو محبوب له، قول صاحب القرآن: المنكرون على
السماع أضعاف أضعاف من حضروه.


[fn:7] فصل أقوال العلماء في سماع العود والغناء وبيان مذاهبهم وحجج كل وتحقيق
المقام بما يشفي ويكفي.
[fn:6] المطالب العالية بزوائد المسانيد الثمانية، رقم 1679، عن هشام بن حسان.

[fn:5] سير أعلام النبلاء، الطبقة الثالثة، الماجشون.
[fn:4] وفيات ابن خلكان، ابن الماجشون (فصل العين).

[fn:3] (ترجمه ابن سعد "كان فقيها ورعا متابعا لمذاهب أهل الحرمين مفرعا على أصولهم، ذابا عنهم.")
[fn:2]سير أعلام النبلاء، الطبقة الحادية عشر، ابن الماجشون.

[fn:1] فيما قاله الأوزاعي الشامي مثلًا "نتجنب من قول أهل العراق شرب المسكر، ومن
قول أهل الحجاز استماع الملاهي" (ترجمة الأوزاعي في سير أعلام النبلاء في الطبقة السادسة.)

