:PROPERTIES:
:ID:       shui29f0w2k0
:END:
#+date: <2024-01-16 Tue 06:58>
#+title: Note on marriage

I've a simple take on marriage and relationships that does not involve my radical thoughts about family, I think it should very obvious, but I find myself have to point it out in many discussions. And it's basically about the struggle that occurs because of class differential between couples, it can be reduced to a simple imbalance or dependency issue. My view derives from the historical nature of the relationship between men and women. Historically speaking, there's a very interesting fact in the very maiden year of human slavery, that's, female slavery appeared earlier that male's[cite:@lerner-1983-women]. To understand the significance of that let us understand why slavery ever appeared; slavery is something that is as new as civilization to the H. sapiens, actually slavery only dates back to 3500 BC[cite:@tetlow-2004-sumer], most anthropologists explain this emergence as related to the new production techniques that were adopted and led eventually to a the first class division known in history. The interesting thing here is that, this division happened earlier to females, they were enslaved but not only by higher class but by an opposite (equal) gender. This happened because the new intensive production techniques tended to prioritize men’s labour over women’s for the first time which was not the case at all: women used to be as productive and their /labour/ was as much important as men's in the pre-horticulture era[cite:@friedl-1975-women p. 28]. What is to be learnt from this historical fact? Well, basically the more differences in power between parties the more pulverization is likely to occur.  Consequently, when you apply this to modern-relationships decisions you will find that many people did not learn this basic lesson of history yet. #[[id:ydb1kfn02wj0][Modus Vivendi]]