:PROPERTIES:
:CATEGORY: stack
:CUSTOM_ID: ae7iqgo0uhk0
:ID: ae7iqgo0uhk0
:lang: ar
:subtitle: Where the Love of Life Delivers
:END:
#+title: وحب الشجاع النفس أورده الحربا
#+DATE: <2025-03-01 Sat 05:15>

قال أبو الطيب: 

#+begin_verse
[[id:hws7d790k6k0][أرى كلنا يبغي الحياة لنفسه]]
حريصًا عليها مُستهامًا بها صبَّا

فحُب الجبان النفس أورده التقى
وحب الشجاع النفس أورده الحربا

ويختلف الرزقان، والفِعل واحدٌ
إلى أن يرى إحسان هذا لذا ذَنبا
#+end_verse
وهذا خير ما قاله، رحمه الله، في التفريق بين الكريم والجبان. فحب الحياة والصراع
من أجل البقاء فطرة عند كل الكائنات، يقول "مُستهامًا" والمُستهام هي مبالغة عربية
جميلة في وصف العاشق، أي يشتد عليه العشق والصبابة حتى يهيم على وجهه لا يدري أين
هو. وهذا هو حالنا. فثم: حب الجبان النفس، أورده التقى، أي أن يتقي ويحتمي من
الدخول في المعركة، ويتجنبها، ويستكن للأمن ويطمئن له (وأليس هو القائل: وما الخوف
إلا ما تخوفه الفتى ولا الأمن إلا ما رآه الفتى أمنا؟) وقال تعالى واصفًا الغافلين:
ورضوا بالحياة الدنيا واطمأنوا بها. وقال أيضًا: ومن الذين أشركوا يود أحدهم لو يعمر
ألف سنة. فالجبان يرى في ذلك مجازاته لحبه لنفسه، أما الكريم فحبه لنفسه ومنزلة
نفسه ومكان نفسه، وعلو مجازاته لها أورده القتال والحرب وإن راحت به مهجته. فاختلف
الرزقان، والفعل واحدٌ. وقد خَلص أبو الطيب نفسه في سنٍ مبكرة من اتقاء الموت والحرب،
فقال في صباه: 

#+begin_verse
رِدي حِياضَ الرَدى يا نَفسُ وَاِتَّرِكي
حِياضَ خَوفِ الرَدى لِلشاءِ وَالنِعَمِ
#+end_verse

فهُنا هو آمر نفسه: ردي هي الأمر لصيغة المؤنث من فعل "ورد" (وهو نفس الفعل الذي
ذكره في البيت أعلاه: أورده الحربا) والحياض هو جمع الحوض، ومنه كانت تشرب الناس
وكذا الإبل والشاء. ثم أنظر إلى قولته "واتركي" وهي تعني اتركي، وتمعن هنا في
استخدام صيغة الافتعال للمبالغة، فيا حبذا ترك كهذا الترك لا رجعة فيه. وفعل الورود
هنا له دلاله، فالورود هو القُدوم على الشيء، وليس فقط تقبله، أي أنه لا يأمر نفسه
بألا تهب الموت وحسب، بل أن ترده، ويعلل ذلك بعد بيتين بأن المجد والعلا لا يأتيان
إلا بذي السُبل، فيقول: 

#+begin_verse
أَيَملِكُ المُلكَ وَالأَسيافُ ظامِئَةٌ 
وَالطَيرُ جائِعَةٌ لَحمٌ عَلى وَضَمِ
#+end_verse
لا والله يا أبا الطيب لا يُملك الملك إلا بذلك. #[[id:nk2kigk0ybk0][al-Mutanabbi]] and [[id:ydb1kfn02wj0][Modus Vivendi]]
