:PROPERTIES:
:ID:       2ar8en10n2k0
:END:
#+title: Anthology and Treasury
#+cite_export: csl  harvard.csl
#+date:  <2024-01-07 Sun 12:25>
#+filetags: :project_archived:

#+begin_export HTML
<head>
<style>
.timestamp-wrapper {display: none !important;}

p {
    text-align: start !important;
    unicode-bidi: plaintext !important;
}

</style>
</head>
#+end_export

Here I collect my highlights from readings. More details of how this works can be found [[file:whata.org][here]].
-----
* insert                                                              :noexport:
#+BEGIN_SRC emacs-lisp :results raw
(defun salih/get-heading-content-by-id (file id &optional only-contents)
  "Get the content of a heading with ID from FILE.
If ONLY-CONTENTS is non-nil, return only the body without the heading itself."
  (with-temp-buffer
    (insert-file-contents file)
    (org-mode)
    (goto-char (point-min))
    (let ((found nil)
          (content ""))
      ;; Search for the ID
      (while (and (not found) (re-search-forward (format ":ID:\\s-*%s" id) nil t))
        (setq found t))
      (when found
        ;; Go to the heading
        (org-back-to-heading t)
        (let ((start (if only-contents
                         (save-excursion
                           (org-end-of-meta-data t)
                           (point))
                       (point)))
              (end (save-excursion
                     (org-end-of-subtree t t)
                     (point))))
          (setq content (buffer-substring-no-properties start end))))
      content)))

(defun salih/mkinclude-expanded (node remove-title &optional astr)
  "Like salih/mkinclude but returns the actual content instead of #+INCLUDE.
This allows Hugo to process the content directly."
  (unless astr
    (setq astr "**"))
  (let* ((id (org-roam-node-id node))
         (entry (org-roam-node-file (org-roam-node-from-id id)))
         (cite (file-name-sans-extension (file-name-nondirectory entry)))
         (content (salih/get-heading-content-by-id entry id remove-title)))
    (if remove-title
        (format "%s\n\n/Derived from/ [cite:@%s], no. %s. Appeared: %s\n-----\n"
                content
                cite
                (substring (cl-first (s-split " " (salih/get-node-property node "NOTER_PAGE"))) 1)
                (format-time-string "%Y-%m-%d (%H:%M)" (cdr (org-id-decode (org-roam-node-id node)))))
      content)))

(defun salih/print-text-nodes-anth-expanded ()
  "Generate anthology content with expanded includes (no #+INCLUDE directives)."
  (let* ((nodes (sort (salih/get-back-nodes "3xedczc0i2k0")
                      #'salih/compare-org-id))
         (strings '()))
    (while nodes 
      (push (salih/mkinclude-expanded (car nodes) t)
            strings)
      (setq nodes (cdr nodes)))
    (mapconcat 'identity strings "")))

;; To use this, replace your eval block with:
(eval (salih/print-text-nodes-anth-expanded))
#+end_src
* Content


#+RESULTS:
وليس يفرح العاقل بالمال الكثير، ولا يحزنه قلته. ولكن ماله عقله وما قدمُ من صالح عمله.


/Derived from/ [cite:@al-muqaffaa-1997-al-athar-kamil], no. 131. Appeared: 2025-12-12 (16:31)
-----
ولا تقل كما يقول السفهاء أُخبر بما سمعتُ؛ فإن الكذب أكثر ما أنت سامع، وإن السفهاء أكثر من هو قائل، وإنك إن صرت للأحاديث واعيًا وحاملًا، كان ما تعي وتحمل عن العامة أكثرها مما يخترع المخترع بأضعاف.



/Derived from/ [cite:@al-muqaffaa-2019-al-durrah-yateem], no. 34. Appeared: 2025-12-03 (22:35)
-----
إن استطعت أن تنزل نفسك دون غايتك في كل مجلس ومقام ومقال ورأي وفعل فافعل، فإنَّ رفْع الناس إياك فوق المنزلة التي تحطُّ إليها نفسك، وتقريبهم إياك في المجلس الذي تباعدت عنه، وتعظيمهم من أمرك ما لم تعظم، وتزيينهم من كلامك ورأيك ما لم تزين؛ هو الجمال.


/Derived from/ [cite:@al-muqaffaa-2019-al-durrah-yateem], no. 32. Appeared: 2025-12-03 (22:24)
-----
لِيكُن مما تصرف به الأذى والعذاب عن نفسك ألا تكون حسودًا؛ فإن الحسد خلق لئيم، ومن لؤمه أنه يؤكل بالأدنى من الأقارب والأكفاء، فليكن ما تُقابِل به الحسد أن تعلم أن خير ما تكون حين تكون مع من هو خير منك، وأن غُنمًا لك أن يكون عشيرُك وخليطُك أفضل منك في القوة، فيدفع عنك بقوته، وأفضل منك في الجاه فتصيب حاجتك بجاهه، وأفضل منك في الدين فتزداد صلاحًا بصلاحه. ليكن ما تنظر فيه من أمر عدوك وحاسدك أن تعلم أنه لا ينفعك أن تخبر عدوك أنك له عدو، فتنذره نفسك، وتؤذنه بحربك قبل الإعداد والفرصة.



/Derived from/ [cite:@al-muqaffaa-2019-al-durrah-yateem], no. 30. Appeared: 2025-12-03 (22:13)
-----
اﻋﻠﻢ أن إﺧﻮان اﻟﺼﺪق ﻫﻢ ﺧير ﻣﻜﺎﺳﺐ اﻟﺪﻧﻴﺎ، زﻳﻨﺔٌ ﰲ اﻟﺮﺧﺎء، وﻋﺪةٌ ﰲ اﻟﺸﺪة، وﻣﻌﻮﻧﺔٌ
ﻋﲆ المعاش والمعاد، ﻓﻼ ﺗﻔﺮﻃﻦ ﰲ اﻛﺘﺴﺎﺑﻬﻢ واﺑﺘﻐﺎء اﻟﻮﺻﻼت واﻷﺳﺒﺎب إﻟﻴﻬﻢ. اﻋﻠﻢ أﻧﻚ
واﺟﺪٌ رﻏﺒﺘﻚ ﻣﻦ اﻹﺧﺎء ﻋﻨﺪ أﻗﻮام ﻗﺪ ﺣﺎﻟﺖ ﺑﻴﻨﻚ وﺑﻴﻨﻬﻢ ﺑﻌﺾ اﻷﺑﻬﺔ اﻟﺘﻲ ﻗﺪ ﺗﻌﱰي أﻫﻞ
المروءات ﻓﺘﺤﺠﺰ ﻣﻨﻬﻢ ﻛﺜيرًا ﻣﻤﻦ ﻳﺮﻏﺐ ﰲ أﻣﺜﺎﻟﻬﻢ، ﻓﺈذا رأﻳﺖ أﺣﺪًا ﻣﻦ أوﻟﺌﻚ ﻗﺪ ﻋﺜﺮ ﺑﻪ
اﻟﺰﻣﺎن ﻓﺄﻗﻠﻪ.


/Derived from/ [cite:@al-muqaffaa-2019-al-durrah-yateem], no. 20. Appeared: 2025-12-03 (20:59)
-----
قال القيرواني عن الشطرنج: الشطرنج حرب سجال، وخيل عجال، وفرسان ورجال، قريبة
الآجال، سريعة عودة المحال، تستغرق الفكرة، وتسلب اللبّ استلاب السكرة. وتترك اللسان
وما أراد، أساء أو أجاد، إلا أنها تدني مجلس الصعلوك من أشرف الملوك.


/Derived from/ [cite:@al-kashkool], no. 234. Appeared: 2025-12-02 (17:21)
-----
In the matter of moral law we witness a strange phenomenon to which men pay too little attention. If I speak to an unlearned man about geology, astronomy, history, natural philosophy, or mathematics, he receives the information as quite new to him, and never says to me, “There is nothing new in what you tell me; every one knows it, and I have known it for a long time.” But tell a man one of the highest moral truths in the simplest manner, in such a way as it has never been before formulated, and every ordinary man, particularly one who does not take any interest in moral questions, and, above all, one who dislikes them, is sure to say, “Who does not know that? It has been always known and expressed.” And he really believes this. Only those who can appreciate moral truths know how to value their elucidation and simplification by a long and laborious process, or can prize the transition from a proposition or desire at first vaguely understood to a firm and determined expression calling for a corresponding change of conduct.


/Derived from/ [cite:@tolstoy-2022-what-shoul], no. 72. Appeared: 2025-11-15 (23:04)
-----
وجميع أحداث الدهر وأمور الناس لا تأثير لها في رجل بنيته كمنل بنيتي، وما من تأثير
تحدثه لي الهموم المستمرة إلا إذا تجددت انطباعاتها لحظة بعد لحظة. لأن الفترات
التي تنقضي ما بين همّ وهمّ، مهما كانت قصيرة، تكفي لأن ترجعني إلى نفسي. أنا هو
الذي يرضى الناس ما داموا قادرين على أن يؤثروا في حواسي. فإذا انقضت هذه الفترة،
أصبحت من جديد ذلك الذي أرادت الطبيعة أن أكون.  هذه هي، مهما أمكنهم أن يعملوا،
حالتي الأكثر ثباتاً والحالة التي بها أتنوق، رغم أنف القدر، السعادة التي أشعر بأني
قد خلقت لها. لقد وصفت هذه الحال في ماجس من هواجي، فهي تلازمني جدّ الملازمة، حتى
إني لا أغني إلا أن تطول مدتها ولا أخشى إلا أن أراها مكدّرة مكرّرة. إن الضرر الذي
أنزله الناس بي لا يمسني بوجه من الوجوه. فإن خشيتي مما يمكنهم أن ينزلوه بي ضرر هي
وحدها جديرة بأن تملأ نفسي اضطراباً. ولقد أيقنت بأنهم أصبحوا خلواً من مأخذ جديد
يتيح لهم أن يؤثروا في بعاطفة مستمرة، ولذلك أستهزئ بجميع دسائسهم، وأتمتع بنفسي
رغم أنوفهم.


/Derived from/ [cite:@rousseau-2015-rever-solit-walker], no. 156. Appeared: 2025-09-02 (16:51)
-----
ويبدو أن النباتات قد زرعت بسخاء على الأرض، كما نثرت الكواكب على وجه السماء،
لتدعو الإنسان، بجاذب من اللذة والفضول، إلى دراسة الطبيعة، ولكن الكواكب نثرت
بعيداً عنا، فلا بدّ من معارف تمهيدية، ومن أدوات وآلات، ومن مراصد طويلة جدّ الطول
لنصل إليها ونقرّبها من متناولنا. وأما النباتات فهي بطبيعتها في متناولنا، ثبتت تحت
أقدامنا بل في أيدينا، وإذا كان صغر أجزائها الجوهرية يُخفيها، أحياناً عن الأنظار،
فإن الأدوات التي تكبرها وتبرزها للعيان هي أسهل جداً في الاستعمال من أدوات علم
الفلك.  وعلم النبات هو دراسة عاطل من العمل كسول منفرد بنفسه، فلا حاجة لمحراث هذا
العلم إلا إلى حدّ وعدسيّة مكبّرة، فهو يتنقّل، حراً هائماً، من غرض إلى آخر ويستعرض كل
زهرة وفضول، ولا يكاد يبين قوانين تكوينها حتى يتذوّق، في مراقبتها، لذة من دون مشقة
تعادل تلك اللذة التي يستمتعها بعد تعب. وفي هذه الهواية فتنة لا يشعر بها المرء
إلا في تمام سكون الشهوات ولكنها تكفي وحدها لجعل الحياة سعيدة حلوة، ولكن ما إن
يمتزج بهذه الهواية داعٍ مصلحة أو كبرياء، سواء أكان ذلك لمال، وظائف أم لتأليف كتاب
أم بغية التعلّم لتثقيف الناس أم ليصبح جامع الحشائش مؤلفاً أو أستاذاً، ما إن تمتزج
هذه الدواعي، حتى تتوارى تلك البهجة العذبة وتزول.

لذّة هذه الدراسة، لأن المنشغل بها لا يطلب معرفة ولكن تبجّحاً بالمعرفة، وكأنه، وهو
في الغابات، على مسرح من مسارح المدن، لا همّ له إلا إعجاب الناس به. وهناك أناس
يكتفون بالاشتغال بعلم النبات في مكاتبهم أو في حدائقهم بدل أن يراقبوا النبات في
الطبيعة، فلا يرون النبات إلا إلى الأساليب وطرق الترتيب، مما يبعث مواضيع للنقاش
والنزاع لا نهاية لها، ولكنها لا تلقي النور على نبتة جديدة غير معروفة، ولا على
التاريخ الطبيعي وعالم النبات. ومن هذا تتولد حروب البغض والحسد التي تثيرها
المزاحمة على الشهرة في قلوب المنشغلين بعلم النبات أكثر مما تثيرها في قلوب غيرهم
من العلماء.  ثم إنهم، يتشوّههم هذه الدراسة المستعصبة، ينقلونها إلى وسط المدن
والمجامع العلمية، حيث يتسرب إليها من الفساد ما لا يقل عما يتسرب إلى النباتات
الغريبة في الحدائق المعدّة للنباتات النادرة.


/Derived from/ [cite:@rousseau-2015-rever-solit-walker], no. 133. Appeared: 2025-09-02 (16:51)
-----
أيتها الأزهار الملائكة، طلاء الروح، وأنت أيتها الظلال المنعشة الرطبة والجداول
والرياض والخضرة! تعالي طهري أخيلتي من الدنس الذي تلطخه به هذه الأمور البشعة. إن
نفسي التي ماتت في السعي وراء عظام الأمور، أصبحت لا تنفعل إلا بكل ما هو مؤثر. لم
يبق لي إلا الأحاسيس، وربها وحدها يستطيع الحزن أو السرور أن يصلا إلي في هذه
الدنيا. وإذا أراني وقد تبنيت الأشياء الضاحكة المحدقة بي، فها إني أمعن النظر
فيها، وأتأملها وأقابل بينها، وها إني قد أصبحت، على حين فجأة، مشتغلاً بعلم النبات،
بقدر ما يحتاج إليه من لا يقبل على دراسة علوم الطبيعة إلا ليجد، يوماً بعد يوم،
دواعي جديدة للإغرام بها.


/Derived from/ [cite:@rousseau-2015-rever-solit-walker], no. 132. Appeared: 2025-09-02 (16:51)
-----
إن الأشجار والشجيرات والنباتات هي حُلى الطبيعة وكساها. ولا شيء أدعى إلى الكآبة من
برية عارية جرداء لا تبسط للناظر إلا حجارة وطيناً ورملاً. ولكن إذا بعثت فيها الحياة
الطبيعة وكستها ثوب عرسها ما بين مجاري المياه وتغريد الطيور، فإن الأرض تعرض على
الإنسان، في تناسق العوالم الثلاثة منظراً مليئاً بالحياة والسحر ومثيراً للاهتمام،
وهو، في العالم، المنظر الوحيد الذي لا يمله العين والقلب أبداً.

وكلما كانت نفس المتأمل مرهفة الإحساس، ازداد استسلاماً إلى الانجذابات الروحية التي
تجيرها فيه هذا الانسجام، فيستولي على حواسه عند ذاك تخيلات حوله عميقة، ويتيه، وهو
في نشوة لذيذة، في لا نهاية هذا التنظيم الجميل الذي يُحسُّ أن ذاتيته قد اندمجت فيه،
وعندئذٍ تختفي أمام عينيه جميع الأشياء الجزئية، فلا يرى شيئاً إلا في الأشياء
الكلية، ولا يحسُّ شيئاً سواها. ولا بد من ظروف خاصة تضيِّق أفكاره وتطوِّق خياله حتى
يستطيع أن يمعن النظر، جزءاً فجزءاً، في هذا العالم الذي يحاول أن يحتضنه.

وطالبت في فترة هذه الاستراحة، استراحة العينين التي، إذا ما خان المرء التوفيق،
تريح وتسلي وتلهي الذهن، وتتوقف إلى وقت ما الشعور بالهموم. وطبيعة الأشياء تساعد
على هذا التلاهي جداً المساعدة وتجعله أكثر فتنة. إن الروائح الذكية، والألوان
الضارخة، والأشكال البالغة الحُسن في الأناقة تبدو وكأنها تتنازع، بجميع قواها، حقَّ
استرعاء انتباهنا. ولا يقتضي الاستسلام إلى هذه الأحاسيس المتناهية في العذوبة إلا
الشعور متذوق اللذة، وإذا لم يشعر باللذة جميع من وقعت هذه المناظر تحت أعينهم،
فلأن بعضهم يعوزه الإحساس الطبيعي، ولأن معظمهم إذا ملكت عليه مشاعره أفكار أخرى،
لا يستسلم، إلا خلسة، إلى الأشياء التي تؤثر في حواسه.


/Derived from/ [cite:@rousseau-2015-rever-solit-walker], no. 123. Appeared: 2025-09-02 (16:51)
-----
ولكن الصبر والرفق والتسليم والنزاهة والعدل الذي لا يحابي، هي كلها مقتنى يحمله
المرء معه، مقتنى يمكن أن يحرز الغنى به من دون انقطاع ومن دون أن يخشى أن يسلبه
إياه سالب ولو كان الموت.  وسأكرس ما بقي من شيخوختي للقيام بهذه الدراسة النافعة
وحدها.  وما أسعدني لو أني باستكمالي لفضائل نفسي، أعرف أن أخرج من الحياة لا أحسن
مما أنا - لاستحالة إمكان هذا - ولكن أكثر فضيلة مني يوم دخلتها.


/Derived from/ [cite:@rousseau-2015-rever-solit-walker], no. 63. Appeared: 2025-09-02 (16:51)
-----
اعلم أن قابل المدح كمادح نفسه، والمرء جدير أن يكون حبُّه المدحَ هو الذي يحمله على
ردِّه، فإن الرادَّ له محمود، والقابل له معيب. لتكن حاجتك في الولاية إلى ثلاث خصال:
رضى ربِّك، ورضى سلطانٍ إن كان فوقك، ورضى صالح من تلي عليه. ولا عليك أن تلهو عن
المال والذكر، فسيأتيك منهما ما يكفي ويطيب. واجعل الخصال الثلاث بمكانِ ما لا بد لك
منه، والمال والذكر بمكانِ ما أنت واجدٌ منه بدًّا.

- [2025-08-08 Fri 21:10] Salih Muhammed: Might be related to: [[id:7eskndp02wj0][Nietzsche on Eulogy]].


/Derived from/ [cite:@al-muqaffaa-2019-al-durrah-yateem], no. 17. Appeared: 2025-09-02 (16:46)
-----
والنتيجة التي يمكن أن أستخلصها من جميع هذه الاعتبارات هي أني لم أكن قط قابلاً
للاندماج في المجتمع المدني، حيث تجد كل شيء إزعاجاً وارتباكاً والتزاماً وواجباً ولأن
طبعي المستقل جعلني دائماً غير قابل لإرغام النفس على اتباع ما تواضع الناس عليه،
وما لا بد منه لمن أراد أن يعيش معهم. وما دمت أعمل حراً فأنا طيب ولا أعمل إلا
خيراً، ولكن لا أكاد أشعر بوطأة النير، سواء أكانت من العزم أم من الناس، حتى أصبح
ثائراً بل جامعاً، وحتى أراني لست شيئاً. وإذا
اضطررت إلى عمل عكس ما تقضي به إرادتي، امتنع عن العمل أياً كانت غبني هذا الامتناع،
بل إني لا أعمل بوحي إرادتي نفسها، لأني ضعيف. فامتنع عن العمل لأن كل ضعفي منصب
على العمل، وكل قوتي هي في الامتناع، وجميع خطاياي هي من الإهمال، ونادراً جداً أن
تكون من الفعل.

ولم أعتقد قط أن حرية المرء تقوم على أن يعمل ما يريد، ولكنها تقوم على ألا يعمل
أبداً ما لا يريده، وهذه هي الحرية التي طالما طالبت بها، وكثيراً ما حرصت عليها وبها
كنت موضع فضيحة عند معاصري، لأنهم، إذ كانوا ذوي نشاط وطموح وحركة، كانوا يعتدون
الحرية عند غيرهم، ولا عند أنفسهم؛ إذ لا يريدونها لأنفسهم، شرط أن يعملوا في بعض
الأحيان، إرادتهم أو بالأحرى أن يسلطوا على حرية غيرهم، قلت ولأنهم يكلفون أنفسهم،
طول حياتهم، عمل ما يشمئزون منه ولا يترددون عنا به غفلة كي يكونوا آمرين. فجعلتهم
على لم يكن إذن في تبحثي من المجتمع على أني عضو غير نافع، بل رباعدي عنه من دون
عاكمة، على أني عضو مفسد؛ وأنا أصرح بأني أقللت من عمل الخير لكني لم أعمل شراً ولا
غني الشر إرادتي طول حياتي، وأملك أن يكون في العالم رجل قد عمل من الشر في الحقيقة
والواقع، أقل مما عملت.


/Derived from/ [cite:@rousseau-2015-rever-solit-walker], no. 117. Appeared: 2025-08-22 (16:59)
-----
هناك أنواع من البلايا تسمو بالنفس وتقوّيها كما أن هناك ضروباً أخرى تحطمها وتقضي
عليها، ومن هذا النوع المصائب التي أصبحت فريسة لها. ولو مزج قليل من الخمير في
مصيبتي لزاد في اختبارها إلى أقصى حد ولأصبحت هائجاً ثائراً، ولكنها لم تجعلني إلا
صفراً. وإذ أصبحت عاجزاً عن أن أحسن عملاً يفيدني أو يفيد غيري، فقد امتنعت عن أن
أعمل، وهذه الحال ليست بحال براءة إلا لأنها تجعلني أجد نوعاً من العذرية أن أستسلم،
بلا لوم، إلى سجيتي. إني تجاوزت الحد بلا شك، لأنني أتجنب الفرص المواتية للعمل،
حتى في الحالات التي لا يكون فيها العمل إلا صالحاً، ولكني ليتبقى أنهم لا بتركوني
أنظر إلى الأشياء كما هي، أمتنع عن الحكم على الظاهر الذي يموهونها به، وعلى ضروب
المخادعة التي يخفون وراءها الأسباب الدافعة للعمل، ويكفي أن أترك هذه الأسباب في
متناولي لأكون على يقين أنها خداعة.


/Derived from/ [cite:@rousseau-2015-rever-solit-walker], no. 112. Appeared: 2025-08-22 (16:57)
-----
وإذا  أنا مطمئن لهذه الاستعدادات، فإني أجد فيها، مع رضاي عن نفسي، الأمل والتعزية
اللذين أنا في حاجة إليهما في حالي الحاضرة. وليس من الممكن أن عزلة تامة كعزلتي،
دائمة كل الدوام، مليئة بالحزن والوحشة، وأن العداوة الحساسة كل الإحساس، الدائمة
العمل، عداوة الجيل الحاضر وما ترميني به من خزي بلا انقطاع - قلت ليس من الممكن
ألا يلقي به كل هذا في أحضان الخور والانهيار؛ وإذا ما وجدتني مزعزع الأمل، فإن
الشكوك المثبطة للهمم تعود من وقت إلى وقت إلى تعكير صفاء نفسي تملؤها حزناً وكآبة.
وعند ذلك، إذ أراني عاجزاً عن ممارسة أعمال الذهن، اللازمة لإدخال الطمأنينة إلى
نفسي، فإني أشعر بحاجة إلى تذكر ما صممت عليه قديماً، فضروب العناية، والانتباه،
وإخلاص القلب، كل هذا الذي تكلفته في سبيل ذلك التصميم يعود عندئذ إلى ذاكرتي وبعيد
إلى ملء نفسي. وهكذا فإني أطرح جميع الفكر الجديدة كما تُطرح الأخطاء المشؤومة التي
ليس لها إلا مظهر مزين لا تصلح إلا لإقلاق راحتي.


/Derived from/ [cite:@rousseau-2015-rever-solit-walker], no. 62. Appeared: 2025-08-22 (16:50)
-----
لا تكوننَّ نزِر الكلام والسلام، ولا تُفرِّطنَّ بالهشاشة والبشاشة، فإن إحداهما من الكِبْر، والأخرى من السخف.

[2025-12-03 Wed 20:55] Salih Muhammed: I translate like the follows: Do not be miserly with your words and greetings, nor excessive in fragility and cheerfulness; for one stems from arrogance, and the other from frivolity.


/Derived from/ [cite:@al-muqaffaa-2019-al-durrah-yateem], no. 18. Appeared: 2025-08-08 (21:24)
-----
اعلم أن رأيك لا يتسع لكل شيء ففَرِّغْه للمهم، وأن مالك لا يغني الناس كلَّهم فاختص به
ذوي الحقوق، وأن كرامتك لا تطيق العامة فتَوِّجْ بها أهل الفضائل، وأن ليلك ونهارك لا
يستوعبان حاجاتك وإن دأبت فيهما، وأنه ليس لك إلى أدائهما سبيلٌ مع حاجة جسدك إلى
نصيبه منهما، فأحسن قسمتهما بين دَعَتِك وعملك. واعلم أنك ما شغلت من رأيك بغير المهم
أزرى بالمهم، وما صرفت من مالك بالباطل فَقَدْتَه حين تريدُه للحق، وما عدلت به من
كرامتك إلى أهل النقص أضرُّ بك في العجز عن أهل الفضل، وما شغلت من ليلك ونهارك في
غير الحاجة أزرى بك في الحاجة.


/Derived from/ [cite:@al-muqaffaa-2019-al-durrah-yateem], no. 18. Appeared: 2025-08-08 (21:15)
-----
The social moresh of capitalism have induced the view that virtually every
subjectively felt need or unhappiness can be eliminated if one can buy more
commodities. The competitive and economically insecure world within which
workers function generally creates subjective feelings of anxiety, loneliness,
and alienation. The cause of these feelings has been perceived by most working
people as their inability to buy enough commodities to make them happy.  But as
workers have received higher w ages and bought more commodities, the general
unhappiness and anxiety have continued. The problem, they have tended to
conclude, is that the increase in wages was insufficient. Misperceiving the root
cause of their condition, they have frequently gotten aboard an Alice in
Wonderland treadmill, where the more one gets the more needy one feels, the
faster one runs the more inadequate one's pace appears to be, the harder one
works the greater appears to be the need for even harder work in the future.


/Derived from/ [cite:@e.-2011-histor-econom-thoug], no. 32. Appeared: 2025-07-12 (20:03)
-----
في وقت السِّلم، يُهاجم المقاتلُ ذاتهُ.


/Derived from/ [cite:@nietzsche-2009-diwan-nietz], no. 187. Appeared: 2025-07-11 (01:11)
-----
#+begin_verse
خاطفًا أريد أن أصير فأنطلق
مع البريق الأول للصّبح الجديد
عاليًا في الفضاء
فوق الواديّ والغاب والهوّة
#+end_verse


/Derived from/ [cite:@nietzsche-2009-diwan-nietz], no. 28. Appeared: 2025-07-11 (00:47)
-----
So great is my unhappiness at this time that in my dreams I am indescribably happy.


/Derived from/ [cite:@hannay-2015-paper-journ], no. 9. Appeared: 2025-06-25 (13:52)
-----
#+BEGIN_QUOTE
The whole of existence makes me anxious, from the smallest fly to the mysteries of the Incarnation. It’s all
inexplicable, myself most of all. For me all existence is contaminated, myself most of all. Great is my distress,
unlimited. No one knows it but God in heaven and he will not comfort me. No one but God in heaven can console me
and he will not take pity on me – Young man, you who are still at the beginning of your endeavour, if you have lost
your way, turn back! Turn to God and under his tutelage you will take with you a youthfulness fortified for adult deeds.
You will never know the suffering of one who, having wasted the strength and courage of youth in rebellion against
him, must now, exhausted and faint, begin a retreat through ruined lands and ravaged regions, surrounded on all sides
by the abomination of destruction, by gutted cities and the smoking ruins of disappointed hopes, by prosperity
trampled down and strength brought low – a retreat as slow as a bad year, long as eternity, interrupted monotonously
by the constantly repeated plaint: ‘These days give me no pleasure.’

#+END_QUOTE


/Derived from/ [cite:@hannay-2015-paper-journ], no. 9. Appeared: 2025-06-25 (13:52)
-----
What has often caused me suffering was that a reflective I has tried as if to imprint on my mind and preserve what my
real I, out of doubt, anxiety, disquiet, wanted in its concern with forming a view of the world to forget – to preserve it
partly because it was a necessary component, partly because it was a transitional factor of some consequence, for
fear that I should fake a result for myself.

So now, for instance, when my life seems set in such a way that I appear to be assigned in perpetuity to reading for
exams, and that no matter how long it lasts, my life will in any case progress no further than where I once arbitrarily
broke it off (just as one occasionally sees mentally deranged people who forget everything that occurred in between
and recall only their childhood, or forget everything except some single moment in their lives) – that I should be thus
reminded, by the thought of being a theology student, of that happy time of possibilities (what one might call one’s
pre-existence) and of my stopping there, in a state of mind rather like that of a child which has been given brandy and
had his growth stunted. When my active I now tries to forget this in order to act, my reflective I would so much rather
keep hold of it because it seems interesting and, as reflection raises itself to the level of a general consciousness,
abstract from my own personal consciousness.



/Derived from/ [cite:@hannay-2015-paper-journ], no. 9. Appeared: 2025-06-25 (12:30)
-----
Man hardly ever makes use of the freedoms he has, such as freedom of thought; in compensation he demands
freedom of speech instead.


/Derived from/ [cite:@hannay-2015-paper-journ], no. 9. Appeared: 2025-06-20 (14:40)
-----
Everyone takes his revenge on the world. My revenge consists in bearing my distress and anguish enclosed deeply
within me while my laughter entertains everyone. If I see someone suffer I give him my sympathy, console him as best
I can, and listen to him calmly when he assures me that I am fortunate. If I can only keep this up until the day I die I
shall have had my revenge.


/Derived from/ [cite:@hannay-2015-paper-journ], no. 9. Appeared: 2025-06-20 (14:32)
-----
I’ve often wondered why I am so reluctant to commit single observations to paper. But
the more I come to know great men in whose writings there is no sign of a kaleidoscopic
jostling together of some bundle of ideas (the example of Jean Paul has perhaps made
me prematurely anxious in this respect), and the more I bear in mind that a writer as
refreshing as Hoffmann has kept a journal, and that Lichtenberg recommends it, the
greater the urge to find out just why I should find this in itself innocent practice so
unpleasant, almost repellent. The reason has obviously been that I have thought every
time of possible publication, which might have called for a fuller treatment, which I didn’t
want to bother with. And enervated by such an abstract possibility (a kind of literary
hiccoughing and squeamishness), the aroma of the idea and mood evaporated. I think it
would be better instead, by frequent note-taking, to let the thoughts emerge with the
umbilical cord of the original mood intact and forget as far as possible any concern for
their possible use (which I would never realize anyway by looking up my journals) but
more as though unburdening myself in a letter to an intimate friend, so gaining on the
one hand the possibility of self-knowledge at a later moment, and on the other fluency,
the same articulateness in written expression which I have to some extent in speaking,
knowledge of many little traits to which I have given no more than a passing glance, and
finally, an advantage, if what Hamann says is true in another sense, in that there are
ideas which one gets only once in one’s life. Such backstage practice is certainly
necessary for anyone not so gifted that his development is in some way a public
phenomenon.

صالح محممد: أترجمها للعربية: كثيراً ما تساءلت لِمَ أتردد هكذا في إيداع الملاحظات
المفردة إلى الورق. لكن كلما ازددت معرفة بالعظماء الذين لا يُرى في كتاباتهم أثر
لذلك التزاحم الكاليدوسكوبي لحزمة من الأفكار (ولعل مثال جان بول قد أثار قلقي في
هذا الصدد قبل الأوان)، وكلما تذكرت أن كاتباً منعشاً كهوفمان قد احتفظ بيومياته، وأن
ليختنبرغ يوصي بذلك، ازداد إلحاح الرغبة في معرفة السبب وراء استياق هذه الممارسة
البريئة في ذاتها، بل واشمئزازي منها تقريباً. السبب واضح: أنني فكرت في كل مرة
بإمكانية النشر، مما قد يستدعي معالجة أوفى لم أكن أريد إرهاق نفسي بها. وإذ
أنهكتني هذه الإمكانية المجردة (نوع من الفواق الأدبي والتقزز)، تبخرت عبقة الفكرة
والمزاج. أعتقد أنه من الأفضل بدلاً من ذلك، عبر التدوين المتكرر، أن أدع الأفكار
تنبثق والحبل السري للمزاج الأصلي سليماً، وأن أنسى قدر الإمكان كل اهتمام
باستخدامها المحتمل (والذي لن أحققه أبداً على أي حال بمراجعة يومياتي) بل أكثر
كأنني أبثُّ همومي في رسالة إلى صديق حميم، فأكسب من جهة إمكانية معرفة الذات في لحظة
لاحقة، ومن جهة أخرى الطلاقة، نفس البلاغة في التعبير الكتابي التي أملكها إلى حد
ما في الكلام، ومعرفة السمات الصغيرة الكثيرة التي لم ألقِ عليها سوى نظرة عابرة،
وأخيراً، ميزة - إن صح ما يقوله هامان بمعنى آخر - في أن ثمة أفكاراً لا تأتي المرء
سوى مرة واحدة في حياته. مثل هذه الممارسة خلف الكواليس ضرورية حتماً لكل من لم يُوهب
موهبة تجعل نموه بطريقة ما ظاهرة عامة.


/Derived from/ [cite:@hannay-2015-paper-journ], no. 9. Appeared: 2025-06-20 (14:31)
-----
How awful on Judgement Day, when all souls return to life, to stand completely alone, alone and unknown to all, all.


/Derived from/ [cite:@hannay-2015-paper-journ], no. 9. Appeared: 2025-06-20 (14:31)
-----
It’s terrible how I have to buy every day, every hour – and the price fluctuates so!


/Derived from/ [cite:@hannay-2015-paper-journ], no. 9. Appeared: 2025-06-20 (14:26)
-----
God in heaven, let me really feel my nothingness, not to despair over it but to feel all the more intensely the greatness
of your goodness.

(This wish is not, as the scoffer in me would say, an Epicureanism, as when a gourmand starves himself so that food
will taste all the better.)


/Derived from/ [cite:@hannay-2015-paper-journ], no. 9. Appeared: 2025-06-20 (14:25)
-----
You, my heart’s sovereign mistress, stored in the deepest recesses of my heart, in my most brimmingly vital
thoughts, there where it is equally far to heaven as to hell – unknown divinity! Oh, can I really believe what the poets
say: that when a man sees the beloved object for the first time he believes he has seen her long before, that all love,
as all knowledge, is recollection, that love in the single individual also has its prophecies, its types, its myths, its Old
Testament? Everywhere, in every girl’s face, I see features of your beauty, yet I think I’d need all the girls in the world
to extract, as it were, your beauty from theirs, that I’d have to criss-cross the whole world to find the continent I lack
yet that which the deepest secret of my whole ‘I’ magnetically points to – and the next moment you are so near me, so
present, so richly supplementing my spirit that I am transfigured and feel how good it is to be here.

You blind god of love! You who see in secret, will you make it known to me? Am I to find here in this world what I
seek, am I to experience the conclusion of all my life’s eccentric premises, am I to conclude you in my embrace34 – or:

Do the orders say: march on?

Have you gone on before me, you, my yearning; are you beckoning to me, transfigured, from another world? Oh, I will
throw everything overboard to become light enough to follow you.


/Derived from/ [cite:@hannay-2015-paper-journ], no. 9. Appeared: 2025-06-16 (23:45)
-----
I too have combined the tragic with the comic: I make witticisms, people laugh – I cry.


/Derived from/ [cite:@hannay-2015-paper-journ], no. 9. Appeared: 2025-06-16 (23:24)
-----
When Adam lived in Paradise, it was: Pray; when he was cast out, it was: Work; when Christ came to the
world, it was: pray and work (ora et labora).



/Derived from/ [cite:@hannay-2015-paper-journ], no. 9. Appeared: 2025-06-13 (15:29)
-----
I simply can’t stand these pseudo-intellectuals. How often at a party haven’t I deliberately put myself beside
some elderly spinster who lives on family gossip and with the utmost gravity listened to everything she had
to offer.


/Derived from/ [cite:@hannay-2015-paper-journ], no. 9. Appeared: 2025-06-13 (15:09)
-----
It’s rather strange with superstition – you would expect a person, once he has seen his morbid dreams fail of
fulfilment, to give them up in the future; but on the contrary, the dreams become stronger, just as your desire to gamble
increases once you have lost in the lottery.

صالح محمد: ترجمتي للعربية: من الغريب أمر الخرافة - فأنت تظن أن المرء، متى شهد
أوهامه العليلة تتبدد دون تحقيق، سيهجرها فيما بعد؛ غير أن العكس يحدث، فتشتد
الأحلام وتقوى، كما تتأجج شهوة القمار في نفسك بعد أن تمنى بالخسران في اليانصيب.


/Derived from/ [cite:@hannay-2015-paper-journ], no. 8. Appeared: 2025-06-10 (10:30)
-----
People understand me so little that they fail even to understand my complaints that they do not understand me.


/Derived from/ [cite:@hannay-2015-paper-journ], no. 8. Appeared: 2025-06-09 (19:13)
-----
There are authors who, like those beggars who try to arouse
sympathy by exposing the defects and deformities of their
bodies, strive to attract attention by revealing the lacerated
states of their hearts.

صالح محمد: أترجمها للعربية كالتالي بتصرف بسيط: ثمة أناس، كأولئك الشحاذين الذين
يسعون لاستدرار العطف بكشف نقائص أبدانهم وعيوبها، يجتهدون في استمالة الأنظار بفضح
جراح قلوبهم النازفة.


/Derived from/ [cite:@hannay-2015-paper-journ], no. 8. Appeared: 2025-06-09 (18:55)
-----
Probably few fields of study bestow on man the serene and happy frame of mind that the
natural sciences give him. Out into nature he goes, everything is familiar, it is as though
he had talked with the plants and the animals beforehand. He sees not only the uses
man can put them to (for that is quite secondary) but their significance in the whole
universe. He stands like Adam of old – all the animals come to him and he gives them
names.


/Derived from/ [cite:@hannay-2015-paper-journ], no. 8. Appeared: 2025-06-06 (20:39)
-----
#+begin_quote
ولا تعني عبارة «حقيقة تكون حقيقية بالنسبة إليَّ» أن الحقيقة اعتباطية أو محكومة
بالهوى الشخصي، أو أن للفرد الاعتقادَ فيما يحلو له. لكنها تشير إلى حلٍّ داخلي، حيث
تعني «بالنسبة إليَّ» الحقيقة التي تغيِّر حياتي شخصيًّا؛ وهو تعبير يقول كيركجارد إنه
قرأه للمرة الأولى في كتابات الراهب مارتن لوثر. ونقيض الحقيقة «التي تكون حقيقية
بالنسبة إليَّ» هو الحقيقة الخامدة التي تخلو من الحياة؛ مجرَّد لغوٍ للتملُّص من متطلبات
الحياة عبر الكلمات الفارغة. فانْشُد أولًا مملكة الله: أي إن على المرء أولًا أن يقوم
بتحويل حياته الباطنية، وليس مراكمة زخارف المعرفة التكهنية. فحقيقة المسيحية ليست
في توفير مادة خام لتأملات الميتافيزيقا الألمانية، وليست أيضًا في قصرها على الطقوس
الدينية في صباح يوم الأحد، وتجاهلها بقيةَ أيام الأسبوع. إذا كانت المسيحية
«حقيقية» فهي حقيقية بالمعنى الذي يتحدَّث عنه الكتاب المقدَّس الذي يقول إن المسيح هو
«الطريق، والحقيقة، والحياة»، وهو ما يعني أن الحقيقة المسيحية هي طريقة للعيش في
الحقيقة. إذا لم تحمِل في قلبك حبَّ جارك، الذي تحدَّث عنه العهد الجديد؛ إذا لم تكن محبًّا
متسامحًا في حياتك؛ إذا لم تنقش هذا الحب في وجودك الشخصي، فأنت لا تعيش «في الحقيقة»
بمعناها «الوجودي». تفتح تدوينة كيركجارد في يومياته البابَ أمام نظرية جديدة
للحقيقة، تتجاوز التعريف العقلاني الكلاسيكي للحقيقة باعتبارها تمثيلًا عقليًّا لشيء
موجود في العالم الخارجي. أعاد كيركجارد وصفَ الحقيقة بناءً على المعايير الذاتية
للفرد، التي نجدها في كتابات القديس أغسطينوس، وتقاليد الفرنسيسكان.
#+end_quote


/Derived from/ [cite:@caputo-2008-how-kierk], no. 20. Appeared: 2025-06-06 (06:26)
-----
ما أحتاج إليه فعلًا هو أن أحسِم ما أنا عازم على فعله، لا ما يجب أن أعرفه، لولا أن
المعرفة يجب أن تسبق كل الأفعال. إنها مسألة تتعلق بفهمٍ قَدَري، أن أرى ما يريدني
الله أن أفعله؛ الأمر يتعلق بإيجاد حقيقة تكون حقيقية بالنسبة إليَّ، إيجاد الفكرة
التي أكون على استعدادٍ للعيش والموت من أجلها. وما نفعُ أن أكتشف ما يُسمَّى بالحقيقة
الموضوعية، أو إذا سلكت طريقي عبر النُّظم الفكرية للفلاسفة وكنت قادرًا على محاسبتهم
جميعًا، مشيرًا إلى تناقضاتهم في كل موضع؟ وما نفعُ أن أكون قادرًا على تطوير نظرية
للدولة، مجمعًا كلَّ الأجزاء من مواضع مختلفة لأُكوِّن نظرية واحدة كلية، وأنشئ عالَمًا لم
أقطنه بنفسي بل شيدته فقط كي يراه الآخرون؟ وما فائدةُ أن أكون قادرًا على إبراز معنى
المسيحية وتوضيح حقائق عديدة منفصلة بخصوصها، إذا لم تكن تحمل معنًى أعمق بالنسبة
إليَّ وإلى حياتي؟ بالتأكيد، لا أنكر أنني ما زلت أقرُّ بأهمية المعرفة، وأن المرء يمكن
أن يتأثر بها، لكن يجب حينها أن تحيا هذه المعرفة داخلي، وهذا ما أراه النقطة
الرئيسية في الموضوع … ولكن كي أجد هذه الفكرة أو بمعنًى أدق كي أجد نفسي، فلا فائدة
من انغماسي أكثرَ في هذا العالم … كان هذا ما ينقصني كي أحيا حياة إنسانية كاملة،
بدلًا من أن أعيش حياة معرفية فقط، كي أتجنَّب بناء تطوري العقلي على — شيء يسميه
الناس بالموضوعي — شيء لا يخصُّني بكل الأحوال، وأن أبنيَه، بدلًا من ذلك، على شيء يتصل
بجذور وجودي كي أنموَ من خلاله وأصل إلى الله، وأتشبَّث به حتى وإن تهاوى العالم كلُّه
حولي. هذا، كما ترى، ما أحتاج إليه، وما أسعى إليه … إن هذه الحركة الداخلية
للإنسان، هذا الجانب الإلهي فيه، هو ما يشكِّل فارقًا، لا أكوام المعلومات … كم سعيتُ
هباءً للبحث عن ملاذٍ ليس فقط في أعماق المعرفة بل أيضًا في بحر المُتَع الذي لا قاع له
… وماذا وجدت؟ لم أجد نفسي، فهذا ما كنت أسعى إلى العثور عليه بهذه الطريقة … على
المرء أن يتعلم أولًا أن يعرِف نفسه قبل أن يعرِف أيَّ شيء آخر … وفيما يتعلق بعلاقتي
بالآخرين، ليس لديَّ الكثير لأكسبه أو أخسره … فلم يُحدِث رفاقي أثرًا واضحًا فيَّ باستثناء
قلة منهم … لذا أقف مجددًا عند نقطة، حيث يجب أن أتخذ طريقًا آخر. سأحاول الآن أن
أنظر إلى نفسي بهدوءٍ، وأن أبدأ في التحرك إلى داخلي. فبهذه الطريقة فقط، يمكن أن
أطلِق على نفسي «أنا» بمعنًى أعمق … لقد عزمتُ أمري؛ وها أنا ذا أعبر نهرَ روبيكون. لا
شك في أن هذا الطريق سيفضي بي إلى معركةٍ، لكنني لن أستسلم.


/Derived from/ [cite:@caputo-2008-how-kierk], no. 17. Appeared: 2025-06-06 (06:03)
-----
``‘To produce’, he remarked on a later occasion, ‘was my life.’''


/Derived from/ [cite:@gardiner-2002-kierk], no. 10. Appeared: 2025-06-06 (05:53)
-----
#+BEGIN_QUOTE
‘what good would it do me if truth stood before me, cold and naked, not caring
whether I recognized her or not?
#+END_QUOTE


/Derived from/ [cite:@gardiner-2002-kierk], no. 10. Appeared: 2025-06-06 (05:43)
-----
#+begin_verse
فلا عبرت بي ساعةٌ لا تُعِزني
ولا صَحبتني مُهجة تَقبل الظُّلما
#+end_verse
أبو الطيب


/Derived from/ [cite:@al-akbari-1997-al-tibyan], no. 109. Appeared: 2025-03-07 (16:13)
-----
ومن الأسباب المتمنَّاة في الحُب أن يهب الله عزَّ وجل للإنسان صديقًا مُخلصًا، لطيفَ القول، بسيطَ
الطَّول، حسنَ المأخذ، دقيقَ المنفذ، متمكنَ البيان، مُرهف اللسان، جليل الحلم، واسع العلم، قليل
المخالفة، عظيم المساعفة، شديد الاحتمال، صابرًا على الإدلال، جم الموافقة، جميل المخالفة،
مستوي المطابقة، محمود الخلائق، مكفوف البوائق، محتوم المساعدة، كارهًا للمباعدة، نبيل المدخل،
مصروف الغوائل، غامض المعاني، عارفًا بالأماني، طيب الأخلاق، سريَّ الأعراق، مكتوم السر، كثير
البر، صحيح الأمانة، مأمون الخيانة، كريم النفس، نافذ الحس، صحيح الحدْس، مضمون العون، كامل
الصون، مشهور الوفاء، ظاهر الغَناء، ثابت القريحة، مبذول النصيحة، مستيقن الوداد، سهل
الانقياد، حسن الاعتقاد، صادق اللهجة، خفيف المهجة، عفيف الطباع، رحب الذراع، واسع الصدر،
متخلقًا بالصبر، يألف الإمحاض، ولا يعرف الإعراض، يستريح إليه ببلابله، ويشاركه في خلوة فكره،
ويفاوضه في مكتوماته.


/Derived from/ [cite:@ibn-1993-tawq-hamam], no. 48. Appeared: 2024-11-18 (02:37)
-----
واعلم أن العين تنوب عن الرُّسل، ويدرك بها المراد. والحواس الأربع أبواب إلى القلب ومنافذ نحو
النفس، والعين أبلغها وأصحها دلالة وأوعاها عملًا، وهي رائد النفس الصادق ودليلها الهادي
ومرآتها المجلوة التي بها تقف على الحقائق وتميّز الصفات وتفهم المحسوسات.


/Derived from/ [cite:@ibn-1993-tawq-hamam], no. 32. Appeared: 2024-11-17 (02:33)
-----
Anyone who knows how to breathe the air of my writings knows that it is an air of the
heights, a bracing air. You must be made for it, or else you are in no little danger of
catching cold in it. The ice is near, the solitude is immense—but how peacefully
everything lies in the light! how freely you breathe! how much you feel to be beneath
you!—Philosophy, as I have understood and lived it so far, is choosing to live in ice and
high mountains—seeking out everything alien and questionable in existence, everything that
has hitherto been excluded by morality.

From the long experience which such a wandering in the forbidden gave me, I learnt to view
the reasons people have moralized and idealized so far very differently from what may be
wished: the hidden history of philosophers, the psychology of their great names came to
light for me.—How much truth can a spirit stand, how much truth does it dare?—for me that
became more and more the real measure of value. Error (belief in the ideal) is not
blindness, error is cowardice... Every achievement, every step forwards in knowledge is
the consequence of courage, of toughness towards oneself, of sincerity* towards oneself...
I do not refute ideals, I just put gloves on to protect myself against them... Nitimur in
vetitum: under this sign my philosophy will triumph one day, for the only thing that has
been altogether forbidden so far is the truth.


/Derived from/ [cite:@nietzsche-2009-ecce-homo], no. 5. Appeared: 2024-11-04 (04:34)
-----
"فمنهم غزير الدمع هامل الشؤون، تُجيبه عينه وتحضره عبرته إذا شاء، ومنهم جَمود العين عديم
الدّمع، وأنا منهم. [...] فإني لأجد قلبي يتفطّر ويتقطّع وأحِس غُضة أمرَّ من العلقم، وتكاد تشوقني
النفس أحيانًا ولا تجيب عيني البتة إلا بالشيء اليسير من الدمع".


/Derived from/ [cite:@ibn-1993-tawq-hamam], no. 17. Appeared: 2024-11-04 (02:15)
-----
لا يعجبنَّك إكرامُ من يكرمك لمنزلة أو سلطان، فإن السلطة أوشك أمور الدنيا زوالًا، ولا يعجبنك
إكرامهم إيَّاك للنسب، فإن الأنساب أقل مناقب الخير غناءً عن أهلها في الدين والدنيا، ولكن إذا
أكرمت على دين أو مروءة فذلك فليعجبك، فإن المروءة لا تزايلك في الدنيا، والدين لا يزايلك في
الآخرة.


/Derived from/ [cite:@al-muqaffaa-2019-al-durrah-yateem], no. 34. Appeared: 2024-08-08 (09:36)
-----
اعلم أن بعض العطية لؤم، وبعض البيان عيٌّ، وبعض العلم جهل، فإن استطعت ألا يكون عطاؤك جورًا،
ولا بيانك هذرًا، ولا علمك جهلًا؛ فافعل.


/Derived from/ [cite:@al-muqaffaa-2019-al-durrah-yateem], no. 33. Appeared: 2024-08-08 (09:34)
-----
إذا تراكمت الأعمال عليك، فلا تلتمس الروح في مدافعتها والروعان منها، فإنه لا راحة لك إلا في
إصدارها، وإن الصبر عليها هو يخفها، وإن الضجر منها هو يُراكمها عليك، فتعهَّد من ذلك في نفسك
خصلة قد رأيتُها تعتري بعض أصحاب الأعمال أن الرجل يكون في أمر من أمره، فيرد عليه شغل آخر،
ويأتيه شاغلٌ من الناس يكره تأخيره، فيكدِّر ذلك بنفسه تكديرًا يفسد ما كان فيه وما ورد عليه حتى
لا يحكم واحدًا منها، فإن ورد عليك مثل ذلك، فليكن معك رأيك الذي تختار به الأمور، ثم اختر
أَوْلى الأمرين بشغلك فاشتغل به؛ حتى تفرغ منه، ولا تُعظمن عليك فوت ما فات، وتأخير ما تأخر، إذا
أعملت الرأي معمله، وجعلت شغلك في حقه. اجعل لنفسك في كل شيء غاية ترجو القوة والتمام عليها،
واعلم أنك إن جاوزت الغاية في العبادة صرت إلى التقصير، وإن جاوزتها في حمل العلم صرت من
الجهال، وإن جاوزتها في تكلُّف رضى الناس والخفة معهم في حاجاتهم، كنت المصنع المحسود.


/Derived from/ [cite:@al-muqaffaa-2019-al-durrah-yateem], no. 33. Appeared: 2024-08-08 (09:32)
-----
- [2025-12-03 Wed 22:08] \\
  Salih Muhammed: I translate it as:

  Discipline yourself with patience toward a bad neighbor, a troublesome companion, and an unpleasant associate; for such trials are hardly avoidable. Patience is of two kinds: a man’s patience in enduring what he dislikes, and his patience in restraining himself from what he desires. Patience in the face of what is disliked is the more common, for its bearer is often compelled to it. Know that the base are hardier in body, while the noble are more steadfast in soul. Praiseworthy patience is not that a man be thick-skinned, brazen, or merely strong of foot against toil or strong of hand in labor—for such traits belong to donkeys. Rather, true patience is that the soul be resolute; that one bear affairs with composure; that he remain collected in distress; that he be firmly anchored in judgment and self-possession; inclined toward prudence; abandoning caprice; lightly regarding the hardship whose outcome he hopes for; persevering in resisting desires and passions; and, with the strength of his resolve, seeing his resolve through.
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.50 |   0 |     0.00 | 2024-08-08T06:22:55Z |
:END:

ذلِّل نفسك بالصبر على جار السوء، وعشير السوء، وجليس السوء؛ فإن ذلك ما لا يكاد يُخطِبك، فإن
الصبر صبران؛ صبر الرجل على ما يكره، وصبره عمَّا يحب، فالصبر على المكروه أكثرهما وأشبههما أن
يكون صاحبه مضطرًّا، واعلم أن اللئام أصبر أجسادًا، والكرام أصبر نفوسًا، وليس الصبر الممدوح بأن
يكون جلد الرجل وقاحًا أو رجله قوية على المشي أو يده قوية على العمل، فإنما هذا من صفات
الحمير، ولكن أن يكون للنفس غلوبًا، وللأمور مُحتمِلًا، وفي الضر مُجمِلًا، ولنفسه عند الرأي والحفاظ
مرتبطًا، وللحزم مؤثرًا، وللهوى تاركًا، وللمشقة التي يرجو عاقبتها مستخفًّا، وعلى مجاهدة الأهواء
والشهوات مواظبًا، ولبصره بعزمه منفدًا.


/Derived from/ [cite:@al-muqaffaa-2019-al-durrah-yateem], no. 30. Appeared: 2024-08-08 (09:22)
-----
الهرب من الحب هو الاقتراب من ثمار فينوس دون دفع غرامة. من يفكرون ببرود تكون لذتهم أكبرّ
وأنقى مما لدى الأرواح التعسة الذين يترجرج شوفهم. لحظةً الامتلاك. بين أمواج عدم اليقين. فلا
تعرف عيونهم وأيديهم وأجسادُهم بأي شيءٍ تستمتع أولا. يعانقون الجسدّ المشتهى بقوةٍ تحمله على
الصراخ وتترك أسنائهم أثرها فوق الشفاه التي يحبون. ونظراً لعدم صفاء لذَتَهِم فإنها تكون فظةً
تدفعهم لجَرح الجسد الذي أيقظ فيهم بذورّ ذلك السعار، أَيَاً كان ذلك الجسد. لا أحد يطفئ الشعلةً
بالحريق.  الطبيعةٌ تعارض ذلك. إنها الحالة الوحيدة التي كلما امتلَكُنَا فيها أكثر أَلهَبَ الامتلاك
القلبّ أكثر برغبةٍ مخيفة. الشراب والطعام الماء وصورة الخبز. لكن الجسد لا يستطيع امتصاصّ شيء
من جمال وجه أو من ألق بشرة. لا شيء: إنه يأكل أطيافاً وآمالا تبلغ من الخفة حداً يجعل الهواء
يخطفها. شأن رجلٍ يلتهمه العطش في منتصف الحلم؛ ولا يتمكن من الوصول إلى أي ماء في قلبٍ سعيره
فيلجاً إلى صورٍ سَواقٍ. لكنه عبثاً يستبسل، فهو يموت عَطَّشاً وسط السيل الذي يشرب منه. هكذا العشاق
في الحب. إنهم الألعوبة التي تلهو بها أطيافٌ فينوس. في النهاية تستحثُ أجسادهم لحظةً وقوع الفرح
الوشيك. إنها اللحظة التي تَبذر فيها فينوسش حقلَ المرأة.  يغرزون أجسادهم بشراهة. ويجمعون
لعابهم. وفوق الشفاه التي يهرسون أسنائّهم عليهاء لا يمتصُون بأفواههم شيئاً سوى الهواء.  ومهما
حاولوا لا يستطيعون انتزاع أية قطعةٍ من ذلك الجسدء لايستطيعون دس جسدهم بكامله داخل جسد. لا
يستطيعون الانتقال بأكملهم إلى الجسد الآخر. نّخال أحياناً بأن هذا هو ما يريدونه لشدةٍ ما
يوثقون بجشع، مِن حولهم، العرّى التي تربطهم إليه. وحين لا تعود الأعصابُ قادرةٌ على احتواء
الرغبة التي توترهم، حين تظهر تلك الرغبة فجأة، تحدث استراحة قصيرة، تهدأ الحمية العنيفة لحظة
قصيرة، ثم يعود السعار نفسه، الهياج نفسه. ومن جديد يبحثون عما يتوقون إليه. من جديد يتساؤلون
عما يشتهونه.



/Derived from/ [cite:@quignard-2019-sex-terror], no. 69. Appeared: 2024-07-19 (16:41)
-----
 إذا كنت مخيرًا في هذا الشيء فلماذا فعلته؟ أما إذا كان غيرك هو المُخيَّر فيه فمن
 تُراك تلوم؛ الذرات (المصادفة) أم الآلهة؟ كلاهما حماقة؛ فلا محل للوم، بل قَوِّم هذا
 الفاعل إن استطعتَ، فإذا لم تستطع فقَوِّم الشيء على الأقل. فإذا لم تستطع فأي هدفٍ
 يُحقِّقه اللوم؛ إذ كل فعلٍ ينبغي أن يتم لهدف.



/Derived from/ [cite:@aurelius-2012-thoughts], no. 114. Appeared: 2024-06-04 (19:26)
-----
لا تكن متثاقلًا في فعلك، ولا مُشوَّشًا في محادثتك، ولا غامضًا في تفكيرك. ولا تترك عقلك نهبًا للانقباض ولا للتيه، واجعل في وقتك ساعةً للفراغ والترويح.

– «إنهم يقتلونني، يمزقونني، يلعنونني.»

– وكيف يمكن لكل ذلك أن يحول بين عقلك وبين الصفاء والحكمة والرصانة والعدل؟ هب
واحدًا أتى إلى نبعٍ من الماء النمير وأخذ يلعنه، فهل سيمنع النبعَ من أن يظل يتدفق
بالماء الزُّلال؟ وهَبْه ألقى فيه بشيءٍ من الطين والرَّوْث … فلن يلبث النبع أن يُفتِّته
ويُزيحه ويعود إلى نقائه. كيف إذن تُؤمِّن لنفسك نبعًا دائمًا لا مجرد صِهريج؟ بأن تُوطِّن
نفسك طول الوقت على الحرية، وتظل قانعًا، بسيطًا، متواضعًا.



/Derived from/ [cite:@aurelius-2012-thoughts], no. 121. Appeared: 2024-06-04 (18:57)
-----
بِحسبِك ثلاث؛ أن يكون حكمك الراهن قائمًا على الفَهم، وفعلُك على الخير الاجتماعي، وميلُك
على الرضا بكل ما يحدُث.



/Derived from/ [cite:@aurelius-2012-thoughts], no. 125. Appeared: 2024-06-04 (18:57)
-----
لا شيء يحدُث للإنسان خارج نطاق الخبرةِ الطبيعية للإنسان. كذلك الأمر في الثور فلا
شيء في خبراته غريبٌ على طبيعة الثور، والكرمة لا شيء لديها غريبٌ على طبيعة الكرم،
والحجر لا شيء لديه خارج خصائص الحجر. فإذا كان كل شيءٍ يخبر ما هو معتادٌ وطبيعي
بالنسبة له ففيم تشكو؟ ما دامت طبيعة العالَم لم تجلب لك شيئًا فوق احتمالك.



/Derived from/ [cite:@aurelius-2012-thoughts], no. 119. Appeared: 2024-06-04 (18:50)
-----
خذني وارمِ بي في أيِّ مكانٍ شئت؛ فأينما كنت فسوف أحفظ الجانب الإلهي مني سعيدًا؛ أي
قانعًا، ما دام وِجداني وفِعلي يتبعان فطرته الخاصة.



/Derived from/ [cite:@aurelius-2012-thoughts], no. 119. Appeared: 2024-06-04 (18:48)
-----
لقد طوَّفتَ ما طوفتَ ومضيتَ في دروبٍ كثيرة ولم تعثُر على السعادة في أيِّ دربٍ منها؛ لم تعثر
عليها في المنطق، ولا في الثروة، ولا في المجد، ولا في المتعة، ولا في أي شيء. أين
إذن يمكن أن تجدها؟ في أن تفعل ما تقتضيه طبيعةُ الإنسان. وكيف تفعل ذلك؟ بأن تكون
لديك مبادئُ تحكم رغباتك وأفعالك. ما هي هذه المبادئ؟ تلك المتصلة بالخير والشر؛
اليقين بأنه لا شيء يُعَد خيرًا للإنسان ما لم يجعله عادلًا، ومعتدلًا، وشهمًا، وحرًّا، ولا
شيء يُعَد شرَّا ما لم يجعله عكس ذلك.



/Derived from/ [cite:@aurelius-2012-thoughts], no. 112. Appeared: 2024-06-04 (18:45)
-----
كيف تفهم خيرك الخاص؟ عاشق الشهرة يجعل خيره في استجابات غيره. عاشق اللذة يجعل
خيره في خبرته السلبية. أما الحكيم فيرى خيره هو أفعاله ذاتها.



/Derived from/ [cite:@aurelius-2012-thoughts], no. 93. Appeared: 2024-06-04 (18:41)
-----
أفِق من نومك، عُد لرشك، لتدرك أن كل الذي عكر صفوك كان أضغاث أحلام. وقد استعدت وعيك
مرة ثانية انظر إلى هذه الأشياء مثلما كنت تنظر إلى تلك الأحلام.



/Derived from/ [cite:@aurelius-2012-thoughts], no. 88. Appeared: 2024-06-04 (18:39)
-----
من العار أن تخذلك الروح في هذه الحياة قبل أن يخذلك جسمك.



/Derived from/ [cite:@aurelius-2012-thoughts], no. 88. Appeared: 2024-06-04 (18:38)
-----
إنه الليل: هي ذي الينابيع الفياضة ترفع صوتها في حديث مسموع. روحي أيضًا هي ينبوعٌ
فياض. إنه الليل: هي ذي أغاني المحبين تستقيظ الآن. وروحي أيضًا هي أغنية محبّ. نورٌ
أنا، ليلٌ أنا، تلك هي وحدتي؛ أن أكون متمنطقًا بحزامٍ من نور.


/Derived from/ [cite:@nietzsche-2006-thus-spoke], no. 210. Appeared: 2024-04-25 (19:54)
-----
ينبغي أن نضع في حُسباننا، ليس فقط أن الحياةَ تنقضي يومًا بعد يوم وأن رصيدَنا الباقي
يتناقص، بل أيضًا أننا إذا امتدَّ بنا الأجلُ فلا ضامن لنا أن عقولنا ستظل محتفظةً
بالقُدرة على فهم العالم وتأمُّله، تلك القدرة التي تُشكِّل خبرتنا بالأمور الإلهية
والإنسانية. فإذا أدرَكَنا العَتَهُ فلن يتوقَّفَ فينا التنفسُ ولا الغذاءُ ولا الخيالُ ولا
الرغبة، بل قبل أن تذهب هذه سيذهب استخدامُ المرء لنفسه استخدامًا صحيحًا، تقديرُه
الدقيق لما يتوجب فعله، قدرتُه على تحليل الانطباعات، وعلى معرفة هل عليه أن يرحل
مختارًا عن الحياة٢ أو لا، هذه وكل الأمور الأخرى التي تتطلب حسابًا حصيفًا. فلنُعجِّل
إذن، ليس فقط لأن الموت يدنو حثيثًا، بل أيضًا لأن قدرتنا الفكرية على معرفةِ الطبيعةِ
الحقَّة للأشياء وتسيير أفعالنا وفقًا لهذه المعرفة سيعروها الزوال قبلنا.


/Derived from/ [cite:@aurelius-2012-thoughts], no. 45. Appeared: 2024-04-25 (19:31)
-----
 لا تُضيِّع ما تبقَّى من عمرك في الانشغال بالغير، ما لم يكن ذلك تصلًا بوجهٍ ما من أوجه
 الخير العام. لماذا تُجرد نفسك من الوقت من أجل مهمةٍ أخرى؟ أعني أن التفكير حول
 فلان، ماذا عساه يفعل ولماذا يقول أو يُضمر أو يُخطِّط وكل هذا الخط من التفكير، يَضِلُّ
 بك عن التأمُّل الدقيق في عقلك المُوجِّه نفسه.

لا … عليك أن تجتنب في مسار فكرك كل ما ليس له هدفٌ أو فائدة، وبخاصةٍ كلَّ ما هو فضوليٌّ
خبيث. رُض نفسك على ألا تُجيل بخاطرك إلا تلك الأفكارَ التي بوُسعِكَ إن سُئلتَ فجأةً: «فيم
تفكر الآن؟» أن تقول لتوِّك ما هي بصراحةٍ فتكون إجابتك دليلًا على أن أفكارك مستقيمةٌ
وحسنةٌ وتليق بكائنٍ اجتماعيٍّ لا يُلقي بالًا لخيالات اللذة أو المُتع الحسية على
الإطلاق، ومُبرَّأٍ من أي غَيرةٍ أو حسدٍ أو شكٍّ أو أي شيءٍ يُخجِل المرء من أن يعترف أنه خَطَرَ
له.

فإنسانٌ مثل هذا، إذا لم يعُد يتنازل عن مكانه بين الصفوة الأخيار، هو أَشبَه بكاهنٍ
وخادمٍ للآلهة، إنه يُلبِّي نداء الأُلوهة القابعة داخله، والتي تجعل المرء غير مُلطَّخ
بالملذَّات وغير مُنغَّص بالآلام، لا تناله الإهانة ولا يعرف الخبث … مقاتلًا في أنبل حرب
… لا يَجرِفه أيُّ انفعال، مُتشرِّبًا بالعدل حتى النُّخاع، يتقبل بمِلءِ قلبِه كُلَّ ما يُصِيبه وكلَّ
ما هو مقسومٌ له، وقلما يتطلع إلى الآخرِين ما عساهم يقولون أو يفعلون أو يُفكِّرون؛
فبِحَسْبه ما يُكِبُّ عليه من عمل لكي يُتِمَّه، وبِحَسْبه نصيبُه المقدورُ من «الكل» لكي ينصرف
إليه بهمةٍ لا تنقطع. فأمَّا عمله فيتقنه أيَّما إتقان، وأما نصيبه المقدور فهو قانع به؛
فنصيب كل امرئٍ هو رفيق رحلته وهو حادِيه في آنٍ معًا. [fn:1]

وهو يذكر أيضًا أن كل كائنٍ عاقلٍ هو قريبُه، وأن رعاية جميع البشر هي أمرٌ تقتضيه طبيعة
الإنسان. وعلى المرء ألَّا يتخذ آراء الجميع بل آراء الذين يعيشون وفق الطبيعة فحَسْب.
أمَّا أولئك الذين لا يعيشون كذلك فإنه لَيذكر دائما أي صِنفٍ من البشر هم في بيوتهم
وخارجها، في ليلهم ونهارهم، يذكر ماذا يكونون ومع من يعيشون حياتهم الآثمة؛ وبالتالي
فهو يزدري أي إطراءٍ يأتي من مثل هؤلاء، إنهم أناسٌ غيرُ راضِين حتى عن أنفسهم.



/Derived from/ [cite:@aurelius-2012-thoughts], no. 48. Appeared: 2024-04-25 (19:27)
-----
ما كان يومًا جهل المرء بما يدور في رءوس الآخرين سببًا للتعاسة والشقاء. إنما الشقي
من لا ينتبه إلى خَطَرات عقله هو، ولا يهتدي؛ من ثم، بعديه وإرشاده.


/Derived from/ [cite:@aurelius-2012-thoughts], no. 40. Appeared: 2024-04-17 (11:25)
-----
كم ذا تُسوفِف هذا وتُرجئه، وكم تمنحك الآلهة فرصة فتضيعها. ألم يأن لك أن تفهم هذا
العالم الذي أنت جزءٌ منه وتفهم مُدبر هذا العالم الذي أنت فيقٌ منه؟ ألا تدرك أن هناك
حدًا لعمرك، فإذا لم تستغله لتبديد غيومك فسوف يذهب العمر وسوف تذهب ولن تعود الفرصة
مرة أخرى؟


/Derived from/ [cite:@aurelius-2012-thoughts], no. 39. Appeared: 2024-04-09 (23:30)
-----
إعراب القلوب على أربعة أنواع: رفع وفتح وخفض ووقف، فرفع القلب في ذكر الله، وفتح
القلب في الرضا عن الله، وخفض القلب في الاشتغال بغير الله، ووقف القلب في الغفلة
عن الله، ألا ترى أن العبد إذا ذكر الله بالتعظيم خالصا ارتفع كل حجاب كان بينه
وبين الله من قبل ذلك، وإذا انقاد القلب لمورد قضاء الله بشرط الرضا عنه كيف ينفتح
القلب بالسرور والروح والراحة، وإذا اشتغل قلبه بشئ من أسباب الدنيا كيف تجده إذا
ذكر الله بعد ذلك وآياته منخفضا [مظلما] كبيت خراب خاويا، وليس فيه العمارة ولا
مؤنس، وإذا غفل عن ذكر الله كيف تراه بعد ذلك موقوفا محجوبا قد قسي وأظلم منذ فارق
نور التعظيم.


/Derived from/ [cite:@al-ghazali-1993-majmuat-rasail], no. 231. Appeared: 2024-03-06 (04:43)
-----
A worm squirms when it is trodden on. Clever move. By doing so it reduces the probability of being trodden on again. In the language of morality: humility.


/Derived from/ [cite:@nietzsche-2010-twilig-idols], no. 16. Appeared: 2024-02-24 (03:29)
-----
What? you are searching? you would like to multiply yourself by ten, by a
hundred? you are looking for followers? Look for zeros[fn:1]


/Derived from/ [cite:@nietzsche-2010-twilig-idols], no. 12. Appeared: 2024-02-24 (03:19)
-----
When your heart flows broad and full like a river, a blessing and a danger
to adjacent dwellers: there is the origin of your virtue. \\
When you are sublimely above praise and blame, and your will wants
to command all things, as the will of a lover: there is the origin of your
virtue. \\
When you despise pleasantness and the soft bed, and cannot bed down
far enough away from the softies: there is the origin of your virtue. \\
When you are the ones who will with a single will, and this turning
point of all need points to your necessity: there is the origin of your virtue.



/Derived from/ [cite:@nietzsche-2006-thus-spoke], no. 153. Appeared: 2024-02-24 (02:43)
-----
Die at the right time: thus Zarathustra teaches it.  To be sure, how could the
person who never lives at the right time ever die at the right time? Would that
he were never born! – Thus I advise the superfluous.



/Derived from/ [cite:@nietzsche-2006-thus-spoke], no. 143. Appeared: 2024-02-19 (21:42)
-----
The scientist does not study nature because it is useful; he studies it because
he delights in it, and he delights in it because it is beautiful. If nature were
not beautiful, it would not be worth knowing, and if nature were not worth
knowing, life would not be worth living. Of course I do not here speak of that
beauty that strikes the senses, the beauty of qualities and appearances; not
that I undervalue such beauty, far from it, but it has nothing to do with
science; I mean that profounder beauty which comes from the harmonious order of
the parts, and which a pure intelligence can grasp.


/Derived from/ [cite:@flake-1998-comput-beaut-natur], no. 11. Appeared: 2024-02-09 (12:27)
-----
We ought to observe also that even the things which follow after the things
which are produced according to nature contain something pleasing and
attractive. For instance, when bread is baked some parts are split at the
surface, and these parts which thus open, and have a certain fashion contrary to
the purpose of the baker's art, are beautiful in a manner, and in a peculiar way
excite a desire for eating. And again, figs, when they are quite ripe, gape
open; and in the ripe olives the very circumstance of their being near to
rottenness adds a peculiar beauty to the fruit. And the ears of corn bending
down, and the lion's eyebrows, and the foam which flows from the mouth of wild
boars, and many other things,—though they are far from being beautiful if a man
should examine them severally,—still, because they are consequent upon the
things which are formed by nature, help to adorn them, and they please the mind;
so that if a man should have a feeling and deeper insight with respect to the
things which are produced in the universe, there is hardly one of those which
follow by way of consequence which will not seem to him to be in a manner
disposed so as to give pleasure. And so he will see even the real gaping jaws of
wild beasts with no less pleasure than those which painters and sculptors show
by imitation; and in an old woman and an old man he will be able to see a
certain maturity and comeliness; and the attractive loveliness of young persons
he will be able to look on with chaste eyes; and many such things will present
themselves, not pleasing to every man, but to him only who has become truly
familiar with Nature and her works.


/Derived from/ [cite:@aurelius-2012-thoughts], no. 46. Appeared: 2024-02-05 (22:40)
-----
Courageous, unconcerned, sarcastic, violent – thus wisdom wants us: she is a
woman and always loves only a warrior. \\
You say to me: “Life is hard to bear.” But why would you have your
pride in the morning and your resignation in the evening?



/Derived from/ [cite:@nietzsche-2006-thus-spoke], no. 105. Appeared: 2024-02-04 (23:11)
-----
Mankind is a rope fastened between animal and overman – a rope over
an abyss. \\
A dangerous crossing, a dangerous on-the-way, a dangerous looking
back, a dangerous shuddering and standing still.

I love those who do not know how to live unless by going under, for
they are the ones who cross over. \\
I love the great despisers, because they are the great venerators and
arrows of longing for the other shore. \\

I love those who do not first seek behind the stars for a reason to go
under and be a sacrifice, who instead sacrifice themselves for the earth, so
that the earth may one day become the overman’s. \\
I love the one who lives in order to know, and who wants to know so
that one day the overman may live. And so he wants his going under. \\
I love the one who works and invents in order to build a house for the
overman and to prepare earth, animals and plants for him: for thus he
wants his going under. \\
I love the one who loves his virtue: for virtue is the will to going under
and an arrow of longing. \\
I love the one who does not hold back a single drop of spirit for himself,
but wants instead to be entirely the spirit of his virtue: thus he strides as
spirit over the bridge. \\
I love the one who makes of his virtue his desire and his doom: thus
for the sake of his virtue he wants to live on and to live no more. \\
I love the one who does not want to have too many virtues. One virtue
is more virtue than two, because it is more of a hook on which his doom
may hang.[fn:: This view is very similar to the one mentioned in
[cite:@DawnofDay no. 325]: The means of becoming the prophet and wonder-worker
of one's age are the same to-day as in former times: one must live apart, with
little knowledge, some ideas, and a great deal of presumption—we then finish by
believing that mankind cannot do without us, because it is clear that we can do
without it.  When we are inspired with this belief we find faith. Finally, a
piece of advice to him who needs it (it was given to Wesley by Boehler, his
spiritual teacher): “Preach faith until you have it; then you will preach it
because you have it!] \\
I love the one whose soul squanders itself, who wants no thanks and
gives none back: for he always gives and does not want to preserve
himself. \\
I love the one who is ashamed when the dice fall to his fortune and who
then asks: am I a cheater? – For he wants to perish. \\
I love the one who casts golden words before his deeds and always does
even more than he promises: for he wants his going under. \\
I love the one who justifies people of the future and redeems those of
the past: for he wants to perish of those in the present. \\
I love the one who chastises his god, because he loves his god: for he
must perish of the wrath of his god. \\
I love the one whose soul is deep even when wounded, and who can
perish of a small experience: thus he goes gladly over the bridge. \\
I love the one whose soul is overfull, so that he forgets himself, and all
things are in him: thus all things become his going under. \\
I love the one who is free of spirit and heart: thus his head is only the
entrails of his heart, but his heart drives him to his going under. \\


/Derived from/ [cite:@nietzsche-2006-thus-spoke], no. 47. Appeared: 2024-01-16 (01:11)
-----
“They do not understand me. I am not the mouth for these ears.  Too long
apparently I lived in the mountains, too much I listened to brooks and trees:
now I speak to them as to goatherds.

My soul is calm and bright as the morning mountains. But they believe I am cold,
that I jeer, that I deal in terrible jests.


/Derived from/ [cite:@nietzsche-2006-thus-spoke], no. 53. Appeared: 2024-01-16 (01:08)
-----
يسلب دين الاستحمار مسؤولياتي تجاه مجتمعي بطريقتين: الأولى يأخذ مني إمكانياتي
ومواهبي التي أملكها ويحرمني منها، فيلزمني أن استعيدها من أجل كوني "إنسانًا" ومن
أجل "درايتي الإنسانية". كما ينبغي علي أن أرفض الظلم من أجل الحاجة إلى العدالة.
أما دين الاستحمار فيدعوني إلى التمكين من الظلم والفقر والسكون والصبر، ويكلني إلى
الله ويزيح عني كل مسؤولية.

والثانية: حين أرى نفسي مقصرًا ، خائنًا، مسيئًا إلى المجتمع ومصيره، أقع تحت ضغط
مسؤولية ضميري فتجرني "الدراية الاجتماعية" إلى أن أرجع حقوق الناس إليهم،
واستسمحهم فيما فرط في جانبهم [والحق هنا قد يكون أي شيء، كالدفاع عن الناس مثلًا].
لكن دين الاستحمار يموه علي ويقول لي: صحيح أنك خنت وبعت مصير الناس الآخرين، إلا
أنك لا تستطيع أن ترجع حقوقهم عليهم وليس هذا صوابًا، هناك ما هو أسهل. ما هو؟ أن
تقرأ هذه الكلمات ست مرات وأنت متجه نحو القبلة، ولن يبقى عليك شيء، وستغفر ذنوبك
كلها لأنك حينها ستنال الشفاعة.

ثم تتساءل: إذًا لأي شيء أتحمل ثقل المسؤولية الاجتماعية؟ لماذا؟ إذا كانت مسؤولياتي
نحو الناس وحياتهم الاجتماعية تلزمني أن أموت من أجلهم، وأضحي بنفسي في سبيلهم،
فهناك طريقة أسهل! وهي كتاب الأدعية. فإنه يفتح لي أبواب الجنان من غير تعب ولا
نصب، ولا مشقة، ولا تشويش، وبدون (إحساس) أو فكر، وبدون أي مسؤولية. كفى أن تدخل
السرور في قلب أحدهم أو تقضي حاجة أحد، فإنه سيمحي كل ذنوبك ويبدل سيئاتك حسنات،
ويقضي عنك كل المسؤوليات الاجتماعية. هذا هو دين الاستحمار.


/Derived from/ [cite:@shariati-2007-nanah-esteh], no. 111. Appeared: 2024-01-08 (20:01)
-----
أريد بالدين هُنا الدين غير التوارث حسب السنن والعادات، لأن الأديان الوراثية كلها
متشابهة، فالشيء الذي يتخذ وراثة وسنة واعتيادًا من غير علم وبصيرة كيف كان، ومهما
كان، هو مردود لا فرق بين أن يكون مذهب الشيعة أو السنة أو الدين البوذي أو المسيحي
أو الإسلامي. إذ لا درجات في الجهل. لذا فإن البحث يدور على "الدين الأرقى من
العلم" لا الدين الذي لقن تلقينًا واستلمه الخلف عن السلف كمجموعة عادات وسنن
تقليدية مكررة. إن الجيل الواعي يرفض هذه السنن والخصائص الموروثة اللاعقلانية ولا
يستمع لها، وإن لم يكن قد القاها في المهملات بعد، فإنه سيلقيها غدًا. هذا شيء
محتوم.

إني اتطلع وأفكر في خط السير الذي تسير عليه هذه البادرة. مثلًا يتمرد الجيل الوراثي
في مجتعمنا على السنن اللاعقلانية التي حملت إليه أولًا فيرفضها كلها، ثم يصل إلى
مرحلة فارغة تمامًا، هي الوجل والاضطراب والبحث والريبة والحاجة إلى كشف الطريق، وفي
النهاية يجده. إن اكتشاف الدين بعد رفض السنن الوراثية المتحجرة، هو الشيء الذي
يعرض اليوم على مستوى إيران، وليس على مستوى مجتمعاتنا الدينية فحسب، بل على مستوى
المثقفين في العالم كله. وعلى مستوى ضمير هذا الجيلمن لشباب الواعد المتمرد في
عصرنا الحاضر.


/Derived from/ [cite:@shariati-2007-nanah-esteh], no. 70. Appeared: 2024-01-08 (20:01)
-----
إلى أي حد يحب المفكر عدوه. يجب ألا تحتفظ أبدًا أو تخفي أمام نفسك أي شيء مما قد
تتم به معارضة أفكارك. اقطع على نفسك نذرًا بهذا. هذا جزء من الاستقامة الأساسية.
يجب كذلك أن تقوم بحملة ضد نفسك كل يوم. لم يعد من شأنك الانتصار أو احتلال قلعة
ما، بل من شأن الحقيقة، — كما أن هزيمتك لم تعد من شأنك هي الأخرى.



/Derived from/ [cite:@DawnofDay], no. 201. Appeared: 2024-01-08 (20:01)
-----
لا زالت الوسيلة التي يصبح بها المرء نبي عصره وصانع معجزاته كما كانت في الماضي
لم تتغير: عليه أن يعيش على الهامش، بقليل من المعرفة، بعض الأفكار والكثير من
الزهو، وفي الأخير سيشعر بأن الإنسانية لا يمكنها الاستغناء عنه لأنه من الواضح جدًا
أنه يستطيع الاستغناء عنها. بمجرد ما يصبح هذا الشعور قويًا لديه يحظى بتصديق الناس
عليه.



/Derived from/ [cite:@DawnofDay], no. 190. Appeared: 2024-01-08 (20:01)
-----
إن لي ست طرق على الأقل في محاربة عنف غريزة ما. أولًا، يمكننا أن نتملص من
الاستجابة لبواعث تربية رغبة ما، أو أن نضعف تلك الرغبة بامتناعنا عن تلبيتها عبر
مدد زمنية تصبح أطول وأطول. ثانيًا، قد نسن لأنفسنا قانونًا صارمًا ومنتظمًا بخصوص
إشباع شهواتنا: وهكذا نخضعها لقاعدة، نحصر مدها وجزرها بين حدود ثابتة، لنربح
الفواصل التي لا تكون فيها مزعجة؛ وربما نصل بهذا للطريقة الأولى. ثالثًا، قد نستسلم،
عن قصد، لإشباع رغبة جامحة وشرسة إلى حد الاشمئزاز، لتصبح لنا، من خلال ذلك
الاشمئزاز، سلطة على الغريزة: إذا سلمنا بأننا لن نفعل مثل الفارس الذي تكسرت عنقه
وهو يحاول إنهاك حصانه—وتلك هي القاعدة مع الأسف في تلك المحاولات. رابعًا، هناك
ممارسة فكرية تقضي ربط فكرة شاقة بفكرة الإشباع بشكل مكثف بحيث تصبح هاته الفكرة
نفسها مع الاعتياد عليها، شاقة في كل مرة أكثر فأكثر. يجب كذلك أن نذكر هنا كبرياء
الإنسان الذي يثور كما فعل بايرون ونابليون، الذين شعرا بهيمنة الهوى على مظهر
العقل وقاعدته العامة كإهانة: وهذا هو مصدر عادة وفرحة الطغيان على الغريزة
وتحطيمها نوعًا ما، "لا أريد أن أكود عبد أية رغبة كانت". خامسًا: يشرع المرء في
التخلص من القوى التي راكمها بإرغام نفسه على القيام بعمل شاق ومتعب، أو باستسلامه
عن قصد لإغراءات وملذات جديدة ليوجه بذلك أفكاره ولعبة قواه البدنية وجهة جديدة.
[..] سادسًا وأخيرًا: الذي يتحمل إضعاف وإحباط كل قواه البدنية والنفسية ويجد ذلك
أمرًا معقولًا، يتمكن في نفس الوقت من إضعاف غريزة خاصة شديدة العنف: كما يفعل الذي
لا يشبع شهوته الجنسية ويدمر في الوقت ذاته قوته، وعقله في الغالب، على طريقة
الزاهد. الطرق الست هي إذًا: تفادي الفرص السانحة، إقحام القاعدة في الغريزة، إثارة
الشعور بالشبع والنفور من الغريزة وربطه بفكرة معذبة (كفكرة الخجل، والعواقب
الوخيمة أو الكبرياء والمهانة)، ثم تشتت القُوَى وأخيرًا الضعف والإنهاك الشامل. لكننا
لا نملك إرادة محاربة عنف غريزة ما، مثلما لا نملك الطريقة التي قد نهتدي إليها
والنجاح الذي قد نحققه من ورائها. وما عقلنا في هاته القضية سوى أداة عمياء في يد
غريزة هي منافسة الغريزة التي تعذبنا، سواء كانت الحاجة للراحة، أو الخوف من العار
وغيره من العواقب الوخيمة، أو الحب. لهذا حين نعتقد أننا نشتكي من عنف غريزة ما،
فإنها في الحقيقة غريزة هي التي تشتكي غريزة أخرى. وهو ما يعني أن إدراك المعاناة
التي يسببها لنا مثل هذا العنف يكون مشروطًا بغريزة أخرى عنيفة مثله، أو أشد منه
عنفًا، وأن صراعًا ما يتهيأ وسيكون عقلنا مجبرًا على خوض غماره.



/Derived from/ [cite:@DawnofDay], no. 77. Appeared: 2024-01-08 (20:00)
-----
Remember how long thou hast been putting off these things, and how often thou
hast received an opportunity from the gods, and yet dost not use it. Thou must
now at last perceive of what universe thou art a part, and of what administrator
of the universe thy existence is an efflux, and that a limit of time is fixed
for thee, which if thou dost not use for clearing away the clouds from thy mind,
it will go and thou wilt go, and it will never return.


/Derived from/ [cite:@aurelius-2012-thoughts], no. 9. Appeared: 2024-01-08 (20:00)
-----
الأحاسيس وارتباطها بالأحكام. — "ثق في إحساسك!" — ولكن الأحاسيس ليست نهائية، ليست
أصلية؛ وراء الأحاسيس هناك الأحكام والتقديرات التي نقلت إلينا على شكل أحاسيس
(الميل لهذا العمل والنفور من ذاك). الإلهام الذي يأتينا من إحساس ما هو وليد —
وغالبًا ما يكون حكمًا خاطئًا — هو لا يكون حكمًا أصدرته أنت. أن يثق المرء في أحاسيسه
معناه أن يطيع جده، وجدته وآباءهم الأولين أكثر ما يطيع الآلهة التي فينا، أي عقلنا
وتجربتنا.


/Derived from/ [cite:@DawnofDay], no. 33. Appeared: 2024-01-08 (20:00)
-----
Through not observing what is in the mind of another a man has seldom been seen
to be unhappy; but those who do not observe the movements of their own minds
must of necessity be unhappy.


/Derived from/ [cite:@aurelius-2012-thoughts], no. 9. Appeared: 2024-01-08 (19:59)
-----
تعلم الوحدة. — أيها الصعاليك، يا من تقطنون المدن الكبرى للسياسة العالمية، أيها
الشبان الموهوبون، الذين يعذبكم الغرور، أتعتقدون أن واجبكم هو أن تعبروا عن رأيكم
في الأحداث (لأن هناك دائمًا حدثا ما)! تعتقدون أنكم حين تثيرون هذا الغبار والضجيج
تصبحون أنتم من يقود التاريخ! تترقبون دائمًا وتنتظرون اللحظة المناسبة لتخاطبوا
الجماهير، وبهذا تفقدوا كل إبداعية حقيقية! مهما تكن الرغبة التي تبدونها في تحقيق
أعمال كبرى فإن صمت النضج المطبق لا يأتي إليكم! يسوقكم حدث اليوم كما تذهب الريح
بالقش الخفيف، وأنتم تتوهمون أنكم تسوقون الحدث.



/Derived from/ [cite:@DawnofDay], no. 125. Appeared: 2024-01-08 (19:59)
-----
إن المجتمعات المتأخرة لها مصير متشابه وحاجة واحدة وانتخاب واحد، لأنها تواجه قدرة
متشابهة في زمان واحد ومشترك. إما أن يختار الفكر أولًا أو الحضارة من غير الفكر.
وأعني بالحضارة الشيء الذي يخرجه المتحضرون لنا. كشفت التجارب طيلة الثلاثين
والعشرين سنة الأخيرة، أن المجتمعات التي بدأت من نقطة عقائدية، وتحركت بعد تحقق
وعيها الفردي والاجتماعي، قد وقفت اليوم في صف القدرات التي تصنع الحضارة العالمية.
لكن المجتمعات التي اقتدت بالحضارة الغربية بدون وعي اجتماعي، أو شعور إنساني
بالوعي الفردي، وبدون عقيدة بل نهضة كاذة، قد ظلت مسخرة للحضارة الغربية، مستهلكة
على الدوام، خاضعة للذل والعبودية


— فرانز فنون.

أما ذا كان ليس همه سوى الصنعة والاقتدار والرأسمالية وما يسمى اليوم بالتقدم
العلمي والصناعي فإنه يبقى مستهلكًا وإن ظن نفسه منتجًا. وهذه الخديعة الكبرى التي
وقعت فيها جميع البلاد المتأخرة.

— علي شريعتي.

    
* Bibliography
#+print_bibliography:

* Local Variables                                                     :noexport:
Local Variables:
salih/rebuild: t
End:

* [[id:4b45b3aa-faac-4698-ba6b-b120ac166453][agenda]]                                                              :noexport:
** DONE Build anthology                                              :@idea:
:LOGBOOK:
CLOCK: [2024-01-08 Mon 18:40]--[2024-01-08 Mon 23:24] =>  4:44
CLOCK: [2024-01-08 Mon 13:17]--[2024-01-08 Mon 13:41] =>  0:24
:END:
[2024-01-08 Mon 12:16]
