:PROPERTIES:
:ID:       pmhhulo02wj0
:END:
#+title: Email Guide

Copied from [[https://alirezahayati.com/connect/][Ali Reza Hayati]]'s.

[[https://useplaintext.email][Send your messages in plain text]]. Don't send HTML messages. If you send me a
link to your message, I won't open it. Please don't send files I haven't asked
for. I won't open any file unless I've asked for it.

You don't need to be so polite, I follow Crocker's rules[fn:1] I appreciate your
politeness but I prefer if you just optimize your messages for information, not
being nice to me. I will always be polite to you and following Crocker's rules
doesn't mean I'm gonna be rude, it just mean that I don't get offended easily,
certainly not by you giving me most information and less time-taking useless
words.

Don't be shy to ask me a for a favor, if you need anything and feel I can do it
for you, ask me. I'll say no if I can't do it or I just don't want to.

If you want to comment on a post, send me the link of the post so I can
understand what you're talking about. Please note that my opinions have changed
many times, and will change again in future, that happens when you're growing
up.

Don't ask for personally identifiable data of me or anybody else.

* Footnotes

[fn:1] Declaring yourself to be operating by "Crocker's Rules" means that other
people are allowed to optimize their messages for information, not for being
nice to you.  Crocker's Rules means that you have accepted full responsibility
for the operation of your own mind - if you're offended, it's your fault.
Anyone is allowed to call you a moron and claim to be doing you a favor.
(Which, in point of fact, they would be.  One of the big problems with this
culture is that everyone's afraid to tell you you're wrong, or they think they
have to dance around it.)  Two people using Crocker's Rules should be able to
communicate all relevant information in the minimum amount of time, without
paraphrasing or social formatting.  Obviously, don't declare yourself to be
operating by Crocker's Rules unless you have that kind of mental discipline.
