:PROPERTIES:
:ID:       omy9ejo02wj0
:END:
#+TITLE: Bibliography
#+options: toc:t
#+cite_export: csl  harvard.csl
#+filetags: :books:
#+HTML_HEAD_EXTRA: <script>document.addEventListener('DOMContentLoaded', () => document.body.classList.add('page-books'));</script>
#+MACRO: inc #+INCLUDE: "$1::#bk" :only-contents t
#+DATE: <2022-12-26 Mon 02:14>

#+begin_export HTML
<head>
<style>


@media screen and (max-width: 1089px) {

.org-ul {
font-size: 13px;
    padding: 0;

}

}

p:has(> a:target) {
  background-color: #ffa;
}


  .footdef {
    display: block !important;
  }

.tag span {
    float: right;
    margin-right: 0.5em;
    border: 1px solid #bbb;
    border-radius: 3px;
    background-clip: padding-box;
    color: #333;
    background-color: #eee;
    line-height: 1;
}

.org-ul {
}

# .sidenote {
#         display: none;
# }


.sidenote a, .footpara a {
    word-break: break-all !important;
}

  .footnotes {
    display: block !important;
  }
</style>
</head>
#+end_export

- [2025-11-22 Sat 03:01] I had a "he is literally me" reading a biography about [[id:ynx5yta0uwj0][Leonadrdo da Vinci]]: "His notebooks are ﬁlled with lists of books he acquired and passages he copied."[cite:@isaacson-2017-leonar-vinci]

These are neither the books I recommend nor the ones I countenance their views.
This is a list of the documents/textbooks that I own (either physically or
digitally), with some side notes that could be helpful.
- [2024-10-01 Tue 17:37] A useful source for cultures and arts http://www.infocobuild.com/
- [2023-10-03 Tue 05:13] If you are looking for new courses/topics to learn
  about, it's highly recommended that you watch this lecture by professor [[id:5a780a66-e9ff-4712-8269-3d1cd1556c95][Noam Chomsky]]:
  https://youtu.be/2p9aKa08cRI [fn:1]
- [2023-03-06 Mon 00:13] I added some papers here too, I think this makes the
  'books' title a little bit misleading. Also I moved the books I regret
  reading, or the ones I wouldn't definitely reread to the "inexpedient" [fn:8]
  sections.
* Humanities and the like
- [[id:qzm4rv80f9k0][Conjectures and Refutations]] (Popper, K.)
- Analytic Philosophy of Religion (Harris, J. F.) [fn:-0-2]
- [[id:6w7g0dw06ak0][The Concept of Religion]] (Schilbrack, K.)
- [[id:pzjhg130b3k0][A History of Western Philosophy]] (Russell, B.)
- [[id:gai38c0070k0][Utilitarianism]] (Lazari-Radek et al.)
- [[id:99f7d930-51d8-4764-a5a1-5a6641c25dd6][The Hero With a Thousand Faces]] (Campbell, J.)
- The Poetics of Iblis (Bodman, W.)
- Beyond Good and Evil (Nietzsche, F.)
- A Theologico-Political Treatise (Spinoza, B.)
- [[id:uq466a50b3k0][In Praise of Idleness and Other Essays]] (Russell, B.)
- [[id:aa974737-5070-4652-985d-2a7a2ad198e9][History of the Western Philosophy and Theologyy]] (Frame, J.)
- Discipline and Punish (Foucault, M.)
- The Fragility of Consciousness (Lawrence, F.)
- The Conquest of Happiness (Russell, B.)
- The Interpretation of Cultures (Geertz, C.)
- [[id:1f939ce6-6cba-43b6-a19b-4b78890be45b][The Open Society and its Enemies]] (Popper, K. R.)
- The Myth of the Framework (Popper, K. R.)
- All Life is Problem Solving (Popper, K. R.)
- After The Open Society (Popper, K. R.)
- Culture in a Liquid Modern World (Bauman, Z.)
- Anatomy of an Epidemic (Whitaker, R.)
- Sources of the Self (Taylor, C.)
- Against Method (Feyerabend, P.)
- Meditations on First Philosophy (Descartes, R.)
- The Cambridge Dictionary of Philosophy (Audi, R.)
- The History of Sexuality (Foucault, M.)
- A Culture of Ambiguity(Ahmed, L.)
- The Philosophical Question of Christ (Gilson, É.)
- Women in the Medieval Islamic World (Hambly, G. R. G.)
- The World (Descartes, R.)
- [[id:9ad20f1f-68d7-4598-8291-c30b6f783f72][Desire and Love in Descartes's Late Philosophy]] (Beavers, A)
- History of Religion (Tokarev, S.)
- [[id:70jkomb184k0][Heidelberg, Spinoza and Academic Freedom]] (Gardiner, M.)
- [[id:5b243a60-ed43-42fb-bb6a-41f55788fc64][Grounding for The Metaphysics of Morals]] (Kant, E.)
- [[id:ks44lrm0vyj0][Chomsky on Democracy and Education]] (Chomsky et al.)
- [[id:e6i5wfa0b0k0][Schopenhauer: A Very Short Introduction]] (Janaway, C.)
- [[id:ose7oia0b0k0][Spinoza: A Very Short Introduction]] (Scruton, R.)
- [[id:uw770ua0b0k0][Kierkegaard: A Very Short Introduction]] (Gardiner, P.)
- [[id:vmv9rdg0elk0][How to Read Kierkegaard]] (Caputo et al.)
- [[id:npl4k8k0elk0][Papers and Journals]] (Kierkegaard et al.)
- [[id:vky3exa0b0k0][Animal Rights: A Very Short Introduction]] (DeGrazia, D.)
- [[id:qtjffac0o2k0][The Highest Good in Aristotle and Kant]] (Aufderheide et al.)
- [[id:z6pk3l719wj0][Violence and the Pornographic Imaginary]] (Purcell, N)
- [[id:f9h2bj719wj0][Exposing the Harms of the Global Pornography Industry]] (Reist et al.)
- [[id:ytna0220xyj0][“The Rebirth of The West Begins With You!”]] (Elley, B.)
- [[id:evwe2qo0gzj0][On The Contrast Between Pity and Compassion in Nietzsche Philosophy]] (Obdrzalek, S.)
- [[id:21b0xb30b3k0][Critical Thinking: A Concise Guide]] (Bowell et al.)
- [[id:gpte2330h4k0][The Story of Art]] (Gombrich, E. H.)
- [[id:vqeihy40v6k0][Bodies as Objects and Property]] (Phillips, A.)
- [[id:dom15390h8k0][The Problem of Induction]] (Henderson, L.)
- [[id:27ticop0ryj0][Philosophical Reflections on Black Mirror]] (Shaw et al.)
- [[id:3wwfar00tyj0][Black Mirror: ‘The National Anthem’]] (González et al.)[fn:-0-1]
- [[id:yydarz71vyj0][The National Anthem and Weighing Moral Obligations]] (Collins et al.)
- [[id:v32cm1u09bk0][What is art?]] (Tolstoy, L.)
- [[id:uue9uyy0tfk0][The Structure of Scientific Revolutions]] (Kuhn, T. S.)
- [[id:fx33kr60yik0][Metaphysics of Love]] (Schopenhauer, A.)
- [[id:rc638n90smk0][An Introduction to The Philosophy of Language]] (Morris, M.)
- [[id:9xy8wqi0mnk0][The Revolutionary Ideas of Karl Marx]] (Callinicos, A.)
- [[id:6ox63kh0qnk0][LLMs Should Not Replace Mental Health Providers]] (Moore et al.)
- [[id:zm2cc490wpk0][All Life is Problem Solving]] (Popper, K.)
** Modernism and Postmodernism
- [[id:e0dc46ae-8acd-426b-a2f9-4cae24dfb5ca][Liquid Modernity]] (Bauman, Z.)
- Community: Seeking Safety in an Insecure World (Bauman, Z.)
- [[id:53d75862-9557-49bd-9b05-44dd1780857e][The Happiness Industry]] (Davies, W.)
- Thinking Sociologically (Bauman, Z.)
- Liquid Times: Living in an Age of Uncertainty (Bauman, Z.)
- Modernity and the Holocaust (Bauman, Z.)
- Consuming Life (Bauman, Z.)
- Liquid Love (Bauman, Z.)
- Liquid Life (Bauman, Z.)
- Liquid Fear (Bauman, Z.)
- Born Liquid (Bauman, Z.)
** Other
- ما وراء الحجاب (المرسيني، ف.)[fn:-0-4]
- الحريم السياسي (المرسيني، ف.)
- لعنة الألفية، لماذا يفشل النشاط التغييري؟ (صغبيني، ط)
- التخلف الاجتماعي، مدخل إلى سيكولوجية الإنسان المقهور (حجازي، م)
- Wahhabism (Subhani, J. A.)[fn:-0-5]
- Fifth Gospel of Nietzsche (Sloterdijk, P)[fn:-0-6]
- هشام شرابي ونقد النظام الأبوي في المجتمع العربي (معزوز، ع)
- المأزق في الفكر الديني بين النص والواقع (الصالح، ن)
- المدينة الإسلامية والأصولية والإرهاب (الديالمي، ع)
- عنف اللغة (لوسركل، ج)
- مغامرة العقل الأولى (السواح، ف)
- قضايا (دراغمة، ج)
- دكتاتورية المستنيرين روح الإنسانوية العابرة وأهدافها [fn:-0-7]
* Science
- [[id:jmijuv81p3k0][The Computational Beauty of Nature]] (Flake, G. W.)[fn:-1-2]
- [[id:zp9cfn41p3k0][Chaos and Fractals]] (Peitgen et al.)[fn:-1-1]
- [[id:vfabj551p3k0][Fractals: A Very Short Introduction]] (Falconer, K. J.)
- [[id:7wciru016ak0][Chaos]] (Gleick, J.)
- [[id:32237fa6-388d-4acc-b0cb-f88e7b5bf785][The Human Web]] (McNeill et al.)[fn:-1-8]
- The Reluctant Mr. Darwin (Quammen, D.)
- Why We Get Sick (Nesse, R. M.)
- Being Mortal (Gawande, A.)
- Straight and Crooked Thinking (Thouless, R. H.)
- [[id:3etcfla0b0k0][Quantum Theory: A Very Short Introduction]] (Polkinghorne, J.)
- [[id:9ktanra0b0k0][Mathematics: A Very Short Introduction]] (Gowers, T.)
- [[id:pia5spi0wzj0][The Fall of The Faculty]] (Ginsberg, B.)
- [[id:urx84na0b0k0][Cryptography: A Very Short Introduction]] (Piper et al.)
- [[id:mipi1wa0b0k0][Cosmology: A Very Short Introduction]] (Coles, P.)
- [[id:z3bakpa0b0k0][Choice Theory: A Very Short Introduction]] (Allingham, M.)
- [[id:5oj6f9d1pwj0][Introduction to Probability and Statistics for Engineers and Scientists]] (Ross, S.)
- [[id:eqkkwk70gxj0][Enhancing Cognitive Abilities with Comprehensive Training]] (Hardy et al.)
- [[id:c934c571b3k0][Thinking, Fast and Slow]] (Kahneman, D.)
- [[id:1d60c417-543d-45f2-930f-072dcfd2ca8e][Expressive Writing Can Increase Working Memory Capacity]] (Klein et al.)
- [[id:974d55fd-3a0e-43da-a283-e4b27d87ac66][Differentiation of Zaghrouta]] (Elshourbagy et al.)
- [[id:rahixib0k1k0][Holy Tweets: Exploring The Sharing of The Quran on Twitter]] (Abokhodair)
- [[id:mrxadgc07zj0][Opening The Black Box of QS World University Rankings]] (Huang, M.)
- [[id:mj2d2k31b4k0][The Limits of Democratizing Science]] (Schroeder, S. A.)[fn:-1-3]
- [[id:eq9k1eh0afk0][The Unreasonable Effectiveness of Mathematics in the Natural Sciences]] (Wigner, E. P)
  Related: https://youtu.be/dK_narib4do?list=PLE418513C3CDF6C11&t=152
** Evolution and Evolutionary Science
:PROPERTIES:
:ID:       l9scma0070k0
:END:
The scientific theory of evolution by natural selection was conceived
independently by two British naturalists, [[id:eah3ao51r8k0][Charles Darwin]] and Alfred Russel
Wallace, in the mid-19th century as an explanation for why organisms are adapted
to their physical and biological environments. The theory was first set out in
detail in Darwin's book On the Origin of Species.
- [[id:34t29e71b3k0][Why Evolution Is True]] (Coyne, J. A.)
- The Selfish Gene (Dawkins, R.)
- [[id:tk94g2a0u2k0][The Naked Ape]] (Morris, D.)[fn:-1-9]
- Fossils: A Very Short Introduction (Briggs, D. E. G.)
- Your Inner Fish (Shubin, N.)
- Life Ascending: The Ten Great Inventions of Evolution (Lane, N.)
- The Greatest Show on Earth: The Evidence for Evolution (Dawkins, R.)
- Evolution and the Myth of Creationism (Berra, T. M.)
** Linguistics
- [[id:dgd3ce90tyj0][The Atoms of Language]] (Baker, M.)
- [[id:361ipf90tyj0][An Introduction to Language]] (Fromkin et al.)
  [fn:: I didn't finish this in favor of [cite:@fasold-2014] which claims to be
  "only introduction to linguistics in which each chapter is written by an
  expert who teaches courses on that topic", also the print is much nicer.]
- [[id:4o93i811zyj0][An Introduction to Language and Linguistics]] (Fasold et al.)
- [[id:nspfvfi04zj0][How arbitrary is language?]] (Monaghan et al.)
- [[id:49fg8am0mbk0][For F*ck's Sake]] (Roache, R.)

*** Stemming
:PROPERTIES:
:ID:       607e726d-e2f5-4a32-b430-2fb8e157feaa
:END:
- [[id:b98c4b4a-01aa-4906-83b0-8dd85c23ec72][A Comparative Survey on Arabic Stemming]] (Mustafa et al.)
- [[id:6bab6c09-54a8-4579-81ca-f26e7720ed5d][Pattern-based Stemmer Analysis and Implementation on Arabic Text]] (Wulandari et al.)[fn:-2-3]
- [[id:be2a503f-17f1-405f-8277-82930b297852][New Rules-based Algorithm to Improve Arabic Stemming Accuracy]] (Cherif et al.)
- [[id:63a1fcf8-bc33-483f-ab76-97bfc530a8db][New Arabic Root Extraction Algorithm]] (Thalji et al.)
- [[id:01vjsww0hwj0][Corpus for Test, Compare and Enhance Arabic Root Extraction Algorithms]] (Thalji et al.)
- [[id:ekr6l541dzj0][Light Stemming for Arabic Information Retrieval]] (Larkey et al.)
- [[id:q3minv71dzj0][Enhanced Algorithm for Extracting The Root of Arabic Words]] (Ghwanmeh et al.)
- [[id:b22i5981dzj0][A Novel Root Based Arabic Stemmer]] (al-Kabi et al.)
** Intelligence
- [[id:f289ff59-1917-4c84-8997-76b0c5020e20][Intelligence: History of the Concept]] (Carson, J.)
- [[id:715fc33f-7d76-42bf-8059-7cff823ca92d][Intelligence Science: Leading the Age of Intelligence]] (Shi, Z.)
- [[id:937be9c2-5204-4596-a8e4-6813409e579c][Intelligence and Chess]] (Gobet et al.)
** Psychology
- [[id:ij67782019k0][Psychology’s Status as a Science]] (Uher, J.)
- The Social Animal (Aronson, E.)
- The Crowd (Le Bon, G.)
- [[id:3u979u71b3k0][Group Psychology]] (Freud, S.) [fn:-4-10]
- [[id:90g3zw71b3k0][Totem and taboo]] (Freud, S.)
- The Ego and the Id (Freud, S.)
- Evolutionary Forensic Psychology (Duntley, J. D.)
- [[id:sz1h7z71b3k0][Evolutionary Psychology: The New Science of the Mind]] (Buss, D. M.)
- The Lucifer Effect (Zimbardo, P. G.)
- Faces of the Enemy (Keen, S.)
- [[id:8d495c28-c0dc-4b04-9c50-b909068d6529][Is Psychoanalysis Still Relevant to Psychiatry?]] (Paris, J.)
- [[id:h89ef5d19wj0][Sex and Self]] (Camal, A.)
- [[id:zrh75sj0m9k0][Sex and Terror]] (Quignard, P.)
*** Sexology                                                          :noexport:
:PROPERTIES:
:ID:       vqkhia40xyj0
:END:
(anything written by Frued, S above is eligible to be here too)
- Psychology of Sex Relations (Kinsey, A. C.)
- [[id:kmb6xv60ayj0][Intersectionality of Cultural Norms and Sexual Behaviours]] (Khumalo et al.)
- [[id:va03ov50ayj0][Sociocultural Factors of Female Sexual Desire and Sexual Satisfaction]] (Evensen, M.)[fn:-4-1]
- [[id:12u8tq50qyj0][Orgasm Equality: Scientific Findings and Societal Implications]] (Mahar et al.)[fn:-4-2]
- [[id:zru6yv50qyj0][Differences in Orgasm Frequency]] (Frederick et al.)[fn:-4-3]
- [[id:hakax260qyj0][Heterosexual Young Adults' Experience [..]​]] (Wetzel et al.)[fn:-4-4]

- [[id:mryki760qyj0][Masturbation Among Women]] (Carvalheira et al.)
  [fn::This states that autoeroticism may get female climax percentage higher
  (92%) than in [cite:@frederick-2017-differ-orgas] (65%) which is usually used
  as an argument against the note on [cite:@wetzel-2022-heter-young], but I
  personally do not think that it's totally valid.]
- [[id:nap92h60qyj0][Orgasm In College Hookups and Relationships]] (Armstrong et al.)
  [fn::This corresponds with my view and also with
  [cite:@evensen-2021-socioc-factor], which has show many sociocultural effects
  on women eroticism. This, studying 12,000 college students, only 10% of the
  women said they orgasm during first-time hookups while 68% said they orgasm
  during sex that occurs in a committed relationship, which, again corresponds
  with [cite:@krasnow-2019-femal] which suggested that females are doing better
  (sexually) when they feel "that their whole self is desired by their partner".
  One can argue that this might reflect the lack of stable and long-term
  relationships in western society which have been always the main sample for
  such studies.]
** Cognitive Science
+ [[id:l3b6u5m0zwj0][Mind as Machine: a History of Cognitive Science]] (Boden, A.)
  [fn::I really liked [cite:@muller-2008-margar] description of this work (I will cut it
  out of context): The bad news is that this is not a book for you. Neither is
  it for me, or for anybody else, in a word: it is not a book for readers.]
+ [[id:wpwhkwq0zwj0][Cognitive Science: An Introduction to the Study of Mind]] (Friednberg et al.)
** Mathematics
- [[id:52n2u0y0pwj0][Introduction to Linear Algebra]] (Strang, G.)
- [[id:w1s05uz0v0k0][The Calculus Wars]] (Bardi, J. S.)
- [[id:ycoi0ih0xxj0][Differential Equations for Dummies]] (Holzner, S.)
- [[id:7bp8wrh0xxj0][Differential Equations w/ Applications and Historical Notes]] (Simmons, G.)
- [[id:sv7dvww0e2k0][Philosophical and Mathematical Logic]] (De Swart, H.)
- [[id:ikdelw30b3k0][Beginning Mathematical Logic]] (Smith, P.)
** Computer Science
:PROPERTIES:
:CUSTOM_ID: cs
:END:
Those are mostly not books of 'recommendations', at least in my opinion. Those are the
must-read books, or must experience, references and books that any computer scientist should
read (or crash with).

- [2025-05-03 Sat 00:55] This might be worth checking out: [[id:37i71rz00ik0][What can be computed?
  A practical guide to the theory of computation (2018) [pdf] ​]]
- Logic (S, Nicholas.)
- Structure and Interpretation of Computer Programs (Sussman et al.)
- Discrete and Combinatorial Mathematics (Grimaldi, R.)
- Data Structures and Algorithm Analysis (Shaffer, C.)[fn:-7-1]
- The Art of Unix Programming (Raymond, E.)
- Operating Systems: Three Easy Pieces (Arpaci-Dusseau et al.)
- Computer Algebra and Polynomials (Guiterrez, J.)
- An Introduction to Genetic Algorithms (Mitchell, M.)
- Speech and Language Processing (Jurafsky et al.)
- Computer Organization and Design (Patterson et al.)
- Fundamentals of Computer Graphics Peter (Shirley et al.)
- The Art of Concurrency (Breshears, C.)
- Mathematical Theory of Communication (Shannon, C.)
- Introduction to Data Comparison (Sayood, K.)
- Database System Concepts (Silerschatz, A.)
- Foundation of Cryptography (Goldreich, O.)
- Signals and Systems (Ghosh, S.)
- Digital Signal Processing (Proakis et al.)[fn:-7-11]
- [[id:kthjft30zik0][Distributed Systems]] (Steen et al.)
- [[id:nokchqp04pk0][Network Programming]] (Hall, B.)[fn:-7-12]
- [[id:kqf007v0eqk0][A Concise Introduction to Data Compression]] (Salomon, D.)
- [[id:664bv0x0eqk0][Introduction to Information Theory and Data Compression]] (Hankerson et al.)
*** Miscellaneous
Those are very important writings, however they are more 'optional' if mentioned with the
above list.

- [[id:tvlghh1071k0][Generative Art]] (Pearson, M.)
- Computational Geometry Algorithms and Applications (Kreveld et al.)
- Algorithms (Sedgewick, R.)[fn:-7-8]
- Coding Theory (Kuhn, V.)[fn:-7-7]
- A Functional Pattern System for Object Oriented Programming
- [[id:uz1gl2e0r2k0][Quantum Computing for Computer Scientists]] (Mannucci, M. A.)
- [[id:zxf7wf71jak0][Mastering Clojure Data Analysis]] (Rochester, E.)
**** Cryptography and Computer Security
- [[id:4nqdufd1m0k0][Gray Hat Hacking]] (Harper et al.)
- Foundation of Cryptography (Goldreich.)
- Cryptographical Mathematics (Lewand.)
- A Course in Number Theory and Cryptography
**** Databases
- Database Internal (Petrov, A.)
- Querying Databases Privately (Asonov, D.)
*** Books of Beauty

- Beauty is Our Business (Feijen et al.)
- A Discipline of Programming (Dijkstra, E.)
- [[id:6v6gfpy07zj0][Selected Writings on Computing: A Personal Perspective]] (Dijkstra, E.)
- Hackers and Painters (Graham, P.)
- Core Techniques and Algorithms in Game Programming (Dalmau, D.)[fn:-7-2]
- Structured Computer Organization (Tanenbaum, A.)
- UNIX: A History and a Memoir (Kernighan, B.)
- The Mythical Man-Month (Brooks, F.)
- Understanding Cryptography (Paar et al.)
- [[id:u96a3n516kk0][The Nature of Code]] (Shiffman, D.)
*** Artificial Intelligence
+ [[id:vw9jv4i0fyj0][An Introduction to Statistical Learning]] (James et al.)
+ [[id:vrqe3zd0fyj0][Paradigms of Artificial Intelligence Programming]] (Norvig, P.)
+ [[id:vvi3a6s08ek0][Deep Learning]] (Goodfellow et al.)
+ [[id:jxkigcn0gek0][Mathematics for Machine Learning]] (Deisenroth et al.)[fn:-7-10]
+ [[id:c48ly321nkk0][A First Course in Probability for Computer and Data Science]] (Tijms, H.)
+ [[id:tz6l84d0olk0][Hands-on Machine Learning]] (Géron, A.)
*** Unscientific
Books that focuses on applications rather than theory.  
  [[id:2a4gvvi0yrk0][Good code, Bad Code]] (Long, T.)
- Distributed Services with Go (Jeffery, T.)
- [[id:wq44pwe03rk0][Building Microservices]] (Newman, S.)
- [[id:0sne67f03rk0][Microservices with Go]] (Shuiskov, A.)
- Building Event-Driven Microservices (Bellemare, A.)
- Designing Distributed Systems (Burns, B.)
- [[id:b6c35om050k0][Practical Binary Analysis]] (Andriesse, D.)
- [[id:9dm1ucn050k0][Designing BSD Rootkits]] (Kong, J.)
- [[id:awjifdh0c0k0][Language Implementation Patterns]] (Parr, T.)
- [[id:tqujrj50eyj0][Build Your Own Lisp]] (Holden, D.)
- [[id:1dt62cl03rk0][Mongodb in Action]] (Borucki, A.)
- [[id:6p559s815sk0][Rabbitmq Essentials]] (Johansson, D.)

**** Languages
- [[id:0xlj3x70eyj0][The C Programming Language]] (Kernighan et al.)[fn:-7-6]
- [[id:ufm1ybx0p2k0][Living Clojure]] (Meier, C.)[fn::I left this for [cite:@higginbotham-2015-clojur-brave-true]]
- [[id:ihcjsoc1p2k0][Clojure for The Brave and True]] (Higginbotham, D.)[fn:-7-9]
- [[id:4nyahz30j3k0][Clojure, The Essential Reference]] (Borgatti, R.)
- On Lisp (Graham , P.)[fn:-7-3]
- Let Over Lambda (Hoyte, D.)
- Learning Perl (Schwartz et. al.)[fn:-7-4]
- Writing a Compiler In Go (Ball, T.)
- Writing an Interpreter In Go (Ball, T.)
- C# (Price, J.)
- System Analysis & Design (Dennis, A.)[fn:-7-5]
- Object Thinking (West, D.)
***** Go
- [[id:wjhkm651trk0][Hands-on Software Engineering with Go]] (Anagnostopoulos, A.)
- [[id:j4bl9s90vrk0][Concurrency in Go]] (Cox-Buday, K.)
- Pro Go (Freeman, A.)
- [[id:yjddvm11trk0][Go Brain Teasers]] (Tebeka, M.)
- [[id:h1ofsh21trk0][Ultimate Go Notebook]] (William Kennedy, H. A.)
- [[id:bdufik21trk0][Know Go: Generics]] (Arundel, J.)
- [[id:eer4eu21trk0][Efficient Go]] (Plotka, B.)
- [[id:3t1heb31trk0][Hands-on Dependency Injection in Go]] (Scott, C.)
- [[id:jpkh9551trk0][100 Go Mistakes]] (Harsanyi, T.)
**** COMMENT Bad Books
Do not read those.
- The Pragmatic Programmer (Thomas et. al.)

#+begin_quote
  I found an Egyptian programmer once in YouTube treats this book (Book? I wrote more
  organized Facebook posts than that.) like a Bible.
#+end_quote
** Other                                                              :noexport:
- الرياضات في حياتنا (زلاتكا، ش)
- إمبراطور المآسي، سيرة للسرطان (موكرجي، س)

  Not a study at all, more like a novel. A sad one.
* Politics
- [[id:1a4ff2ad-cab1-47bf-9426-4c6d375de318][Manifesto of the Communist Party]] (Marx et al.)[fn:-8-11]
  #+begin_quote
Nothing would be more erroneous than to stamp the whole of the Communist
Manifesto simply as an historic document. On the contrary. The principles
developed by it, the method to which it leads us, the characteristic it gives by
a few strokes of the capitalist mode of production, are to-day more valid than
ever. The whole actual development, as well as the whole theoretic
investigation, of the time since the drawing-up of the Manifesto, are nothing
but an unbroken line of confirmations of its fundamental conceptions. Never was
the principle more universally accepted that the history of all hitherto
existing (civilised) society is the history of class wars; and never has it
appeared plainer that the great moving power of our times is the class war
between bourgeoisie and proletariat.
  #+end_quote
  From [cite:@kautsky-2009-chapt-four]
- [[id:5cr04p00tzj0][Out of Bounds: Academic Freedom and the Question of Palestine]] (Abraham, M.)
- [[id:mwcbjj70h2k0][The Myth of The Rational Voter ]] (Caplan, B.)
- [[id:ptv9ppv0i2k0][Foundations of Christianity]] (Kautsky, K.)[fn:-8-1]
- The Dark Side of Democracy (Mann, M.)
- Global Culture, Globalization and Modernity (Robertson et al.)
- The Road to Unfreedom (Snyder, T.)
- Discourse on Voluntary Servitude (Boétie, E.)[fn:-8-12]
- [[id:iajfgqz0a0k0][Understanding Power: The Indispensable Chomsky]] (Chomsky et al.)
- The Great Revolt (Zito, S.)
- [[id:qqel2kv06ek0][Who Rules the World?]] (Chomsky, N.)
- Who is Charlie, Xenophobia and New Middle Class (Todd, E.)[fn:-8-13]
- The Myth of Development (Oswaldo, R.)[fn:-8-2]
- [[id:mgtarfc142k0][How Much is a Seat On the Security Council Worth?]] (Kuziemko et al.)
- [[id:btij218021k0][Al-nanahaah and al-estehmar ]](Shariati, A.)
- [[id:ohyf4l118bk0][The Israel Lobby and U.S. Foreign Policy]] (Mearsheimer et al.)
- [[id:6ldllxn02ek0][Global Language Dictionary]] (Luntz, F.)
- [[id:k34fhgc07pk0][Civil Society: A Critical Study]] (Beshara, A.)
- في الثورة والقابلية للثورة (بشارة، ع.)
- أشياء لن تسمع بها أبدًا (تشومسكي، ن.)
- معضلة التنمية الإستعمارية: نظرات في دعاوي إيجابيات الاستعمار (صوان، م.)
- مدخل إلى الأيدولوجيات السياسية (هيود، أ.)
- قواعد في الممارسة السياسية (سلطان، ج.) [fn:-8-16]
- */غزو غير مسلح/*[fn:-8-15]
- [[id:0ntcmjp00bk0][Wreckonomics]] (Andersson et al.)
- [[id:0pi55ey00ck0][Punishing The Poor]] (Wacquant, L.)
- [[id:00lij8t0wek0][War in Ukraine]] (Benjamin et al.)
** Propaganda
Are you interested in reading about the propaganda model? Following related
literature is recommended, however, I recommend starting with a small modern
paper: [cite:@Robinson2015]. It examines each filter proposed in the propaganda
model assessing its relevancy and giving modern examples.

- [[id:889d78a9-8707-407b-9be4-e508c45033c3][Manufacturing Consent: The Political Economy of the Mass Media]] (Chomsky et al.)
  [fn:: (NOTE: for a readable PDF version, see [[id:acx9s711gzj0][Better PDF version of
  Manufacuring Consent]]) While it's one of my favorite works ever, I do not
  think that it was best-written. The book is full with examples for propaganda
  promoted mainly by the US-based media (of course the book gave a reasoning for
  that, that's the [[id:c2whd5819zj0][US provides highly accessible information]] systems if compared
  to any other place) instead of forming and answering questions related to the
  propaganda model. It's still highly recommended book for people who are new to
  the real uncovered US politics against enemy states. For further investigation
  about propaganda models, [cite:@pedro-caranana-2018-propag] is recommended
  instead.]
- Media Control: The Spectacular Achievements of Propaganda (Chomsky, N.)[fn::
  This is an oversimplified Manufacturing Consent, however the latter is about
  to be an out-of-date model, see [cite:@pedro-caranana-2018-propag]]
- [[id:8vykhwd0sxj0][The Propaganda Model Today]] (Broudy et al.)
- [[id:4n7cwpf061k0][The Propaganda Model: Still Relevant Today?]] (Robinson, P.)
- [[id:zf7553g0w4k0][Media and The Neoliberal Swindle]] (Freedman, D.)
- [[id:860c1q60efk0][Too Polemical or Too Critical? Chomsky on the Study of the News Media and us Foreign Policy]]
  (Herring, E.)
* Economics/ Capitalism
- Capitalism, Socialism and Democracy (Schumpeter, J. A.)
- [[id:ghu7xl5110k0][History of Economic Thought]] (Hunt et al.)[fn:-10-1]
- [[id:od09z691dck0][Socialism: A Very Short Introduction]] (Newman, M.)
- [[id:xx4bmla1dck0][Understanding Socialism]] (Wolff, R. D.)
- [[id:hrt1cuc184k0][Introduction to Marxist]] Economy (Mandel, E.)
- [[id:c8g5yc70qnk0][Marx's Capital Illustrated]] (Smith, D.)
- [[id:cerhth30spk0][Marxism and Marketing]] (Berger, A.)
* Religion
- [[id:v1z15ff0dak0][al-Sirah al-Nabawiyyah]] (Ibn Hisham, a.)
- [[id:7580q231fxj0][The Origins and Early Development of Shia Islam]] (Ja'fari, S)
- [[id:fu9926j0ryj0][Khilafat o Malukiyat]] (Maududi, A)
- [[id:idb7nm41m4k0][Zaid's Tafsir Ghareeb al-Quran]] (al-Jalali, J.)[fn:-11-2]
- Islam and Science (Hoodbhoy, P.)[fn:-11-1]
- [[id:7m7180u0x5k0][Avesta]] (Abdulrahman, K.)[fn:-11-3]
- [[id:ixegdgm0y5k0][Burahin al-Nubuwwah]] (Amery, S.)
- [[id:850krqe0dak0][Writing Sirah Among Arab Scholars]] (Bziouech, H.)
- [[id:c4x7h6w0hak0][Jadl al-Tanzeel]] (al-Khayyun, R.)
- [[id:lb73s3y0hak0][The debates of the Createdness of the Qur’an]] (Ediwibowo, S.)
- [[id:0e8i3uy0hak0][Freewill, Qadar, and Kasb]] (Salem, F.)
- [[id:j0a4ut50kak0][The Prophet's Life]] (Hussien, T.)
- [[id:4dfjayv0qgk0][Repetition in the Story of Moses and Pharaoh in Holy Quran]] (Ghiyasvand et al.)
- [[id:edniq2g0uhk0][al-Sirah al-Nabawiyyah al-Sahihah]] (al-Umari, A. D.)
- ابن رشد (الجابري، م.)
- مذاهب الإسلاميين (البدوي، ع.)
- الفتنة الكبرى (حسين، ط.)
- محي الدين بن عربي، حياته ومذهبه (بلاتيوس، أ.)
- الوحدة الإسلامية (أبو زهرة، م.)
- الأحوال الشخصية (أبو زهرة، م.)
- من قاموس التراث (العلوي، هـ.)
- الإمام زيد (أبو زهرة، م.)
- أبو حنيفة (أبو زهرة، م.)
- ابن حنبل (أبو زهرة، م.)
- الشافعي (أبو زهرة، م.)
- مالك (أبو زهرة، م.)
- ابن حزم (أبو زهرة، م.)
** Wahhabism
- [[id:50fe1418-f2b8-4dc9-9ef8-1e26c20063a2][Wahhabism and the World Understanding Saudi Arabia's Global Influence on Islam]] (Mandaville, P.)
- Intellectual Life in the Ḥijāz before Wahhabism (al-Abduljabbar, N. A.)
** Other
- مثالب معاوية (المالكي، ف.)[fn:-11-19]
- مثالب معاوية 2 (المالكي، ف.)
- نقد رأي ابن تيمية في إسلام معاوية (المالكي، ف.)
- الإغتيال السياسي في الإسلام (العلوي، ط.)
* History

"There's a good reason why nobody studies history, it just teaches you too much". — Noam Chomsky.

«إنّ التَارْيخَ فيْ ظَاهِرهِ لا يّزْيدُ عَنِ الإِخْبَار، ولَكِنْ فْي بَاطِنهِ نَظَرٌ وتَحْقيق». — إبن خَلْدُون.

«وَتِلْكَ الْأَمْثَالُ نَضْرِبُهَا لِلنَّاسِ وَمَا يَعْقِلُهَا إِلَّا الْعَالِمُونَ».

--------------

- [[id:lnb7vya0b0k0][The Russian Revolution: A Very Short Introduction]] (Smith, S. A.)
- [[id:ii99pw21j2k0][A People History of The World]] (Harman, C.)
- [[id:ae695d0f-04a6-4398-9785-0a4e925d689b][History of The French Revolution]] (Soboul, A.)
- [[id:fe8i4z50v6k0][Forced Secularization in Soviet Russia]] (Froese, P.)
- [[id:9s0ib1u0mqk0][Yugoslavia]] (Chomsky, N.)
** Ancient World
- [[id:45fdc50f-6b08-4555-a1dd-417074349cbd][Our Oriental Heritage]] (Durant et al.)
- [[id:j8ejd9e1t0k0][The First Social Revolution in Ancient Egypt]] (Mahran, M. B.)
- Poems of Heaven and Hell (Sandars, N.)
- The Pyramids Texts (Faulkner, R.)
- A History of the Ancient Near East (Mieroop, M.)
- [[id:x11gcq51b3k0][The Epic of Gilgamesh]] (George, A.)
- تاريخ روسيا (غوميليوف، م.)
- المدن الفينيقية (مهران، م. ب.)
- بنو إسرائيل (مهران، م. ب.)
- المدن الكبرى (مهران، م. ب.)
- تاريخ العراق القديم (مهران، م. ب.)
- دراسات في تاريخ العرب (مهران، م. ب.)
** Middle East/ Ummah
- [[id:108251b9-770b-407e-87a6-c571d88ba4a7][The Arabs: A History]] (Rogan, E.)[fn:-12-1]
- [[id:0msecjc0o2k0][The Egyptian Intelligence Service]] (Sirrs, O. L.)
- [[id:o0359l61b3k0][Engineers of Jihad]] (Gambetta et al.)[fn:-12-17]
- [[id:g9li3l51b3k0][All The Shah Men]] (Kinzer, S.)
- [[id:stcfo7y0fak0][Siyar A'lam al-Nubala]] (al-Dhababi)[fn:-12-2]
- From Beirut to Jerusalem (Friedman, L.)
- Confronting an Empire, Constructing a Nation (Zeine, N.)
- The Unmaking of the Middle East (Salt, J.)
- Islamic Response to Imperialism (Keddie, R.)
- Mapping the Middle East (Antrim, Z.)
- Faisal I of Iraq (Allawi, A.) [fn:-12-18]
- [[id:1ftgx751b3k0][The Ottoman Age of Exploration]] (Casale, G.)
- [[id:m0ch6c51b3k0][Before Taliban: Genealogies of The Afghan Jihad]] (Edwards, D. B.)
- The Balfour Declaration (Schneer, J.)
- Destiny Disrupted (Ansary, T.)
- After the Prophet (Hazleton, L.)
- Blood and Rage (Burleigh, M.)
- America's Kingdom (Vitalis, R.)
- [[id:0504e85e-b33b-46d0-acb7-3ed2c2402ab4][Yemen in Crisis: Road to War]] (Lackner, H)
- [[id:byljkbr0wak0][al-Kamel fi al-Tarikh]] (al-Athir, I.)
 #+begin_quote
فأما فوائدها الدنيوية فمنها ان الإنسان لا يخفي أنه يحب البقاء ويؤثر أن يكون في زمرة
الأحياء فياليت شعري أي فرق بين ما رآه أمس أو سمعه وبين ما قرأه في الكتب المتضمنة أخبار
الماضين وحوادث المتقدمين فإذا طالعها فكأنه عاصرهم وإذا علمها فكأنه حاضرهم. ومنها ما يحصل
للانسان من التجارب والمعرفة بالحوادث وما تصير إليه عواقبها فإنه لا يحدث أمر إلا قد تقدم هو
أو نظيره فيزداد بذلك عقلا ويصبح لأن يفتدى به أهلا. ومنها التخلق بالصبر والتأسي وهما من
محاسن الأخلاق فإن العاقل إذا رأى ان مصاب الدنيا لم يسلم منه نبي مكرم ولا ملك معظم بل ولا
أحد من البشر علم أنه يصيبه ما أصابهم وينوبه ما نابهم.
 #+end_quote
- من داخل الجهادية، فهم الحركات الجهادية (خاور، ف.)
- نحو إعادة بناء قضايا الفكر العربي المعاصر (الجابري، م.)
- المجتمع والدولة في الوطن العربي (سعدالدين، إ.)
- الخروج من زقاق التاريخ (سعد الدين، إ.)
- النظام الاجتماعي العربي الجديد (سعد الدين، إ.)
- تأملات في مسألة الأقليات (سعد الدين، إ.)
- نحن والتراث، قراءة معاصرة في تراثنا الفلسفي (الجابري، م.)
- تكوين العقل العربي (الجابري، م.)
*** Iran
- تاريخ إيران بعد الإسلام (إقبال، ع.) [fn:-12-20]
- إيران من الداخل (هويدي، ف.)
*** Algeria
- الثورة الجزائرية (الزبيري، م.)
- كيف دخل الفرنسيون الجزائر (الجزائري، ا.)
- فرانز فنون والثورة الجزائرية (الميلي، م.)
*** Zionism/ Palestine

- Prelude to Israel: Zionist Diplomacy (Schulze, K.)
- [[id:9xt7hq61b3k0][State of Terror]] (Suarez, Y.)
- Out of the Frame (Pappe, I.)
- The General's Son (Peled, M.)
- On Palestine (Pappe et al.)
- اليد الخفية، دراسة في الحركات اليهودية الهدامة والسرية (المسيري، ع.)
- من هو اليهودي؟ (المسيري، ع.)
- الصراع العربي الإسرائيلي (بريجر، ب.)
*** Other
- الحداثة والإمبريالية: الغزو الفرنسي وإشكالية نهضة مصر (الشلق، أ)
- نجد قبل الوهابية (الجهني، ع)
- حقائق حول أزمة الخليج (الحوالي، س)
** The United States
- [[id:aibkxw51b3k0][A People History of The United States]] (Zinn, H.)
- [[id:rt2d5z51b3k0][Killing Hope]] (Blum, W.)
- Tories: Fighting for the King in America's First Civil War (B. Allen, T)
* Modus Vivendi
- [[id:gnyd0l90n2k0][Les Passions de L'âme]] (Descartes, R.)
- [[id:ba7059m08ok0][Reveries of The Solitary Walker]] (Rousseau, J.)
- [[id:afk10521s2k0][Thus Spoke Zarathustra]] (Nietzsche, F.)
  From [cite:@nietzsche-2009-ecce-homo]:
  #+begin_quote
Among my writings my Zarathustra stands alone. With it I have given humanity the greatest
gift it has ever been given. This book, with a voice that stretches over millennia, is not
only the most exalted book there is, the real book of the mountain air—the entire fact of
man lies at a vast distance beneath it—it is also the most profound book, born of the
innermost richness of the truth, an inexhaustible well into which no bucket descends that
does not come back up ﬁlled with gold and goodness. Here speaks no ‘prophet’, none of
those gruesome hybrids of sickness and will to power* called founders of religions. Above
all you have to hear properly the tone that comes out of this mouth, this halcyon tone, if
you are not to be pitifully unjust towards the meaning of its wisdom. ‘It is the stillest
words that bring on the storm; thoughts that come on doves’ feet direct the world—’
  #+end_quote
- [[id:fmhfkyz0edk0][Ecce Homo]] (Nietzsche, F.)
- [[id:4py58sa0q0k0][The Responsibility of The Intellectual]] (Shariati, A.)
- [[id:lrka8vm0rck0][Back to Self]] (Shariati, A.)
- [[id:6xu1bnz034k0][Majmu'at Rasail al-Imam al-Ghazali]] (al-Ghazali, A.)
- [[id:xxihy72134k0][Fadl al-I'tizal wa Tabqat al-Mu'tazilah]] (al-Balkhi et al.)
- Human, All-Too-Human (Nietzsche, F.)
- [[id:b3q546c1fdk0][Tawq al-Hamamah fi al-Ulfah wa-al-Ullaf]] (Ibn Hazm, A.)
- [[id:kur3wcc1m2k0][Imam Ali in His Three Ordeals]] (Shariati, A.)
- [[id:pgx6knh0e2k0][The Coiled Serpent]] (Vanvliet, C.)[fn:-13-21]
- The Peacock and The Buffalo (Nietzsche, F.)
- [[id:v8fhgn1121k0][Deliverance From Error]] (al-Ghazali, A.)
- [[id:c11a6be3-7f3e-4ff1-983a-19bf81e9fa02][The Dawn of The Day]] (Nietzsche, F.)
- [[id:6ad40bm0nwj0][The Thoughts of Marcus Aurelius]] (Aurelius, M.)
- [[id:3fxhry418xj0][Islam and The Destiny of Man]] (Eaton, G)
- [[id:6y7buw40uwj0][The Polymath]] (Ahmed, W)
- [[id:nxd3q4j0m9k0][Bina' al-Dhat al-Thawriyya]] (Shariati, A.)
- [[id:jz742qa0q9k0][The Cat & The Mouse]] (Al-Amily, B.)
- [[id:356ikhg02ck0][Rehlati al-Fikriah]] (El-Messiri, A.)
- [[id:d7v53d20qck0][Critical Thinking]] (Waller, B. N.)
- [[id:l9qc1dw0nek0][Philosophy of Desire]] (Lenoir, F.)
- [[id:zwz2c6g0wek0][Command-line Finances]] (Dean, C.)
- الأخلاق (شريعتي، ع) [fn:-13-22]
- عن المثقف والثورة (بشارة، ع.)
- مقالة في الحرية (بشارة، ع.)
- [[id:jzydovf0wik0][You're not Listening]] (Murphy, K.)
- [[id:lm7eprh0wik0][Crucial Conversations]] (Patterson et al.)
- [[id:hb8cl140cqk0][Leonardo da Vinci]] (Isaacson, W.)
- [[id:2x1fmp71crk0][What Should We Do?]] (Tolstoy, L.)
- [[id:x81le6x0n4k0]['Uluw al-Himmah]] (al-Muqaddim, I.)
- [[id:dukds27016k0][al-Durrah al-Yateemah]] (al-Muqaffa'a, A.)
- [[id:8q55wd311sk0][al-Athar al-Kamila]] (al-Muqaffa'a, A.)
- [[id:h5a4rjw0i3k0][Ibn Abi al-Dunya Letters]] (al-Dunya, I.)
- [[id:xh13pg01j2k0][Twilight of The Idols]] (Nietzsche, F.)
* Aesthetics

All ancient books which have once been called sacred by man, will have their
lasting place in the history of mankind, and those who possess the courage, the
perseverance, and the self-denial of the true miner, and of the true scholar,
will find even in the darkest and dustiest shafts what they are seeking
for,—real nuggets of thought, and precious jewels of faith and hope.
— Max Müller, Introduction to the Upanishads Vol. II.

- [[id:s2sg0cp0f4k0][Testimony: The Memoirs of Dmitri Shostakovich]] (Volkov, S.)
- Fear of Life (Lowen, A.)
- Letters From a Stoic (Seneca, A.)
- [[id:47o3e41134k0][Kifayat al-Talib fi Manaqib Ali ibn abi-Talib]] (al-Kinji, M.)
- [[id:emkhaqz064k0][Mujm'a al-'amthal]] (Meydani et al.)[fn:-14-2]
- [[id:t2edbr414ak0][Jamharat al-Amthāl]] (al-'Askari, A.)
- [[id:t4dg64l0x6k0][Al-Kashkool]] (Al-Bahai, A)
- ربيع الأبرار في نصوص الأخبار (الزمخشري، ج)
- ديوان ترجمان الأشواق (ابن عربي، م)
- يتيمة الدهر في محاسن أهل العصر (النيسابوري، ع)
- قلائد الجمان في فرائد شعراء هذا الزمان (الموصلي، ك)
- المستجاد من فعلات الأجواد (التنوخي، ا)
- نسمة السحر بذكر من تشيع وشعر (اليمني، ا)
- ريحاينة الألبا وزاهرة الحياة الدنيا (شهاب الدين، أ)
- الموازنة بين أبي تمام والبحتري (الأمدي، أ)
- فوائد الظمئان لدروس الزمان (السلمان، ع)
- التذكرة (الحسيني، ص)
- قول على قول (الكرمي، ح)
- [[id:b543e0c9-8413-41fb-a0c1-8188831f589e][Confucian Analects]] (Legge, J.)
- The Executioner (de Maistre,
# - 88 Precepts (Lane, D)
# - Letters To a Young Poet (Rilke, A)
- Gardens of Renaissance Europe and the Islamic Empires (Reggles, D)
- طبائع الاستبداد ومصارع الاستعباد (الكواكبي، ع)
- +Love Letters of Nathaniel Hawthorne+
- +Culture and Value (Wittgenstein)+
- [[id:9oiaz4a092k0][No Apologies]] (Esolen, A)[fn:-14-1]

** Literature
This section will not be updated anymore.

This section will not be updated anymore

- [2025-06-16 Mon 23:35] Also see this interesting part by [[id:34zfdap0slk0][Kierkegaard on fiction]]:
  #+begin_quote
  What does the soul find so recuperative about reading fairy-tales? When I am tired of everything and ‘full of days’,
  fairy-tales are for me always the refreshing bath that proves so beneficial. There all earthly, all finite cares vanish; joy,
  yes sorrow even, are infinite (which is just why they are so expanding and beneficial). One sets out to find the
  bluebird, just like the princess who, chosen to be queen, lets someone else take care of the kingdom so that she
  herself can seek out her unhappy lover. What infinite sorrow is implied in her saying to the old woman she meets, as
  she roams about dressed as a peasant girl: ‘I am not alone, good mother, I have with me a great following of trouble,
  cares and suffering.’ […]
  #+end_quote
- [2023-10-24 Tue 18:19]  I wrote the sentence above "This section will not be updated anymore" years
  ago, after a discussion with someone that really convinced me that reading
  literature is an absolute waste of time, since it is not possible to extract
  concrete expressive knowledge, at best it might help you at giving parables
  before telling a theory, making you look more eloquent. I also believe that it
  might deeply help in understanding how people might act in some situation,
  literature is human experience after all. What I've understood recently is
  that [[id:4y03zoa1bxj0][entertainment]] is necessary in man's life, no matter how disciplined and
  optimized you are, at some point you will need a rest, whereupon you will be
  interested in an ease and have two options cinema and TV /or/ literature. Here
  you can see where this is going. Sadly, the current state of producing art
  forms it onto a mere proprietor tool used for whatever reasons.  Although
  literature always has been like that [cite:see for example @mccall-2021-money-as],
  but much less if compared to media [cite:@alford-2018-screen-enter].
  One can actually tell that the major reveal of "correctness" was a recent
  change in media. If you are like me, you won't be much interesting in watching
  works from the 30s to avoid that, however, people can easily read works from
  past centuries without a problem. So, this

قال مُخلِد بن حسين (تـ191 هـ) لابن المبارك: "نحنُ إلى كثيرٍ من الأدب أحوَجَ منّا إلى كثيرٍ من
الحديث".

- [[id:kq94aly0jxj0][Ḥayy ibn Yaqẓān]] (Ibn Tufayl et al.)
- [[id:zv7b8b11j2k0][Don Quixote]] (Cervantes, M. d.)
- [[id:c1o0ayi0yrk0][Biyad wa Riyad]] (Arbnikel)
- [[id:o1g4vx50dak0][Rameau's Nephew and First Satire]] (Diderot, D.)
- [[id:mppbrof0r1k0][The Double and The Gambler]] (Dostoevsky, F.)
- [[id:wned02a160k0][The Faerie Queene]] (Spenser, E.)
- [[id:eiseq6b0m0k0][The Bride of Lammermoor]] (Scott, W)
- [[id:z80b389160k0][The Canterbury Tales, and Other Poems]] (Chaucer, G.)
- [[id:69bg8u0134k0][Complete Works of Frans Kafka]] (Kafka, F.)
- [[id:ntgexwn0y9k0][Manfred]] (Byron, L)
- [[id:y897k9d0lak0][The Lover]] (Duras, M.)
- [[id:waa5fah08ek0][Ibn Sina or The Road to Isfahan]] (Sinoue, G.) [fn:-15-2]
- [[id:a3u7c130gek0][Selected Works]] (Chekhov, A.)
- [[id:wmm5i030iek0][Siddhartha]] (Hesse, H.)
- [[id:2fz7p261nkk0][Momo]] (Ende, M.)
- A Streetcar Named Desire (Williams, T)
- [[id:60c1de65-8fde-4300-af26-124bbc984a45][The Kite Runner]] (Khalid, H)
- Lolita (Nabokob, V)
- Suddenly Last Summer (Williams, T)
- [[id:538ejds0uzj0][The Brothers Karamazov]] (Dostoevsky, F)
- Umm Sa'd (Ghassan, K)
- Children of the Alley (Mahfouz, N)
- Cat on a Hot Tin Roof (Williams, T)
- Crime and Punishment (Dostoevsky, F)
- The Idiot (Dostoevsky, F)
- Orpheus Descending (Williams, T)
- Marx in Soho (Zinn, H)
- One Arm and Other Stories (Williams, T)
- The Misunderstanding (Camus)
- Notes from Underground (Dostoevsky, F)
- Crime and Punishment (Dostoevsky, F)
- The Dream of a Ridiculous Man (Dostoevsky, F)
- Chronicle of a Death Foretold (Márquez, G)
- The Unbearable Lightness of Being (Kundera, M)
- Poor Folk (Dostoevsky, F)
- In the Penal Colony (Kafka, F)
- Men in the Sun (Kanafani, G)
- Animal Farm (Orwell, G)
- Karnak Kafe (Mahfouz, N)
- The Insulted and Humiliated (Dostoevsky, F)
- Love in the Time of Cholera (Márquez, G)
- One Hundred Years of Solitude (Márquez, G)
- Adrift on the Nile (Mahfouz, N)
- The Overcoat (Gogol, N)
- The Land of Sad Oranges (Kanafani, G)
- The Bet and Other Stories (Chekhov, A)
- [[id:g7o3v2v090k0][The Death of Ivan Ilyich & Confession]]  (Tolostoy, L)
- The Picture of Dorian Gray (Wilde, O)
- 1984 (Orwell, G)
- The Festival of Insignificance (Kundera, M)
- When Nietzsche Wept (Yalom, I)
- The Death of a Government Clerk (Gogol, N)
- The Silent Patient (Michaelides, A)
- Season of Migration to the North (Salih, A)
- The Inspector General (Gogol, N)
- Oscar And The Lady In Pink (Schmitt, E)
- No One Sleeps in Alexandria (AbdelMeguid, I)
- يوم غائم في البر الغربي (قنديل، م)
- Alexander Pope: Selected Works (Pope, A)
- [[id:74d63dbe-10b6-42f9-b562-ed75b030ca23][Agamemnon]] (Aeschylus, A)
- A Confession (Tolstoy, L)
- [[id:044lps019wj0][Make Something Up]] (Palahniuk, C)
- [[id:jb7i11x06xj0][Fight Club]] (Palahniuk, C.)
- [[id:0697ihs0yzj0][The Antiquary]] (Scott, W.)
- القميص المسروق (كنفاني، غ)
- الزيتون لا يموت (نصر، ع)
- [[id:kdq76by0vck0][Letters from Ansi al-Hajj to Ghada al-Samman]] (al-Haj, A.)
- [[id:je7d7rc0xck0][Letters from Ghassan Kanafani to Ghada al-Samman]] (Kanafani, G.)

Ones I didn't enjoy reading:

- Memories of My Melancholy Whores (Márquez, G.)[fn:-15-1]
- The Metamorphosis
- Hidden Figures
- War and Peace
- Wind, Sand and Stars
- Testaments Betrayed, An Essay in Nine Parts
- A Tale of Two Cities
- The Hunchback of Notre-Dame
- Sundays in August
- الحكايات الشعبية من آسيا
- [[id:18dc9758-c629-434f-85ec-0153cf5eeeda][A Confession]] (Tolstoy, L)

** Heritage
*Note*: the author names in this list are to be fixed, there is a small bug in
the script I use to generate them, and I'm too lazy to check for them by hand.

- [[id:fggh95a1ajk0][Muhadarat al-Udaba]] (Isfahani, A.)
- [[id:fnp5rx61ock0][Nawadir al-Ayk]] (Suyuti, A.)
- المقامات (الزمخشري، ج)
- كتاب الأمالي (القالي، أ)
- فقه القلوب (التويجري، م)
- فضائل الأعمال (المقدسي، ض)
- لباب الأداب (منقذ، أ)
- كتاب المِحن (التميمي، أ)
- روضة العقلاء (حبان، ا)
- تصفية القلوب (الذماري، ي)
- البيان والتبيان (الحاحظ، أ)
- شرح كتاب الشهاب (القضياعي، أ)
- الوابل الطيب (الجوزية، أ)
- العزلة (البستي، م)
- المنازل والديار (منقذ، أ)
- العزلة والانفراد (الدنيا، أ)
- الزهد الكبير (البيهقي)
- الإعتبار (أسامه بن منقذ)
- أحسن ما سمعت (الثعالبي)
- أدب الدين والدنيا (الماوردي، أ)
- الفوائد (الجوزية، ا)
- الفرج بعد الشدة (التنوخي، ع)
- أخبار الظراف ومتماجنين (ابن الجوزي، أ)
- نسمة السحر (الحريري، ب)
- جواهر الحكم (ابن يعلى، ع)
- أنيس المسافر وجليس الخاطر (البحراني، ع)
- روائع الكلم في شرح قصار الحكم (العجلوني، ج)
- تحف العقول عن آل الرسول (التستري، ع)
- مِصباحُ المُتَهجِّد وسلاحُ المُتَعَبّد (الزركشي، م)
- عيون الأخبار (ابن قتيبة، ع)
- سمط الآلي (العقاد، ع)
- زهرة الأكم (الحريري، ب)
- بهجة المجالس (ابن حجر، أ)
- الموازنة بين أبي تمام والبحترى (السمرقندي، ع)
- بين الثقافة والسياسة (العتيبي، ط)
- العقد الفريد (الأصفهاني، ع)
- التذكرة الحمدونية (القرطبي، ا)
- المستطرف في كل فن مستظرف (الغزالي، ا)
- إحياء علوم الدين (الغزالي، ا)
- مدارج السالكين (ابن القيم، ا)
- الإمتاع والمؤانسة (التوحيدي، م)
- النساء في لوحات المستشرقين (الباز، ل)
- اتحاف النبلاء بأخبار الثقلاء (الحراني، ع)
- ألف باء في أنواع الآداب (الجاحظ، ع)
** Poetry
- [[id:hjnk8t4160k0][The Norton Anthology of Poetry]] (Ferguson et al.)
- [[id:x3027m41x2k0][Abuzun al-Omani's Poetry]] (al-Omani, A.)
- [[id:0c5gqav0e4k0][Hamasah]] (Tamam, H.)
- [[id:1qfh0oa0k5k0][al-Tibyan fi Sharh al-Diwan]] (al-Akbari, A.)
- [[id:yw9dphj0tgk0][al-Mutanabbi]] (Shakir, M. M.)
- [[id:vlng7aa0omk0][Nietzsche's Poetry]] (Nietzsche, F.)
- [[id:zox83l50yrk0][Mahmoud Sami al-Barudi]] (al-Barudi, M. S.)
*** hide                                                              :noexport:
- [[id:d045cf59-16a3-46de-8eb8-cc04f6312cce][تأبط شرًا]]
- [[id:ade2f549-9762-48d5-a0b7-2c58fbb15dc9][أبو تمام]]
- [[id:743e68eb-cb88-418b-9833-85f0bf9ac87d][الشريف المرتضى]]

* Chess

- [[id:69af51e3-318f-4055-867c-7f6b8eba39c5][Play Winning Chess]] (Seirawan, W)[fn:-18-1]
- A First Book of Morphy (Lawson, D)
- Chess Openings for Dummies (Eade, J)
- 7 Deadly Chess Sins (Rowson, J)
- Improve Your Chess Pattern Recognition (Oudeweetering, A)
- The Soviet Chess Primer (Maizelis, I)
- Logical Chess: Move by Move (Chernev, I)

* Current                                                             :noexport:
Reading:
- [[id:2cj25u00sxj0][Invisible Var: The US and The Iraq Sanctions]] (Gordon, J)
- [[id:kq94aly0jxj0][Ḥayy ibn Yaqẓān]] (Zidan, Y)
- [[id:6ad40bm0nwj0][The Thoughts of Marcus Aurelius]] (Aurelius, M.)
- [[id:jb7i11x06xj0][Fight Club]] (Palahniuk, C.)
- [[id:044lps019wj0][Make Something Up]] (Palahniuk, C.)
- [[id:45fdc50f-6b08-4555-a1dd-417074349cbd][Our Oriental Heritage]] (Durant, W.)
- [[id:ae695d0f-04a6-4398-9785-0a4e925d689b][History of The French Revolution]] (Soboul, A.)
- [[id:aa974737-5070-4652-985d-2a7a2ad198e9][History of the Western Philosophy and Theologyy]] (Frame, J. M.)
- [[id:1f939ce6-6cba-43b6-a19b-4b78890be45b][The Open Society and its Enemies]] (Popper, K. R.)
- [[id:3fxhry418xj0][Islam and The Destiny of Man]] (Eaton, G)
- [[id:6y7buw40uwj0][The Polymath]] (Ahmed, W)
* Other
- [[id:w083zt618xj0][The Subtle Art of Not Giving a F*ck]] (Manson, M.).
- [[id:t8w6y3j0dxj0][Why is it so hard to do my work?]] (Leroy, S.)
- [[id:2qv2wq71yxj0][Ubersleep: Nap-based Sleep Schedules and the Polyphasic Lifestyle]] (Doxyk, P)
- [[id:4fih09l0f4k0][Qusr al-Kalam]] (Amer, G.)
- [[id:b20c7yy026k0][Discipline is Destiny]] (Holiday, R.)
* wt                                                                  :noexport:
[fn:7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".

[fn:6]   I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.
[fn:5]   It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:4]   Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.

[fn:3]  A prelude of the human history from the 'civilization' perspective, a
  deep-rooted academic corresponding would be Will Durant's first chapter of
  "The Full Story of Civilization", Our Oriental Heritage. Russel's book is good
  for having a good time with a book “The time
 

[fn:2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].

# [fn:1] Not a bad book after all, it sounds like neo-Nazis are one of the rare
#   denomination that preserved some فِطرة and genuine values. Some of the quotes I
#   liked:

# Unfounded belief is pitfall. A People who do not check the validity and effect
# of their beliefs with reason will suffer or perish.

# In a democracy those who control the media, and thus the minds of the
# electorate, have power undreamed by kings or dictators.

# Propaganda is major component in all power systems, both secular and religious;
# false propaganda is a major component of unprincipled power systems. All power
# systems endeavor to convince their subjects that the system is good, just,
# beneficent and noble, as well as worthy of perpetuation and defense. The more
# jingoistic propaganda issued, the more suspicious one should be of its truth.

# There exists no such thing as rights or privileges under the Laws of Nature. The
# deer being stalked by a hungry lion has no right to life. However, he may
# purchase life by obedience to nature ordained instincts for vigilance and
# flight. Similarly, men have no rights to life, liberty or happiness. These
# circumstances may be purchased by oneself, by ones family, by ones tribe or by
# ones ancestors, but they are nonetheless purchases and are not rights.
# Furthermore, the value of these purchases can only be maintained through
# vigilance and obedience to Natural Law.

# Tyrannies teach what to think; free men learn how to think.

# Sexual pornography degrades the Nature of all who are involved. A beautiful nude
# woman is art; a camera between her knees to explore her private parts is
# pornography. [I think he meant by pornography at the end as pornography in its
# root Grecian meaning (dirt)]

* References
#+print_bibliography:

* Footnotes
[fn:8] As of [2024-11-15 Fri 09:15] this section no longer exists.
[fn:1] If the link is somehow broken, please search for "Noam Chomsky University of Arizona
on Feb. 8, 2012" or by the title of the lecture: "Noam Chomsky: Education For
Whom and For What".

[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-7-1] I've many special memories with this book < 3.


[fn:-7-11] This was one of my most enjoyable classes ever, however, that's all what
I can recall about it (as of [2025-04-01 Tue 00:13]), I forgot most of the
course material.. it will be very nice if I could interact with this subject
again someday in a master class.


[fn:-7-12] [2025-09-16 Tue 00:23] I'm reading this along with doing https://codingchallenges.fyi/challenges/challenge-webserver/


[fn:-7-8] I really recommend Shaffer's book, however, this one contained additional
algorithms that were not included in the former.


[fn:-7-7] Do not confuse for computer code. See: https://en.wikipedia.org/w/index.php?title=Code&oldid=1194309533


[fn:-7-2] I'm not into game programming, but it was very fun to read this book.


[fn:-7-10] I'm not reading this, just using it as a reference book.


[fn:-7-6] For a better PDF version of this great book, please +find this link+
contact me.


[fn:-7-9] [2024-02-04 Sun 06:35]: funny enough that I didn't complete this book
either and left it for Renzo Borgatti's, I think it's great learning recoruce though.


[fn:-7-3] I also read Seibel's Practical Common Lisp, this is my book of choice for
people who want to get into Lisp.


[fn:-7-4] I unlearned it later.


[fn:-7-5] Enjoyable work.


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-7-1] I've many special memories with this book < 3.


[fn:-7-11] This was one of my most enjoyable classes ever, however, that's all what
I can recall about it (as of [2025-04-01 Tue 00:13]), I forgot most of the
course material.. it will be very nice if I could interact with this subject
again someday in a master class.


[fn:-7-12] [2025-09-16 Tue 00:23] I'm reading this along with doing https://codingchallenges.fyi/challenges/challenge-webserver/


[fn:-7-8] I really recommend Shaffer's book, however, this one contained additional
algorithms that were not included in the former.


[fn:-7-7] Do not confuse for computer code. See: https://en.wikipedia.org/w/index.php?title=Code&oldid=1194309533


[fn:-7-2] I'm not into game programming, but it was very fun to read this book.


[fn:-7-10] I'm not reading this, just using it as a reference book.


[fn:-7-6] For a better PDF version of this great book, please +find this link+
contact me.


[fn:-7-9] [2024-02-04 Sun 06:35]: funny enough that I didn't complete this book
either and left it for Renzo Borgatti's, I think it's great learning recoruce though.


[fn:-7-3] I also read Seibel's Practical Common Lisp, this is my book of choice for
people who want to get into Lisp.


[fn:-7-4] I unlearned it later.


[fn:-7-5] Enjoyable work.


[fn:-8-11] I won't usually recommend reading this, but I want to make sure that
everyone will read it, even if you are not going to study Marxism, reading the
Manifesto at least is أضعف الإيمان to prevent yourself from the odds and the
ends of the anti-bolshevism propaganda (which usually includes "Marxism"). A
better alternative would be Nikoalai Bukharin's "ABC of Communism", or even
better, read Marx carefully.


[fn:-8-1] Also known as: religion and class struggle


[fn:-8-12] I consider this as a very nice literary message, actually it reminds
me of how the intellectual treated "crowds" in the early 19 and 20 centuries,
read about this here [DELETED]. Simply, like Le Bon and Frizer did in there
psychology and anthropology papers, Étienne de La Boétie is cursing the scum
peoples who let tyrant governors control and torture them. Of course without
giving any explanation on why they do so. It's very obsolete to take it as an
'intellectual' or 'anthropological' approach.


[fn:-8-13] This books is about the laïcité (the f*ricnh secularism) and how the
xenophobia works as very good engine for moving the French people towards more
and more so-called 'free speech' movements. A very important and related book is
Jean Baubérot's La laïcité Française et ses Mutations.


[fn:-8-2] أوهَمَ رأس المال الناس أنّ الدُّول "المتقدِّمة" هي كذلك بفعل خفض الإنفاق
العمومي. ولكن الإنفاق العمومي، مقارنة بالناتِج القومي، لم ينخفِض إلاّ لدى الدُّول
الفقيرة، وبالذّات بإكراهات من الدُّول "المتقدِّمة". (عباس برهام)


[fn:-8-16] Both of these books are good reads for kids.


[fn:-8-15] I don't know who authored this book/article; however it is not
available for some reason on the internet and I can't even remember where did I
download it from, anyway I've reuploaded it; you can get it from /(link is
broken)/.


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-7-1] I've many special memories with this book < 3.


[fn:-7-11] This was one of my most enjoyable classes ever, however, that's all what
I can recall about it (as of [2025-04-01 Tue 00:13]), I forgot most of the
course material.. it will be very nice if I could interact with this subject
again someday in a master class.


[fn:-7-12] [2025-09-16 Tue 00:23] I'm reading this along with doing https://codingchallenges.fyi/challenges/challenge-webserver/


[fn:-7-8] I really recommend Shaffer's book, however, this one contained additional
algorithms that were not included in the former.


[fn:-7-7] Do not confuse for computer code. See: https://en.wikipedia.org/w/index.php?title=Code&oldid=1194309533


[fn:-7-2] I'm not into game programming, but it was very fun to read this book.


[fn:-7-10] I'm not reading this, just using it as a reference book.


[fn:-7-6] For a better PDF version of this great book, please +find this link+
contact me.


[fn:-7-9] [2024-02-04 Sun 06:35]: funny enough that I didn't complete this book
either and left it for Renzo Borgatti's, I think it's great learning recoruce though.


[fn:-7-3] I also read Seibel's Practical Common Lisp, this is my book of choice for
people who want to get into Lisp.


[fn:-7-4] I unlearned it later.


[fn:-7-5] Enjoyable work.


[fn:-8-11] I won't usually recommend reading this, but I want to make sure that
everyone will read it, even if you are not going to study Marxism, reading the
Manifesto at least is أضعف الإيمان to prevent yourself from the odds and the
ends of the anti-bolshevism propaganda (which usually includes "Marxism"). A
better alternative would be Nikoalai Bukharin's "ABC of Communism", or even
better, read Marx carefully.


[fn:-8-1] Also known as: religion and class struggle


[fn:-8-12] I consider this as a very nice literary message, actually it reminds
me of how the intellectual treated "crowds" in the early 19 and 20 centuries,
read about this here [DELETED]. Simply, like Le Bon and Frizer did in there
psychology and anthropology papers, Étienne de La Boétie is cursing the scum
peoples who let tyrant governors control and torture them. Of course without
giving any explanation on why they do so. It's very obsolete to take it as an
'intellectual' or 'anthropological' approach.


[fn:-8-13] This books is about the laïcité (the f*ricnh secularism) and how the
xenophobia works as very good engine for moving the French people towards more
and more so-called 'free speech' movements. A very important and related book is
Jean Baubérot's La laïcité Française et ses Mutations.


[fn:-8-2] أوهَمَ رأس المال الناس أنّ الدُّول "المتقدِّمة" هي كذلك بفعل خفض الإنفاق
العمومي. ولكن الإنفاق العمومي، مقارنة بالناتِج القومي، لم ينخفِض إلاّ لدى الدُّول
الفقيرة، وبالذّات بإكراهات من الدُّول "المتقدِّمة". (عباس برهام)


[fn:-8-16] Both of these books are good reads for kids.


[fn:-8-15] I don't know who authored this book/article; however it is not
available for some reason on the internet and I can't even remember where did I
download it from, anyway I've reuploaded it; you can get it from /(link is
broken)/.


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-7-1] I've many special memories with this book < 3.


[fn:-7-11] This was one of my most enjoyable classes ever, however, that's all what
I can recall about it (as of [2025-04-01 Tue 00:13]), I forgot most of the
course material.. it will be very nice if I could interact with this subject
again someday in a master class.


[fn:-7-12] [2025-09-16 Tue 00:23] I'm reading this along with doing https://codingchallenges.fyi/challenges/challenge-webserver/


[fn:-7-8] I really recommend Shaffer's book, however, this one contained additional
algorithms that were not included in the former.


[fn:-7-7] Do not confuse for computer code. See: https://en.wikipedia.org/w/index.php?title=Code&oldid=1194309533


[fn:-7-2] I'm not into game programming, but it was very fun to read this book.


[fn:-7-10] I'm not reading this, just using it as a reference book.


[fn:-7-6] For a better PDF version of this great book, please +find this link+
contact me.


[fn:-7-9] [2024-02-04 Sun 06:35]: funny enough that I didn't complete this book
either and left it for Renzo Borgatti's, I think it's great learning recoruce though.


[fn:-7-3] I also read Seibel's Practical Common Lisp, this is my book of choice for
people who want to get into Lisp.


[fn:-7-4] I unlearned it later.


[fn:-7-5] Enjoyable work.


[fn:-8-11] I won't usually recommend reading this, but I want to make sure that
everyone will read it, even if you are not going to study Marxism, reading the
Manifesto at least is أضعف الإيمان to prevent yourself from the odds and the
ends of the anti-bolshevism propaganda (which usually includes "Marxism"). A
better alternative would be Nikoalai Bukharin's "ABC of Communism", or even
better, read Marx carefully.


[fn:-8-1] Also known as: religion and class struggle


[fn:-8-12] I consider this as a very nice literary message, actually it reminds
me of how the intellectual treated "crowds" in the early 19 and 20 centuries,
read about this here [DELETED]. Simply, like Le Bon and Frizer did in there
psychology and anthropology papers, Étienne de La Boétie is cursing the scum
peoples who let tyrant governors control and torture them. Of course without
giving any explanation on why they do so. It's very obsolete to take it as an
'intellectual' or 'anthropological' approach.


[fn:-8-13] This books is about the laïcité (the f*ricnh secularism) and how the
xenophobia works as very good engine for moving the French people towards more
and more so-called 'free speech' movements. A very important and related book is
Jean Baubérot's La laïcité Française et ses Mutations.


[fn:-8-2] أوهَمَ رأس المال الناس أنّ الدُّول "المتقدِّمة" هي كذلك بفعل خفض الإنفاق
العمومي. ولكن الإنفاق العمومي، مقارنة بالناتِج القومي، لم ينخفِض إلاّ لدى الدُّول
الفقيرة، وبالذّات بإكراهات من الدُّول "المتقدِّمة". (عباس برهام)


[fn:-8-16] Both of these books are good reads for kids.


[fn:-8-15] I don't know who authored this book/article; however it is not
available for some reason on the internet and I can't even remember where did I
download it from, anyway I've reuploaded it; you can get it from /(link is
broken)/.


[fn:-10-1] Also check Dr Anwar's: [[https://www.youtube.com/playlist?list=PLTMFx0t8kDzc72vtNWeTP05x6WYiDgEx7][Anwar Shaikh: Historical Foundations of Political Economy]]


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-7-1] I've many special memories with this book < 3.


[fn:-7-11] This was one of my most enjoyable classes ever, however, that's all what
I can recall about it (as of [2025-04-01 Tue 00:13]), I forgot most of the
course material.. it will be very nice if I could interact with this subject
again someday in a master class.


[fn:-7-12] [2025-09-16 Tue 00:23] I'm reading this along with doing https://codingchallenges.fyi/challenges/challenge-webserver/


[fn:-7-8] I really recommend Shaffer's book, however, this one contained additional
algorithms that were not included in the former.


[fn:-7-7] Do not confuse for computer code. See: https://en.wikipedia.org/w/index.php?title=Code&oldid=1194309533


[fn:-7-2] I'm not into game programming, but it was very fun to read this book.


[fn:-7-10] I'm not reading this, just using it as a reference book.


[fn:-7-6] For a better PDF version of this great book, please +find this link+
contact me.


[fn:-7-9] [2024-02-04 Sun 06:35]: funny enough that I didn't complete this book
either and left it for Renzo Borgatti's, I think it's great learning recoruce though.


[fn:-7-3] I also read Seibel's Practical Common Lisp, this is my book of choice for
people who want to get into Lisp.


[fn:-7-4] I unlearned it later.


[fn:-7-5] Enjoyable work.


[fn:-8-11] I won't usually recommend reading this, but I want to make sure that
everyone will read it, even if you are not going to study Marxism, reading the
Manifesto at least is أضعف الإيمان to prevent yourself from the odds and the
ends of the anti-bolshevism propaganda (which usually includes "Marxism"). A
better alternative would be Nikoalai Bukharin's "ABC of Communism", or even
better, read Marx carefully.


[fn:-8-1] Also known as: religion and class struggle


[fn:-8-12] I consider this as a very nice literary message, actually it reminds
me of how the intellectual treated "crowds" in the early 19 and 20 centuries,
read about this here [DELETED]. Simply, like Le Bon and Frizer did in there
psychology and anthropology papers, Étienne de La Boétie is cursing the scum
peoples who let tyrant governors control and torture them. Of course without
giving any explanation on why they do so. It's very obsolete to take it as an
'intellectual' or 'anthropological' approach.


[fn:-8-13] This books is about the laïcité (the f*ricnh secularism) and how the
xenophobia works as very good engine for moving the French people towards more
and more so-called 'free speech' movements. A very important and related book is
Jean Baubérot's La laïcité Française et ses Mutations.


[fn:-8-2] أوهَمَ رأس المال الناس أنّ الدُّول "المتقدِّمة" هي كذلك بفعل خفض الإنفاق
العمومي. ولكن الإنفاق العمومي، مقارنة بالناتِج القومي، لم ينخفِض إلاّ لدى الدُّول
الفقيرة، وبالذّات بإكراهات من الدُّول "المتقدِّمة". (عباس برهام)


[fn:-8-16] Both of these books are good reads for kids.


[fn:-8-15] I don't know who authored this book/article; however it is not
available for some reason on the internet and I can't even remember where did I
download it from, anyway I've reuploaded it; you can get it from /(link is
broken)/.


[fn:-10-1] Also check Dr Anwar's: [[https://www.youtube.com/playlist?list=PLTMFx0t8kDzc72vtNWeTP05x6WYiDgEx7][Anwar Shaikh: Historical Foundations of Political Economy]]


[fn:-11-2] whoever attributed this to Zaid, they did not spend enough time writing
it.


[fn:-11-1] Check my (very old unrevised) review: [[id:c1c6b159-608c-4db1-9c55-88f33883f079][Pervez Hoodbhoy's Islam and Science]].


[fn:-11-3] Dr. Abdulrahman Khalil's introduction is extremely interesting. Avesta is
very interesting to read as well, however, the current version is filled with
paganism. It's hard for a plain reader like me to filter all it to reach for
some wisdom, but I might do it someday.


[fn:-11-19] Poorly written book, nothing new or special in the study, the author
tends to have an evident ignorance on Takhrij al-hadith.


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-7-1] I've many special memories with this book < 3.


[fn:-7-11] This was one of my most enjoyable classes ever, however, that's all what
I can recall about it (as of [2025-04-01 Tue 00:13]), I forgot most of the
course material.. it will be very nice if I could interact with this subject
again someday in a master class.


[fn:-7-12] [2025-09-16 Tue 00:23] I'm reading this along with doing https://codingchallenges.fyi/challenges/challenge-webserver/


[fn:-7-8] I really recommend Shaffer's book, however, this one contained additional
algorithms that were not included in the former.


[fn:-7-7] Do not confuse for computer code. See: https://en.wikipedia.org/w/index.php?title=Code&oldid=1194309533


[fn:-7-2] I'm not into game programming, but it was very fun to read this book.


[fn:-7-10] I'm not reading this, just using it as a reference book.


[fn:-7-6] For a better PDF version of this great book, please +find this link+
contact me.


[fn:-7-9] [2024-02-04 Sun 06:35]: funny enough that I didn't complete this book
either and left it for Renzo Borgatti's, I think it's great learning recoruce though.


[fn:-7-3] I also read Seibel's Practical Common Lisp, this is my book of choice for
people who want to get into Lisp.


[fn:-7-4] I unlearned it later.


[fn:-7-5] Enjoyable work.


[fn:-8-11] I won't usually recommend reading this, but I want to make sure that
everyone will read it, even if you are not going to study Marxism, reading the
Manifesto at least is أضعف الإيمان to prevent yourself from the odds and the
ends of the anti-bolshevism propaganda (which usually includes "Marxism"). A
better alternative would be Nikoalai Bukharin's "ABC of Communism", or even
better, read Marx carefully.


[fn:-8-1] Also known as: religion and class struggle


[fn:-8-12] I consider this as a very nice literary message, actually it reminds
me of how the intellectual treated "crowds" in the early 19 and 20 centuries,
read about this here [DELETED]. Simply, like Le Bon and Frizer did in there
psychology and anthropology papers, Étienne de La Boétie is cursing the scum
peoples who let tyrant governors control and torture them. Of course without
giving any explanation on why they do so. It's very obsolete to take it as an
'intellectual' or 'anthropological' approach.


[fn:-8-13] This books is about the laïcité (the f*ricnh secularism) and how the
xenophobia works as very good engine for moving the French people towards more
and more so-called 'free speech' movements. A very important and related book is
Jean Baubérot's La laïcité Française et ses Mutations.


[fn:-8-2] أوهَمَ رأس المال الناس أنّ الدُّول "المتقدِّمة" هي كذلك بفعل خفض الإنفاق
العمومي. ولكن الإنفاق العمومي، مقارنة بالناتِج القومي، لم ينخفِض إلاّ لدى الدُّول
الفقيرة، وبالذّات بإكراهات من الدُّول "المتقدِّمة". (عباس برهام)


[fn:-8-16] Both of these books are good reads for kids.


[fn:-8-15] I don't know who authored this book/article; however it is not
available for some reason on the internet and I can't even remember where did I
download it from, anyway I've reuploaded it; you can get it from /(link is
broken)/.


[fn:-10-1] Also check Dr Anwar's: [[https://www.youtube.com/playlist?list=PLTMFx0t8kDzc72vtNWeTP05x6WYiDgEx7][Anwar Shaikh: Historical Foundations of Political Economy]]


[fn:-11-2] whoever attributed this to Zaid, they did not spend enough time writing
it.


[fn:-11-1] Check my (very old unrevised) review: [[id:c1c6b159-608c-4db1-9c55-88f33883f079][Pervez Hoodbhoy's Islam and Science]].


[fn:-11-3] Dr. Abdulrahman Khalil's introduction is extremely interesting. Avesta is
very interesting to read as well, however, the current version is filled with
paganism. It's hard for a plain reader like me to filter all it to reach for
some wisdom, but I might do it someday.


[fn:-11-19] Poorly written book, nothing new or special in the study, the author
tends to have an evident ignorance on Takhrij al-hadith.


[fn:-12-1] Very good book. I recommend it as a good start for anybody who wants to
understand how we got "the middle east".


[fn:-12-17] An important research to understand the uprising of Jihad movements between
  pan-Arabists, ex pan-Arabists in general, and between engineers and the middle
  class in particular. I think it's even a good introduction to answer the
  question of why Muslims might bomb themselves. It's one of the greatest books
  I've ever read about the armed Jihad.


[fn:-12-2] I only used it to read the first two volumes about Sirah.


[fn:-12-18] If there is only one book that is neutral in the history of The Middle East,
  it would be this book. I recommend it for everyone needs to understand how we
  winded up with the 2000s pitiful middle east. Note that the books is
  oversimplified in the post-caliphate era.


[fn:-12-20] Too much informative, in the sense that it doesn't really provide a historical
  context rather than historical information. I will consider searching for
  another book on the early history of Iran soon.


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-7-1] I've many special memories with this book < 3.


[fn:-7-11] This was one of my most enjoyable classes ever, however, that's all what
I can recall about it (as of [2025-04-01 Tue 00:13]), I forgot most of the
course material.. it will be very nice if I could interact with this subject
again someday in a master class.


[fn:-7-12] [2025-09-16 Tue 00:23] I'm reading this along with doing https://codingchallenges.fyi/challenges/challenge-webserver/


[fn:-7-8] I really recommend Shaffer's book, however, this one contained additional
algorithms that were not included in the former.


[fn:-7-7] Do not confuse for computer code. See: https://en.wikipedia.org/w/index.php?title=Code&oldid=1194309533


[fn:-7-2] I'm not into game programming, but it was very fun to read this book.


[fn:-7-10] I'm not reading this, just using it as a reference book.


[fn:-7-6] For a better PDF version of this great book, please +find this link+
contact me.


[fn:-7-9] [2024-02-04 Sun 06:35]: funny enough that I didn't complete this book
either and left it for Renzo Borgatti's, I think it's great learning recoruce though.


[fn:-7-3] I also read Seibel's Practical Common Lisp, this is my book of choice for
people who want to get into Lisp.


[fn:-7-4] I unlearned it later.


[fn:-7-5] Enjoyable work.


[fn:-8-11] I won't usually recommend reading this, but I want to make sure that
everyone will read it, even if you are not going to study Marxism, reading the
Manifesto at least is أضعف الإيمان to prevent yourself from the odds and the
ends of the anti-bolshevism propaganda (which usually includes "Marxism"). A
better alternative would be Nikoalai Bukharin's "ABC of Communism", or even
better, read Marx carefully.


[fn:-8-1] Also known as: religion and class struggle


[fn:-8-12] I consider this as a very nice literary message, actually it reminds
me of how the intellectual treated "crowds" in the early 19 and 20 centuries,
read about this here [DELETED]. Simply, like Le Bon and Frizer did in there
psychology and anthropology papers, Étienne de La Boétie is cursing the scum
peoples who let tyrant governors control and torture them. Of course without
giving any explanation on why they do so. It's very obsolete to take it as an
'intellectual' or 'anthropological' approach.


[fn:-8-13] This books is about the laïcité (the f*ricnh secularism) and how the
xenophobia works as very good engine for moving the French people towards more
and more so-called 'free speech' movements. A very important and related book is
Jean Baubérot's La laïcité Française et ses Mutations.


[fn:-8-2] أوهَمَ رأس المال الناس أنّ الدُّول "المتقدِّمة" هي كذلك بفعل خفض الإنفاق
العمومي. ولكن الإنفاق العمومي، مقارنة بالناتِج القومي، لم ينخفِض إلاّ لدى الدُّول
الفقيرة، وبالذّات بإكراهات من الدُّول "المتقدِّمة". (عباس برهام)


[fn:-8-16] Both of these books are good reads for kids.


[fn:-8-15] I don't know who authored this book/article; however it is not
available for some reason on the internet and I can't even remember where did I
download it from, anyway I've reuploaded it; you can get it from /(link is
broken)/.


[fn:-10-1] Also check Dr Anwar's: [[https://www.youtube.com/playlist?list=PLTMFx0t8kDzc72vtNWeTP05x6WYiDgEx7][Anwar Shaikh: Historical Foundations of Political Economy]]


[fn:-11-2] whoever attributed this to Zaid, they did not spend enough time writing
it.


[fn:-11-1] Check my (very old unrevised) review: [[id:c1c6b159-608c-4db1-9c55-88f33883f079][Pervez Hoodbhoy's Islam and Science]].


[fn:-11-3] Dr. Abdulrahman Khalil's introduction is extremely interesting. Avesta is
very interesting to read as well, however, the current version is filled with
paganism. It's hard for a plain reader like me to filter all it to reach for
some wisdom, but I might do it someday.


[fn:-11-19] Poorly written book, nothing new or special in the study, the author
tends to have an evident ignorance on Takhrij al-hadith.


[fn:-12-1] Very good book. I recommend it as a good start for anybody who wants to
understand how we got "the middle east".


[fn:-12-17] An important research to understand the uprising of Jihad movements between
  pan-Arabists, ex pan-Arabists in general, and between engineers and the middle
  class in particular. I think it's even a good introduction to answer the
  question of why Muslims might bomb themselves. It's one of the greatest books
  I've ever read about the armed Jihad.


[fn:-12-2] I only used it to read the first two volumes about Sirah.


[fn:-12-18] If there is only one book that is neutral in the history of The Middle East,
  it would be this book. I recommend it for everyone needs to understand how we
  winded up with the 2000s pitiful middle east. Note that the books is
  oversimplified in the post-caliphate era.


[fn:-12-20] Too much informative, in the sense that it doesn't really provide a historical
  context rather than historical information. I will consider searching for
  another book on the early history of Iran soon.


[fn:-13-21] This was very beautiful, I need to reread it multiple times in the future.


[fn:-13-22] If I were to raise someone one day, I'd definitely use this book.


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-7-1] I've many special memories with this book < 3.


[fn:-7-11] This was one of my most enjoyable classes ever, however, that's all what
I can recall about it (as of [2025-04-01 Tue 00:13]), I forgot most of the
course material.. it will be very nice if I could interact with this subject
again someday in a master class.


[fn:-7-12] [2025-09-16 Tue 00:23] I'm reading this along with doing https://codingchallenges.fyi/challenges/challenge-webserver/


[fn:-7-8] I really recommend Shaffer's book, however, this one contained additional
algorithms that were not included in the former.


[fn:-7-7] Do not confuse for computer code. See: https://en.wikipedia.org/w/index.php?title=Code&oldid=1194309533


[fn:-7-2] I'm not into game programming, but it was very fun to read this book.


[fn:-7-10] I'm not reading this, just using it as a reference book.


[fn:-7-6] For a better PDF version of this great book, please +find this link+
contact me.


[fn:-7-9] [2024-02-04 Sun 06:35]: funny enough that I didn't complete this book
either and left it for Renzo Borgatti's, I think it's great learning recoruce though.


[fn:-7-3] I also read Seibel's Practical Common Lisp, this is my book of choice for
people who want to get into Lisp.


[fn:-7-4] I unlearned it later.


[fn:-7-5] Enjoyable work.


[fn:-8-11] I won't usually recommend reading this, but I want to make sure that
everyone will read it, even if you are not going to study Marxism, reading the
Manifesto at least is أضعف الإيمان to prevent yourself from the odds and the
ends of the anti-bolshevism propaganda (which usually includes "Marxism"). A
better alternative would be Nikoalai Bukharin's "ABC of Communism", or even
better, read Marx carefully.


[fn:-8-1] Also known as: religion and class struggle


[fn:-8-12] I consider this as a very nice literary message, actually it reminds
me of how the intellectual treated "crowds" in the early 19 and 20 centuries,
read about this here [DELETED]. Simply, like Le Bon and Frizer did in there
psychology and anthropology papers, Étienne de La Boétie is cursing the scum
peoples who let tyrant governors control and torture them. Of course without
giving any explanation on why they do so. It's very obsolete to take it as an
'intellectual' or 'anthropological' approach.


[fn:-8-13] This books is about the laïcité (the f*ricnh secularism) and how the
xenophobia works as very good engine for moving the French people towards more
and more so-called 'free speech' movements. A very important and related book is
Jean Baubérot's La laïcité Française et ses Mutations.


[fn:-8-2] أوهَمَ رأس المال الناس أنّ الدُّول "المتقدِّمة" هي كذلك بفعل خفض الإنفاق
العمومي. ولكن الإنفاق العمومي، مقارنة بالناتِج القومي، لم ينخفِض إلاّ لدى الدُّول
الفقيرة، وبالذّات بإكراهات من الدُّول "المتقدِّمة". (عباس برهام)


[fn:-8-16] Both of these books are good reads for kids.


[fn:-8-15] I don't know who authored this book/article; however it is not
available for some reason on the internet and I can't even remember where did I
download it from, anyway I've reuploaded it; you can get it from /(link is
broken)/.


[fn:-10-1] Also check Dr Anwar's: [[https://www.youtube.com/playlist?list=PLTMFx0t8kDzc72vtNWeTP05x6WYiDgEx7][Anwar Shaikh: Historical Foundations of Political Economy]]


[fn:-11-2] whoever attributed this to Zaid, they did not spend enough time writing
it.


[fn:-11-1] Check my (very old unrevised) review: [[id:c1c6b159-608c-4db1-9c55-88f33883f079][Pervez Hoodbhoy's Islam and Science]].


[fn:-11-3] Dr. Abdulrahman Khalil's introduction is extremely interesting. Avesta is
very interesting to read as well, however, the current version is filled with
paganism. It's hard for a plain reader like me to filter all it to reach for
some wisdom, but I might do it someday.


[fn:-11-19] Poorly written book, nothing new or special in the study, the author
tends to have an evident ignorance on Takhrij al-hadith.


[fn:-12-1] Very good book. I recommend it as a good start for anybody who wants to
understand how we got "the middle east".


[fn:-12-17] An important research to understand the uprising of Jihad movements between
  pan-Arabists, ex pan-Arabists in general, and between engineers and the middle
  class in particular. I think it's even a good introduction to answer the
  question of why Muslims might bomb themselves. It's one of the greatest books
  I've ever read about the armed Jihad.


[fn:-12-2] I only used it to read the first two volumes about Sirah.


[fn:-12-18] If there is only one book that is neutral in the history of The Middle East,
  it would be this book. I recommend it for everyone needs to understand how we
  winded up with the 2000s pitiful middle east. Note that the books is
  oversimplified in the post-caliphate era.


[fn:-12-20] Too much informative, in the sense that it doesn't really provide a historical
  context rather than historical information. I will consider searching for
  another book on the early history of Iran soon.


[fn:-13-21] This was very beautiful, I need to reread it multiple times in the future.


[fn:-13-22] If I were to raise someone one day, I'd definitely use this book.


[fn:-14-2] ثمَّ إِنِّي مَا رَأَيْت حَاجَة الشريف إِلَى شَيْء من أدب اللِّسَان بعد سَلَامَته من اللّحن كحاجته إِلَى
الشَّاهِد والمثل والشذرة والكلمة السائرة فَإِن ذَلِك يزِيد الْمنطق تفخيما ويكسبه قبولاً وَيجْعَل لَهُ
قدرا فِي النُّفُوس وحلاوةً فِي الصُّدُور وَيَدْعُو الْقُلُوب إِلَى وعيه ويبعثها على حفظه ويأخذها باستعداده
لأوقات المذاكرة والاستظهار بِهِ أَوَان المجاولة فِي ميادين المجادلة والمصاولة فِي حلبات المقاولة
وَإِنَّمَا هُوَ فِي الْكَلَام كالتفصيل فِي العقد والتنوير فِي الرَّوْض والتسهيم فِي الْبرد فَيَنْبَغِي أَن يستكثر
من أَنْوَاعه لَان الإقلال مِنْهَا كاسمه إقلال وَالتَّقْصِير فِي التماسه قُصُور وَمَا كَانَ مِنْهُ مثلا سائراً
فمعرفته ألزم لَان منفعَته أَعم وَالْجهل بِهِ أقبح (العسكري)


[fn:-14-1] Was that really a book about "women are so weak omg"?


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-7-1] I've many special memories with this book < 3.


[fn:-7-11] This was one of my most enjoyable classes ever, however, that's all what
I can recall about it (as of [2025-04-01 Tue 00:13]), I forgot most of the
course material.. it will be very nice if I could interact with this subject
again someday in a master class.


[fn:-7-12] [2025-09-16 Tue 00:23] I'm reading this along with doing https://codingchallenges.fyi/challenges/challenge-webserver/


[fn:-7-8] I really recommend Shaffer's book, however, this one contained additional
algorithms that were not included in the former.


[fn:-7-7] Do not confuse for computer code. See: https://en.wikipedia.org/w/index.php?title=Code&oldid=1194309533


[fn:-7-2] I'm not into game programming, but it was very fun to read this book.


[fn:-7-10] I'm not reading this, just using it as a reference book.


[fn:-7-6] For a better PDF version of this great book, please +find this link+
contact me.


[fn:-7-9] [2024-02-04 Sun 06:35]: funny enough that I didn't complete this book
either and left it for Renzo Borgatti's, I think it's great learning recoruce though.


[fn:-7-3] I also read Seibel's Practical Common Lisp, this is my book of choice for
people who want to get into Lisp.


[fn:-7-4] I unlearned it later.


[fn:-7-5] Enjoyable work.


[fn:-8-11] I won't usually recommend reading this, but I want to make sure that
everyone will read it, even if you are not going to study Marxism, reading the
Manifesto at least is أضعف الإيمان to prevent yourself from the odds and the
ends of the anti-bolshevism propaganda (which usually includes "Marxism"). A
better alternative would be Nikoalai Bukharin's "ABC of Communism", or even
better, read Marx carefully.


[fn:-8-1] Also known as: religion and class struggle


[fn:-8-12] I consider this as a very nice literary message, actually it reminds
me of how the intellectual treated "crowds" in the early 19 and 20 centuries,
read about this here [DELETED]. Simply, like Le Bon and Frizer did in there
psychology and anthropology papers, Étienne de La Boétie is cursing the scum
peoples who let tyrant governors control and torture them. Of course without
giving any explanation on why they do so. It's very obsolete to take it as an
'intellectual' or 'anthropological' approach.


[fn:-8-13] This books is about the laïcité (the f*ricnh secularism) and how the
xenophobia works as very good engine for moving the French people towards more
and more so-called 'free speech' movements. A very important and related book is
Jean Baubérot's La laïcité Française et ses Mutations.


[fn:-8-2] أوهَمَ رأس المال الناس أنّ الدُّول "المتقدِّمة" هي كذلك بفعل خفض الإنفاق
العمومي. ولكن الإنفاق العمومي، مقارنة بالناتِج القومي، لم ينخفِض إلاّ لدى الدُّول
الفقيرة، وبالذّات بإكراهات من الدُّول "المتقدِّمة". (عباس برهام)


[fn:-8-16] Both of these books are good reads for kids.


[fn:-8-15] I don't know who authored this book/article; however it is not
available for some reason on the internet and I can't even remember where did I
download it from, anyway I've reuploaded it; you can get it from /(link is
broken)/.


[fn:-10-1] Also check Dr Anwar's: [[https://www.youtube.com/playlist?list=PLTMFx0t8kDzc72vtNWeTP05x6WYiDgEx7][Anwar Shaikh: Historical Foundations of Political Economy]]


[fn:-11-2] whoever attributed this to Zaid, they did not spend enough time writing
it.


[fn:-11-1] Check my (very old unrevised) review: [[id:c1c6b159-608c-4db1-9c55-88f33883f079][Pervez Hoodbhoy's Islam and Science]].


[fn:-11-3] Dr. Abdulrahman Khalil's introduction is extremely interesting. Avesta is
very interesting to read as well, however, the current version is filled with
paganism. It's hard for a plain reader like me to filter all it to reach for
some wisdom, but I might do it someday.


[fn:-11-19] Poorly written book, nothing new or special in the study, the author
tends to have an evident ignorance on Takhrij al-hadith.


[fn:-12-1] Very good book. I recommend it as a good start for anybody who wants to
understand how we got "the middle east".


[fn:-12-17] An important research to understand the uprising of Jihad movements between
  pan-Arabists, ex pan-Arabists in general, and between engineers and the middle
  class in particular. I think it's even a good introduction to answer the
  question of why Muslims might bomb themselves. It's one of the greatest books
  I've ever read about the armed Jihad.


[fn:-12-2] I only used it to read the first two volumes about Sirah.


[fn:-12-18] If there is only one book that is neutral in the history of The Middle East,
  it would be this book. I recommend it for everyone needs to understand how we
  winded up with the 2000s pitiful middle east. Note that the books is
  oversimplified in the post-caliphate era.


[fn:-12-20] Too much informative, in the sense that it doesn't really provide a historical
  context rather than historical information. I will consider searching for
  another book on the early history of Iran soon.


[fn:-13-21] This was very beautiful, I need to reread it multiple times in the future.


[fn:-13-22] If I were to raise someone one day, I'd definitely use this book.


[fn:-14-2] ثمَّ إِنِّي مَا رَأَيْت حَاجَة الشريف إِلَى شَيْء من أدب اللِّسَان بعد سَلَامَته من اللّحن كحاجته إِلَى
الشَّاهِد والمثل والشذرة والكلمة السائرة فَإِن ذَلِك يزِيد الْمنطق تفخيما ويكسبه قبولاً وَيجْعَل لَهُ
قدرا فِي النُّفُوس وحلاوةً فِي الصُّدُور وَيَدْعُو الْقُلُوب إِلَى وعيه ويبعثها على حفظه ويأخذها باستعداده
لأوقات المذاكرة والاستظهار بِهِ أَوَان المجاولة فِي ميادين المجادلة والمصاولة فِي حلبات المقاولة
وَإِنَّمَا هُوَ فِي الْكَلَام كالتفصيل فِي العقد والتنوير فِي الرَّوْض والتسهيم فِي الْبرد فَيَنْبَغِي أَن يستكثر
من أَنْوَاعه لَان الإقلال مِنْهَا كاسمه إقلال وَالتَّقْصِير فِي التماسه قُصُور وَمَا كَانَ مِنْهُ مثلا سائراً
فمعرفته ألزم لَان منفعَته أَعم وَالْجهل بِهِ أقبح (العسكري)


[fn:-14-1] Was that really a book about "women are so weak omg"?


[fn:-15-2] Not a very nice work, I'd prefer Youssef Ziedan's novel about Ibn Sina. I never
thought of Ibn Sina in such an erotic context, ever.


[fn:-15-1] ([2024-07-22 Mon 18:23]) One of the most distasteful works I've ever read.


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-7-1] I've many special memories with this book < 3.


[fn:-7-11] This was one of my most enjoyable classes ever, however, that's all what
I can recall about it (as of [2025-04-01 Tue 00:13]), I forgot most of the
course material.. it will be very nice if I could interact with this subject
again someday in a master class.


[fn:-7-12] [2025-09-16 Tue 00:23] I'm reading this along with doing https://codingchallenges.fyi/challenges/challenge-webserver/


[fn:-7-8] I really recommend Shaffer's book, however, this one contained additional
algorithms that were not included in the former.


[fn:-7-7] Do not confuse for computer code. See: https://en.wikipedia.org/w/index.php?title=Code&oldid=1194309533


[fn:-7-2] I'm not into game programming, but it was very fun to read this book.


[fn:-7-10] I'm not reading this, just using it as a reference book.


[fn:-7-6] For a better PDF version of this great book, please +find this link+
contact me.


[fn:-7-9] [2024-02-04 Sun 06:35]: funny enough that I didn't complete this book
either and left it for Renzo Borgatti's, I think it's great learning recoruce though.


[fn:-7-3] I also read Seibel's Practical Common Lisp, this is my book of choice for
people who want to get into Lisp.


[fn:-7-4] I unlearned it later.


[fn:-7-5] Enjoyable work.


[fn:-8-11] I won't usually recommend reading this, but I want to make sure that
everyone will read it, even if you are not going to study Marxism, reading the
Manifesto at least is أضعف الإيمان to prevent yourself from the odds and the
ends of the anti-bolshevism propaganda (which usually includes "Marxism"). A
better alternative would be Nikoalai Bukharin's "ABC of Communism", or even
better, read Marx carefully.


[fn:-8-1] Also known as: religion and class struggle


[fn:-8-12] I consider this as a very nice literary message, actually it reminds
me of how the intellectual treated "crowds" in the early 19 and 20 centuries,
read about this here [DELETED]. Simply, like Le Bon and Frizer did in there
psychology and anthropology papers, Étienne de La Boétie is cursing the scum
peoples who let tyrant governors control and torture them. Of course without
giving any explanation on why they do so. It's very obsolete to take it as an
'intellectual' or 'anthropological' approach.


[fn:-8-13] This books is about the laïcité (the f*ricnh secularism) and how the
xenophobia works as very good engine for moving the French people towards more
and more so-called 'free speech' movements. A very important and related book is
Jean Baubérot's La laïcité Française et ses Mutations.


[fn:-8-2] أوهَمَ رأس المال الناس أنّ الدُّول "المتقدِّمة" هي كذلك بفعل خفض الإنفاق
العمومي. ولكن الإنفاق العمومي، مقارنة بالناتِج القومي، لم ينخفِض إلاّ لدى الدُّول
الفقيرة، وبالذّات بإكراهات من الدُّول "المتقدِّمة". (عباس برهام)


[fn:-8-16] Both of these books are good reads for kids.


[fn:-8-15] I don't know who authored this book/article; however it is not
available for some reason on the internet and I can't even remember where did I
download it from, anyway I've reuploaded it; you can get it from /(link is
broken)/.


[fn:-10-1] Also check Dr Anwar's: [[https://www.youtube.com/playlist?list=PLTMFx0t8kDzc72vtNWeTP05x6WYiDgEx7][Anwar Shaikh: Historical Foundations of Political Economy]]


[fn:-11-2] whoever attributed this to Zaid, they did not spend enough time writing
it.


[fn:-11-1] Check my (very old unrevised) review: [[id:c1c6b159-608c-4db1-9c55-88f33883f079][Pervez Hoodbhoy's Islam and Science]].


[fn:-11-3] Dr. Abdulrahman Khalil's introduction is extremely interesting. Avesta is
very interesting to read as well, however, the current version is filled with
paganism. It's hard for a plain reader like me to filter all it to reach for
some wisdom, but I might do it someday.


[fn:-11-19] Poorly written book, nothing new or special in the study, the author
tends to have an evident ignorance on Takhrij al-hadith.


[fn:-12-1] Very good book. I recommend it as a good start for anybody who wants to
understand how we got "the middle east".


[fn:-12-17] An important research to understand the uprising of Jihad movements between
  pan-Arabists, ex pan-Arabists in general, and between engineers and the middle
  class in particular. I think it's even a good introduction to answer the
  question of why Muslims might bomb themselves. It's one of the greatest books
  I've ever read about the armed Jihad.


[fn:-12-2] I only used it to read the first two volumes about Sirah.


[fn:-12-18] If there is only one book that is neutral in the history of The Middle East,
  it would be this book. I recommend it for everyone needs to understand how we
  winded up with the 2000s pitiful middle east. Note that the books is
  oversimplified in the post-caliphate era.


[fn:-12-20] Too much informative, in the sense that it doesn't really provide a historical
  context rather than historical information. I will consider searching for
  another book on the early history of Iran soon.


[fn:-13-21] This was very beautiful, I need to reread it multiple times in the future.


[fn:-13-22] If I were to raise someone one day, I'd definitely use this book.


[fn:-14-2] ثمَّ إِنِّي مَا رَأَيْت حَاجَة الشريف إِلَى شَيْء من أدب اللِّسَان بعد سَلَامَته من اللّحن كحاجته إِلَى
الشَّاهِد والمثل والشذرة والكلمة السائرة فَإِن ذَلِك يزِيد الْمنطق تفخيما ويكسبه قبولاً وَيجْعَل لَهُ
قدرا فِي النُّفُوس وحلاوةً فِي الصُّدُور وَيَدْعُو الْقُلُوب إِلَى وعيه ويبعثها على حفظه ويأخذها باستعداده
لأوقات المذاكرة والاستظهار بِهِ أَوَان المجاولة فِي ميادين المجادلة والمصاولة فِي حلبات المقاولة
وَإِنَّمَا هُوَ فِي الْكَلَام كالتفصيل فِي العقد والتنوير فِي الرَّوْض والتسهيم فِي الْبرد فَيَنْبَغِي أَن يستكثر
من أَنْوَاعه لَان الإقلال مِنْهَا كاسمه إقلال وَالتَّقْصِير فِي التماسه قُصُور وَمَا كَانَ مِنْهُ مثلا سائراً
فمعرفته ألزم لَان منفعَته أَعم وَالْجهل بِهِ أقبح (العسكري)


[fn:-14-1] Was that really a book about "women are so weak omg"?


[fn:-15-2] Not a very nice work, I'd prefer Youssef Ziedan's novel about Ibn Sina. I never
thought of Ibn Sina in such an erotic context, ever.


[fn:-15-1] ([2024-07-22 Mon 18:23]) One of the most distasteful works I've ever read.


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-7-1] I've many special memories with this book < 3.


[fn:-7-11] This was one of my most enjoyable classes ever, however, that's all what
I can recall about it (as of [2025-04-01 Tue 00:13]), I forgot most of the
course material.. it will be very nice if I could interact with this subject
again someday in a master class.


[fn:-7-12] [2025-09-16 Tue 00:23] I'm reading this along with doing https://codingchallenges.fyi/challenges/challenge-webserver/


[fn:-7-8] I really recommend Shaffer's book, however, this one contained additional
algorithms that were not included in the former.


[fn:-7-7] Do not confuse for computer code. See: https://en.wikipedia.org/w/index.php?title=Code&oldid=1194309533


[fn:-7-2] I'm not into game programming, but it was very fun to read this book.


[fn:-7-10] I'm not reading this, just using it as a reference book.


[fn:-7-6] For a better PDF version of this great book, please +find this link+
contact me.


[fn:-7-9] [2024-02-04 Sun 06:35]: funny enough that I didn't complete this book
either and left it for Renzo Borgatti's, I think it's great learning recoruce though.


[fn:-7-3] I also read Seibel's Practical Common Lisp, this is my book of choice for
people who want to get into Lisp.


[fn:-7-4] I unlearned it later.


[fn:-7-5] Enjoyable work.


[fn:-8-11] I won't usually recommend reading this, but I want to make sure that
everyone will read it, even if you are not going to study Marxism, reading the
Manifesto at least is أضعف الإيمان to prevent yourself from the odds and the
ends of the anti-bolshevism propaganda (which usually includes "Marxism"). A
better alternative would be Nikoalai Bukharin's "ABC of Communism", or even
better, read Marx carefully.


[fn:-8-1] Also known as: religion and class struggle


[fn:-8-12] I consider this as a very nice literary message, actually it reminds
me of how the intellectual treated "crowds" in the early 19 and 20 centuries,
read about this here [DELETED]. Simply, like Le Bon and Frizer did in there
psychology and anthropology papers, Étienne de La Boétie is cursing the scum
peoples who let tyrant governors control and torture them. Of course without
giving any explanation on why they do so. It's very obsolete to take it as an
'intellectual' or 'anthropological' approach.


[fn:-8-13] This books is about the laïcité (the f*ricnh secularism) and how the
xenophobia works as very good engine for moving the French people towards more
and more so-called 'free speech' movements. A very important and related book is
Jean Baubérot's La laïcité Française et ses Mutations.


[fn:-8-2] أوهَمَ رأس المال الناس أنّ الدُّول "المتقدِّمة" هي كذلك بفعل خفض الإنفاق
العمومي. ولكن الإنفاق العمومي، مقارنة بالناتِج القومي، لم ينخفِض إلاّ لدى الدُّول
الفقيرة، وبالذّات بإكراهات من الدُّول "المتقدِّمة". (عباس برهام)


[fn:-8-16] Both of these books are good reads for kids.


[fn:-8-15] I don't know who authored this book/article; however it is not
available for some reason on the internet and I can't even remember where did I
download it from, anyway I've reuploaded it; you can get it from /(link is
broken)/.


[fn:-10-1] Also check Dr Anwar's: [[https://www.youtube.com/playlist?list=PLTMFx0t8kDzc72vtNWeTP05x6WYiDgEx7][Anwar Shaikh: Historical Foundations of Political Economy]]


[fn:-11-2] whoever attributed this to Zaid, they did not spend enough time writing
it.


[fn:-11-1] Check my (very old unrevised) review: [[id:c1c6b159-608c-4db1-9c55-88f33883f079][Pervez Hoodbhoy's Islam and Science]].


[fn:-11-3] Dr. Abdulrahman Khalil's introduction is extremely interesting. Avesta is
very interesting to read as well, however, the current version is filled with
paganism. It's hard for a plain reader like me to filter all it to reach for
some wisdom, but I might do it someday.


[fn:-11-19] Poorly written book, nothing new or special in the study, the author
tends to have an evident ignorance on Takhrij al-hadith.


[fn:-12-1] Very good book. I recommend it as a good start for anybody who wants to
understand how we got "the middle east".


[fn:-12-17] An important research to understand the uprising of Jihad movements between
  pan-Arabists, ex pan-Arabists in general, and between engineers and the middle
  class in particular. I think it's even a good introduction to answer the
  question of why Muslims might bomb themselves. It's one of the greatest books
  I've ever read about the armed Jihad.


[fn:-12-2] I only used it to read the first two volumes about Sirah.


[fn:-12-18] If there is only one book that is neutral in the history of The Middle East,
  it would be this book. I recommend it for everyone needs to understand how we
  winded up with the 2000s pitiful middle east. Note that the books is
  oversimplified in the post-caliphate era.


[fn:-12-20] Too much informative, in the sense that it doesn't really provide a historical
  context rather than historical information. I will consider searching for
  another book on the early history of Iran soon.


[fn:-13-21] This was very beautiful, I need to reread it multiple times in the future.


[fn:-13-22] If I were to raise someone one day, I'd definitely use this book.


[fn:-14-2] ثمَّ إِنِّي مَا رَأَيْت حَاجَة الشريف إِلَى شَيْء من أدب اللِّسَان بعد سَلَامَته من اللّحن كحاجته إِلَى
الشَّاهِد والمثل والشذرة والكلمة السائرة فَإِن ذَلِك يزِيد الْمنطق تفخيما ويكسبه قبولاً وَيجْعَل لَهُ
قدرا فِي النُّفُوس وحلاوةً فِي الصُّدُور وَيَدْعُو الْقُلُوب إِلَى وعيه ويبعثها على حفظه ويأخذها باستعداده
لأوقات المذاكرة والاستظهار بِهِ أَوَان المجاولة فِي ميادين المجادلة والمصاولة فِي حلبات المقاولة
وَإِنَّمَا هُوَ فِي الْكَلَام كالتفصيل فِي العقد والتنوير فِي الرَّوْض والتسهيم فِي الْبرد فَيَنْبَغِي أَن يستكثر
من أَنْوَاعه لَان الإقلال مِنْهَا كاسمه إقلال وَالتَّقْصِير فِي التماسه قُصُور وَمَا كَانَ مِنْهُ مثلا سائراً
فمعرفته ألزم لَان منفعَته أَعم وَالْجهل بِهِ أقبح (العسكري)


[fn:-14-1] Was that really a book about "women are so weak omg"?


[fn:-15-2] Not a very nice work, I'd prefer Youssef Ziedan's novel about Ibn Sina. I never
thought of Ibn Sina in such an erotic context, ever.


[fn:-15-1] ([2024-07-22 Mon 18:23]) One of the most distasteful works I've ever read.


[fn:-0-2] An inequilateral note about reading /philosophy/; the vast majority of
philosophy books is not worth reading, in fact it's painful to read it, which is
a thing I realized too late (~1 year ago, thanks to a friend of mine allowed me
to read his dissertation in /Obscurantism/ of philosophers), a lot of philosophy
books I've read in my life was useful but not really that 'useful', this is not
the best place to explain why, but I'll talk about this in the future Inshaa'
Allah. Also, read [[https://sophy.ca/blog/2013/03/how-not-to-write-in-philosophy/][How not to write in philosophy -- Against obscurantism]].


[fn:-0-1] Very poor review.


[fn:-0-4] Mernissi forces herself to act like an orientalist, however she ain't. Since I
  can't write a lot in this small box, I'd like to point 3 important issues in
  this dissertation; 1. Usage of past-criticized Takhrij of some Hadiths, which
  was claimed by her in /Political Harem: The Prophet and Women/ that it cannot
  be noted after the prophet, but was 'made up' for interests. 2. Which is sorta
  correlated with 1, is the inference from history book like Tabaqat al-Kubra.
  We can not tell what is 'Islamic' based on such late area of the Islamic
  History. However, if Mernissi surfs what is told to be 'Islamic', not what is
  'Islamic', those 2 points are not valid. 3. Al-Ghazali used to address his
  students that were always men, which clarify why he gives advices about
  treating women, I couldn't interpret it like Mernissi did, that he meant
  'Women are tools for men to help them pass through the hurdles of life'. This
  is meaningless.


[fn:-0-5] It's sad that non-scientific (in the academic means) Islamic scholars can not
  write a readable argument without bloat it with x10 hate and swearing.


[fn:-0-6] I think this book could make a use for me in the future in giving instances of
  how most of philosophy authors & books are either pointless or obscure.


[fn:-0-7] Pretty much up-to-date version of "The Protocols of the Elders of Zion".


[fn:-1-2] On fractals, for computer scientists.


[fn:-1-1] An advanced textbook on fractals.


[fn:-1-8] I used to read it in my high school, I still remember that I enjoyed it more
  than any other history book I've ever read.


[fn:-1-3] I think the concept of democratizing science that this paper demonstrate
falls to social norms: the author find that there are "indeed certain situations
in which scientists can reject the public’s judgments while remaining committed
to democratizing science" when some of those views are unacceptable by the
"scientist veto". But what's an unacceptable view (that still holds to be
non-epistemic) that will not be subjective? The author gives an example: "the
public offers a horribly racist set of value judgments." A /horribly racist/ is
a highly subjective argument unlike it sounds, in fact, a racist government will
accuse someone who is not racist (i.e. doesn't believe in their superiority) an
infidel, blasphemer (in such a situation those words would have the same impact
as racist) or even just racist for belittling the "main race".


[fn:-1-9] One of the most books I've ever enjoyed when I was a kid, it might be not very
  accurate in many scientific aspects that it ties to approach, however it's
  nice to unlock those roads of thinking, I generally recommend it if you are
  new to thinking about evolution.


[fn:-2-3] Does not include a testing/accuracy section.


[fn:-4-10] The reason I put LeBon's book first is that Frued text is very correlated to
  it, actually it responds to it, and I much agree with Frued regarding the fact
  that Le Bon is just describing Crowds but not analyzing them at all. Of
  course, Frued's analysis is considered to be pure obsolete by common tropes
  today, however, I still find it an interesting method to understand crowds'
  behavior.


[fn:-4-1] Not a recommended reading, very general and not useful, reminds me of
typical bureaucratic academia work stereotype.


[fn:-4-2] This paper give concrete documenting on the pleasure gap.


[fn:-4-3] A U.S. National Sample study of more than 50,000 people. It states a
pleasure gap (95% of heterosexual men to 65% of heterosexual women)


[fn:-4-4] This shows the collective thinking that female sexual climax are
'biologically elusive'


[fn:-7-1] I've many special memories with this book < 3.


[fn:-7-11] This was one of my most enjoyable classes ever, however, that's all what
I can recall about it (as of [2025-04-01 Tue 00:13]), I forgot most of the
course material.. it will be very nice if I could interact with this subject
again someday in a master class.


[fn:-7-12] [2025-09-16 Tue 00:23] I'm reading this along with doing https://codingchallenges.fyi/challenges/challenge-webserver/


[fn:-7-8] I really recommend Shaffer's book, however, this one contained additional
algorithms that were not included in the former.


[fn:-7-7] Do not confuse for computer code. See: https://en.wikipedia.org/w/index.php?title=Code&oldid=1194309533


[fn:-7-2] I'm not into game programming, but it was very fun to read this book.


[fn:-7-10] I'm not reading this, just using it as a reference book.


[fn:-7-6] For a better PDF version of this great book, please +find this link+
contact me.


[fn:-7-9] [2024-02-04 Sun 06:35]: funny enough that I didn't complete this book
either and left it for Renzo Borgatti's, I think it's great learning recoruce though.


[fn:-7-3] I also read Seibel's Practical Common Lisp, this is my book of choice for
people who want to get into Lisp.


[fn:-7-4] I unlearned it later.


[fn:-7-5] Enjoyable work.


[fn:-8-11] I won't usually recommend reading this, but I want to make sure that
everyone will read it, even if you are not going to study Marxism, reading the
Manifesto at least is أضعف الإيمان to prevent yourself from the odds and the
ends of the anti-bolshevism propaganda (which usually includes "Marxism"). A
better alternative would be Nikoalai Bukharin's "ABC of Communism", or even
better, read Marx carefully.


[fn:-8-1] Also known as: religion and class struggle


[fn:-8-12] I consider this as a very nice literary message, actually it reminds
me of how the intellectual treated "crowds" in the early 19 and 20 centuries,
read about this here [DELETED]. Simply, like Le Bon and Frizer did in there
psychology and anthropology papers, Étienne de La Boétie is cursing the scum
peoples who let tyrant governors control and torture them. Of course without
giving any explanation on why they do so. It's very obsolete to take it as an
'intellectual' or 'anthropological' approach.


[fn:-8-13] This books is about the laïcité (the f*ricnh secularism) and how the
xenophobia works as very good engine for moving the French people towards more
and more so-called 'free speech' movements. A very important and related book is
Jean Baubérot's La laïcité Française et ses Mutations.


[fn:-8-2] أوهَمَ رأس المال الناس أنّ الدُّول "المتقدِّمة" هي كذلك بفعل خفض الإنفاق
العمومي. ولكن الإنفاق العمومي، مقارنة بالناتِج القومي، لم ينخفِض إلاّ لدى الدُّول
الفقيرة، وبالذّات بإكراهات من الدُّول "المتقدِّمة". (عباس برهام)


[fn:-8-16] Both of these books are good reads for kids.


[fn:-8-15] I don't know who authored this book/article; however it is not
available for some reason on the internet and I can't even remember where did I
download it from, anyway I've reuploaded it; you can get it from /(link is
broken)/.


[fn:-10-1] Also check Dr Anwar's: [[https://www.youtube.com/playlist?list=PLTMFx0t8kDzc72vtNWeTP05x6WYiDgEx7][Anwar Shaikh: Historical Foundations of Political Economy]]


[fn:-11-2] whoever attributed this to Zaid, they did not spend enough time writing
it.


[fn:-11-1] Check my (very old unrevised) review: [[id:c1c6b159-608c-4db1-9c55-88f33883f079][Pervez Hoodbhoy's Islam and Science]].


[fn:-11-3] Dr. Abdulrahman Khalil's introduction is extremely interesting. Avesta is
very interesting to read as well, however, the current version is filled with
paganism. It's hard for a plain reader like me to filter all it to reach for
some wisdom, but I might do it someday.


[fn:-11-19] Poorly written book, nothing new or special in the study, the author
tends to have an evident ignorance on Takhrij al-hadith.


[fn:-12-1] Very good book. I recommend it as a good start for anybody who wants to
understand how we got "the middle east".


[fn:-12-17] An important research to understand the uprising of Jihad movements between
  pan-Arabists, ex pan-Arabists in general, and between engineers and the middle
  class in particular. I think it's even a good introduction to answer the
  question of why Muslims might bomb themselves. It's one of the greatest books
  I've ever read about the armed Jihad.


[fn:-12-2] I only used it to read the first two volumes about Sirah.


[fn:-12-18] If there is only one book that is neutral in the history of The Middle East,
  it would be this book. I recommend it for everyone needs to understand how we
  winded up with the 2000s pitiful middle east. Note that the books is
  oversimplified in the post-caliphate era.


[fn:-12-20] Too much informative, in the sense that it doesn't really provide a historical
  context rather than historical information. I will consider searching for
  another book on the early history of Iran soon.


[fn:-13-21] This was very beautiful, I need to reread it multiple times in the future.


[fn:-13-22] If I were to raise someone one day, I'd definitely use this book.


[fn:-14-2] ثمَّ إِنِّي مَا رَأَيْت حَاجَة الشريف إِلَى شَيْء من أدب اللِّسَان بعد سَلَامَته من اللّحن كحاجته إِلَى
الشَّاهِد والمثل والشذرة والكلمة السائرة فَإِن ذَلِك يزِيد الْمنطق تفخيما ويكسبه قبولاً وَيجْعَل لَهُ
قدرا فِي النُّفُوس وحلاوةً فِي الصُّدُور وَيَدْعُو الْقُلُوب إِلَى وعيه ويبعثها على حفظه ويأخذها باستعداده
لأوقات المذاكرة والاستظهار بِهِ أَوَان المجاولة فِي ميادين المجادلة والمصاولة فِي حلبات المقاولة
وَإِنَّمَا هُوَ فِي الْكَلَام كالتفصيل فِي العقد والتنوير فِي الرَّوْض والتسهيم فِي الْبرد فَيَنْبَغِي أَن يستكثر
من أَنْوَاعه لَان الإقلال مِنْهَا كاسمه إقلال وَالتَّقْصِير فِي التماسه قُصُور وَمَا كَانَ مِنْهُ مثلا سائراً
فمعرفته ألزم لَان منفعَته أَعم وَالْجهل بِهِ أقبح (العسكري)


[fn:-14-1] Was that really a book about "women are so weak omg"?


[fn:-15-2] Not a very nice work, I'd prefer Youssef Ziedan's novel about Ibn Sina. I never
thought of Ibn Sina in such an erotic context, ever.


[fn:-15-1] ([2024-07-22 Mon 18:23]) One of the most distasteful works I've ever read.


[fn:-18-1] I wish if I've started with this book instead of chess for dummies.

