:PROPERTIES:
:ID:       er8e2n91crk0
:CUSTOM_ID: er8e2n91crk0
:END:
#+title: Do they deserve help?
#+DATE: <2025-11-15 Sat 22:48>

#+BEGIN_propert
{{{s}}} [[id:x0egwn81crk0][What is it to be done?]]
#+END_propert


The second class of unfortunates, whom I hoped afterwards to be able to help, were women of the town. These women were very numerous in the Rzhanoff Houses; and they were of every kind, from young girls still bearing some likeness to women, to old and fearful-looking creatures without a vestige of humanity. The hope of helping these women, whom I had not at first in view, was aroused by the following circumstances.

When we had finished half of our tour, we had already acquired a somewhat mechanical method. On entering a new lodging we at once asked for the landlord. One of us sat down, clearing a space to write; and the other went from one to another, questioning each man and woman in the room, and reporting the information obtained to him who was writing.

On our entering one of the basement lodgings, the student went to look for the landlord; and I began to question all who were in the place. This place was divided thus: In the middle of the room, which was four yards square, there stood a stove. From the stove four partitions or screens radiated, making a similar number of small compartments. In the first of these, which had two doors in it opposite each other, and four pallets, were an old man and a woman. Next to this was a rather long but narrow room, in which was the landlord, a young, pale, good-looking man dressed in a gray woollen coat. To the left of the first division was a third small room where a man was sleeping, seemingly tipsy, and a woman in a pink dressing-gown. The fourth compartment was behind a partition, access to it being through the landlord's room.

The student entered the latter, while I remained in the first, questioning the old man and the woman. The former had been a compositor, but now had no means of livelihood whatever.

The woman was a cook's wife.

I went into the third compartment, and asked the woman in the dressing-gown about the man who was asleep.

She answered that he was a visitor.

I asked her who she was.

She replied that she was a peasant girl from the county of Moscow.

“What is your occupation?” She laughed, and made no answer.

“What do you do for your living?” I repeated, thinking she had not understood the question.

“I sit in the inn,” she said.

I did not understand her, and asked again,—

“What are your means of living?”

She gave me no answer, but continued to giggle. In the fourth room, where we had not yet been, I heard the voices of women also giggling.

The landlord came out of his room, and approached us. He had evidently heard my questions and the woman's answers. He glanced sternly at her, and, turning to me, said, “She is a prostitute”; and it was evident that he was pleased that he knew this word,—which is the one used in official circles,—and at having pronounced it correctly. And having said this with a respectful smile of satisfaction towards me, he turned to the woman. As he did so, the expression of his face changed. In a peculiarly contemptuous manner, and with rapid utterance as one would speak to a dog, he said, without looking at her, “Don't be a fool! instead of saying you sit in the inn, speak plainly, and say you are a prostitute.—She does not even yet know her proper name,” he said, turning to me.

This manner of speaking shocked me.

“It is not for us to shame her,” I said. “If we were all living according to God's commandment, there would be no such persons.”

“There are such doings,” said the landlord, with an artificial smile.

“Therefore we must pity them, and not reproach them. Is it their fault?”

I do not remember exactly what I said. I remember only that I was disgusted by the disdainful tone of this young landlord, in a lodging filled with females whom he termed prostitutes; and I pitied the woman, and expressed both feelings.

No sooner had I said this, than I heard from the small compartment where the giggling had been, the noise of creaking bed-boards; and over the partition, which did not reach to the ceiling, appeared the dishevelled curly head of a female with small swollen eyes, and a shining red face; a second, and then a third, head followed. They were evidently standing on their beds; and all three were stretching their necks and holding their breath, and looking silently at me with strained attention.

A painful silence followed.

The student, who had been smiling before this happened, now became grave; the landlord became confused, and cast down his eyes; and the women continued to look at me in expectation.

I felt more disconcerted than all the rest. I had certainly not expected that a casual word would produce such an effect. It was like the field of battle covered with dead bones seen by the prophet Ezekiel, on which, trembling from contact with the spirit, the dead bones began to move. I had casually uttered a word of love and pity, which produced upon all such an effect that it seemed as if they had been only waiting for it, to cease to be corpses, and to become alive again.

They continued to look at me, as if wondering what would come next, as if waiting for me to say those words and do those acts by which these dry bones would begin to come together,—be covered with flesh and receive life.

But I felt, alas! that I had no such words or deeds to give, or to continue as I had begun. In the depth of my soul I felt that I had told a lie, that I myself was like them, that I had nothing more to say; and I began to write down on the card the names and the occupations of all the lodgers there.

This occurrence led me into a new kind of error. I began to think that these unhappy creatures also could be helped. This, in my self deception, it seemed to me would be very easily done. I said to myself, “Now we shall put down the names of these women too; and afterwards, when we (though it never occurred to me to ask who were the we) have written everything down, we can occupy ourselves with their affairs.” I imagined that we, the very persons who, during many generations, have been leading such women into such a condition, and still continue to do so, could one fine morning wake up and remedy it all. And yet, if I could have recollected my conversation with the lost woman who was nursing the baby for the sick mother, I should have understood the folly of such an idea.

When we first saw this woman nursing the child, we thought that it was hers; but upon our asking her what she was, she answered us plainly that she was a wench. She did not say “prostitute.” It was left for the proprietor of the lodgings to make use of that terrible word.

The supposition that she had a child gave me the idea of helping her out of her present position.

“Is this child yours?” I asked.

“No: it is that woman's there.”

“Why do you nurse him?”

“She asked me to. She is dying.”

Though my surmise turned out to be wrong, I continued to speak with her in the same spirit. I began to question her as to who she was, and how she came to be in such a position. She told me her story willingly, and very plainly. She belonged to the artisan class of Moscow, the daughter of a factory workman. She was left an orphan, and adopted by her aunt, from whose house she began to visit the inns. The aunt was now dead.

When I asked her whether she wished to change her course of life, my question did not even interest her. How can a supposition about something quite impossible awaken an interest in any one? She smiled and said,—

“Who would take me with a yellow ticket?”[3]

“But,” said I, “if it were possible to find you a situation as a cook or something else?” I said this because she looked like a strong woman, with a kind, dull, round face, not unlike many cooks I had seen.

Evidently my words did not please her. She repeated, “Cook! but I do not understand how to bake bread.”

She spoke jestingly; but, by the expression of her face, I saw that she was unwilling; that she even considered the position and rank of a cook beneath her.

This woman, who, in the most simple manner, like the widow in the gospel, had sacrificed all that she had for a sick person, at the same time, like other women of the same profession, considered the position of a workman or workwoman low and despicable. She had been educated to live without work,—a life which all her friends considered quite natural. This was her misfortune. And by this she came into her present position, and is kept in it. This brought her to the inns. Who of us men and women will cure her of this false view of life? Are there among us any men convinced that a laborious life is more respectable than an idle one, and who are living according to this conviction, and who make this the test of their esteem and respect?

If I had thought about it I should have understood that neither I nor anybody else I know, was able to cure a person of this disease.

I should have understood that those wondering and awakened faces that looked over the partition expressed merely astonishment at the pity shown to them, but no wish to reform their lives. They did not see the immorality. They knew that they were despised and condemned, but the reason for this they could not understand. They had lived in this manner from their infancy among women like themselves, who, they know very well, have always existed, do exist, and are necessary to society, that there are officials deputed by government to see that they conform to regulations.

Besides, they know that they have power over men, and subdue them, and often influence them more than any other women. They see that their position in society, notwithstanding the fact that they are always blamed, is recognised by men as well as by women and by the government; and therefore they cannot even understand of what they have to repent, and wherein they should reform.

During one of our tours the student told me that in one of the lodgings there was a woman who sends out her daughter, thirteen years old, to walk the streets. Wishing to save this little girl I went on purpose to their lodging.

Mother and daughter were living in great poverty. The mother, a small, dark-complexioned prostitute of forty years of age, was not simply ugly, but disagreeably ugly. The daughter was also bad-looking. To all my indirect questions about their mode of life, the mother replied curtly, with a look of suspicion and animosity, apparently feeling that I was an enemy with bad intentions: the daughter said nothing without looking first at the mother, in whom she evidently had entire confidence.

They did not awaken pity in my heart, but rather disgust. Still I decided that it was necessary to save the daughter, to awaken an interest in ladies who might sympathize with the miserable condition of these women and might so be brought here.

Yet if I had thought about the antecedents of the mother, how she had given birth to her daughter, how she had fed and brought her up, certainly without any outside help, and with great sacrifices to herself; if I had thought of the view of life which had formed itself in her mind,—I should have understood, that, in the mother's conduct, there was nothing at all bad or immoral, seeing she had been doing for her daughter all she could; i.e., what she considered best for herself.

It was possible to take this girl away from her mother by force; but to convince her that she was doing wrong in selling her daughter was not possible. It would first be necessary to save this woman—this mother—from a condition of life approved by every one, and according to which a woman may live without marrying and without working, serving exclusively as a gratification to the passions. If I had thought about this, I should have understood that the majority of those ladies whom I wished to send here for saving this girl were not only themselves avoiding family duties, and leading idle and sensuous lives, but were consciously educating their daughters for this very same mode of existence. One mother leads her daughter to the inn, and another to court and to balls. Both the views of the world held by both mothers are the same; viz., that a woman must gratify the passions of men, and for that she must be fed, dressed, and taken care of.

How, then, are our ladies to reform this woman and her daughter?
