:PROPERTIES:
:ID:       38we8p91crk0
:CUSTOM_ID: 38we8p91crk0
:END:
#+title: Fake goodness
#+DATE: <2025-11-15 Sat 22:49>

Still more strange were my dealings with the children. In my rôle as benefactor I paid attention to the children too, wishing to save innocent beings from going to ruin in this den; and I wrote down their names in order to attend to them myself afterwards.

Among these children my attention was particularly drawn to Serozha, a boy twelve years old. I sincerely pitied this clever, intelligent lad, who had been living with a bootmaker, and who was left without any place of refuge when his master was put into prison. I wished to do something for him.

I will now give the result of my benevolence in his case, because this boy's story will show my false position as a benefactor better than anything else.

I took the boy into my house, and lodged him in the kitchen. Could I possibly bring a lousy boy out of a den of depravity to my children? I considered that I had been very kind in having put him where he was, amongst my servants. I thought myself a great benefactor for having given him some of my old clothes and fed him; though it was properly my cook who did it, not I. The boy remained in my house about a week.

During this week I saw him twice, and, passing him, spoke some words to him, and, when out walking, called on a bootmaker whom I knew and proposed the boy as an apprentice. A peasant who was on a visit at my house invited him to go to his village and work in a family. The boy refused to accept it and disappeared within a week.

I went to Rzhanoff's house to enquire after him. He had returned there; but when I called, he was not at home. He had already been two days in a menagerie in Presnem Ponds, where he hired himself for 6d. a day to appear in a procession of savages in costume, leading an elephant. There was some public show on at the time.

I went to see him again, but he was so ungrateful, he evidently avoided me. Had I reflected upon the life of this boy and on my own, I should have understood that the boy had been spoiled by the fact of his having tasted the sweets of a merry and idle life, and that he had lost the habit of working. And I, in order to confer on him a benefit and reform him, took him into my own house. And what did he see there? He saw my children, some older than he, some younger, and some of the same age, who not only never did anything for themselves, but gave as much work to others as they could. They dirtied and spoiled everything about them, surfeited themselves with all sorts of dainties, broke the china, upset and threw to the dogs food which would have been a treat to him. If I took him out of a den and brought him to a respectable place, he could not but assimilate the views of life which existed there; and, according to these views, he understood that in a respectable position one must live without working, eat and drink well, and lead a merry life.

True, he did not know that my children had much labour in learning the exceptions in Latin and Greek grammars; nor would he have been able to understand the object of such work. But one cannot help seeing that even had he understood it the influence upon him of the example of my children would have been still stronger. He would have then understood that they were being educated in such a way, that, not working now, they might afterwards also work as little as possible, and enjoy the good things of life by virtue of their diplomas.

But what he did understand of it made him go, not to the peasant to take care of cattle and feed on potatoes and kvas,[4] but to the menagerie in the costume of a savage to lead an elephant for 6d. a day. I ought to have understood how foolish it was of one who was educating his own children in complete idleness and luxury to try to reform other men and their children, and save them from going to ruin and idleness in what I called the dens in Rzhanoff's house; where, however, three-fourths of the men were working for themselves and for others. But then I understood nothing of all this.

In Rzhanoff's house there were a great many children in the most miserable condition. There were children of prostitutes, orphans, and children carried about the streets by beggars. They were all very wretched. But my experience with Serozha showed me that so long as I continued living the life I did I was not able to help them.

While the boy was living with us I remember I took pains to hide from him our way of life, particularly that of my children. I felt that all my endeavours to lead him to a good and laborious life were frustrated by my example and that of my children. It is very easy to take away a child from a prostitute or a beggar. It is very easy, when one has money, to wash him, dress him in new clothes, feed him well, and even teach him different accomplishments; but to teach him how to earn his living, is, for us who have not been earning ours but doing just the contrary, not only difficult but quite impossible, because by our example and by the very improvements of his mode of life effected by us without any cost on our part, we teach him the very opposite.

You may take a puppy, pet him, feed him, teach him to carry things after you, and be pleased with looking at him: but it is not enough to feed a man, dress him, and teach him Greek; you must teach him how to live; i.e., how to take less from others and give them more in return: and yet through our own mode of life we cannot help teaching him the very opposite whether we take him into our house or put him into a home to bring up. #[[id:x0egwn81crk0][What is it to be done?]]
