:PROPERTIES:
:ID:       4v1hmt91crk0
:CUSTOM_ID: 4v1hmt91crk0
:END:
#+title: Confession of guilt
#+DATE: <2025-11-15 Sat 22:52>

It was hard for me to own this; but when I had got so far I was terrified at the delusion in which I had been living. I had been head over ears in the mud myself, and yet I had been trying to drag others out of it.

What is it that I really want? I want to do good; I want to contrive so that no human beings shall be hungry and cold, and that men may live as it is proper for them to live. I desire this; and I see that in consequence of all sorts of violence, extortions, and various expedients in which I too take part, the working people are deprived of the necessary things, and the non-working community, to whom I also belong, monopolize the labour of others. I see that this use of other people's labour is distributed thus: That the more cunning and complicated the devices employed by the man himself (or by those from whom he has inherited his property), the more largely he employs the labours of other people, and the less he works himself.

First come the millionaires; then the wealthy bankers, merchants, land-owners, government officials; then the smaller bankers, merchants, government officials and land-owners, to whom I belong too; then shopmen, publicans, usurers, police sergeants and inspectors, teachers, sacristans, clerks; then, again, house-porters, footmen, coachmen, water-carters, cabmen, pedlers; and then, last of all, the workmen, factory hands and peasants, the number of this class in proportion to the former being as ten to one.

I see that the lives of nine-tenths of the working people essentially require exertion and labour, like every other natural mode of living; but that, in consequence of the devices by which the necessaries of life are taken away from these people, their lives become every year more difficult, and more beset with privations; and our lives, the lives of the non-labouring community, owing to the co-operation of sciences and arts which have this very end in view, become every year more sumptuous, more attractive and secure.

I see that in our days the life of a labouring man, and especially the lives of the old people, women, and children of the working-classes, are quite worn away by increased labour out of proportion to their nourishment, and that even the very first necessaries of life are not secured for them. I see that side by side with these the lives of the non-labouring class, to which I belong, are each year more and more filled up with superfluities and luxury, and are becoming continually more secure. The lives of the wealthy have reached that degree of security of which in olden times men only dreamed in fairy-tales, to the condition of the owner of the magic purse with the “inexhaustible ruble”; to a state where a man not only is entirely free from the law of labour for the sustenance of his life, but has the possibility of enjoying all the goods of this life without working, and of bequeathing to his children, or to anyone he chooses, this purse with the “inexhaustible ruble.”

I see that the results of the labour of men pass over more than ever from the masses of labourers to those of the non-labourers; that the pyramid of the social structure is, as it were, being rebuilt, so that the stones of the foundation pass to the top, and the rapidity of this passage increases in a kind of geometric progression.

I see that there is going on something like what would take place in an ant-hill if the society of ants should lose the sense of the general law, and some of them were to take the results of labour out of the foundations and carry them to the top of the hill, making the foundation narrower and narrower and thus enlarging the top, and so by that means cause their fellows to pass also from the foundation to the top.

I see that instead of the ideal of a laborious life, men have created the ideal of the purse with the “inexhaustible ruble.” The rich, I among their number, arrange this ruble for themselves by various devices; and in order to enjoy it we locate ourselves in towns, in a place where nothing is produced but everything is swallowed up.

The poor labouring man, swindled so that the rich may have this magic ruble, follows them to town; and there he also has recourse to tricks, either arranging matters so that he may work little and enjoy much (thus making the condition of other workingmen still more heavy), or, not having attained this state, he ruins himself and drifts into the continually and rapidly increasing number of cold and hungry tenants of doss-houses.

I belong to the class of those men who by means of these various devices take away from the working people the necessaries of life, and who thus, as it were, create for themselves the inexhaustible fairy ruble which tempts in turn these unfortunate ones.

I wish to help men; and therefore it is clear that first of all I ought on the one side to cease to plunder them as I am doing now, and on the other to leave off tempting them. But by means of most complicated, cunning, and wicked contrivances practised for centuries, I have made myself the owner of this ruble; that is, have got into a condition where, never doing anything myself, I can compel hundreds and thousands of people to work for me, and I am really availing myself of this privileged monopoly notwithstanding that all the time I imagine I pity these men and wish to help them.

I sit on the neck of a man, and having quite crushed him down compel him to carry me and will not alight from off his shoulders, though I assure myself and others that I am very sorry for him and wish to ease his condition by every means in my power—except by getting off his back.

Surely this is plain. If I wish to help the poor, that is, to make the poor cease to be poor, I ought not to create the poor. Yet I give money capriciously to those who have gone astray, and take away tens of rubles from men who have not yet become bad, thereby making them poor and at the same time depraved.

This is very clear; but it was exceedingly difficult for me to understand at first, without some modification or reserve which would justify my position. However as soon as I come to see my own error, all that formerly appeared strange, complicated, clouded, and inexplicable, became quite simple and intelligible; but the important matter was, that the direction of my life indicated by this explanation, became at once, simple, clear, and agreeable, instead of being, as formerly, intricate, incomprehensible, and painful.

Who am I, I thought, that desire to better men's condition? I say I desire this, and yet I do not get up till noon, after having played cards in a brilliantly lighted saloon all night,—I, an enfeebled and effeminate man requiring the help and services of hundreds of people, I come to help them! to help these men who rise at five, sleep on boards, feed on cabbage and bread, understand how to plough, to reap, to put a handle to an axe, to hew, to harness horses, to sew; men who, by their strength and perseverance and skill and self-restraint are a hundred times stronger than I who come to help them.

What could I experience in my intercourse with these people but shame? The weakest of them, a drunkard, an inhabitant of Rzhanoff's house, he whom they call “the sluggard,” is a hundred times more laborious than I; his balance, so to say,—in other words the relation between what he takes from men and what he gives to them,—is a thousand times more to his credit than mine when I count what I receive from others and what I give them in return. And such men I go to assist!

I go to help the poor. But of the two who is the poorer? No one is poorer than myself. I am a weak, good-for-nothing parasite who can only exist under very peculiar conditions, can live only when thousands of people labour to support this life which is not useful to anyone. And I, this very caterpillar which eats up the leaves of a tree, I wish to help the growth and the health of the tree and to cure it!

All my life is spent thus: I eat, talk, and listen; then I eat, write, or read, which are only talking and listening in another form; I eat again, and play; then eat, talk, and listen, and finally eat and go to sleep: and thus every day is spent; I neither do anything else nor understand how to do it. And in order that I may enjoy this life it is necessary that from morning till night house-porters, dvorniks, cooks (male and female), footmen, coachmen, and laundresses, should work; to say nothing of the manual labour necessary so that the coachmen, cooks, footmen, and others may have the instruments and articles by which and upon which they work for me,—axes, casks, brushes, dishes, furniture, glasses, shoe-black, kerosene, hay, wood, and food. All these men and women work hard all the day and every day in order that I may talk, eat, and sleep. And I, this useless man, imagined I was able to benefit the very people who were serving me! That I did not benefit any one and that I was ashamed of myself, is not so strange as the fact that such a foolish idea ever came into my mind.

The woman who nursed the sick old man helped him; the peasant's wife, who cut a slice of her bread earned by herself, from the very sowing of the corn that made it, helped the hungry one; Simon, who gave three kopeks which he had earned, assisted the pilgrim, because these three kopeks really represented his labour; but I had served nobody, worked for no one, and knew very well that my money did not represent my labour.

And so I felt that in money, or in money's worth, and in the possession of it, there was something wrong and evil; that the money itself, and the fact of my having it, was one of the chief causes of those evils which I had seen before me; and I asked myself, What is money? #[[id:x0egwn81crk0][What is it to be done?]]
