:PROPERTIES:
:ID:       w654qi91crk0
:CUSTOM_ID: w654qi91crk0
:END:
#+title: Is misery born of poverty, or does it precede it?
#+DATE: <2025-11-15 Sat 22:45>

On the appointed day, the students who were to assist me started early in the morning; while I, the philanthropist, only joined them at twelve o'clock. I could not come earlier, as I did not get up till ten, after which I had to take some coffee, and then smoke for the sake of my digestion. Twelve o'clock, then, found me at the door of the Rzhanoff Houses. A policeman showed me a public-house to which the census-clerks referred all those who wished to enquire for them. I entered, and found it very dirty and unsavoury. Here, right in front of me, was a counter; to the left a small room, furnished with tables covered with soiled napkins; to the right a large room on pillars, containing similar little tables placed in the windows and along the walls; with men here and there having tea, some very ragged, others well dressed, apparently workmen or small shopkeepers. There were also several women. In spite of the dirt, it was easy to see, by the business air of the man in charge, and the ready, obliging manners of the waiters, that the eating-house was driving a good trade. I had no sooner entered than one of the waiters was already preparing to assist me in getting off my overcoat, anxious to take my orders, and showing that evidently the people here were in the habit of doing their work quickly and readily.

My enquiry for the census-clerks was answered by a call for “Ványa” from a little man dressed in foreign fashion, who was arranging something in a cupboard behind the counter. This was the proprietor of the public-house, a peasant from Kaluga, Iván Fedotitch by name, who also rented half of the other houses, sub-letting the rooms to lodgers. In answer to his call, a thin, sallow-faced, hook-nosed lad, about eighteen years old, came forward hastily. The landlord said, “Take this gentleman to the clerks: they have gone to the main body of the building over the well.”

The lad put down his napkin, pulled on a coat over his white shirt and trousers, picked up a large cap with a peak, and then, with quick, short steps, led the way by a back-door through the buildings. At the entrance of a greasy, malodorous kitchen, we met an old woman who was carefully carrying some putrid tripe in a rag. We descended into a court, built up all round with wooden buildings on stone foundations. The smell was most offensive, and seemed to be concentrated in a privy to which numbers of people were constantly resorting. This privy was really only the place which custom accepted as a privy. One could not avoid noticing this place as one passed through the courtyard. One suffered in entering the acrid atmosphere of the bad smells issuing from it.

The boy, taking care not to soil his white trousers, led me cautiously across frozen and unfrozen filth, and approached one of the buildings. The people crossing the yard and galleries all stopped to gaze at me. It was evident that a cleanly-dressed man was an unusual sight in the place.

The boy asked a woman whom we met, whether she had seen where the census officials had entered, and three people at once answered his question: some said that they were over the well; others said that they had been there, but had now gone to Nikita Ivanovitch's.

An old man in the middle of the court, who had only a shirt on, said that they were at No. 30. The boy concluded that this information was the most probable and led me to No. 30, into the basement, where darkness prevailed and a bad smell, different from that which filled the court.

We continued to descend along a dark passage. As we were traversing it a door was suddenly opened, out of which came a drunken old man in a shirt, evidently not of the peasant class. A shrieking washerwoman with tucked-up sleeves and soapy arms was pushing him out of the room. “Ványa” (my guide) shoved him aside, saying, “It won't do to kick up such a row here—and you an officer too!”

When we arrived at No. 30, Ványa pulled the door, which opened with the sound of a wet slap; and we felt a gush of soapy steam and an odor of bad food and tobacco, and entered in complete darkness. The windows were on the other side; and we were in a crooked corridor, that went right and left, with doors leading at different angles into rooms separated from it by a partition of unevenly laid boards, roughly whitewashed.

In a dark room to the left we could see a woman washing at a trough. Another old woman was looking out of a door at the right. Near an open door was a hairy, red-skinned peasant in bark shoes, sitting on a couch. His hands rested upon his knees; and he was swinging his feet and looking sadly at his shoes.

At the end of the passage a small door led into the room where the census officers had assembled. This was the room of the landlady of the whole of No. 30, who rented it from Iván Fedotitch and sub-let to ordinary or night lodgers.

In this tiny room a student sat under an image glittering with gilt paper, and, with the air of a magistrate, was putting questions to a man dressed in shirt and vest. This last was a friend of the landlady's, who was answering the questions in her stead. The landlady herself,—an old woman,—and two inquisitive lodgers, were also present.

When I entered, the room was quite filled up. I pushed through to the table, shook hands with the student, and he went on extracting his information, while I studied the inhabitants, and put questions to them for my own ends.

It appeared, however, I could find no one here upon whom to bestow my benevolence. The landlady of the rooms, notwithstanding their wretchedness and filth (which especially struck me in comparison with the mansion in which I lived), was well off, even from the point of view of town poverty; and compared with country destitution, with which I was well acquainted, she lived luxuriously. She had a feather-bed, a quilted blanket, a samovár, a fur cloak, a cupboard, with dishes, plates, etc. The landlady's friend had the same well-to-do appearance, and boasted even a watch and chain. The lodgers were poor, but among them there was no one requiring immediate help.

Three only applied for aid,—the woman washing linen, who said she had been abandoned by her husband; an old widowed woman, without means of livelihood; and the peasant in the bark shoes, who told me he had not had anything to eat that day. But, upon gathering more precise information, it became evident that all these people were not in extreme want, and that, before one could really help, it would be necessary to make their more intimate acquaintance.

When I offered the washerwoman to place her children in a “home,” she became confused, thought over it some time, then thanked me much, but evidently did not desire it; she would rather have had some money. Her eldest daughter helped her in the washing, and the second acted as nurse to the little boy.

The old woman asked to be put into a refuge; but, examining her corner, I saw she was not in extreme distress. She had a box containing some property and a teapot, two cups, and old bon-bon boxes with tea and sugar. She knitted stockings and gloves, and received a monthly allowance from a lady benefactress.

The peasant was evidently more desirous of wetting his throat after his last day's drunkenness than of food, and anything given him would have gone to the public-house. In these rooms, therefore, there was no one whom I could have rendered in any respect happier by helping them with money.

There were only paupers there,—and paupers, it seemed, of a questionable kind.

I put down the names of the old woman, the laundress, and the peasant, and settled in my mind that it would be necessary to do something for them, but that first I would help those other especially unfortunate ones whom I expected to come across in this house. I made up my mind that some system was necessary in distributing the aid which we had to give: first, we must find the most needy, and then come to such as these.

But in the next lodging, and in the next again, I found only similar cases, which would have to be looked into more closely before being helped. Of those whom pecuniary aid alone would have rendered happy, I found none.

However ashamed I feel in confessing it, I began to experience a certain disappointment at not finding in these houses anything resembling what I had expected. I thought to find very exceptional people; but, when I had gone over all the lodgings, I became convinced that their inhabitants were in no way extremely peculiar, but much like those amongst whom I lived.

As with us, so also with them, there were some more or less good and others more or less bad: there were some more or less happy and others more or less unhappy. Those who were unhappy amongst them would have been equally wretched with us, their misery being within themselves,—a misery not to be mended by any kind of bank-note. #[[id:x0egwn81crk0][What is it to be done?]]
