:PROPERTIES:
:ID:       wpj1x1a1crk0
:CUSTOM_ID: wpj1x1a1crk0
:END:
#+title: Moral blindness
#+DATE: <2025-11-15 Sat 22:57>
#+BEGIN_propert
{{{s}}} [[id:x0egwn81crk0][What is it to be done?]]
#+END_propert

Last March I was returning home late in the evening. On turning into a bye-lane I perceived on the snow in a distant field some black shadows. I should not have noticed this but for the policeman who stood at the end of the lane and cried in the direction of the shadows, “Vasili, why don't you come along?”

“She won't move,” answered a voice; and thereupon the shadows came towards the policeman. I stopped and asked him,—

“What is the matter?”

He said, “We have got some girls from Rzhanoff's house, and are taking them to the police-station; and one of them lags behind, and won't come along.”

A night-watchman in sheepskin coat appeared now driving on a girl who slouched along while he prodded her from behind. I, the watchman and the policeman, were wearing winter coats: she alone had none, having only her gown on. In the dark I could distinguish only a brown dress and a kerchief round her head and neck. She was short, like most starvelings, and had a broad, clumsy figure.

“We aren't going to stay here all night for you, you hag! Get on, or I'll give it you!” shouted the policeman. He was evidently fatigued and tired of her. She walked some paces and stopped again.

The old watchman, a good-natured man (I knew him), pulled her by the hand. “I'll wake you up! come along!” said he, pretending to be angry. She staggered, and began to speak with a croaking hoarse voice, “Let me be; don't you push. I'll get on myself.”

“You'll be frozen to death,” he returned.

“A girl like me won't be frozen: I've lots of hot blood.”

She meant it as a joke, but her words sounded like a curse. By a lamp, which stood not far from the gate of my house, she stopped again, leaned back against the paling, and began to seek for something among her petticoats with awkward, frozen hands. They again shouted to her; but she only muttered and continued searching. She held in one hand a crumpled cigarette and matches in the other. I remained behind her: I was ashamed to pass by or to stay and look at her. But I made up my mind and came up to her. She leaned with her shoulder against the paling and vainly tried to light a match on it.

I looked narrowly at her face. She was indeed a starveling and appeared to me to be a woman of about thirty. Her complexion was dirty; her eyes small, dim, and bleared with drinking; she had a squat nose; her lips were wry and slavering, with downcast angles; from under her kerchief fell a tuft of dry hair. Her figure was long and flat; her arms and legs short.

I stopped in front of her. She looked at me and grinned as if she knew all that I was thinking about. I felt that I ought to say something to her. I wanted to show her that I pitied her.

“Have you parents?” I asked. She laughed hoarsely, then suddenly stopped, and, lifting her brows, began to look at me steadfastly.

“Have you parents?” I repeated.

She smiled with a grimace which seemed to say, “What a question for him to put!”

“I have a mother,” she said at last; “but what's that to you?”

“And how old are you?”

“I am over fifteen,” she said, at once answering a question she was accustomed to hear.

“Come, come! go on; we shall all be frozen for you, the deuce take you!” shouted the policeman; and she edged off from the paling and staggered along the lane to the police-station: and I turned to the gate and entered my house, and asked whether my daughters were at home. I was told that they had been to an evening party, had enjoyed themselves much, and now were asleep.

The next morning I was about to go to the police-station to enquire what had become of this unhappy girl. I was ready to start early enough, when one of those unfortunate men called, who from weakness have dropped out of the gentlemanly line of life to which they have been accustomed, and who rise and fall by turns. I had been acquainted with him three years. During this time he had several times sold every thing he had,—even his clothes; and, having just done so again, he passed his nights temporarily in Rzhanoff's house, and his days at my lodgings. He met me as I was going out, and, without listening to me, began at once to relate what had happened at Rzhanoff's house the night before.

He began to relate it, yet had not got through one-half when, all of a sudden, he, an old man, who had gone through much in his life, began to sob, and, ceasing to speak, turned his face away from me. This was what he related. I ascertained the truth of his story on the spot, where I learned some new particulars, which I shall relate too.

A washerwoman thirty years of age, fair, quiet, good-looking, but delicate, passed her nights in the same lodging-house, the ground-floor of No. 32 where my friend slept among various shifting night-lodgers, men and women, who for five kopeks slept with each other.

The landlady at this lodging was the mistress of a boatman. In summer her lover kept a boat; and in winter they earned their living by letting lodgings to night-lodgers at three kopeks without a pillow, and at five kopeks with one.

The washerwoman had been living here some months, and was a quiet woman; but lately they began to object to her because she coughed, and prevented the other lodgers from sleeping. An old woman in particular, eighty years old, half silly, and a permanent inmate of this lodging, began to dislike the washerwoman and kept annoying her because she disturbed her sleep; for all night she coughed like a sheep.

The washerwoman said nothing. She owed for rent, and felt herself guilty, and was therefore compelled to endure. She began to work less and less, for her strength failed her; and that was why she was unable to pay her rent. She had not been to work at all the whole of the last week; and she had been making the lives of all, and particularly of the old woman, miserable by her cough.

Four days ago the landlady gave her notice to leave. She already owed sixty kopeks, and could not pay them, and there was no hope of doing so; and other lodgers complained of her cough.

When the landlady gave the washerwoman notice, and told her she must go away if she did not pay the rent, the old woman was glad, and pushed her out into the yard. The washerwoman went away, but came back again in an hour, and the landlady had not the heart to send her away again.... During the second and the third day the landlady left her there. “Where shall I go?” she kept saying. On the third day the landlady's lover, a Moscow man, who knew all the rules and regulations, went for a policeman. The policeman, with a sword and a pistol slung on a red cord, came into the lodging and quietly and politely turned the washerwoman out into the street.

It was a bright, sunny, but frosty day in March. The melting snow ran down in streams, the house-porters were breaking the ice. The hackney sledges bumped on the ice-glazed snow, and creaked over the stones. The washerwoman went up the hill on the sunny side, got to the church, and sat down in the sun at the church-porch. But when the sun began to go down behind the houses and the pools of water began to be covered with a thin sheet of ice, the washerwoman felt chilly and terrified. She got up and slowly walked on.... Where? Home,—to the only house in which she had been living lately.

While she was walking there, several times resting herself, it began to get dark. She approached the gate, turned into it, her foot slipped, she gave a shriek, and fell down.

One man passed by, then another. “She must be drunk,” they thought. Another man passed, and stumbled up against her, and said to the house-porter, “Some tipsy woman is lying at the gate. I very nearly broke my neck over her. Won't you take her away?”

The house-porter came. The washerwoman was dead. This was what my friend related to me.

The reader will perhaps fancy I have picked out particular cases in the prostitute of fifteen years of age and the story of this washerwoman; but let him not think so: this really happened in one and the same night. I do not exactly remember the date, only it was in March, 1884.

Having heard my friend's story I went to the police-station, intending from there to go to Rzhanoff's house to learn all the particulars of the washerwoman's story.

The weather was fine and sunny; and again under the ice of the previous night, in the shade, you could see the water running; and in the sun, in the square, everything was melting fast. The trees of the garden appeared blue from over the river; the sparrows that were reddish in winter, and unnoticed then, now attracted people's attention by their merriness; men also tried to be merry, but they all had too many cares. The bells of the churches sounded; and blending with them were heard sounds of shooting from the barracks,—the hiss of the rifle balls, and the crack when they struck the target.

I entered the police-station. There some armed men—policemen—led me to their chief. He, also armed with a sword, sabre, and pistol, was busy giving some orders about a ragged, trembling old man who was standing before him, and from weakness could not clearly answer what was asked of him. Having done with the old man, he turned to me. I inquired about the prostitute of last night. He first listened to me attentively, then he smiled, not only because I did not know why they were taken to the police-station, but more particularly at my astonishment at her youth. “Goodness! there are some of twelve, thirteen, and fourteen years of age often,” said he, in a lively tone.

To my question about the girl of yesterday, he told me that she had probably been already sent to the committee (if I understood him right). To my question where such women passed the night, he gave a vague answer. The one about whom I spoke he did not remember. There were so many of them every day.

At Rzhanoff's house, in No. 32, I already found the sacristan reading prayers over the dead washerwoman. She had been brought in and laid on her former pallet; and the lodgers, all starvelings themselves, contributed money for the prayers, the coffin, and the shroud; the old woman had dressed her, and laid her out. The clerk was reading something in the dark; a woman in a cloak stood holding a wax taper; and with a similar wax taper stood a man (a gentleman, it is fair to state), in a nice great-coat, trimmed with an astrachan collar, in bright goloshes, and with a starched shirt. That was her brother. He had been hunted up.

I passed by the dead woman to the landlady's room in order to ask her all the particulars. She was afraid of my questions,—afraid probably of being charged with something; but by and by she grew talkative and told me all. On passing by again, I looked at the dead body. All the dead are beautiful; but this one was particularly beautiful and touching in her coffin, with her clear, pale face, with closed, prominent eyes, sunken cheeks, and fair, soft hair over her high forehead; her face looked weary, but kind, and not sad at all, but rather astonished. And indeed, if the living do not see, the dead may well be astonished.

On the day I wrote this there was a great ball in Moscow. On the same night I left home after eight o'clock. I live in a locality surrounded by factories; and I left home after the factory whistle had sounded, and when, after a week of incessant work, the people were freed for their holiday. Factory-men passed by me, and I by them, all turning their steps to the public-houses and inns. Many were already tipsy: many were with women.

Every morning at five I hear each of the whistles, which means that the labour of women, children, and old people has begun. At eight o'clock another whistle,—this means half an hour's rest; at twelve the third whistle,—this means an hour for dinner. At eight o'clock the fourth whistle, indicating cessation from work. By a strange coincidence, all the three factories in my neighbourhood produce only the articles necessary for balls.

In one factory,—the one nearest to me,—they make nothing but stockings; in the other opposite, silk stuffs; in the third, perfumes and pomades.

One may, on hearing these whistles, attach to them no other meaning than that of the indication of time. “There, the whistle has sounded: it is time to go out for a walk.”

But one may associate with them also the meaning they have in reality,—that at the first whistle at five o'clock in the morning, men and women, who have slept side by side in a damp cellar, get up in the dark, and hurry away into the noisy building to take their part in a work of which they see neither cessation nor utility for themselves, and work often so in the heat, in suffocating exhalations, with very rare intervals of rest, for one, two, or three, or even twelve or more hours. They fall asleep, and get up again, and again do this work, meaningless for themselves, to which they are goaded only by want. So it goes on from one week to another, interrupted only by holidays.

And now I see these working-people freed for one of these holidays. They go out into the street: everywhere there are inns, public-houses, and gay women. And they, in a drunken state, pull each other by the arms, and carry along with them girls like the one whom I saw conducted to the police-station: they hire hackney-coaches, and ride and walk from one inn to another, and abuse each other, and totter about, and say they know not what.

Formerly when I saw the factory people knocking about in this way I used to turn aside with disgust, and almost reproached them; but since I hear these daily whistles, and know what they mean, I am only astonished that all these men do not come into the condition of the utter beggars with whom Moscow is filled, and the women into the position of the girl whom I had met near my house.

Thus I walked on, looking at these men, observing how they went about the streets, till eleven o'clock. Then their movements became quieter: there remained here and there a few tipsy people, and I met some men and women who were being conducted to the police-station. And now, from every side, carriages appeared, all going in one direction. On the coach-box sat a coachman, sometimes in a sheepskin coat, and a footman,—a dandy with a cockade. Well-fed horses, covered with cloth, trotted at the rate of fifteen miles an hour. In the carriages sat ladies wrapped in shawls, taking great care not to spoil their flowers and their toilets. All, beginning with the harness on the horses, the carriages, indiarubber wheels, the cloth of the coachman's coat, down to the stockings, shoes, flowers, velvet, gloves, scents,—all these articles have been made by those men, some of whom fell asleep on their own pallets in their mean rooms, some in night-houses with prostitutes, and others in the police-station.

The ball-goers drive past these men, in and with things made by them; and it does not even enter into their minds that there could possibly be any connection between the ball they are going to, and these tipsy people to whom their coachmen shout out so angrily. With easy minds and assurance that they are doing nothing wrong, but something very good, they enjoy themselves at the ball.

Enjoy themselves!

From eleven o'clock in the evening till six in the morning, in the very depth of the night; while with empty stomachs men are lying in night-lodgings, or dying as the washer-woman had done!

The enjoyment of the ball consists in women and girls uncovering their bosoms, putting on artificial protuberances at the back, and altogether getting themselves up as no girl and no woman who is not yet depraved would, on any account, appear before men; and in this half-naked condition, with uncovered bosoms, and arms bare up to the shoulders, with dresses puffed behind and tight round the hips, in the brightest light, women and girls, whose first virtue has always been modesty, appear among strange men, who are also dressed in indecently tight-fitting clothes, embrace each other, and pivot round and round to the sound of exciting music. Old women, often also half naked like the younger ones, are sitting looking on, and eating and drinking: the old men do the same. No wonder it is done at night when everyone else is sleeping, so that no one may see it!

But it is not done at night in order to hide it; there is nothing indeed to hide; all is very nice and good; and by this enjoyment, in which is swallowed up the painful labour of thousands, not only is nobody harmed, but by this very thing poor people are fed!

The ball goes on very merrily, may be, but how did it come to do so? When we see in society or among ourselves one who has not eaten, or is cold, we are ashamed to enjoy ourselves, and cannot begin to be merry until he is fed, to say nothing of the fact that we cannot even imagine that there are people who can enjoy themselves by means of anything which produces the sufferings of others.

We are disgusted with and do not understand the enjoyment of brutal boys who have squeezed a dog's tail into a piece of split wood. How is it, then, that in our enjoyment we become blind, and do not see the cleft in which we have pinched those men who suffer for our enjoyment.

We know that each woman at this ball whose dress costs a hundred and fifty rubles was not born at the ball, but has lived in the country, has seen peasants, is acquainted with a nurse and maid whose fathers and brothers are poor, for whom the earning of a hundred and fifty rubles to build a cottage with is the end and aim of a long, laborious life. She knows all this; how can she, then, enjoy herself, knowing that on her half-naked body she is wearing the cottage which is the dream of her housemaid's brother?

But let us suppose she has not thought about this: still she cannot help knowing that velvet and silk, sweetmeats and flowers, and laces and dresses, do not grow of themselves, but are made by men. One would think she could not help knowing that men make all these things, and under what circumstances, and why. She cannot help knowing that her dressmaker, whom she scolded to-day, made this dress not at all out of love to her, therefore she cannot help knowing that all these things—her laces, flowers, and velvet—were made from sheer want.

But perhaps she is so blinded that she does not think of this. Well, but, at all events, she could not help knowing that five people, old, respectable, often delicate men and women, have not slept all night, and have been busy on her account. She saw their tired, gloomy faces. This, also, she could not help knowing,—that on this night there were twenty-eight degrees of frost, and that her coachman—an old man—was sitting in this frost all night on his coach-box.

But I know that they do not really see this. If from the hypnotic influence of the ball these young women and girls fail to see all this, we cannot judge them. Poor things! They consider all to be good which is pronounced so by their elders. How do these elders explain their cruelty? They, indeed, always answer in the same way: “I compel no one; what I have, I have bought; footmen, chambermaids, coachman, I hire. There is no harm in engaging and in buying. I compel none; I hire; what wrong is there in that?”

Some days ago I called on a friend. Passing through the first room I wondered at seeing two women at a table, for I knew my acquaintance was a bachelor. A skinny yellow, old-looking woman, about thirty, with a kerchief thrown over her shoulders, was briskly doing something over the table with her hands, jerking nervously, as if in a fit. Opposite to her sat a young girl, who was also doing something and jerking in the same way. They both seemed to be suffering from St. Vitus's dance. I came nearer and looked closer to see what they were about.

They glanced up at me and then continued their work as attentively as before.

Before them were spread tobacco and cigarettes. They were making cigarettes. The woman rubbed the tobacco fine between the palms of her hands, caught it up by a machine, put on the tubes, and threw them to the girl. The girl folded the papers, put them over the cigarette, threw it aside, and took up another.

All this was performed with such speed, with such dexterity, that it was impossible to describe it. I expressed my wonder at their quickness. “I have been at this business fourteen years,” said the woman.

“Is it hard work?”

“Yes: my chest aches, and the air is choky with tobacco.”

But it was not necessary for her to have said so: you need only have looked at her or at the girl. The latter had been at this business three years; but anyone not seeing her at this work would have said that she had a strong constitution which was already beginning to be broken.

My acquaintance, a kind-hearted man of liberal views, hired these women to make him cigarettes at two rubles and a half (5s.) a thousand. He has money, and he pays it away for this work: what harm is there in it?

My acquaintance gets up at twelve. His evenings, from six to two, he spends at cards or at the piano; he eats and drinks well; other people do all the work for him. He has devised for himself a new pleasure,—smoking. I can remember when he began to smoke. Here are a woman and a girl who can scarcely earn their living by transforming themselves into machines, and who pass all their lives in breathing tobacco, thus ruining their lives. He has money which he has not earned, and he prefers playing at cards to making cigarettes for himself. He gives these women money only on condition that they continue to live as miserably as they lived before in making cigarettes for him.

I am fond of cleanliness; and I give money on condition that the washerwoman washes my shirts, which I change twice a day; and the washing of these shirts having taxed the utmost strength of the washerwoman, she has died.

What is wrong in this?

Men who buy and hire will continue doing so whether I do or do not; they will force other people to make velvets and dainties, and will buy them whether I do or do not; so also they will hire people to make cigarettes and to wash shirts. Why should I, then, deprive myself of velvets, sweetmeats, cigarettes, and clean shirts, when their production is already set in going. Often,—almost constantly I hear this reasoning.

This is the very reasoning which a crowd, maddened with the passion of destruction, will employ. It is the same reasoning which leads a pack of dogs, when one of their number runs against another and knocks it down, the rest attack it and tear it to pieces. Others have already begun, have done a little mischief; why shouldn't I, too, do the same? What can it possibly signify if I wear a dirty shirt and make my cigarettes myself? could that help any one? men ask who desire to justify themselves.

Had we not wandered so far from truth one would be ashamed to answer this question; but we are so entangled that such a question seems natural to us, and, therefore, though I feel ashamed, I must answer it.

What difference would it be if I should wear my shirt a week instead of a day, and make my cigarettes myself, or leave off smoking altogether?

The difference would be this,—that a certain washerwoman, and a certain cigarette-maker, would exert themselves less, and what I gave formerly for the washing of my shirt, and for the making of my cigarettes, I may give now to that or to another woman; and working-people who are tired by their work, instead of overworking themselves, will be able to rest and to have tea. But I have heard objections to this, so ashamed are the rich and luxurious to understand their position.

They reply, “If I should wear dirty linen, leave off smoking, and give this money away to the poor, then this money would be all the same taken away from them, and my drop will not help to swell the sea.”

I am still more ashamed to answer such a reply, but at the same time I must do so. If I came among savages who gave me chops which I thought delicious, but the next day I learned (perhaps saw myself) that these delicious chops were made of a human prisoner who had been slain in order to make them; and if I think it bad to eat men, however delicious the cutlets may be, and however general the custom to eat men among the persons with whom I live, and however small the utility of my refusal to eat them may be,—to the prisoners who have been prepared for food,—I shall not and cannot eat them.

It may be that I shall eat human flesh when urged by hunger; but I shall not make a feast of it, and shall not take part in feasts with human flesh, and shall not seek such feasts, nor be proud of my partaking of them.
